- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
- Merge PR. Do not leave open
- Updated stable build
> chore(Dockerfile): updated build date

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-secure-passwd

- docker-jans-certmanager/scripts/bootstrap.py
- docker-jans-certmanager/scripts/client_api_handler.py
- docker-jans-certmanager/scripts/utils.py
Overview:
- fix implicit string concatenation in a list
- remove variable that defined multiple times
- refactor options handler
> fix(certmanager): handle issues reported by CodeQL

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/Dockerfile
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/Dockerfile
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/Dockerfile
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/Dockerfile
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/Dockerfile
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/Dockerfile
- docker-jans-scim/requirements.txt
The changeset ensure images use compatible `libcst` version.
> build(docker): avoid incompatible libcst version #617

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-pycloudlib-copy-timestamp

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
- jans-pycloudlib/jans/pycloudlib/meta/kubernetes_meta.py
The changeset fixes the timestamp issue as mentioned in https://github.com/JanssenProject/jans/issues/613
> fix(pycloudlib): missing tar option to not restore file timestamp #613

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
Signed-off-by: mo-auto <54212639+mo-auto@users.noreply.github.com>
> chore(jans-pycloudlib): updated build

- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalDynamicClientRegistrationService.java
- jans-core/script/src/main/java/io/jans/model/custom/script/type/client/ClientRegistrationType.java
- jans-core/script/src/main/java/io/jans/model/custom/script/type/client/DummyClientRegistrationType.java
feat(jans-auth-server): add methods to dynamic client registration script to modify POST and PUT responses
https://github.com/JanssenProject/jans/issues/380
> feat(jans-auth-server): add methods to dynamic client registration script to modify POST and PUT responses

- README.md
Added some clarifying details to the Rancher installation instructions.
> docs: clarified Rancher instructions

- jans-auth-server/client/pom.xml
- jans-auth-server/pom.xml
- jans-auth-server/server/pom.xml
https://github.com/JanssenProject/jans/issues/656
> chore(jans-auth-server): removed findbugs

- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-scim/Dockerfile
- Always leave open
- Updated build dates for images.
> chore(Dockerfiles): updated build dates

- jans-config-api/plugins/admin-ui-plugin/config/auiConfiguration.properties
https://github.com/JanssenProject/jans/issues/720
> Bug: remove licenseSpring keys from properties file in admin-ui plugin #720

- jans-client-api/server/src/test/resources/testng.xml
https://github.com/JanssenProject/jans/issues/724
> Bug(jans-client-api): fix all test cases #724

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
https://github.com/JanssenProject/jans/issues/728
> fix(jans-auth-server): corrected npe in jarm

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
https://github.com/JanssenProject/jans/issues/728
> fix(jans-auth-server): corrected jarm error response

- jans-linux-setup/install.py
- jans-linux-setup/setup_app/config.py
- jans-linux-setup/setup_app/installers/node.py
Node installer is needed for flex-linux setup (https://github.com/GluuFederation/flex/issues/21)
> feat: linux-setup node installer

- jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
fix(jans-auth-server): covered one more case when consent is off
https://github.com/JanssenProject/jans/issues/736
> fix(jans-auth-server): covered one more case when consent is off

- jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
https://github.com/JanssenProject/jans/issues/736
> fix(jans-auth-server): fixed device authz tests

- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/LicenseRequest.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
https://github.com/JanssenProject/jans/issues/731
> fix: license validity period should be read only #731

- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java
Disabled the tests that requires setting fapiCompatibility to true and deleted unsused method userDeniedAuthentiation
> fix: jarm failing tests

- jans-notify/client/src/main/java/io/jans/notify/client/NotifyClientFactory.java
This is to fix Sonar bug: https://sonarcloud.io/project/issues?id=JanssenProject_jans-notify&open=AX52445zyQx5uPF9tBIK&resolved=false&types=CODE_SMELL
> fix: reorder java modifiers

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
This is correction in fix for the issue#315 to ensure registered redirectUri
> fix: for issue#315 JARM registered redirect uri

- jans-auth-server/client/src/main/java/io/jans/as/client/OpenIdConnectDiscoveryResponse.java
> fix(jans-auth-server): use diamond operator

- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/stat/StatWS.java
https://github.com/JanssenProject/jans/issues/317
> feat(jans-auth-server): added cache support to /stat endpoint

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
> fix(jans-auth-server): jarm tests fix

- jans-fido2/model/src/main/java/io/jans/entry/DeviceRegistrationStatus.java
This is to fix code smell reported by Sonar
> fix(jans-fido2): use diamond operator

- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatResponseService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/stat/StatWS.java
- jans-auth-server/server/src/test/java/io/jans/as/server/service/stat/StatResponseServiceTest.java
https://github.com/JanssenProject/jans/issues/317
> test(jans-auth-server): added new stat response service with test

- jans-auth-server/server/integrations/cert/Generate certs without configs.md
This is to fix GH pages site for Jans which is facing issues due to encountering non UTF-8 characters. 
I have scanned all md files in `jans`, and only one file has this problem. This PR fixes it.
> fix: replace non UTF-8 characters

- _config.yml
> fix: update _config.yml

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
check the algorithm none and display none algorithm is not allowed in FAPI
> fix: check alg none to display error JARM issue310

- jans-config-api/server/src/main/java/io/jans/configapi/rest/ApiApplication.java
https://github.com/JanssenProject/jans/issues/793
> fix: sql configuration endpoints are not found #793

- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
https://github.com/JanssenProject/jans/issues/795
> fix(jans-auth-server): fixed error code during error response creation (#795)

- jans-auth-server/common/pom.xml
- jans-auth-server/common/src/main/java/io/jans/as/common/util/RedirectUri.java
- jans-auth-server/common/src/test/java/io/jans/as/common/util/RedirectUriTest.java
- jans-auth-server/common/src/test/resources/testng.xml
- jans-auth-server/pom.xml
NOTE: This PR replaces https://github.com/JanssenProject/jans/pull/767 
1.- Fixed, all sonar issues
2.- inproved, code coverage percent with unit test ( methods with logic)
> fix: RedirectUri test-coverage

- jans-config-api/common/src/main/java/io/jans/configapi/model/status/FacterData.java
- jans-config-api/common/src/main/java/io/jans/configapi/model/status/StatsData.java
- jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/plugins/pom.xml
- jans-config-api/plugins/sample/demo/pom.xml
- jans-config-api/plugins/sample/helloworld/pom.xml
- jans-config-api/profiles/local/test.properties
- jans-config-api/server/pom.xml
- jans-config-api/server/src/main/java/io/jans/configapi/configuration/AppInitializer.java
- jans-config-api/server/src/main/java/io/jans/configapi/rest/health/ApiHealthCheck.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ConfigurationService.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/cdi/event/StatusCheckerTimerEvent.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/logger/LoggerService.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/status/StatusCheckerTimer.java
- jans-config-api/server/src/test/resources/feature/health/server-health.feature
- jans-config-api/shared/pom.xml
@yuriyz, request your review and approval
Added server stats functionality.
Related request issues_275 -> https://github.com/JanssenProject/jans/issues/275
> feat: underlying server stats

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
Corrected the error code for unregistered redirect URI.
https://github.com/JanssenProject/jans/issues/816
> fix: error code correction unregister redirect_uri

- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
fix(jans-linux-setup): restore changes after 4babe55a494c0edad899776f086d8c59368031f2
Related to https://github.com/JanssenProject/jans/pull/800/files
> fix(jans-linux-setup): restore changes after 4babe55a494c0edad899776f086d8c59368031f2

- jans-config-api/plugins/admin-ui-plugin/pom.xml
- jans-config-api/plugins/pom.xml
- jans-config-api/plugins/sample/demo/pom.xml
- jans-config-api/plugins/scim-plugin/pom.xml
https://github.com/JanssenProject/jans/issues/851
> feat: all config-api plugins should be in same plugins folder in maven repo #851

- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/util/ServerUtil.java
https://github.com/JanssenProject/jans/issues/824
> fix(jans-auth-server): corrected wrong expires_in

- jans-auth-server/client/src/main/java/io/jans/as/client/par/ParClient.java
- jans-auth-server/client/src/main/java/io/jans/as/client/par/ParRequest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/par/ParHttpTest.java
- jans-auth-server/model/src/main/java/io/jans/as/model/authorize/AuthorizeRequestParam.java
- jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java
- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
feat: par should be able to register with nbf
https://github.com/JanssenProject/jans/issues/865
> feat: par should be able to register with nbf

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-table-mapping

- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/par/ParHttpTest.java
test(jans-auth-server): fixed nbf value in par test
https://github.com/JanssenProject/jans/issues/865
> test(jans-auth-server): fixed nbf value in par test

- README.md
the only change is adding the Janssen logo banner to the readme file
> docs: added the Janssen Logo to the readme file

- jans-auth-server/client/src/test/java/io/jans/as/client/ciba/RegistrationTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/CanProvideEncryptedUserInfoResponse.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/CanProvideSignedUserInfoResponse.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/CanRequestAndUseSignedUserInfoResponse.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/RejectsSecondUseOfAccessCode.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/RequestingUserInfoClaimsWithOpenIdRequestObject.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/RequestingUserInfoClaimsWithScopeValues.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/SecondUseOfAccessCodeRevokesPreviouslyIssuedAccessToken.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/SupportScopeRequestingProfileClaims.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/UserInfoEndpointAccessWithFormEncodedBodyMethod.java
- jans-auth-server/client/src/test/java/io/jans/as/client/interop/UserInfoEndpointAccessWithHeaderMethod.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AddressClaimsTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizationCodeFlowHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizeRestWebServiceHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ClientAuthenticationFilterHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ClientCredentialsGrantHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ClientInfoRestWebServiceHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ClientSecretBasicTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/EnableClientToRestrictJavascriptOrigin.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/GrantTypesRestrictionHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/IndividualClaimsRequestsTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/OpenIDRequestObjectHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SectorIdentifierUrlVerificationHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/TokenRestWebServiceHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/TokenRevocationTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/UserInfoRestWebServiceHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ValidateIdTokenHashesTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/deviceauthz/DeviceAuthzFlowHttpTest.java
Fix build errors in test cases due to refactor common asserts
module: jans-auth-client
errors caused by PR merged:
https://github.com/JanssenProject/jans/pull/879
origin Issue:
https://github.com/JanssenProject/jans/issues/804
> fix: jans-auth-client - error build test cases Issue#804

- jans-linux-setup/jans_setup/static/extension/person_authentication/U2fExternalAuthenticator.py
> fix: update wrong import #905

- jans-config-api/plugins/scim-plugin/src/main/assembly/assembly.xml
- jans-config-api/server/src/main/java/io/jans/configapi/security/service/OpenIdAuthorizationService.java
- jans-config-api/server/src/main/resources/log4j2.xml
- jans-config-api/shared/src/main/java/io/jans/configapi/core/service/ClientService.java
- jans-config-api/shared/src/main/java/io/jans/configapi/core/util/AuthUtil.java
Request review and approve for fixes for https://github.com/JanssenProject/jans/issues/664
> fix(jans-config-api): multiple custom lib not working 

- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
- jans-auth-server/server/src/test/java/io/jans/as/server/par/ws/rs/ParValidatorTest.java
https://github.com/JanssenProject/jans/issues/875
> feat(jans-auth-server): reject par without pkce for fapi

- .github/workflows/build-packages.yml
> ci: fixed tag name in building binary packages

- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
feat(jans-auth-server): forbid plain pkce if fapi=true (fapi1-advanced-final-par-plain-pkce-rejected fail) #946
https://github.com/JanssenProject/jans/issues/946
> feat(jans-auth-server): forbid plain pkce if fapi=true (fapi1-advanced-final-par-plain-pkce-rejected fail) #946

- .github/workflows/build-packages.yml
> Build binary packages

- jans-auth-server/server/src/test/java/io/jans/as/server/par/ws/rs/ParValidatorTest.java
https://github.com/JanssenProject/jans/issues/946
> fix(jans-auth-server): corrected ParValidatorTest #946

- .github/workflows/build-packages.yml
> ci: added seperate steps for sign and checksum

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-cert-validity

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
npe when checking for client config option defaultpromptlogin
> fix(jans-auth-server): fix npe

- jans-auth-server/server/src/test/resources/testng.xml
fix(jans-auth-server): removed reference of removed tests #996
> fix(jans-auth-server): removed reference of removed tests #996

- jans-orm/standalone/src/main/java/io/jans/orm/service/StandalonePersistanceFactoryService.java
https://github.com/JanssenProject/jans/issues/1006
> Jans orm issue 1006

- jans-cli/docs/cli/cli-cache-configuration.md
> docs: cli-cache-configuration.md

- .github/workflows/build-packages.yml
> ci: added python_version in martix

- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-client-api/scripts/entrypoint.sh
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/gluu-casa/clients.ldif
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- docker-jans-persistence-loader/templates/jans-config-api/admin-ui-clients.ldif
- docker-jans-scim/Dockerfile
Overview:
- all images dependencies are updated
- updated image LABELs to conform to container cerfitication
- refactored upgrade script in `docker-jans-persistence-loader`
- synchronized static and templates (taken from latest `jans-linux-setup`) in `docker-jans-persistence-loader`
> chore: update images

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- sync schema for sql and spanner persistence
- modify column size of jansFido2AuthnEntry.jansAuthData column (related to #1044)
> fix: change column size of jansFido2AuthnEntry.jansAuthData column

- docker-jans-auth-server/Dockerfile
Overview:
- updated `casa` source
- updated `auth-server.war`
> chore: update auth-server image

- .github/SECURITY.md
- README.md
- docs/user/README.md
README should have more details to describe and promote Janssen in a better way in the user base and community
> docs: Jans readme updates

- jans-auth-server/client/src/test/resources/testng.xml
fix: isolate regex redirection uri validation test
> fix: isolate regex redirection uri validation test

- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatResponseService.java
chore(jans-auth-server): added more trace logs to stats
https://github.com/JanssenProject/jans/issues/805
> chore(jans-auth-server): added more trace logs to stats

- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatResponseService.java
https://github.com/JanssenProject/jans/issues/805
> fix(jans-auth-server): corrected log vulnerability (sonar)

- README.md
- docs/user/README.md
- Target issue
PR addresses review comments by @nynymike
> docs: Janssen readme updates

- jans-auth-server/server/src/main/resources/oxauth.properties
- jans-auth-server/server/src/main/resources/oxauth_en.properties
- jans-auth-server/server/src/main/resources/oxauth_fr.properties
https://github.com/JanssenProject/jans/issues/1061
Fix static text
> fix:jans-auth-server authorize page message agree policy

- jans-auth-server/model/src/main/java/io/jans/as/model/common/ResponseType.java
- jans-auth-server/model/src/test/java/io/jans/as/model/common/ResponseTypeTest.java
fix(jans-auth-server): corrected npe in response type class
https://github.com/JanssenProject/jans/issues/1087
> fix(jans-auth-server): corrected npe in response type class

- docs/user/how-to/authn-with-apache-reverse-proxy.md
Includes minor edits to use case documentation
> docs: review and minor edits to use case doc

- .github/CODEOWNERS
- .github/workflows/central_code_quality_check.yml
- .github/workflows/release.yaml
- super-jans/README.md
> ci: add new project super-jans

- jans-auth-server/server/src/main/java/io/jans/as/server/audit/ApplicationAuditLogger.java
fix(jans-auth-server): corrected thread-safety bug in ApplicationAuditLogger #803
https://github.com/JanssenProject/jans/issues/803
> fix(jans-auth-server): corrected thread-safety bug in ApplicationAuditLogger #803

- jans-auth-server/model/pom.xml
- jans-auth-server/model/src/test/java/io/jans/as/model/BaseTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/Base64UtilTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/ByteUtilTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/CertUtilsTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/HashUtilTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/JwtUtilTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/PairTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/QueryBuilderTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/SecurityProviderUtilityTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/StringUtilsTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/SubjectIdentifierTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/URLPatternListTest.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/UtilTest.java
- jans-auth-server/pom.xml
Unit test to cover all the utils in model module.
Target Issue #
https://github.com/JanssenProject/jans/issues/992
This is the first PR for this issue, please do not close the Issue.
> test: (jans-auth-model ) Utils in model module has to be covered with tests Issue#992

- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterCreateAction.java
refactor(jans-auth-server): register create action
https://github.com/JanssenProject/jans/issues/1126
> refactor(jans-auth-server): register create action

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- fixed indexing error on MySQL column with JSON type
- changed `jansFido2RegistrationEntry.jansCodeChallengeHash` column type
- synchronized templates and static from `jans-linux-setup` at SHA-commit cfdc70e6a2ddcc9d2ba4e3cf07df19344d613944
> chore: sync SQL/Spanner schema changes and indexes

- .github/workflows/label_pr.yml
- automation/github-labels/label.py
- automation/github-labels/labels-schema.json
- docs/community/triage.md
> ci: add label schema and pr autolabel

- docker-jans-auth-server/Dockerfile
- docker-jans-scim/Dockerfile
The changeset removes Jython's `pip` from images.
Ref: #1174
> feat: remove Jython's pip from images

- README.md
Changed the link in the logo HTML to be on the main branch instead of a commit branch.
> docs: Corrected logo image address

- jans-auth-server/common/src/main/java/io/jans/as/common/model/common/User.java
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
- jans-config-api/docs/jans-config-api-swagger.yaml
fix(jans-auth-server): disabled issuing AT by refresh token if user status=inactive
https://github.com/JanssenProject/jans/issues/1093
> fix(jans-auth-server): disabled issuing AT by refresh token if user status=inactive

- jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/DynamicConfig.java
- jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/LicenseSpringCredentials.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/LicenseApiResponse.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/LicenseConfiguration.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/user/UserManagementService.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/AppConstants.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java
https://github.com/JanssenProject/jans/issues/1196
> feat: create apis to verify and save license api-keys in Admin UI #1196

- docs/CONTRIBUTING.md
> docs: fix hyperlinks

- jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
This is fix for https://github.com/JanssenProject/jans/issues/1214
> fix: linux-setup don't use personCustomObjectClassList for RDBMS

- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterDeleteAction.java
fix(jans-auth-server): dynamic client registration managment delete event
https://github.com/JanssenProject/jans/issues/1206
> fix(jans-auth-server): dynamic client registration managment delete event

- jans-linux-setup/jans_setup/install.py
- jans-linux-setup/jans_setup/setup_app/installers/config_api.py
This PR is for https://github.com/JanssenProject/jans/issues/1213
> feat: jans-linux-setup config-api user management plugin (ref: #1213)

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java
We have to encapsulate request parameters into separate object with will allow to refactor AuthorizeRestWebServiceImpl 
> feat(jans-auth-server): added authzrequest abstraction

- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-scim/Dockerfile
The changeset removes `pip` library after installing all required Python libs
Ref: #1240
> build: uninstall Python pip

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java
refactor(jans-auth-server): keep authzrequest as single source of redirect info
> refactor(jans-auth-server): keep authzrequest as single source of redirect info

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java
refactor(jans-auth-server): moved acr validation to validator
> refactor(jans-auth-server): moved acr validation to validator

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-persistence

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
refactor(jans-auth-server): extracted request object processing into separate method
> refactor(jans-auth-server): extracted request object processing into separate method

- jans-linux-setup/jans_setup/static/extension/introspection/introspection_role_based_scope.py
- jans-linux-setup/jans_setup/templates/jans-auth/role-scope-mappings.json
https://github.com/JanssenProject/jans/issues/1258
> fix: the admin-ui backend issues related to jetty 11 migration #1258

- jans-auth-server/common/src/main/java/io/jans/as/common/util/RedirectUri.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
extracted user and response parameters handling into separate methods during authz
> refactor(jans-auth-server): extracted user and response parameters handling into separate methods during authz

- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
https://github.com/JanssenProject/jans/issues/1258
> fix: fix license apis#1258

- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
https://github.com/JanssenProject/jans/issues/1258
> feat: adding logs to debug license issues#1258

- jans-cli/cli/config_cli.py
Previously when user list is queried, all attributes of all users are displayed. This is not helpful for admins. With this PR, users are displayed in tabular form, and he can choose to display details of specific user.
> feat: jans-cli display users in tabular form

- jans-cli/cli/config_cli.py
- jans-config-api/docs/jans-config-api-swagger.yaml
Enancements discussed in https://github.com/JanssenProject/jans/issues/892
> feat: jans-cli tabulate attribute list

- jans-cli/cli/config_cli.py
- jans-config-api/docs/jans-config-api-swagger.yaml
Scope dn/id when chreating clients
> Jans cli fixes

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
feat(jans-auth-server): hide 302 redirect exception in logs #1294
> feat(jans-auth-server): hide 302 redirect exception in logs #1294

- jans-scim/server/src/main/java/io/jans/scim/service/init/AppInitializer.java
- jans-scim/service/pom.xml
- jans-scim/service/src/main/java/io/jans/scim/service/GroupService.java
- jans-scim/service/src/main/java/io/jans/scim/service/PersonService.java
> feat: call id-generation script when creating user/group #1145

- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalUmaRptPolicyService.java
- jans-bom/pom.xml
- jans-core/script/pom.xml
- jans-core/script/src/main/java/io/jans/model/custom/script/CustomScriptType.java
- jans-core/script/src/main/java/io/jans/model/custom/script/model/CustomScript.java
- jans-core/script/src/main/java/io/jans/model/custom/script/model/ScriptError.java
- jans-core/script/src/main/java/io/jans/service/PythonService.java
- jans-core/script/src/main/java/io/jans/service/custom/script/CustomScriptManager.java
- jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java
- jans-core/script/src/main/java/io/jans/service/custom/script/StandaloneCustomScriptManager.java
- jans-core/script/src/test/java/io/jans/service/custom/script/test/SimpleJavaCompileTest.java
- jans-linux-setup/jans_setup/static/extension/discovery/Discovery.java
feat(jans-core): compile java code on the fly for custom script
> feat(jans-core): compile java code on the fly for custom script

- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalUmaClaimsGatheringService.java
fix(jans-core): corrected ExternalUmaClaimsGatheringService
> fix(jans-core): corrected ExternalUmaClaimsGatheringService

- jans-auth-server/client/src/test/resources/testng.xml
test(jans-auth-server): enabled tests disabled during jetty 11 integration
> test(jans-auth-server): enabled tests disabled during jetty 11 integration

- agama/README.md
- agama/engine/src/main/java/io/jans/agama/engine/service/ActionService.java
- agama/engine/src/main/java/io/jans/agama/engine/service/WebContext.java
> chore: add README #1336

- jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/client/RegisterRequestTest.java
Corrected serialization and deserialization of RegisterRequest list fields.
https://github.com/JanssenProject/jans/issues/1341
> test(jans-auth-server): fixed RegistrationRestWebServiceHttpTest

- agama/engine/src/main/java/io/jans/agama/engine/script/LogUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/script/ScriptUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/service/FlowService.java
- agama/engine/src/main/java/io/jans/agama/engine/servlet/ExecutionServlet.java
- agama/model/src/main/java/io/jans/agama/model/FlowMetadata.java
- agama/transpiler/grammar/AuthnFlow.g4
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowBaseListener.java
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowBaseVisitor.java
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowLexer.java
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowListener.java
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowParser.java
- agama/transpiler/src/main/java/io/jans/agama/antlr/AuthnFlowVisitor.java
- agama/transpiler/src/main/resources/JSGenerator.ftl
> feat: allow flows to access their metadata properties #1340

- agama/README.md
- jans-linux-setup/jans_setup/schema/jans_schema.json
> feat: add schema updates #1390

- jans-eleven/client/src/test/resources/testng.properties
- jans-eleven/client/src/test/resources/testng.xml
- jans-eleven/server/src/main/java/io/jans/eleven/service/PKCS11Service.java
fix compilation issues
https://github.com/JanssenProject/jans/issues/1104
> Jans eleven compile issue for crypto code

- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/scripts/utils.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-scim/Dockerfile
Overview:
* update dependencies of images
* sync templates, schema, static files, etc from jans-linux-setup
* add external files for FIDO2
> chore: sync image manifests

- agama/engine/pom.xml
> fix(agama): adjust pom version #1402

- agama/engine/pom.xml
- agama/engine/src/main/java/io/jans/agama/engine/misc/FlowUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/servlet/BaseServlet.java
- agama/engine/src/main/java/io/jans/agama/engine/servlet/ExecutionServlet.java
- agama/engine/src/main/java/io/jans/agama/engine/servlet/RestartServlet.java
- agama/engine/src/main/java/io/jans/agama/timer/FlowRunsCleaner.java
- agama/engine/src/main/java/io/jans/agama/timer/Transpilation.java
- agama/misc/bridge.py
- agama/model/pom.xml
- agama/model/src/main/java/io/jans/agama/model/EngineConfig.java
- agama/pom.xml
- agama/transpiler/pom.xml
- jans-auth-server/model/pom.xml
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/conf/jans-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
> chore(agama): place configuration inside AS configuration

- agama/engine/pom.xml
- agama/pom.xml
> fix(agama): depend on latest available artifacts

- agama/engine/src/main/java/io/jans/agama/engine/misc/FlowUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ServicesFactory.java
- agama/engine/src/main/java/io/jans/agama/timer/ConfigReloaderEvent.java
- agama/misc/agama_web_resources.xml
- jans-auth-server/server/conf/jans-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
> chore: update config refresh logic and related files

- jans-scim/model/src/main/java/io/jans/scim/model/scim2/util/ResourceValidator.java
> feat: include the name of problematic attribute part of extension in the error response

- jans-core/script/src/main/java/io/jans/service/custom/script/StandaloneCustomScriptManager.java
- jans-core/script/src/test/java/io/jans/service/custom/script/test/SampleContext.java
- jans-core/script/src/test/java/io/jans/service/custom/script/test/StandaloneCustomScriptManagerTest.java
- jans-core/script/src/test/java/io/jans/service/custom/script/test/java/SimpleJavaCompileTest.java
chore(jans-core): do not create python service for java type creator
> chore(jans-core): do not create python service for java type creator

- jans-auth-server/server/src/main/java/io/jans/as/server/service/ResteasyInitializer.java
fix(jans-auth-server): added SessionRestWebService to rest initializer
https://github.com/JanssenProject/jans/issues/1457
> fix(jans-auth-server): added SessionRestWebService to rest initializer

- jans-core/script/src/test/java/io/jans/service/custom/script/test/java/StandaloneJavaCustomScriptManagerTest.java
feat(jans-core): added StandaloneJavaCustomScriptManagerTest
> feat(jans-core): added StandaloneJavaCustomScriptManagerTest

- jans-scim/service/pom.xml
- jans-scim/service/src/main/java/io/jans/scim/service/ExternalIdGeneratorService.java
- jans-scim/service/src/main/java/io/jans/scim/service/GroupService.java
- jans-scim/service/src/main/java/io/jans/scim/service/PersonService.java
> fix(jans-scim): remove jans-auth-common dep to avoid startup issues

- jans-orm/pom.xml
fix(jans-orm): switch to 1.0.1-SNAPSHOT
> fix(jans-orm): switch to 1.0.1-SNAPSHOT

- jans-core/pom.xml
fix(jans-core): switch to 1.0.1-SNAPSHOT
> fix(jans-core): switch to 1.0.1-SNAPSHOT

- jans-config-api/plugins/fido2-plugin/pom.xml
- jans-config-api/plugins/pom.xml
- jans-config-api/plugins/sample/demo/pom.xml
- jans-config-api/plugins/sample/helloworld/pom.xml
- jans-config-api/plugins/user-mgt-plugin/pom.xml
fix(jans-config-api): switch to 1.0.1-SNAPSHOT
> fix(jans-config-api): switch to 1.0.1-SNAPSHOT

- jans-config-api/plugins/admin-ui-plugin/pom.xml
@yuriyz request you to please review and approve the change for build issue
> build(jans-config-api): fixed client-api dependency for admin-ui

- jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java
- jans-config-api/plugins/admin-ui-plugin/pom.xml
- jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/service/Fido2RegistrationService.java
https://github.com/JanssenProject/jans/pull/1470
> feat: fix the dependencies and code issues #1465

- docs/user/integration/saml.md
> docs: added header to saml doc

- jans-auth-server/server/pom.xml
- jans-auth-server/server/src/main/resources/log4j2.xml
- jans-auth-server/server/src/main/resources/quartz.properties
- jans-auth-server/server/src/main/webapp/agama.xhtml
> chore(agama): complete integration of agama to auth-server

- docker-jans-auth-server/Dockerfile
- docker-jans-auth-server/jetty/agama_web_resources.xml
- docker-jans-auth-server/jetty/log4j2.xml
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/scripts/utils.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-scim/Dockerfile
- add agama integration into `janssenproject/auth-server` image
- update dependencies of remaining images
> chore: update images dependencies

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-merge-hybrid

- jans-config-api/docs/jans-config-api-swagger.yaml
https://github.com/JanssenProject/jans/issues/1465
> fix: add path parameter to /fido2/registration/entries #1465

- jans-cli/cli/config_cli.py
Fix issue described in https://github.com/JanssenProject/jans/issues/1352
> fix: jans-cli help message format and prompt values (ref: #1352)

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-reconfigure-logging

- docker-jans-auth-server/Dockerfile
- docker-jans-auth-server/conf/jans.properties.tmpl
- docker-jans-auth-server/requirements.txt
- docker-jans-auth-server/scripts/wait.py
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-client-api/scripts/wait.py
- docker-jans-config-api/Dockerfile
- docker-jans-config-api/requirements.txt
- docker-jans-config-api/scripts/wait.py
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/Dockerfile
- docker-jans-fido2/conf/jans.properties.tmpl
- docker-jans-fido2/requirements.txt
- docker-jans-fido2/scripts/wait.py
- docker-jans-persistence-loader/requirements.txt
- docker-jans-persistence-loader/scripts/wait.py
- docker-jans-scim/Dockerfile
- docker-jans-scim/conf/jans.properties.tmpl
- docker-jans-scim/requirements.txt
- docker-jans-scim/scripts/wait.py
- jans-pycloudlib/setup.py
Overview:
* re-configure logging for `jans.pycloudlib` logger in image containers
* update dependencies
* sync `jans.properties` template
> refactor: re-configure logging for jans.pycloudlib logger

- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatResponseService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/stat/Months.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/stat/StatWS.java
- jans-auth-server/server/src/test/java/io/jans/as/server/service/stat/StatResponseServiceTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/stat/MonthsTest.java
- jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): add support for ranges in statistic endpoint (UI team request)
https://github.com/JanssenProject/jans/issues/1089
> feat(jans-auth-server): add support for ranges in statistic endpoint (UI team request)

- agama/engine/pom.xml
- agama/engine/src/main/java/io/jans/agama/engine/page/Page.java
- agama/engine/src/main/java/io/jans/agama/engine/script/ScriptUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/serialize/ContinuationSerializer.java
- agama/engine/src/main/java/io/jans/agama/engine/serialize/NativeJavaBox.java
- agama/engine/src/main/java/io/jans/agama/engine/serialize/ObjectSerializer.java
- agama/engine/src/main/java/io/jans/agama/engine/serialize/SerializerFactory.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ActionService.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ManagedBeanService.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ServicesFactory.java
> chore(agama): avoid serialization of managed beans

- jans-cli/cli/config_cli.py
- jans-linux-setup/jans_setup/templates/jans-auth/people.ldif
Fix issues described in https://github.com/JanssenProject/jans/issues/418#issuecomment-1149713951 as a consequence of https://github.com/JanssenProject/jans/issues/1517
> fix: Jans cli user userpassword

- jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthenticationService.java
feat(jans-auth-server): make check whether user is active case insensitive #1550
https://github.com/JanssenProject/jans/issues/1550
> feat(jans-auth-server): make check whether user is active case insensitive #1550

- jans-linux-setup/jans_setup/static/extension/person_authentication/other/uaf/Properties description.md
> docs: update script link #1570

- jans-linux-setup/jans_setup/setup_app/utils/crypto64.py
- jans-linux-setup/jans_setup/templates/scripts.ldif
Witihn this PR, forgot password script is loaded to database
> feat: jans-linux-setup add forgot password script

- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java
feat(jans-auth-server): added convenient method for up-scoping or down-scoping AT scopes #1218
https://github.com/JanssenProject/jans/issues/1218
> feat(jans-auth-server): added convenient method for up-scoping or down-scoping AT scopes #1218

- .github/workflows/build-wars.yml
- agama/pom.xml
- jans-auth-server/pom.xml
- jans-auth-server/static/pom.xml
- jans-bom/pom.xml
- jans-client-api/pom.xml
- jans-config-api/pom.xml
- jans-core/pom.xml
- jans-eleven/pom.xml
- jans-fido2/pom.xml
- jans-notify/pom.xml
- jans-orm/pom.xml
- jans-scim/pom.xml
[issue](https://github.com/JanssenProject/jans/issues/1599)
> ci: publish wars to GH packages

- jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java
- jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserService.java
- jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/util/MgtUtil.java
https://github.com/JanssenProject/jans/issues/1593
> fix (jans-config-api) : error in POST, PUT endpoint of user management plugin if birthdate attribute is present in request #1593

- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/server/src/test/resources/feature/config/properties/properties.feature
- jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
feat(jans-auth-server): removed dcrSkipSignatureValidation configuration property #1623
https://github.com/JanssenProject/jans/issues/1623
> feat(jans-auth-server): removed dcrSkipSignatureValidation configuration property #1623

- jans-client-api/client/pom.xml
https://github.com/JanssenProject/jans/issues/1629
Removing filtering of test.properties file (unused)
> test(jans-client-api):jenkins Fullrebuild loading test.properties

- jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/service/Fido2RegistrationService.java
- jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/service/UserFido2Service.java
- jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java
- jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java
https://github.com/JanssenProject/jans/issues/1632
> fix: fido2-plugin throwing error during deployment #1632

- jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java
https://github.com/JanssenProject/jans/issues/1057
fix missing JsonObject annotation
> fix(jans-auth-server): fix missing jsonobject annotation

- jans-config-api/docs/jans-config-api-swagger.yaml
fix(jans-config-api): removed java_script from programmingLanguages
> fix(jans-config-api): removed java_script from programmingLanguages

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/utils.py
Overview:
* added script for forgot password
* removed `dcrSkipSignatureValidation` config
> chore: update persistence-loader

- jans-auth-server/client/src/main/java/io/jans/as/client/ClientAuthnRequest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ClientAuthnRequestTest.java
feat(jans-auth-server): improve client assertion creation code (ClientAuthnRequest) #1182
> feat(jans-auth-server): improve client assertion creation code #1182

- jans-auth-server/common/src/main/java/io/jans/as/common/model/stat/StatEntry.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatResponseService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatService.java
- jans-linux-setup/jans_setup/schema/jans_schema.json
- jans-linux-setup/jans_setup/static/opendj/101-jans.ldif
fix(jans-auth-server) : for mysql backend /stats endpoint produce incorrect response #1686
> fix(jans-auth-server) : for mysql backend /stats endpoint produce incorrect response #1686

- docs/admin/developer/scripts/application-session.md
> docs: Added interception script template headers

- .github/workflows/build-packages.yml
> ci: added distutils package install for py3.6

- jans-auth-server/server/pom.xml
- jans-auth-server/server/src/test/java/io/jans/as/server/model/TClientService.java
- jans-auth-server/server/src/test/java/io/jans/as/server/util/JSONObjectAsserter.java
- jans-auth-server/server/src/test/java/io/jans/as/server/util/ResponseAsserter.java
- jans-auth-server/server/src/test/java/io/jans/as/server/util/TestUtil.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/AuthorizationCodeFlowEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/AuthorizeRestWebServiceEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/AuthorizeWithResponseModeEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/ClientAuthenticationFilterEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/ClientInfoRestWebServiceEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/EndSessionRestWebServiceEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/OpenIDRequestObjectEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/OpenIDRequestObjectWithESAlgEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/OpenIDRequestObjectWithRSAlgEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/RegistrationRestWebServiceEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/TokenRestWebServiceEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/UserAuthenticationFilterEmbeddedTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/UserInfoRestWebServiceEmbeddedTest.java
fix(jans-auth-server): removed jans-auth-client test dependency #1723
> fix(jans-auth-server): removed jans-auth-client test dependency #1723

- docs/admin/integration/casa.md
Install and quick configure casa #1758
> docs: Update casa.md

- docs/admin/developer/scripts/application-session.md
- [ x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)
Corrected the header outline for Interception Scripts
> docs: corrected template headers

- README.md
- docs/CONTRIBUTING.md
- Added glossary of terms to bring consistency in usage
- Updated README to reflect correct module names consistent with code
> docs: update contribution guidelines for docs

- docs/admin/integration/casa.md
> docs(casa): fixed incorrect URL #1758

- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java
fix(jans-auth-server): fixed NPE during getting AT lifetime #1233
> fix(jans-auth-server): fixed NPE during getting AT lifetime #1233

- jans-scim/client/src/test/resources/single/user_minimal_web_login.json
> fix: test data for login

- jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidator.java
- jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidatorTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/util/TestUtil.java
- jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): improved TokenRestWebServiceValidator and added test for it 
#1591
Unified grant type validation and removed duplicated code for it. Added detailed test to this validator.
- [-] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)
> feat(jans-auth-server): improved TokenRestWebServiceValidator and added test for it  #1591

- docs/CONTRIBUTING.md
Added guidelines around documentation commit in CONTRIBUTING.md
closes #1796
> docs: document docs commit check

- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/WebKeysTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/dpop/DpopTokenRequestHttpTest.java
https://github.com/JanssenProject/jans/issues/1784
Use java.security instead of sun.security
> FIX / Fixed package sun.security

- jans-linux-setup/jans_setup/scan/static/extension/update_token/UpdateToken.py
Script not loading because of indentation
> fix: indentation

- README.md
> docs: add artifact link and latest release

- docs/admin/developer/agama/dsl-full.md
- docs/admin/developer/agama/flows-lifecycle.md
- docs/admin/developer/agama/index.md
- docs/admin/developer/agama/ui-pages.md
> docs(agama): add sample flows to docs

- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java
- jans-auth-server/server/src/test/java/io/jans/as/server/servlet/OpenIdConfigurationTest.java
- jans-auth-server/server/src/test/resources/testng.xml
- jans-config-api/docs/jans-config-api-swagger.yaml
Removed id_generation_endpoint and other claims from discovery response
#1827
> feat(jans-auth-server): removed id_generation_endpoint and other claims from discovery response #1827

- jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
> feat(jans-linux-setup): added discoveryDenyKeys #1827

- jans-linux-setup/jans_setup/scan/static/extension/update_token/UpdateToken.py
- jans-linux-setup/jans_setup/static/extension/update_token/UpdateToken.py
- jans-linux-setup/jans_setup/templates/scripts.ldif
Feat: as described in https://github.com/GluuFederation/oxAuth/issues/1695
Closes #1820
Closes #1854
> feat: jans-linux-setup Script for Keystroke Authentication

- docker-jans-persistence-loader/Dockerfile
Closes #1820 
Synchronize templates from `jans-linux-setup` to `docker-jans-persistence-loader` image
Closes #1858, 
Closes #1859,
> build: sync scan_update_token script #1820

- docs/admin/developer/scripts/openid-config.md
Added a new header and placeholders
> docs: update openid-config.md

- jans-orm/filter/pom.xml
- jans-orm/filter/src/test/java/io/jans/orm/search/filter/FileProcessorTest.java
- jans-orm/filter/src/test/resources/testng.xml
- jans-orm/pom.xml
- jans-orm/util/pom.xml
- jans-orm/util/src/main/java/io/jans/orm/util/StringHelper.java
- jans-orm/util/src/test/java/io/jans/orm/util/StringHelperTest.java
- jans-orm/util/src/test/resources/testng.xml
Fixed npe in filter processor
https://github.com/JanssenProject/jans/issues/1868
Closes #1870,
> fix(jans-orm): fixed npe in filter processor and covered with tests

- docs/mkdocs.yml
Updating the filepaths to hopefully resolve #1894 .
> docs: Updating filepaths to logo and favicon

- docs/admin/developer/agama/logging.md
- docs/admin/developer/agama/samples.md
This finalizes the error log updates. Fixes #1885
> Docs link fixes

- docs/admin/config-guide/jans-cli/index.md
- docs/mkdocs.yml
> Docs img rename yml

- jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ConfigurationRestWebServiceHttpTest.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(jans-auth-server): increased period of session authn time check
closes #1873
> fix(jans-auth-server): increased period of session authn time check

- docs/admin/developer/agama/dsl-full.md
- docs/admin/developer/agama/dsl.md
- docs/admin/developer/agama/faq.md
- docs/admin/developer/agama/logging.md
- docs/admin/developer/agama/quick-start.md
- docs/admin/developer/agama/ui-pages.md
> docs(agama): work on TODOs

- jans-core/service/src/test/java/io/jans/service/cache/SampleSessionId.java
Removed redundant reference #1927
closes #1927
> fix(jans-core): removed redundant reference #1927

- docs/mkdocs.yml
> docs: Corrected spacing on yaml hierarchy

- docs/admin/install/helm-install/local.md
- docs/admin/install/helm-install/rancher.md
- docs/admin/install/index.md
- docs/admin/install/vm-install/dynamic-download.md
- docs/admin/install/vm-install/rhel.md
- docs/admin/install/vm-install/suse.md
- docs/admin/install/vm-install/ubuntu.md
- docs/admin/install/vm-install/vm-requirements.md
Moved [installation instructions](https://github.com/JanssenProject/jans/wiki#janssen-installation) from Wiki.
Closes #1936,
> Docs: move install instructions from Wiki to repo

- .github/workflows/central_code_quality_check.yml
- .github/workflows/docker_build_image.yml
- .github/workflows/docs.yml
> ci: use gh pr view

- jans-auth-server/server/pom.xml
- jans-bom/pom.xml
- jans-config-api/server/pom.xml
- jans-core/script/pom.xml
- jans-scim/service/pom.xml
Remove deprecated apns library and use jython from jans repo
> Remove apns #1978 and use right jython #1980

- docs/admin/install/index.md
Added links under cloud section of installation map table
closes #1983
> docs: add links for public cloud installation

- docs/admin/install/index.md
Need to add relevant links to documentation
closes #1989 
Added missing links to relevant pages
> docs: add links to relevant docs in index page

- jans-linux-setup/jans_setup/templates/apache/httpd_2.4.conf
Fix apache config
Closes #1988,
> fix: jans-linux-setup add mod_rewrite to httpd_2.4.conf

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-pycloudlib-fix

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
- jans-pycloudlib/jans/pycloudlib/pki.py
- jans-pycloudlib/tests/test_pki.py
closes #2003 
Fixed by adding fallback value if type is mismatch.
> fix(pycloudlib): handle type mismatch for iterable

- agama/engine/src/main/java/io/jans/agama/engine/service/FlowService.java
- docs/admin/developer/agama/engine-config.md
> chore(agama): remove usage of classes in com.sun package

- docs/governance/testing.md
[Testing](https://github.com/JanssenProject/jans/blob/main/docs/governance/testing.md) guidelines need to include instructions for how to test documentation changes locally.
closes #2011 
add details in [Testing.md](https://github.com/JanssenProject/jans/blob/main/docs/governance/testing.md)
> docs: add documentation testing instructions

- docs/admin/config-api/plugins.md
Updated Jans Config Api Plugin documentation
closes #2019 
Updated Jans Config Api Plugin documentation
Reviewed the document for spelling and grammar as well as tested the standalone content using Mkdocs
> docs(jans-config-api): doc for plugin development

- jans-auth-server/model/src/main/java/io/jans/as/model/common/CreatorType.java
- jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/Scope.java
- jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ScopeAttributes.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/SpontaneousScopeService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaPermissionService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaScopeService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaValidationService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/uma/ws/rs/UmaResourceRegistrationWS.java
- jans-linux-setup/jans_setup/schema/jans_schema.json
feat(jans-auth-server): added creator info to scope (time/id/type) 
closes #1934
> feat(jans-auth-server): added creator info to scope (time/id/type) #1934

- agama/model/src/main/java/io/jans/agama/model/EngineConfig.java
- docs/admin/developer/agama/test
- jans-auth-server/server/conf/jans-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
> chore(agama): use Cache-Control instead of Expires header

- mkdocs.yml
[](https://github.com/JanssenProject/jans/issues/2049)
closes #2049 
> docs: updated config to enable Mermaid charts

- mkdocs.yml
> docs: corrected mistake from Mkdocs docs

- docs/admin/auth-server/oauth-features/device-grant.md
Proof of concept converting the Device Auth sequence diagram to mermaid.js.
https://github.com/JanssenProject/jans/issues/2055
closes #2055 
> docs: updated sequence diagram for mkdocs mermaid

- docs/admin/auth-server/oauth-features/device-grant.md
Corrected specific instance syntax for Mkdocs Mermaid.
https://github.com/JanssenProject/jans/issues/2055
closes #2055 
> docs: corrected syntax for mkdocs mermaid SD

- jans-linux-setup/jans_setup/jans_setup.py
- jans-linux-setup/jans_setup/setup_app/utils/base.py
Closes https://github.com/JanssenProject/jans/issues/2065
Closes #2067,
> fix: jans-linux-setup humanize os name

- docs/admin/config-guide/curl.md
> docs: #2069

- docs/stylesheets/mermaid-extra.css
- mkdocs.yml
https://github.com/JanssenProject/jans/issues/2075
closes #2075 
> Docs: mermaid css stylesheet

- jans-auth-server/client/src/test/resources/testng.xml
test(jans-auth-server): disabled DefaultPromptLoginTest 
closes #2073
> test(jans-auth-server): disabled DefaultPromptLoginTest #2073

- jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py
- jans-pycloudlib/jans/pycloudlib/persistence/spanner.py
- jans-pycloudlib/jans/pycloudlib/persistence/sql.py
- jans-pycloudlib/jans/pycloudlib/utils.py
- jans-pycloudlib/tests/conftest.py
> refactor: handle code smells reported by bandit

- jans-linux-setup/jans_setup/openbanking/templates/scopes.ldif
- jans-linux-setup/jans_setup/templates/scopes.ldif
> feat: add inum claim in profile scope #2095

- agama/engine/src/main/java/io/jans/agama/timer/Transpilation.java
- agama/transpiler/src/main/resources/JSGenerator.ftl
- docs/admin/developer/agama/quick-start.md
- jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaResource.java
> chore(agama): grammar cleaning

- jans-orm/core/src/main/java/io/jans/orm/PersistenceEntryManager.java
- jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
Reffactor code to allow use methods to work with custom attributes list
> feat: add new methods to allow get/set list of custom attributes from

- jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
- jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py
Closes https://github.com/JanssenProject/jans/issues/2101
Closes #2103,
> fix: random password for keystores

- docker-jans-auth-server/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-config-api/clients.ldif
- docker-jans-persistence-loader/templates/jans-config-api/clients.ob.ldif
- docker-jans-persistence-loader/templates/jans-config-api/dynamic-conf.json
- docker-jans-persistence-loader/templates/scripts.ob.ldif
- docker-jans-scim/Dockerfile
> chore: sync templates and schema from jans-linux-setup

- jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
Fixed ORM ConcurrentModificationException  issue while token generation
closes #2137
Fixed attribute iteration logic
> fix(jans-orm): use iterator to correctly to remove OC attribute

- docs/admin/recipes/social-login-apple.md
- docs/admin/recipes/social-login-google.md
- docs/admin/recipes/social-login.md
> docs: #2146

- docs/admin/recipes/social-login.md
> docs: #2146 link corrected

- docs/admin/developer/interception-scripts.md
- docs/admin/developer/managed-beans.md
> fix: #2157

- jans-linux-setup/jans_setup/setup_app/data/package_list.json
- jans-linux-setup/jans_setup/setup_app/utils/base.py
> fix: jans-linux-setup debian11 installation

- .gitignore
- jans-auth-server/server/conf/jans-couchbase.properties
- jans-linux-setup/jans_setup/templates/jans-couchbase.properties
- jans-orm/couchbase/src/main/java/io/jans/orm/couchbase/impl/CouchbaseEntryManagerFactory.java
Disable TLS in CB client by default
Closes #2168,
> feat: disable TLS in CB client by default

- jans-orm/couchbase/src/main/java/io/jans/orm/couchbase/operation/impl/CouchbaseOperationServiceImpl.java
- jans-orm/spanner/src/main/java/io/jans/orm/cloud/spanner/operation/impl/SpannerOperationServiceImpl.java
https://github.com/JanssenProject/jans/issues/2170
> fix: don't execute next paged search if current result count less than

- docs/CONTRIBUTING.md
Need to add technical writing resources to CONTRIBUTING.md
closes #2174
> docs: add technical writing resources to CONTRIBUTING.md

- .gitignore
- jans-orm/spanner-sample/src/main/java/io/jans/orm/cloud/spanner/SpannerClientSample.java
- jans-orm/spanner/src/main/java/io/jans/orm/cloud/spanner/operation/impl/SpannerOperationServiceImpl.java
Update count(*) to conform latest Spanner API #2179
> Spanner count fix

- jans-config-api/docs/jans-config-api-swagger.yaml
> fix (jans-config-api) : incorrect request parameter added to scope apis (swagger specs) #2176

- agama/engine/src/main/java/io/jans/agama/engine/script/LogUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ActionService.java
- agama/engine/src/main/java/io/jans/agama/engine/service/AgamaPersistenceService.java
- agama/transpiler/src/main/resources/JSGenerator.ftl
- docs/admin/developer/agama/flows-lifecycle.md
- docs/admin/developer/agama/ui-pages.md
> bug(agama): changes in maxItemsLoggedInCollections not picked when using Log

- agama/inboundID/CustomMappings.java.txt
- agama/inboundID/pom.xml
- agama/inboundID/src/main/java/io/jans/inbound/Attrs.java
- agama/inboundID/src/main/java/io/jans/inbound/IdentityProcessor.java
- agama/inboundID/src/main/java/io/jans/inbound/Mappings.java
- agama/inboundID/src/main/java/io/jans/inbound/Provider.java
- agama/inboundID/src/main/java/io/jans/inbound/oauth2/CodeGrantUtil.java
- agama/inboundID/src/main/java/io/jans/inbound/oauth2/OAuthParams.java
- agama/inboundID/src/main/java/io/jans/util/NetworkUtils.java
- agama/pom.xml
- agama/transpiler/src/main/java/io/jans/agama/dsl/Visitor.java
- docs/admin/developer/agama/basic/login.ftlh
- docs/admin/developer/agama/otp-email-registration/confirmation.ftlh
- docs/admin/developer/agama/otp-email-registration/login.ftlh
- docs/admin/developer/agama/otp-email/otp.ftlh
- docs/admin/developer/agama/registration/confirmation.ftlh
- docs/admin/developer/agama/registration/index.ftlh
- docs/script-catalog/agama/inboundID/README.md
- jans-bom/pom.xml
> feat(agama): add utility classes for inbound identity

- docs/CONTRIBUTING.md
- docs/developer/testing.md
add details about local testing of documentation
closes #2209
> docs: update testing instructions

- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/profiles/local/test.properties
Synched swagger spec scheme with Auth App Configuration 
closes #2211
> fix(config-api): fixing discrepancies in the api

- docs/admin/reference/database/ldap-schema.md
> docs: ldap schema #2208

- agama/inboundID/CustomMappings.java.txt
- docs/admin/developer/agama/dsl-full.md
- docs/script-catalog/agama/inboundID/README.md
> docs: add instructions to setup inbound identity flows

- docs/script-catalog/agama/inboundID/README.md
> docs: rework inbound identity README #2198

- docs/CONTRIBUTING.md
- docs/admin/config-guide/jans-cli/cli-group.md
- docs/admin/config-guide/jans-cli/cli-smtp-configuration.md
- docs/admin/config-guide/jans-cli/cli-user.md
- docs/admin/config-guide/jans-cli/im/im-custom-scripts.md
- docs/admin/config-guide/jans-cli/im/im-janssen-fido2.md
- docs/admin/config-guide/jans-cli/im/im-uma-resources.md
- docs/admin/developer/agama/dsl.md
- docs/admin/developer/agama/engine-config.md
- docs/admin/developer/interception-scripts-debug.md
- docs/admin/integration/passport-js.md
- docs/admin/recipes/custom-web-development/authn-with-apache-reverse-proxy.md
- docs/admin/recipes/passportjs.md
- docs/admin/recipes/social-login-apple.md
- docs/script-catalog/client_registration/OpenBanking/client-registration.md
- mkdocs.yml
add missing files and config entries in mkdocs.yml
closes #2219 
- added `admin/developer/managed-beans.md` to `admin/developer/scripts`
- added `admin/reference/kubernetes/image-config-init.md` to `ref guide -> kubernetes -> image conf properties `
> docs: add missing files and config entries

- docs/admin/integration/casa.md
This merge includes formatting updates for the Casa integration doc.
#2224 2224
closes #2224 
> docs: formatting updates to casa integration doc

- docs/admin/integration/casa.md
Updating ordered list missed in previous PR.
#2224 
closes #2224
> docs: corrected formatting in ordered list

- docs/script-catalog/agama/inboundID/README.md
> docs: minor update to inbound identity with agama

- jans-bom/pom.xml
> chore: update jackrabbit

- jans-linux-setup/jans_setup/setup_app/installers/jans.py
closes https://github.com/JanssenProject/jans/issues/2275
> fix: jans-linux-setup Config API installation status

- docs/script-catalog/agama/inboundID/apple/README.md
> docs(agama): add sample flows for inbound identity

- jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
- jans-orm/couchbase/src/main/java/io/jans/orm/couchbase/impl/CouchbaseEntryManager.java
- jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java
- jans-scim/model/src/main/java/io/jans/scim/model/scim/ScimCustomPerson.java
Issue: https://github.com/JanssenProject/jans/issues/2297
> feat: update search by example to use multivalued property

- jans-cli/cli/config_cli.py
> fix: jans-cli tabulate attrbiutes

- docs/admin/developer/agama/dsl-full.md
- jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
> fix(jans-linux-setup): review columns size for Agama tables

- jans-auth-server/server/src/main/java/io/jans/as/server/exception/GlobalExceptionHandler.java
chore(jans-auth-server): avoid redirect exception logging on every authn #2287
closes #2287
- []  Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)
> chore(jans-auth-server): avoid redirect exception logging on every authn #2287

- jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
> fix: jans-linux-setup install cb via apt for dependencies

- docs/admin/developer/agama/dsl-full.md
> docs(agama): add limitation of call directive

- docs/admin/config-guide/jans-cli/cli-attribute.md
Edit document for getting attirbutes, since swagger definitions were changed.
> fix: docs jans-cli 

- jans-cli/cli/config_cli.py
> fix: jans-cli access token expiration

- docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> docs: moving fido2 under path

- docs/script-catalog/person_authentication/duo-external-authenticator/README.md
> docs: diagram not rendering

- docs/script-catalog/person_authentication/duo-external-authenticator/README.md
Correct arrow syntax on flowchart on Duo External Authenticator page.
#2375 2375
closes #2375
> docs: corrected flowchart syntax

- docs/script-catalog/update_token/sample-script/README.md
> docs: UpdateToken script

- docs/admin/README.md
- docs/admin/index.md
- mkdocs.yml
Added a placeholder page for the admin guide landing page (full page in progress)
#2379 
closes #2379 
> Docs admin landing page

- docker-jans-persistence-loader/templates/jans-config-api/clients.ldif
- docker-jans-persistence-loader/templates/jans-config-api/clients.ob.ldif
- docs/admin/config-guide/jans-cli/cli-openid-connect-client-configuration.md
- docs/admin/config-guide/jans-cli/im/im-openid-connect-clients.md
- docs/admin/recipes/custom-web-development/authn-with-apache-reverse-proxy.md
- docs/script-catalog/client_registration/OpenBanking/Registration.py
- docs/script-catalog/client_registration/OpenBanking/client-registration.md
- jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
- jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java
- jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java
- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterJsonService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java
- jans-config-api/docs/jans-config-api-swagger-auto.yaml
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/server/src/test/resources/feature/openid/clients/client.json
- jans-config-api/server/src/test/resources/feature/openid/clients/openid-client.json
- jans-config-api/server/src/test/resources/feature/openid/clients/openid_clients_create.json
- jans-linux-setup/jans_setup/openbanking/static/extension/client_registration/Registration.py
- jans-linux-setup/jans_setup/setup_app/installers/config_api.py
- jans-linux-setup/jans_setup/templates/jans-cli/client.ldif
rename runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims to runIntrospectionScriptBeforeJwtCreation #2387
closes #2387
> chore(jans-auth-server): rename runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims to runIntrospectionScriptBeforeJwtCreation #2387

- jans-auth-server/model/src/main/java/io/jans/as/model/uma/persistence/UmaResource.java
- jans-auth-server/server/src/main/java/io/jans/as/server/uma/ws/rs/UmaResourceRegistrationWS.java
Removed "rev" attribute from UmaResource as redundant #2392
closes #2392
> chore(jans-auth-server): remove "rev" attribute from UmaResource as redundant #2392

- jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/UserWebService.java
- jans-scim/server/src/main/resources/jans-scim-openapi.yaml
- jans-scim/server/src/main/resources/jans-scim-swagger.yaml
> fix: update authn schemes in yaml descriptor #2414

- docs/developer/implementation-design/jans-scim.md
- jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/ScimResourcesUpdatedWebService.java
> fix(jans-scim): improper handling response of get user operation

- jans-linux-setup/jans_setup/install.py
- jans-linux-setup/jans_setup/setup_app/data/package_list.json
> fix: jans-linux-setup python3-psycopg2

- docs/admin/developer/agama/lifecycle.md
- docs/admin/developer/agama/quick-start.md
> docs(agama): clarify how to specify the flow to launch in authorization request

- jans-linux-setup/jans_setup/install.py
> fix: jans-linus-setup typo

- jans-cli/README.md
> docs(jans-cli): fix broken link

- docs/CONTRIBUTING.md
closes #2438
Added guidelines to contribution guide
> add guidelines for title and tags for documentation

- docker-jans-auth-server/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-scim/Dockerfile
- jans-pycloudlib/setup.py
closes #2435 
* upgrade Prometheus JMX exporter
* upgrade oauthlib
* upgrade to Alpine `expat` package should be taken care by image build automatically
> fix(image): handle vulnerabilities reported by artifacthub scanner

- docker-jans-auth-server/Dockerfile
- docker-jans-client-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-scim/Dockerfile
> chore(images): sync templates and static manifests

- jans-auth-server/server/src/test/resources/testng.xml
test(jans-auth-server): disable application type restriction embedded test
docs: no docs
https://github.com/JanssenProject/jans/issues/2087
closes #2087
> test(jans-auth-server): disable application type restriction embedded test

- jans-cli/cli/config_cli.py
- jans-config-api/docs/jans-config-api-swagger.yaml
> fix: jans-config-api parameter month is not mandatory for endpoint /stat

- jans-linux-setup/jans_setup/static/extension/person_authentication/other/forgot_password/forgot_password.py
> fix(forgot_password): update script according to jans specs

- jans-linux-setup/jans_setup/setup_app/installers/config_api.py
- jans-linux-setup/jans_setup/setup_app/installers/scim.py
- jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py
- jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
> feat: jans-linux-setup delete_dn()

- docs/script-catalog/person_authentication/duo-external-authenticator/README.md
> docs: mentioning the link to the mobile app

- docs/admin/reference/openapi.md
closes #2461 
Moved details from Janssen Wiki
> docs: add API reference content

- docs/script-catalog/person_authentication/duo-external-authenticator/README.md
> docs: script link fixed

- docs/script-catalog/update_token/sample-script/README.md
> docs: corrections and additional notes

- jans-linux-setup/jans_setup/setup_app/config.py
- jans-linux-setup/jans_setup/setup_app/utils/base.py
- jans-linux-setup/jans_setup/setup_app/utils/crypto64.py
> Jans linux setup utils

- README.md
- docs/developer/README.md
- docs/governance/README.md
> Refresh links and sections in Jans README

- jans-scim/client/src/test/java/io/jans/scim2/client/search/ComplexSearchUserTest.java
- jans-scim/client/src/test/java/io/jans/scim2/client/singleresource/FullUserTest.java
- jans-scim/model/src/main/java/io/jans/scim/model/scim2/user/UserResource.java
> chore(jans-scim): sync wrt latest changes in gluu-scim

- docker-jans-monolith/README.md
As in target issue
closes #2489
> docs: fix container name in quick start

- jans-cli/README.md
> Add remote connection section

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java
fix(jans-auth-server): perform redirect_uri validation if FAPI flag is true #2500
closes #2500
> fix(jans-auth-server): perform redirect_uri validation if FAPI flag is true #2500

- jans-linux-setup/jans_setup/setup_app/installers/fido.py
> fix: jans-linux-setup upgrade to MDS3 in fido2

- docker-jans-monolith/README.md
Corrected the yaml file name in the clean-up command
closes #2512 
> fix: correct yml file name in clean-up command

- jans-cli/README.md
CentOS Stream 8 build instruction was added to CLI
> jans-cli CentOS Stream 8 build instruction

- jans-cli/cli/config_cli.py
closes #2400
closes #2516 
closes #2336
> fix: jans-cli fixes

- jans-linux-setup/jans_setup/setup_app/installers/node.py
closes https://github.com/JanssenProject/jans/issues/2521
> fix: jans-linux-setup typo

- docker-jans-fido2/Dockerfile
> feat: sync mds v3 config in fido2 image

- README.md
- docs/admin/install/vm-install/quick-start-install.md
- mkdocs.yml
As in target issue
closes #2482
> docs: add quick start guide

- docs/admin/install/install-faq.md
As in target issue
closes #2535 
> docs: add health check endpoint to FAQ

- jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
https://github.com/JanssenProject/jans/issues/1482
> fix: localized String should be converted to JSON

- jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/Ssa.java
- jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/SsaAttributes.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaJsonService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaJsonServiceTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateActionTest.java
- jans-linux-setup/jans_setup/schema/jans_schema.json
Added schema for ssa, corrected persistence, added ttl #2543
closes #2543
> fix(jans-auth-server): added schema for ssa, corrected persistence, added ttl #2543

- docs/developer/developer-faq.md
- docs/developer/testing.md
move wiki content for setting up the Janssen Server open banking for testing
closes #2550 
> docs: move wiki content for setting up the Janssen Server open banking for testing

- jans-scim/server/src/main/java/io/jans/scim/service/scim2/ExternalConstraintsService.java
> chore(jans-scim): log warning when no token details can be obtained when creating context for scim custom script

- docs/admin/install/vm-install/quick-start-install.md
> docs: update title and remove mention of OS

- jans-cli/cli/config_cli.py
> fix: jans-cli info for ConfigurationAgamaFlow

- jans-auth-server/server/src/main/java/io/jans/as/server/model/config/ConfigurationFactory.java
chore(jans-auth-server): when configuration load is failed print full stack trace 
closes #2583
> chore(jans-auth-server): when configuration load is failed print full stack trace #2587

- docs/admin/install/vm-install/suse.md
- docs/admin/install/vm-install/ubuntu.md
Add Janssen Server installation instructions for SLES
closes #2600 
> docs: need Janssen Server installation instructions for SLES

- jans-auth-server/pom.xml
- jans-bom/pom.xml
- jans-core/pom.xml
- jans-fido2/pom.xml
- jans-orm/pom.xml
https://github.com/JanssenProject/jans/issues/2606
chore: updated repo2.maven.org with repo1.maven.org
closes #2606
> chore: updated repo2.maven.org with repo1.maven.org

- docs/README.md
- docs/admin/developer/agama/engine-config.md
- docs/admin/developer/agama/hello-world-closer.md
- docs/admin/developer/agama/logging.md
- docs/admin/developer/agama/ui-pages.md
- docs/admin/developer/scripts/person-authentication.md
- docs/script-catalog/README.md
- docs/script-catalog/update_token/sample-script/README.md
Fixing broken links in various documents
> docs: fix broken links

- jans-bom/pom.xml
https://github.com/JanssenProject/jans/issues/2609
chore(jans-bom): upgraded jackson to 2.14.0-rc2
closes #2609
> chore(jans-bom): upgraded jackson to 2.14.0-rc2

- docs/admin/install/vm-install/dynamic-download.md
> docs: add details to dynamic download installation

- docs/admin/developer/agama/faq.md
- docs/admin/developer/agama/flows-lifecycle.md
- docs/admin/developer/agama/ui-pages.md
> docs: broken links in Agama docs

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
closes #2612 
1. Synchronized templates from upstream.
2. On fresh setup, SSA configuration are loaded from templates
3. On existing setup, missing SSA configuration will be added into persistence
> fix(image): add missing ssa configuration

- jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
https://github.com/JanssenProject/jans/issues/2560
fix(jans-auth-server): PKCE parameters from first SSO request retains in futher calls #2560
closes #2560
> fix(jans-auth-server): PKCE parameters from first SSO request retains in further calls

- jans-client-api/server/pom.xml
https://github.com/JanssenProject/jans/issues/2621
chore(jans-auth-server): upgrade protobuf dependency #2621
closes #2621
> chore(jans-auth-server): upgrade protobuf dependency #2621

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-client-api/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-postgres-manifests

- docs/admin/planning/components.md
- docs/admin/planning/use-cases.md
2631 
closes #2631 
closes #2619 
> docs: moved over Mike's changes from PR 2619

- docs/admin/planning/persistence.md
- docs/admin/planning/vm-cluster.md
Overview of database options.
[Docs Planning Guide](https://github.com/JanssenProject/jans/issues/2628)
Added details about various database options.
> Docs / Planning Guide: Persistence

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-jsonb-default-values

- agama/engine/src/main/java/io/jans/agama/engine/misc/PrimitiveUtils.java
- agama/engine/src/main/java/io/jans/agama/engine/service/ActionService.java
> chore(agama): log signature of the actual Java method picked when using Call

- docs/admin/auth-server/endpoints/client-registration.md
> docs: Explaining DCR

- docs/admin/reference/database/mysql-schema.md
> docs: ER diagram

- agama/engine/pom.xml
- agama/engine/profiles/default/config-agama-test.properties
- agama/engine/src/main/java/io/jans/agama/engine/service/ActionService.java
- agama/engine/src/test/java/io/jans/agama/test/BaseTest.java
- agama/engine/src/test/java/io/jans/agama/test/CustomConfigsFlowTest.java
- agama/engine/src/test/java/io/jans/agama/test/MathFlowTest.java
- agama/engine/src/test/java/io/jans/agama/test/SaySomething2FlowTest.java
- agama/engine/src/test/java/io/jans/agama/test/SaySomething3FlowTest.java
- agama/engine/src/test/java/io/jans/agama/test/SaySomethingFlowTest.java
- agama/engine/src/test/java/io/jans/agama/test/UidOnlyAuthTest.java
- agama/engine/src/test/resources/flows/io.jans.agama.test.auth.uidOnly
- agama/engine/src/test/resources/flows/io.jans.agama.test.math
- agama/engine/src/test/resources/flows/io.jans.agama.test.showConfig
- agama/engine/src/test/resources/flows/org.gluu.flow1
- agama/engine/src/test/resources/flows/org.gluu.flow2
- agama/engine/src/test/resources/flows/org.gluu.flow3
- agama/engine/src/test/resources/log4j2-test.xml
- agama/engine/src/test/resources/templates/custom/printConfigs.ftlh
- agama/engine/src/test/resources/templates/f1/index.ftl
- agama/engine/src/test/resources/templates/f1/index2.ftl
- agama/engine/src/test/resources/templates/hello/index.ftlh
- agama/engine/src/test/resources/templates/login.ftlh
- agama/engine/src/test/resources/templates/me/myindex.ftlh
- agama/engine/src/test/resources/testng.properties
- agama/engine/src/test/resources/testng.xml
- docs/admin/developer/agama/dsl-full.md
> chore(agama): add test cases for agama engine

- jans-scim/server/src/main/java/io/jans/scim/service/scim2/UserPersistenceHelper.java
> chore(jans-scim): reduce log noise on user lookup by inum

- jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
- jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
> fix: jans-linux-setup test data load

- docs/admin/planning/caching.md
- docs/admin/planning/load-balancers.md
- docs/admin/planning/security-best-practices.md
- docs/admin/planning/vm-cluster.md
Initial checkin for these docs
[Caching](https://github.com/JanssenProject/jans/issues/2628)
ues/tracking-your-work-with-issues/about-task-lists -->
Initial content for these pages. 
> docs: Planning Guide: Cache, LB, Security Best Practices

- docs/admin/install/vm-install/vm-requirements.md
Updated old, inaccurate information
[docs: Fix VM Install Docs #2703)](https://github.com/JanssenProject/jans/issues/2703)
Removed old info about static IP, wrong firewall ports, wrong operating system versions, extraneous information about firewalls and  other vestigual info.
> docs: Fix VM requirements

- docs/admin/install/vm-install/README.md
- docs/admin/install/vm-install/ubuntu.md
- docs/admin/planning/load-balancers.md
- docs/admin/planning/security-best-practices.md
Improved readability
[Fix Install Docs](https://github.com/JanssenProject/jans/issues/2703)
Improved for readability and consistency
> docs: fixes to Ubuntu install

- docs/admin/install/vm-install/rhel.md
- docs/admin/install/vm-install/suse.md
- docs/admin/install/vm-install/ubuntu.md
Made some small improvements to VM install for Ubuntu, RHEL and SUSE
[Fix Install Docs](https://github.com/JanssenProject/jans/issues/2703)
Simplified VM install docs: three step process: install package, run setup, test
> Improved VM Install docs

- docs/admin/planning/certificates-keys.md
- docs/admin/planning/dns.md
Initial Checkins
Wrote the initial pages for the planing guide for DNS and Key/Certificates
Initial pages... just a starting point. 
> Certs and DNS Planning Pages

- jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
- jans-linux-setup/jans_setup/setup_app/installers/jetty.py
- jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
- jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py
> feat: jans-linux-setup external CB/Spanner libs

- docs/admin/planning/load-balancers.md
- docs/admin/planning/multi-tenancy.md
Initial draft for multitenancy 
Initial draft for multitenanchy
> docs: Mulitenancy Doc

- docs/admin/install/vm-install/rhel.md
- docs/admin/install/vm-install/suse.md
- docs/admin/install/vm-install/ubuntu.md
Minor edits
- correct fomatting for `notes`
- point to correct file for setup instructions
> docs: minor edits to install docs

- mkdocs.yml
> docs: fix syntax issue in mkdocs config file

- mkdocs.yml
Jans Docs navigation contained a broken link because of a reference to a page that no longer exists. 
https://github.com/JanssenProject/jans/issues/2745
closes #2745 
> docs: Removed incorrect index.md reference

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-scopes

- jans-linux-setup/jans_setup/templates/scopes.ldif
Native SSO
https://github.com/JanssenProject/jans/issues/2518
Added device_sso scope.
closes #2765
> feat(jans-linux-setup): added device_sso scope

- docs/admin/planning/customization.md
This was a demo of how to checkin docs.
This was just a demo docs checkin.
> docs: Demo merge : Customizations 

- docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
> docs: Update README.md

- docs/admin/developer/interception-scripts.md
- docs/admin/planning/customization.md
- docs/admin/planning/timeout-management.md
initial checkin of customization and timeout pages.
Initial checkin. Timeout page still needs work. 
> Customization / Timeouts

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
> feat(image): add token-exchange and device secret

- jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/issues/2793
NPE during OB discovery #2793
closes #2793
> fix(jans-auth-server): NPE during OB discovery #2793

- docs/admin/auth-server/endpoints/client-registration.md
- docs/admin/developer/customization/customize-web-pages.md
- docs/admin/developer/interception-scripts.md
- docs/admin/developer/scripts/person-authentication.md
> fix: minor edits

- jans-auth-server/server/src/test/java/io/jans/as/server/util/TestUtil.java
test(jans-auth-server): fix TokenExchangeServiceTest (native sso) #2829
closes #2829
> test(jans-auth-server): fix TokenExchangeServiceTest (native sso) #2829

- docs/admin/developer/interception-scripts.md
- docs/admin/vm-ops/checking-service-status.md
- docs/admin/vm-ops/logs.md
- docs/admin/vm-ops/restarting-services.md
Adds documentation on VM operations such as logging, service commands and fixes formatting in the interception script overview doc.
closes #2831 
NA
> docs: vm operation

- jans-linux-setup/jans_setup/setup_app/installers/jetty.py
- jans-linux-setup/jans_setup/templates/jetty/default_webcontext.xml
> fix: jans-linux-setup render webapps.xml

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-pycloudlib-spanner-search

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
- jans-pycloudlib/jans/pycloudlib/persistence/spanner.py
> fix(pycloudlib): searching values from spanner returns empty set

- docker-jans-fido2/Dockerfile
- docker-jans-scim/Dockerfile
> fix(image): add missing write access in filesystem

- docker-jans-scim/Dockerfile
> build(image): trailing character prevent SCIM image rebuild

- jans-auth-server/client/src/main/java/io/jans/as/client/BaseResponse.java
- jans-auth-server/client/src/main/java/io/jans/as/client/ssa/create/SsaCreateClient.java
- jans-auth-server/client/src/main/java/io/jans/as/client/ssa/validate/SsaValidateClient.java
- jans-auth-server/client/src/main/java/io/jans/as/client/ssa/validate/SsaValidateRequest.java
- jans-auth-server/client/src/main/java/io/jans/as/client/ssa/validate/SsaValidateResponse.java
- jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaCreateRestTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaGetRestTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaValidateRestTest.java
- jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/Ssa.java
- jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/SsaState.java
- jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaErrorResponseType.java
- jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetAction.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaValidateAction.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaJsonServiceTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImplTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateActionTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaGetActionTest.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaValidateActionTest.java
- jans-linux-setup/jans_setup/schema/jans_schema.json
Implement new endpoint to validate SSA's already issued using JTI.
https://github.com/JanssenProject/jans/issues/2239
closes #2239 
https://gluu-arpine.stoplight.io/docs/ssa-1/2d1658a3842b3-validate-ssa
> SSA Validation endpoint

- docs/admin/planning/identity-access-governance.md
- docs/admin/planning/identity-management.md
- docs/admin/planning/self-service-password-2fa.md
Initial commit
Initial commit for IDM, IAG and 2FA portal pages. 
Wrote initial planning guide content for three pages: IDM, IAG and 2FA portal.
> Initial commit IDM, IAG, 2FA Portal

- docs/admin/planning/central-auth-service.md
- docs/admin/planning/role-based-access-management.md
Starting point for these topics
[Update Admin / Planning Guide](https://github.com/JanssenProject/jans/issues/2628) 
Initial checkin
> Initial checkin: RBAC, central authz

- mkdocs.yml
https://github.com/JanssenProject/jans/issues/2835
closes #2835
> docs: Fixed nav errors

- automation/startjanssendemo.sh
> fix(demo): incorrect URL to helm charts location

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
> chore(image): sync missing localized attributes for sql and spanner

- jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/GluuOrganization.java
fix(jans-auth-server): wrong import in GluuOrganization class which leads to failure on jans-config-api #2957
closes #2957
> fix(jans-auth-server): wrong import in GluuOrganization class which leads to failure on jans-config-api #2957

- docs/admin/install/setup.md
> docs: moving Manoj's commits to standard branch for refinement

- docs/admin/developer/interception-scripts.md
- docs/admin/developer/scripts/client-registration.md
- docs/admin/developer/scripts/consent-gathering.md
> docs: consent gathering script

- jans-linux-setup/jans_setup/setup_app/installers/opendj.py
> fix: jans-linux-setup remove opendj sysv script

- docs/admin/install/setup.md
> docs: Update setup.md

- docs/admin/install/install-faq.md
The specific links in this section will likely change as documentation grows
#3002 3002
closes #3002 
> docs: added link to configuration docs to FAQ

- jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
- jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImplTest.java
- jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): check offline_access implementation has all conditions defined in spec #1945
closes #1945
> feat(jans-auth-server): check offline_access implementation has all conditions defined in spec #1945

- docs/admin/reference/json/auth-server.md
- docs/admin/reference/json/fido.md
Uploading markdown generated through property documentation annotation to docs. This is an intermediate delivery while full automation is still in works. 
> Update property details

- docs/admin/install/helm-install/README.md
- docs/admin/reference/kubernetes/helm-chart.md
> docs: helm deployment

- docs/admin/auth-server/endpoints/device-authorization.md
- docs/admin/auth-server/endpoints/introspection.md
> docs: #3036 #3037

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-scim/Dockerfile
>  chore(image): add agama_flow custom parameter

- docs/admin/vm-ops/backup.md
> backup Janssen backup strategy - vm snapshot

- docs/admin/vm-ops/backup.md
> docs-backup-Janssen-strategy---zico---individual-file-system-location

- docs/admin/vm-ops/certificates.md
> docs: apache cert update - vm operation

- docs/admin/vm-ops/certificates.md
> docs: apache-cert-installation---vm-operation

- docs/admin/vm-ops/certificates.md
> docs: syntax error - cert installation - vm operation

- docs/admin/config-guide/tui.md
- mkdocs.yml
> docs: create TUI placeholder page

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
> chore(Dockerfiles): updated janspycloud build in cn-aws-secretsmanager

- jans-core/uma-rs-core/pom.xml
- jans-core/uma-rs-core/src/main/java/io/jans/ca/rs/protect/Condition.java
- jans-core/uma-rs-core/src/main/java/io/jans/ca/rs/protect/JsonLogicNode.java
- jans-core/uma-rs-core/src/main/java/io/jans/ca/rs/protect/RsResource.java
chore(jans-core): avoid jans-auth-model dependency in uma-rs-core module #2826
closes #2826
> chore(jans-core): avoid jans-auth-model dependency in uma-rs-core module #2826

- docs/admin/fido/README.md
> docs: fix the formatting

- docs/admin/reference/kubernetes/config-secret-keys.md
> docs: configmaps and secrets

- docs/admin/auth-server/README.md
- docs/admin/auth-server/config.md
- docs/admin/install/README.md
- docs/admin/vm-ops/README.md
Writing some overview docs for the summary pages. 
Writing docs for some of the summary pages. 
> Summary Page Updates

- docs/admin/config-guide/tui.md
How to install Config TUI in Jans
> docs: Jans TUI installation -- Config Guide - TUI

- docs/admin/config-guide/tui.md
> fix(docs): jans TUI installation -- Config Guide - TUI

- docs/admin/config-guide/tui.md
> fix(docs): jans TUI administration -- Config Guide - TUI -- Auth server

- jans-linux-setup/jans_setup/schema/jans_schema.json
- jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
- jans-linux-setup/jans_setup/templates/agama.ldif
> feat(jans-linux-setup): update setup to support ADS projects

- docs/admin/auth-server/endpoints/client-registration.md
> fix(docs): missing single quotes

- jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
> fix: jans-linux setup enable couchbase for packages

- docs/admin/vm-ops/certificates.md
Fixes certbot instructions and adds certificate details
closes #3279 
NA
> docs: fix certbot instructions

- jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaFlowService.java
> fix: fix config-api agama flow dn generation 

- docs/admin/developer/scripts/scim.md
> docs: moved SCIM script guide into developer guide

- docs/admin/config-guide/tui.md
> feat(docs): jans TUI SCIM configuration feature

- docs/admin/config-api/README.md
- docs/admin/config-api/attribute.md
- docs/admin/config-api/config.md
- docs/admin/config-api/openid-client.md
- docs/admin/config-api/plugins.md
- mkdocs.yml
> Docs: configapi edits

- docs/admin/reference/database/index.md
- mkdocs.yml
> docs: fix 404 errors from nav bar links

- jans-bom/pom.xml
chore(jans-bom): postgresql upgrade 42.5.0 -> 42.5.1
> chore(jans-bom): postgresql upgrade 42.5.0 -> 42.5.1

- jans-auth-server/jmeter/test/Authorization Code Flow_jans.jmx
test(jans-auth-server): prepare jmeter test for authorization code flow #3308
closes #3308
> test(jans-auth-server): prepare jmeter test for authorization code flow #3308

- docs/admin/config-guide/tui.md
> feat(docs): jans TUI SCIM configuration -- screenshot

- jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ADSDeploymentsResource.java
> chore: make ADS listing 0-based index 

- docs/admin/planning/benchmarking.md
- jans-auth-server/jmeter/test/ResourceOwnerPasswordCredentials_jans.jmx
created ROPC jmeter test
closes #3316 
> test(jans-auth-server): created ROPC jmeter test #3316

- docs/admin/developer/customization/customize-web-pages.md
#3238
1. mention of gluu instead of jans
2. added search labels to the customization-web-pages.md
> docs: minor corrections

- docs/admin/developer/customization/customize-web-pages.md
> docs: minor fixes

- docs/admin/developer/customization/customize-web-pages.md
> docs:minor

- docs/script-catalog/person_authentication/super-gluu-external-authenticator/README.md
> docs: Super Gluu interception script #3340

- docs/admin/developer/interception-scripts-debug-ce.md
> docs: debugging CE - #3257

- docs/admin/vm-ops/logs.md
> fix(docs): jans logging configuration - VM Operation Guide - 1

- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalIntrospectionService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java
feat(jans-auth-server): added ability to return error out of introspection and update_token custom script #3255
closes #3255
> feat(jans-auth-server): added ability to return error out of introspection and update_token custom script #3255

- docs/admin/developer/interception-scripts.md
- docs/admin/developer/scripts/dynamic-scope.md
Adds documentation for the Dynamic Scope script. Adapted from https://gluu.org/docs/gluu-server/4.4/admin-guide/sample-dynamic-script.py
closes #3358 
NA
> docs: dynamic scope script

- docs/README.md
- docs/admin/install/vm-install/README.md
> docs: fix link to install section

- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/model/src/main/java/io/jans/as/model/userinfo/UserInfoConfiguration.java
- jans-auth-server/server/conf/jans-config.json
- jans-auth-server/server/src/main/java/io/jans/as/server/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
- jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
feat(jans-auth-server): new configuration for userinfo has been added.
closes #3347
> Feature: Date Formatter configuration for userinfo endpoint

- jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java
fix(jans-auth-server): compilation error of server side tests #3363
closes #3363
> fix(jans-auth-server): compilation error of server side tests #3363

- docs/admin/developer/interception-scripts.md
- docs/admin/developer/scripts/post-authentication.md
> docs: add post authn script

- jans-auth-server/agama/engine/src/test/resources/libs/co/ListUtil.java
- jans-auth-server/agama/engine/src/test/resources/libs/co/MyInterface.java
- jans-auth-server/agama/engine/src/test/resources/libs/co/SubTest.java
- jans-auth-server/agama/engine/src/test/resources/libs/co/Test.java
- jans-auth-server/agama/engine/src/test/resources/libs/co/coo/Foo.groovy
- jans-auth-server/agama/engine/src/test/resources/libs/co/coo/Foobar.groovy
> chore(agama): upload missing Java/Groovy files for tests

- docs/admin/kubernetes-ops/logs.md
> docs: k8s logs

- docs/admin/kubernetes-ops/backup-restore.md
> docs: backup and restore

- docs/admin/auth-server/crypto/supported-algorithms.md
https://github.com/JanssenProject/jans/issues/3235
> docs: crypto keys.

- docs/admin/auth-server/crypto/key-generation.md
https://github.com/JanssenProject/jans/issues/3235
> docs: key generation

- docs/admin/config-guide/jans-cli/cli-custom-scripts.md
- docs/admin/developer/interception-scripts.md
- docs/admin/developer/scripts/end-session.md
- docs/admin/developer/scripts/ropc.md
- docs/admin/developer/scripts/update-token.md
- docs/script-catalog/person_authentication/duo-external-authenticator/README.md
- docs/script-catalog/update_token/README.md
> docs: end session script

- jans-linux-setup/jans_setup/templates/jans-cli/client.ldif
> fix: TUI client pre-authorized

- docs/admin/developer/scripts/revoke-token.md
> docs: add revoke token

- docs/admin/developer/scripts/id-generator.md
- docs/admin/developer/scripts/revoke-token.md
> docs: add ID generator script

- jans-linux-setup/jans_setup/setup_app/installers/config_api.py
- jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py
> fix: jans-linux-setup remove dependency to removed dependency yaml

- docs/admin/auth-server/endpoints/userinfo.md
Initial draft for userinfo endpoint with TODOs
> Docs userinfo endpoint

- docs/developer/developer-faq.md
Added steps to enable CLI and TUI logs to dev FAQ
> docs: add steps for enabling logs

- docs/admin/config-guide/curl.md
improve formatting and arrangement for curl document
> docs: improve formatting and arrangement for curl document

- docs/admin/kubernetes-ops/health-check.md
> docs: health check

- docker-jans-auth-server/Dockerfile
- docker-jans-auth-server/scripts/entrypoint.sh
- docker-jans-config-api/Dockerfile
- docker-jans-config-api/scripts/entrypoint.sh
- docker-jans-fido2/Dockerfile
- docker-jans-fido2/scripts/entrypoint.sh
- docker-jans-scim/Dockerfile
- docker-jans-scim/scripts/entrypoint.sh
> chore(prometheus): exclude optional prometheus exporter from images

- docs/admin/developer/scripts/uma-rpt.md
> docs: add UMA RPT authorization

- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- docs/admin/config-guide/jans-cli/cli-jans-authorization-server.md
- docs/admin/reference/json/properties/janssenauthserver-properties.md
- jans-auth-server/common/src/main/java/io/jans/as/common/model/session/SessionId.java
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
- jans-config-api/docs/jans-config-api-swagger-auto.yaml
- jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
chore(jans-auth-server): removed vestigial sessionsAsJwt Auth Server Property #3443
closes #3443
> chore(jans-auth-server): removed vestigial sessionsAsJwt Auth Server Property #3443

- docs/admin/developer/scripts/dynamic-scope.md
- docs/admin/developer/scripts/uma-rpt.md
> docs: fix spellings

- docs/admin/auth-server/endpoints/authorization.md
> docs: document authorization endpoint

- docs/admin/developer/scripts/client-registration.md
- docs/admin/developer/scripts/consent-gathering.md
- docs/admin/developer/scripts/dynamic-scope.md
- docs/admin/developer/scripts/end-session.md
- docs/admin/developer/scripts/id-generator.md
- docs/admin/developer/scripts/introspection.md
- docs/admin/developer/scripts/post-authentication.md
- docs/admin/developer/scripts/revoke-token.md
- docs/admin/developer/scripts/ropc.md
- docs/admin/developer/scripts/uma-rpt.md
> docs: script references

- docs/admin/auth-server/session-management/multiple-sessions-one-browser.md
- docs/admin/auth-server/tokens/openid-id-token.md
Initial checkin for Auth Server / Tokens / id_token. Small fixes to sessions page.
Initial chekin in Auth Server Guide / Tokens / ID Token. Also small fixes for Sessions page.
> docs: Auth Server Guide / id_token

- docs/admin/auth-server/endpoints/authorization.md
add details to authorization endpoint doc
#3454 
> docs: add details to authorization endpoint doc

- docs/admin/developer/agama/dsl-full.md
- docs/admin/developer/agama/dsl.md
> docs(agama): Clarify how RFAC redirect occurs and how to send POST authentication requests in inbound identity

- jans-auth-server/model/src/main/java/io/jans/as/model/jwt/JwtClaimSet.java
The error was because it could not parse to String from Object.
> Fix: Parse String from Object

- docs/admin/developer/interception-scripts.md
- docs/admin/developer/managed-beans.md
- docs/admin/fido/README.md
- docs/admin/fido/logs.md
> docs: typos #2201

- mkdocs.yml
> fix:#2201 removing an irrelevant head from mkdocs

- docs/admin/auth-server/endpoints/authorization.md
add details to authorize endpoint 
#3454 
> docs: add details to authorize endpoint 

- docs/admin/auth-server/endpoints/token-revocation.md
Add token revocation endpoint documentation
closes #3492 
> docs: add token revocation endpoint documentation

- docs/admin/auth-server/endpoints/authorization.md
- docs/admin/auth-server/endpoints/session-revocation.md
- docs/admin/auth-server/endpoints/token-revocation.md
- docs/admin/auth-server/endpoints/userinfo.md
Add session revocation endpoint documentation
closes #3495 
> docs: add session revocation endpoint documentation

- docs/admin/auth-server/endpoints/authorization.md
edit PAR details in Authz endpoint document
closes #3454 
> docs: edit PAR details in Authz endpoint document

- jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
> fix: jans-linux-setup start mysql server before jans-auth on SUSE

- charts/janssen/charts/config/templates/configmaps.yaml
- charts/janssen/values.yaml
- docker-jans-auth-server/Dockerfile
- docker-jans-auth-server/README.md
- docker-jans-auth-server/jetty/log4j2.xml
- docker-jans-auth-server/scripts/bootstrap.py
- docker-jans-config-api/Dockerfile
- docker-jans-config-api/README.md
- docker-jans-config-api/jetty/log4j2.xml
- docker-jans-config-api/plugins/admin-ui/log4j2-adminui.xml
- docker-jans-config-api/scripts/bootstrap.py
- docker-jans-fido2/Dockerfile
- docker-jans-fido2/README.md
- docker-jans-fido2/jetty/log4j2.xml
- docker-jans-fido2/scripts/bootstrap.py
- docker-jans-scim/Dockerfile
- docker-jans-scim/README.md
- docker-jans-scim/jetty/log4j2.xml
- docker-jans-scim/scripts/bootstrap.py
> feat(docker-jans): enable prefix and group for stdout logs

- docs/admin/kubernetes-ops/cert-management.md
> docs: certificate management

- jans-pycloudlib/jans/pycloudlib/config/google_config.py
- jans-pycloudlib/jans/pycloudlib/secret/google_secret.py
> refactor(jans-pycloudlib): simplify Google Secret integration

- docs/admin/auth-server/scopes/README.md
- docs/admin/auth-server/scopes/oauth.md
- docs/admin/auth-server/scopes/openid.md
- docs/admin/auth-server/scopes/uma.md
- mkdocs.yml
> docs: add scopes documentation to Auth Guide

- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java
- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/user/UserManagementResource.java
- jans-config-api/server/src/main/resources/config-api-rs-protect.json
> Jans config api issue 3508

- automation/docs/generate-javadocs.sh
Remove multiple sed commands
closes #3525 
> fix: remove multiple sed commands

- agama/transpiler/src/main/java/io/jans/agama/dsl/VarsTransformer.java
- jans-bom/pom.xml
> fix: add 'java' to the list of restricted variable names

- docs/admin/auth-server/endpoints/jwks-uri.md
document jwks uri endpoint
closes #3535
> docs: document jwks uri endpoint

- docs/admin/auth-server/endpoints/ssa.md
> docs: update documentation for ssa endpoint

- docs/admin/auth-server/oauth-features/client-credential-grant.md
> docs: sequence diagram - client credentials grant

- .github/workflows/build-packages.yml
> ci: added missing python packages

- jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/DeploymentDetails.java
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ADSDeploymentsService.java
> feat(agama): account metadata in `.gama` files 

- docs/admin/auth-server/endpoints/introspection.md
#3238
minor typo and added reference links
> docs: minor typo and added reference links

- docs/admin/developer/managed-beans.md
#3238
typo in method signature
> docs: typo

- docs/admin/auth-server/oauth-features/auth-code-grant.md
> docs: Sequence diagram for auth code grant

- docs/admin/auth-server/oauth-features/client-credential-grant.md
> docs: fix syntax error diagram

- docs/admin/auth-server/oauth-features/implicit-grant.md
> docs: implicit grant diagram

- docs/admin/auth-server/endpoints/token.md
Document token endpoint
#3591 
> docs: document token endpoint

- docs/admin/auth-server/endpoints/token.md
update token ep doc to remove UMA grant 
closes #3591 
> docs: update token ep doc to remove UMA grant 

- .github/workflows/build-packages.yml
> ci: updated python packages build

- jans-linux-setup/jans_setup/app_info.json
- jans-linux-setup/jans_setup/jans_setup.py
> fix: jans-linux-setup downgrade jwt for py3.6

- docker-jans-persistence-loader/scripts/utils.py
- jans-pycloudlib/jans/pycloudlib/wait.py
> feat(docker-jans): change persistence entry check to read configuration

- docker-jans-auth-server/requirements.txt
- docker-jans-auth-server/scripts/bootstrap.py
- docker-jans-config-api/requirements.txt
- docker-jans-config-api/scripts/bootstrap.py
- docker-jans-fido2/requirements.txt
- docker-jans-fido2/scripts/bootstrap.py
- docker-jans-scim/requirements.txt
- docker-jans-scim/scripts/bootstrap.py
> feat(docker-jans): add support for mounted hybrid properties file

- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java
feat(jans-auth-server): provided convenient method to add claim to AT as JWT in modifyAccessToken() method 
closes #3579
> feat(jans-auth-server): provided convenient method to add claim to AT as JWT in modifyAccessToken() method #3579

- jans-auth-server/server/src/main/java/io/jans/as/server/model/registration/RegisterParamsValidator.java
- jans-auth-server/server/src/test/java/io/jans/as/server/model/registration/RegisterParamsValidatorTest.java
feat(jans-auth-server): added sector_identifier_uri content validation (certification) #3639
closes #3639
> feat(jans-auth-server): added sector_identifier_uri content validation (certification) #3639

- docs/admin/developer/agama/lifecycle.md
- jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/DeploymentDetails.java
> feat: process lib directory in `.gama` files for ADS projects deployment

- docs/admin/developer/agama/gama-deployment.md
> docs: add section about deployments internals of `.gama` files

- docs/admin/auth-server/tokens/oauth-access-tokens.md
- docs/admin/auth-server/tokens/oauth-refresh-tokens.md
- docs/admin/auth-server/tokens/uma-rpt-token.md
Initial checkin... some todo's on the RPT token page.
> docs: Refresh / RPT token pages

- docs/admin/reference/database/ldap-namespace.md
> docs: LDAP namespace

- docs/admin/reference/database/ldap-schema.md
> docs: fix LDAP schema

- docs/admin/reference/database/ldap-schema.md
> docs: LDAP schema fixes

- docs/admin/reference/database/ldap-schema.md
> docs: fixes minor

- docs/admin/auth-server/client-management/README.md
> docs: client management overview

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/utils.py
- docs/admin/config-guide/jans-cli/install.md
- docs/admin/recipes/benchmark.md
- docs/admin/reference/kubernetes/config-secret-keys.md
- jans-cli-tui/docs/build.md
> fix: rename role_based_client as tui_client

- jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py
> fix: jans-linux-setup rename config-api swagger file

- docs/admin/auth-server/endpoints/introspection.md
- docs/admin/auth-server/endpoints/token-revocation.md
- docs/admin/auth-server/tokens/oauth-access-tokens.md
- docs/admin/auth-server/tokens/oauth-refresh-tokens.md
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
doc(jans-auth-server): put more info about token related configuration properties  
closes #3680
> doc(jans-auth-server): put more info about token related configuration properties  #3680

- jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/client/RegisterRequestTest.java
fix(jans-auth-server): corrected issue caught by RegisterRequestTest 
closes #3683
> fix(jans-auth-server): corrected issue caught by RegisterRequestTest

- docs/admin/auth-server/crypto/keys.md
https://github.com/JanssenProject/jans/issues/3235
> docs: update Auth Server Admin Guide - Crypto

- .github/workflows/testcases.yml
> ci: fix python version used in testcases workflow

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-config-api/scripts/upgrade.py
- docker-jans-fido2/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- docker-jans-scim/Dockerfile
> chore(docker-jans): sync schema, templates, and config from upstream

- jans-linux-setup/jans_setup/setup_app/installers/jans.py
- jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
- jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
> fix: jans-linux-setup test client fixes

- docs/developer/useful-tools.md
> docs : useful tools

- docs/admin/auth-server/client-management/client-authn.md
> docs: add documentation for client authn

- mkdocs.yml
> docs: add emoji support for docs

- jans-auth-server/agama/inboundID/pom.xml
fix(jans-auth-server): added testng to agama-inbound 
closes #3714
> fix(jans-auth-server): added testng to agama-inbound #3714

- jans-linux-setup/jans_setup/app_info.json
- jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py
> fix: jans-linux-setup add twilio and fido2 client libs to jans-auth

- jans-fido2/server/src/main/java/io/jans/fido2/service/persist/RegistrationPersistenceService.java
> fix(jans-fido2): RegistrationPersistenceService implemntation

- charts/janssen/charts/config/templates/configmaps.yaml
- charts/janssen/values.yaml
- docker-jans-auth-server/Dockerfile
- docker-jans-auth-server/jetty/log4j2.xml
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-fido2/README.md
- docker-jans-fido2/jetty/log4j2.xml
- docker-jans-fido2/scripts/bootstrap.py
- docker-jans-fido2/scripts/entrypoint.sh
- docker-jans-fido2/scripts/upgrade.py
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-scim/Dockerfile
> chore(docker-jans): update dependencies and assets from upstream

- docs/admin/auth-server/client-management/client-authn.md
> docs: update client auth documentation

- jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py
closes https://github.com/JanssenProject/jans/issues/3764
> fix: jans-cli-tui SSA org_id, status and software_roles

- docs/admin/developer/agama/quick-start.md
> docs(agama): update instructions on how to retrieve client creds in quick-start guide

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/upgrade.py
> feat(docker-jans-persistence-loader): add ssa admin scope

- docs/admin/kubernetes-ops/scaling.md
> docs: scaling

- docs/admin/developer/agama/otp-email/EmailOTPUtil.groovy
- docs/admin/developer/agama/samples.md
> chore(agama): include Groovy code in sample flows

- docs/admin/developer/agama/gama-deployment.md
> docs: corrected broken link

- jans-auth-server/client/src/main/java/io/jans/as/client/util/KeyGenerator.java
- jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AbstractCryptoProvider.java
- jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java
- jans-auth-server/model/src/main/java/io/jans/as/model/jwk/JSONWebKey.java
- jans-auth-server/model/src/main/java/io/jans/as/model/jwk/KeyOps.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/model/token/JwrService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/model/token/JwtSigner.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/ServerCryptoProvider.java
- jans-auth-server/server/src/main/java/io/jans/as/server/userinfo/ws/rs/UserInfoRestWebServiceImpl.java
fix(jans-auth-server): key_ops in jwks must be array
closes #3777
> fix(jans-auth-server): key_ops in jwks must be array #3777

- docs/admin/auth-server/client-management/README.md
- docs/admin/auth-server/client-management/client-configuration.md
> docs: add redirect URI documentation for client configuration

- docs/script-catalog/person_authentication/fido2-external-authenticator/Fido2ExternalAuthenticator.py
- jans-auth-server/common/src/main/java/io/jans/as/common/service/common/fido2/RegistrationPersistenceService.java
- jans-auth-server/server/src/main/webapp/auth/fido2/platform.xhtml
- jans-auth-server/server/src/main/webapp/auth/fido2/secKeys.xhtml
- jans-auth-server/server/src/main/webapp/stylesheet/style.css
- jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AssertionService.java
> fix(jans-auth-server): jansApp attribute only relevant for SG

- jans-linux-setup/jans_setup/templates/scripts.ldif
> fix: jans-linux-setup script locatipn is db

- jans-linux-setup/jans_setup/openbanking/templates/scripts.ldif
> fix: jans-linux-setup script locatipn is db openbanking

- docs/admin/auth-server/endpoints/client-registration.md
> docs: fix the formatting in registration endpoint doc

- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/scripts/spanner_setup.py
- docker-jans-persistence-loader/scripts/sql_setup.py
- docker-jans-persistence-loader/scripts/upgrade.py
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
- docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
- docker-jans-persistence-loader/templates/scripts.ob.ldif
- docker-jans-scim/Dockerfile
> chore(docker-jans): sync manifests from upstream

- jans-linux-setup/jans_setup/templates/test/agama/config-agama-test.properties
>  chore(agama): create custom parameter for agama flows

- jans-pycloudlib/jans/pycloudlib/config/google_config.py
- jans-pycloudlib/jans/pycloudlib/secret/google_secret.py
> fix(jans-pycloudlib): avoid overwritten data by using merge strategy for Google wrappers

- jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py
> fix: jans-cli-tui fail to create SSA

- jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py
> fix: jans-cli-tui working branch 8

- docs/admin/developer/agama/gama-deployment.md
> docs: minor updates on agama deployment guide

- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java
fix(jans-auth-server): AS complication fails on main 
closes #3863
> fix(jans-auth-server): AS complication fails on main #3863

- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterCreateAction.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/ClientService.java
feat(jans-auth-server): add configurable rotation of client's registration access token 
closes #3578
> feat(jans-auth-server): add configurable rotation of client's registration access token #3578

- docs/admin/auth-server/client-management/client-configuration.md
> docs: client configuration updates

- jans-auth-server/model/src/main/java/io/jans/as/model/common/IntrospectionResponse.java
- jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
feat(jans-auth-server): OAuth 2.0 Step-up - added acr and auth_time 
closes #2589
> feat(jans-auth-server): OAuth 2.0 Step-up - added acr and auth_time #2589

- jans-linux-setup/jans_setup/templates/scripts.ldif
> fix: auto installing of the GithubAuthenticatorForADS.py

- docker-jans-auth-server/requirements.txt
- docker-jans-certmanager/requirements.txt
- docker-jans-config-api/requirements.txt
- docker-jans-configurator/requirements.txt
- docker-jans-fido2/requirements.txt
- docker-jans-persistence-loader/requirements.txt
- docker-jans-scim/requirements.txt
Updated build date. Auto-generated.
> chore(Dockerfile): updated build dates

- docs/admin/fido/config.md
> docs : fix add SG config property

- README.md
On Janssen Project README
- Fixed broken links
- Removed `jans-client-api` from module list
- Fixed grammar
closes #3898 
> docs: minor fixes for Janssen Project README

- jans-cli-tui/cli_tui/plugins/020_fido/main.py
> feat(jans-cli-tui): enable super gluu option

- .github/workflows/build-packages.yml
> ci: added ubuntu22 build

- jans-linux-setup/jans_setup/setup_app/config.py
- jans-linux-setup/jans_setup/setup_app/installers/base.py
- jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
- jans-linux-setup/jans_setup/setup_app/installers/opendj.py
- jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
- jans-linux-setup/jans_setup/static/system/systemd/jans-auth.service
> fix(jans-linux-setup): start jans-auth after backend

- docs/admin/auth-server/endpoints/ssa.md
- jans-auth-server/client/src/main/java/io/jans/as/client/ssa/create/SsaCreateRequest.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaJsonService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java
- jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java
- Added `custom attributes` in create SSA, Get SSA and Get Jwt from SSA.
- In Get SSA, also added the fields: `description`, `one_time_use` and `rotate_ssa`.
- Site docs for SSA has also been updated.
closes #3803
> Feature: Include additional attributes on SSA Get endpoint

- docker-jans-certmanager/scripts/auth_handler.py
- docker-jans-configurator/scripts/bootstrap.py
> fix(docker-jans): resolve required keys_ops_type for generating/rotating keys

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-scim/Dockerfile
> chore(docker-jans): uninstall Jython ensurepip module to reduce vulnerabilities

- docker-jans-config-api/plugins/admin-ui/log4j2-adminui.xml
- docker-jans-config-api/scripts/bootstrap.py
- docker-jans-scim/jetty/log4j2.xml
> fix(docker-jans): add missing logs due to improper configuration

- docker-jans-auth-server/Dockerfile
> chore(docker-jans-auth-server): update external scripts used by casa

- docs/developer/developer-faq.md
> docs: fix formatting issue

- docs/admin/developer/agama/gama-deployment.md
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java
> feat(agama): update gama deployment endpoint to support configuration properties

- docs/admin/install/vm-install/ubuntu.md
> docs: update ubuntu.md with ubuntu 22

- jans-orm/core/src/main/java/io/jans/orm/operation/auth/BCrypt.java
- jans-orm/core/src/main/java/io/jans/orm/reflect/util/ReflectHelper.java
- jans-orm/ldap/src/main/java/io/jans/orm/ldap/operation/LdapOperationService.java
- jans-orm/ldap/src/main/java/io/jans/orm/ldap/operation/impl/LdapConnectionProvider.java
Fix javadoc generation for jans-orm
closes #4059
> fix: javadoc errors

- docs/admin/developer/agama/gama-deployment.md
- docs/admin/developer/agama/ui-pages.md
> docs: fix response codes in deployment endpoints table 

- jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaFlowService.java
> fix: prevent getFlowByName method crash by refactoring

- jans-cli-tui/cli_tui/jans_cli_tui.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/defaults.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
- jans-cli-tui/cli_tui/plugins/020_fido/main.py
- jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py
- jans-cli-tui/cli_tui/plugins/060_scripts/main.py
- jans-cli-tui/cli_tui/plugins/070_users/main.py
- jans-cli-tui/cli_tui/utils/static.py
- jans-cli-tui/cli_tui/wui_components/jans_drop_down.py
- jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
- add status for saving fido configuration
- feat: enhance presentation of agama deployments (closes #3854)
- feat: save default ACR (closes #4031)
- feat: view, edit, create attributes (closes #4035)
- fix: dropdown changes value with up/down even if not activated (closes #4122)
> fix(jans-cli-tui): working branch 11

- docs/admin/install/vm-install/rhel.md
- docs/admin/install/vm-install/suse.md
- docs/admin/install/vm-install/ubuntu.md
Our installation documentation pages need a transition to the steps that should be taken after install is finished and verified.
#4133 
closes #4133
> docs: added TUI instructions to VM installation docs

- docs/admin/auth-server/endpoints/client-registration.md
> docs: add details of CRUD operations in registration EP document

- mkdocs.yml
> docs: remove OIDC client doc link

- docs/admin/config-guide/config-api/README.md
- docs/admin/config-guide/config-api/attribute.md
- docs/admin/config-guide/config-api/authorization.md
- docs/admin/config-guide/config-api/monitoring.md
- docs/admin/config-guide/config-api/openid-client.md
- docs/admin/config-guide/config-api/security.md
4153 - fixed broken links 
4154 - reviewed docs and add new
closes #4153 #4154
> docs(config-api): fixed broken link and added monitoring, client doc

- docs/admin/auth-server/client-management/sector-identifiers.md
> docs: add documentation for sector identifiers

- docs/agama-catalog/jans/inboundID/README.md
Correct location of login.ftlh
> docs-enhancement: agama configuration  -1

- docs/agama-catalog/jans/inboundID/README.md
> docs-enhancement: Agama configuration - loginF

- docs/agama-catalog/jans/inboundID/README.md
> docs-enhancement:Agama configuration-Add main flow

- docs/agama-catalog/jans/inboundID/README.md
> docs-enhancement: email template

- docs/agama-catalog/jans/inboundID/README.md
> docs(agama): fix broken links in agama inbound identity docs

- docs/agama-catalog/jans/inboundID/README.md
> docs-enhancement: Add Facebook provider

- docs/admin/install/vm-install/ubuntu.md
No target issue. Fixed typo installing 
> Fixed ubuntu version in shell command

- docs/admin/fido/config.md
> fix(docs): minor

- jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
> fix(jans-cli-tui): display jans id in scope list

- docs/admin/install/vm-install/ubuntu.md
> docs: added cd command to sha256sum instructions

- jans-linux-setup/jans_setup/jans_setup.py
> fix(jans-linux-setup): TUI string

- docs/admin/config-guide/jans-tui/navigation-guide.md
> docs: edited doc for proofreading and formatting

- demos/jans-tent/README.md
Restructure and reformat readme sections and steps
closes #4290
> docs(tent): reformat readme 

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-scim/Dockerfile
> chore(docker-jans): remove obsolete attribute county

- docs/admin/developer/agama/faq.md
- docs/admin/developer/agama/quick-start.md
- docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
- jans-linux-setup/jans_setup/templates/scripts.ldif
> feat(agama): add a "default agama flow" to bridge

- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/acr/AcrChangedHttpTest.java
- jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/deviceauthz/DeviceAuthzRequestRegistrationTest.java
- jans-auth-server/client/src/test/resources/testng.xml
- jans-auth-server/model/src/main/java/io/jans/as/model/config/Constants.java
- jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java
- jans-auth-server/model/src/test/java/io/jans/as/model/util/UtilTest.java
- jans-auth-server/server/src/main/java/io/jans/as/server/auth/Authenticator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/DeviceAuthorizationAction.java
- jans-auth-server/server/src/main/java/io/jans/as/server/model/authorize/AuthorizeParamsValidator.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
- jans-core/util/src/main/java/io/jans/util/Util.java
fix(jans-auth-server) : corrected acr change handling from device authorization to other acr 
closes #4255
> fix(jans-auth-server) : corrected acr change handling from device authorization to other acr #4255

- jans-auth-server/server/src/main/resources/jans-auth.properties
- jans-auth-server/server/src/main/webapp/auth/fido2/platform.xhtml
> fix(jans-auth): #4137 properties file entries were missing

- jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java
- jans-auth-server/server/src/test/java/io/jans/as/server/service/RedirectionUriServiceTest.java
fix(jans-auth-server): corrected npe in redirect uri validator 
closes #4330
> fix(jans-auth-server): corrected npe in redirect uri validator #4330

- demos/jans-tent/clientapp/client_handler.py
- demos/jans-tent/tests/unit_integration/helper.py
- demos/jans-tent/tests/unit_integration/test_dynamic_client_registration.py
Client registration tests needed to be restructured according to new implementation.
Closes #4353,
> test(tent): restructure client registration unit

- docs/admin/install/vm-install/suse.md
> docs: added note to disable firewall during installation

- jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
> fix(jans-linux-setup): remove password strength check for ldap

- docs/admin/developer/agama/engine-config.md
- docs/admin/developer/agama/quick-start.md
- jans-auth-server/server/conf/jans-config.json
- jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
> bug(jans-linux-setup): agama engine should be disabled by default

- jans-auth-server/model/src/test/java/io/jans/as/model/util/SecurityProviderUtilityTest.java
fix(jans-auth-server): fixed test which prevents build from completion 
closes #4386
> fix(jans-auth-server): fixed test which prevents build from completion #4386

- docs/admin/auth-server/client-management/README.md
- docs/admin/auth-server/client-management/client-authn.md
- docs/admin/auth-server/client-management/client-configuration.md
- docs/admin/auth-server/config.md
- docs/admin/auth-server/crypto/key-generation.md
- docs/admin/auth-server/crypto/keys.md
- docs/admin/auth-server/endpoints/authorization.md
- docs/admin/auth-server/endpoints/client-registration.md
- docs/admin/auth-server/endpoints/clientinfo.md
- docs/admin/auth-server/endpoints/configuration.md
- docs/admin/auth-server/endpoints/end-session.md
- docs/admin/auth-server/endpoints/introspection.md
- docs/admin/auth-server/endpoints/jwks-uri.md
- docs/admin/auth-server/endpoints/par.md
- docs/admin/auth-server/endpoints/session-revocation.md
- docs/admin/auth-server/endpoints/ssa.md
- docs/admin/auth-server/endpoints/token-revocation.md
- docs/admin/auth-server/endpoints/token.md
- docs/admin/auth-server/endpoints/userinfo.md
- docs/admin/auth-server/oauth-features/auth-code-grant.md
- docs/admin/auth-server/oauth-features/device-grant.md
- docs/admin/auth-server/oauth-features/implicit-grant.md
- docs/admin/auth-server/openid-features/acrs.md
- docs/admin/auth-server/session-management/README.md
- docs/admin/auth-server/session-management/multiple-sessions-one-browser.md
- docs/admin/auth-server/tokens/oauth-access-tokens.md
- docs/admin/auth-server/tokens/oauth-refresh-tokens.md
- docs/admin/auth-server/tokens/openid-userinfo-token.md
As described in closed issue.
closes #4389 
> docs: fix broken links in docs under auth server directory

- jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
- Add active scope filter on the search field value change
[[  
](https://github.com/JanssenProject/jans/issues/4299)](https://github.com/JanssenProject/jans/issues/4299)
> jans-cli-tui filter scopes (ref: #4299)

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
> feat(docker-jans): upstream changes for license credentials

- docs/admin/auth-server/oauth-features/device-grant.md
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/DeviceAuthorizationAction.java
added configurable acr to Device Flow 
closes #4305
> feat(jans-auth-server): added configurable acr to Device Flow #4305

- docs/admin/auth-server/openid-features/README.md
- docs/admin/auth-server/uma-features/README.md
- docs/admin/recipes/README.md
Initial readme drafts
Partially addresses #4340 
> docs: initial category readme drafts

- docs/admin/config-guide/jans-tui/navigation-guide.md
> fix(docs): jans TUI configuration -- update user password

- demos/README.md
- demos/jans-tent/README.md
demos folder readme and tent readme now have the same description
closes #4441
> docs(tent): synch demos and tent description

- agama/transpiler/src/main/antlr4/io/jans/agama/antlr/AuthnFlow.g4
- agama/transpiler/src/main/resources/JSGenerator.ftl
- agama/transpiler/src/main/resources/util.js
- docs/admin/developer/agama/dsl-full.md
- docs/admin/developer/agama/flows-lifecycle.md
- docs/admin/developer/agama/lifecycle.md
- jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/service/FlowService.java
- jans-auth-server/agama/engine/src/main/java/org/mozilla/javascript/SubflowRhinoException.java
- jans-auth-server/agama/inboundID/src/main/java/io/jans/util/NetworkUtils.java
> feat(agama): add means to selectively prevent flow crash when a subflow crashes

- jans-cli-tui/cli_tui/cli/config_cli.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/wui_components/jans_path_browser.py
In this PR:
- Hide hidden files in path browser (closes #4421)
- Fix url-suffix param in post (closes #4422)
> fix(jans-cli-tui): agama related issues

- .github/workflows/python-pytest.yml
Add workflow to run pytest @ Jans Tent.
> ci(tent): add pytest workflow

- jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java
- jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaDeploymentsService.java
> fix(agama): avoid assets mess/loss when different projects use the same folder/file names

- demos/jans-tent/README.md
Quick fixes to Tent README
https://github.com/JanssenProject/jans/issues/4506
closes #4506
Added docs and fixed some other syntax
Closes #4508,
> Updated Tent README for testing new OP

- docs/admin/auth-server/openid-features/acrs.md
> fix(docs): Paraphrasing #4369

- demos/benchmarking/docker-jans-loadtesting-jmeter/Dockerfile
- docker-jans-auth-server/Dockerfile
- docker-jans-certmanager/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-configurator/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
- docker-jans-scim/Dockerfile
> build(docker-jans): fix incorrect syntax on label

- jans-cli-tui/cli_tui/plugins/060_scripts/main.py
- jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
https://github.com/JanssenProject/jans/issues/4306
closes #4306
> jans-cli-tui noticable script error (ref: #4306)

- jans-cli-tui/cli_tui/plugins/010_auth_server/view_property.py
https://github.com/JanssenProject/jans/issues/4521
closes #4521
> jans-cli-tui TUI view is not updated (ref: #4521)

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py
- jans-cli-tui/cli_tui/plugins/060_scripts/main.py
- jans-cli-tui/cli_tui/plugins/070_users/main.py
- jans-cli-tui/wrapper_test.py
https://github.com/JanssenProject/jans/issues/4267
https://github.com/JanssenProject/jans/issues/4034
closes #4267
closes #4034
> Jans cli tui works2

- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java
> feat(agama): add version to project metadata

- docs/admin/install/helm-install/rancher.md
- docs/admin/planning/README.md
- docs/admin/planning/application-portal.md
- docs/admin/planning/caching.md
- docs/admin/planning/central-auth-service.md
- docs/admin/planning/components.md
- docs/admin/planning/discovery.md
- docs/admin/planning/load-balancers.md
- docs/admin/planning/persistence.md
- docs/admin/planning/platform-goal.md
- docs/admin/planning/role-based-access-management.md
- docs/admin/planning/security-best-practices.md
- docs/admin/planning/self-service-password-2fa.md
- docs/admin/planning/stepped-up-auth.md
- docs/admin/planning/timeout-management.md
- docs/admin/planning/use-cases.md
- docs/admin/planning/vm-cluster.md
- docs/admin/planning/vm-single-instance.md
> docs: review and update documentation search tags

- jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
> fix(jans-cli-tui): edit client's scope

- jans-cli-tui/cli_tui/cli_style.py
- jans-cli-tui/cli_tui/jans_cli_tui.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/utils/static.py
- jans-cli-tui/cli_tui/wui_components/jans_cli_dialog.py
- jans-cli-tui/cli_tui/wui_components/jans_table.py
- jans-cli-tui/cli_tui/wui_components/jans_table.py.org
- fix list agama deployments (closes #4458)
- show the details of an agama deployment (closes #4459)
- support for management of agama projects configurations (closes #4460)
> fix(jans-cli-tui): agama deployments fixes

- docs/admin/install/vm-install/suse.md
> docs: clarified firewall note

- jans-cli-tui/cli_tui/jans_cli_tui.py
> fix(jans-cli-tui): check if verification uri exists during authorization

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
Fixes mentioned in comments of 
closes #4459 
closes #4560
> fix(jans-tui-cli): Jans cli tui agama post fixes

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py
- jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
> Jans cli tui on page enter

- jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java
> fix(jans-config-api): agama deployment detail endpoint not including all flows IDs

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/wui_components/jans_table.py
> fix(jans-cli-tui): null valued agama flow error

- jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
> fix(jans-cli-tui): save 'Suppress Authorization'

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
> fix(jans-cli-tui): agama project removal message

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
> fix(jans-cli-tui) remove agama project

- demos/jans-tent/clientapp/__init__.py
- demos/jans-tent/clientapp/utils/dcr_from_config.py
- demos/jans-tent/tests/unit_integration/helper.py
- demos/jans-tent/tests/unit_integration/test_callback_endpoint.py
- demos/jans-tent/tests/unit_integration/test_client_register_endpoint.py
- demos/jans-tent/tests/unit_integration/test_configuration_endpoint.py
- demos/jans-tent/tests/unit_integration/test_dcr_from_config.py
- demos/jans-tent/tests/unit_integration/test_flask_factory.py
- demos/jans-tent/tests/unit_integration/test_gluu_preselected_provider.py
- demos/jans-tent/tests/unit_integration/test_protected_content_endpoint.py
> test(tent): mock auto register on server start

- jans-auth-server/server/src/main/java/io/jans/as/server/service/net/HttpService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/net/HttpService2.java
- jans-bom/pom.xml
> chore: merge libs and services from update from Gluu

- jans-auth-server/server/src/main/java/io/jans/as/server/service/ErrorHandlerService.java
chore(jans-auth-server): added more logs when show error page
> chore(jans-auth-server): added more logs when show error page

- docs/admin/auth-server/session-management/README.md
>  fix(docs): session persistence #3235

- docs/script-catalog/person_authentication/super-gluu-external-authenticator/README.md
> fix(docs): #3340 mention push notification server

- jans-core/service/src/main/java/io/jans/service/MailService.java
> chore(jans-auth-server): provide a simpler sendMail method in MailService

- jans-linux-setup/jans_setup/openbanking/static/extension/update_token/updatetoken.json
- jans-linux-setup/jans_setup/openbanking/templates/scripts.ldif
- jans-linux-setup/jans_setup/templates/scripts.ldif
> fix(jans-linux-setup): remove scan_update_token

- docker-jans-persistence-loader/Dockerfile
- docker-jans-persistence-loader/templates/scripts.ob.ldif
> chore(docker-jans-persistence-loader): remove scan_update_token script

- charts/janssen/charts/config/templates/configmaps.yaml
- charts/janssen/charts/config/templates/secrets.yaml
- charts/janssen/charts/config/values.yaml
- charts/janssen/values.yaml
- docs/admin/kubernetes-ops/external-secrets-configmaps.md
- mkdocs.yml
> docs: external secrets

- jans-cli-tui/cli_tui/cli/config_cli.py
- add orgument --output-access-token for CLI (closes #4670)
> feat(jans-cli-tui): CLI works

- docs/admin/config-guide/jans-cli/README.md
Update cli docs for new argument features
> doc(jans-cli-tui): update cli doc

- jans-cli-tui/cli_tui/cli/config_cli.py
> fix(jans-cli-tui): endpoint arguments with multiple value

- jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py
> feat(jans-cli-tui): obtain auth scripts with single query

- jans-cli-tui/cli_tui/cli/config_cli.py
> fix(jans-cli-tui): remove unused code

- jans-auth-server/server/src/main/java/io/jans/as/server/filter/CorsFilter.java
- jans-core/server/src/main/java/io/jans/server/filters/AbstractCorsFilter.java
> fix: cors filter should not store in local variable allowed

- jans-cli-tui/cli_tui/cli/config_cli.py
- jans-cli-tui/cli_tui/jans_cli_tui.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/view_property.py
- jans-cli-tui/cli_tui/utils/utils.py
- jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
https://github.com/JanssenProject/jans/issues/4511
https://github.com/JanssenProject/jans/issues/4686
https://github.com/JanssenProject/jans/issues/4532
closes #4532
closes #4686 
closes #4511
> jans-cli-tui properties edit missing object items (ref: #4532)

- jans-cli-tui/cli_tui/jans_cli_tui.py
> fix(jans-cli-tui): typo

- docs/admin/upgrade/vm/README.md
> jans upgrade document

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
> fix(jans-cli-tui): remove popup on agama screen

- jans-cli-tui/docs/upgrade.md
I prepared upgrading steps
Closes #4724,
> doc(jans-cli-tui): upgrade.md

- jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/TPMProcessor.java
- jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/SignatureVerifier.java
- Improvement in `getHashedBuffer` method
- Modified the `signatureAlgorithm` parameter of the `verifySignature` method to `attStmt.alg` field
- Added `verifyVersion2` method
- Added `verifyAlg` method
closes #4141
> Feature: TPM Attestation

- jans-bom/pom.xml
- jans-fido2/server/pom.xml
- jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/AttestationVerifier.java
- jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/DomainVerifier.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/sg/FullFlowAppleTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/AssertionVerifierTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/AttestationVerifierTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/AuthenticatorDataVerifierTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/DomainVerifierTest.java
- Reimported `io.jans.as.model.util.SecurityProviderUtility` to `io.jans.util.security.SecurityProviderUtility`
- Added dependency `mockito-junit-jupiter`
- Added unit testing for `AttestationVerifier`
- Added unit testing for `AssertionVerifier`
- Added unit testing for `DomainVerifier`
- Added unit testing for `AuthenticatorDataVerifierTest`
closes #240
> Feature: Unit Test for Fido2

- docs/admin/auth-server/endpoints/introspection.md
- jans-auth-server/model/src/main/java/io/jans/as/model/common/ScopeConstants.java
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/IntrospectionService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalUpdateTokenContext.java
- jans-auth-server/server/src/test/java/io/jans/as/server/service/IntrospectionServiceTest.java
- jans-linux-setup/jans_setup/templates/scopes.ldif
feat(jans-auth-server): add "introspection" scope check on introspection endpoint access 
closes #4557
> feat(jans-auth-server): add "introspection" scope check on introspection endpoint access #4557

- docs/admin/config-guide/jans-tui/navigation-guide.md
- jans-cli-tui/cli_tui/jans_cli_tui.py
> fix(jans-cli-tui): f4 to close dialog

- jans-cli-tui/README.md
- jans-cli-tui/docs/upgrade.md
> docs(jans-cli-tui): update readme

- docs/developer/implementation-design/README.md
- mkdocs.yml
> docs(developer): update mapping to README of implementation and design section

- jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java
> fix: set appropriate redirect_uris for registration in DCR using ssa (admin-ui)#4748

- demos/jans-tent/clientapp/templates/home.html
Add headers to json payloads (userinfo and id_token) at home page. 
closes #4726
> feat(tent): add headers to home JSON payloads

- docker-jans-config-api/Dockerfile
- docker-jans-monolith/Dockerfile
- docker-jans-persistence-loader/Dockerfile
> fix(docker-jans): sync role-based introspection script

- .github/workflows/test_docker_linux_installer.yml
- automation/docs/generate-rdbms-docs.py
- automation/docs/generate-rdbms-docs.sh
This adds auto generation for RDBMS docs
closes #4517
> ci: add generate rdbms docs script

- docs/admin/config-guide/jans-tui/navigation-guide.md
- update tui navigation docs 
- 
https://github.com/JanssenProject/jans/issues/4729
closes #4729
> fix(docs): Jans cli tui update tui navigation docs

- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- warn the user when agama is disabled and an upload is attempted.
https://github.com/JanssenProject/jans/issues/4702
closes #4702
> feat(jans-cli-tui): warn the user when upload agama project if disapled 

- jans-orm/sql-sample/src/main/java/io/jans/orm/sql/model/SimpleCustomScript.java
- jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
> fix(config-api): filtering script is not working when backend is

- docs/admin/developer/scripts/update-token.md
This document was previously incorrectly formatted, causing readability and navigation errors.
> docs: corrected formatting and layout of Update Token page

- jans-linux-setup/tools/key_regeneration.py
> fix(jans-linux-setup): key_regeneration should look up db for keystore type

- jans-cli-tui/cli_tui/jans_cli_tui.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
- jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
- Change help (<f1>) content in agam page.
https://github.com/JanssenProject/jans/issues/4725
closes #4725
- it is generic now, and we can add custom help for any desired page.
> fix(jans-cli-tui): change help content for agama page

- jans-auth-server/server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java
feat(jans-auth-server): avoided unnecessary "session not found" error messages during refresh token flow 
closes #4785
> feat(jans-auth-server): avoided unnecessary "session not found" error messages during refresh token flow #4785

- docs/admin/kubernetes-ops/external-secrets-configmaps.md
> docs: migration and fresh install on aws and gcp

- docker-jans-auth-server/Dockerfile
- docker-jans-config-api/Dockerfile
- docker-jans-fido2/Dockerfile
- docker-jans-scim/Dockerfile
> chore(docker-jans): upgrade jetty to mitigate vulnerabilities

- jans-linux-setup/jans_setup/setup_app/installers/opendj.py
> fix(jans-linux-setup): create opendj sysv script for k8s

- jans-linux-setup/jans_setup/setup_app/installers/base.py
- jans-linux-setup/jans_setup/setup_app/utils/base.py
> fix(jans-linux-setup): use /opt/dist/scripts in case of k8s

- jans-auth-server/agama/engine/src/test/java/io/jans/agama/test/UidOnlyAuthTest.java
> fix(agama): fix test case randUid

- docker-jans-monolith/jans-mysql-compose.yml
- docker-jans-monolith/jans-postgres-compose.yml
> fix(docker-jans-monolith): incorrect image tag for compose-based deployment

- docs/admin/config-guide/config-api/config.md
- docs/admin/scim/config.md
> docs: config-api configuration and SCIM typo

- docker-jans-persistence-loader/scripts/upgrade.py
> fix(docker-jans-persistence-loader): ensure smtp config is multivalued

- .gitignore
- demos/benchmarking/docker-jans-loadtesting-jmeter/Makefile
- docker-jans-auth-server/Makefile
- docker-jans-certmanager/Makefile
- docker-jans-config-api/Makefile
- docker-jans-configurator/Makefile
- docker-jans-fido2/Makefile
- docker-jans-monolith/Makefile
- docker-jans-persistence-loader/Makefile
- docker-jans-scim/Makefile
> chore(docker-jans): add support for extra build/scan args

- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml
- jans-config-api/pom.xml
> fix(config-api): starup issue realted to mail service

- docs/admin/developer/agama/quick-start-using-agama-lab.md
- mkdocs.yml
> docs: add agama lab guide to the docs navigation

- jans-auth-server/client/pom.xml
- jans-auth-server/server/pom.xml
> chore: fix test resources processing

- docker-jans-auth-server/README.md
- docker-jans-certmanager/README.md
- docker-jans-config-api/README.md
- docker-jans-configurator/README.md
- docker-jans-fido2/README.md
- docker-jans-monolith/jans-mysql-compose.yml
- docker-jans-monolith/jans-postgres-compose.yml
- docker-jans-persistence-loader/README.md
- docker-jans-scim/README.md
- docs/admin/kubernetes-ops/cert-management.md
- docs/admin/reference/kubernetes/docker-jans-auth-server.md
- docs/admin/reference/kubernetes/docker-jans-certmanager.md
- docs/admin/reference/kubernetes/docker-jans-config-api.md
- docs/admin/reference/kubernetes/docker-jans-configurator.md
- docs/admin/reference/kubernetes/docker-jans-fido2.md
- docs/admin/reference/kubernetes/docker-jans-persistence-loader.md
- docs/admin/reference/kubernetes/docker-jans-scim.md
> docs: fix reference to OCI images

- jans-auth-server/common/pom.xml
- jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml
- jans-core/util/src/main/java/io/jans/model/SmtpConfiguration.java
> fix(config-api): hide smtp and client model utility method

- docs/admin/developer/agama/gama-deployment.md
- jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/DeploymentDetails.java
- jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java
- jans-config-api/docs/jans-config-api-swagger.yaml
- jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java
> chore(agama): refactor deployment endpoint

- jans-cli-tui/cli_tui/jans_cli_tui.py
> fix(jans-cli-tui): height of checkbox field

- docs/admin/reference/json/properties/janssenauthserver-properties.md
- jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/GrantService.java
- jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
- jans-config-api/docs/jans-config-api-swagger.yaml
feat(jans-auth-server): made not found exceptions logging level configurable 
closes #4973
> feat(jans-auth-server): made not found exceptions logging level configurable #4973

- docs/admin/reference/database/mysql-config.md
> docs(jans-auth): #4957

- jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthenticationService.java
> feat: add method to allow authenticate user by inum #5004

- jans-fido2/server/src/main/java/io/jans/fido2/service/CertificateService.java
- jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/CertificateVerifier.java
- jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/CommonVerifiers.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/CertificateVerifierTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/CommonVerifiersTest.java
- jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/UserVerificationVerifierTest.java
- Unit test `CommonVerifiers`
- Unit test `CertificateVerifier`
- Unit test `UserVerificationVerifier`
closes #240
Closes #4783,
> fix(fido2): unit test for the package io.jans.fido2.service.verifier

- docs/admin/developer/agama/dsl-full.md
- docs/admin/developer/agama/quick-start.md
- docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
- jans-linux-setup/jans_setup/templates/scripts.ldif
> feat(agama): allow flows to supply the identity of the user to authenticate with a parameterizable attribute

- jans-orm/sql/src/main/java/io/jans/orm/sql/dsl/template/MariaDBJsonTemplates.java
- jans-orm/sql/src/main/java/io/jans/orm/sql/operation/SupportedDbType.java
- jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlConnectionProvider.java
- jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
> feat: update MariaDB JSON_CONTAINS function usage to conform latest

- terraform-provider-jans/docs/resources/fido2_configuration.md
- terraform-provider-jans/examples/resources/jans_fido2_configuration/resource.tf
- terraform-provider-jans/jans/fido2_config.go
- terraform-provider-jans/jans/fido2_config_test.go
- terraform-provider-jans/provider/resource_fido2_configuration.go
- terraform-provider-jans/provider/resource_fido2_configuration_test.go
The following attributes has been added:
- `old_u2f_migration_enabled`
- `super_gluu_enabled`
closes #5024 
> feat(terraform): add missing attributes for fido2 app configuration updates

- docs/admin/planning/kubernetes.md
- docs/admin/planning/vm-cluster.md
> docs: add recommendation about HA 

- demos/benchmarking/docker-jans-loadtesting-jmeter/README.md
- demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/authorization_code_flow.jmx
- demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-test/load_test_ropc.yaml
- demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_couchbase_job.yaml
- demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_ldap_job.yaml
- demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_rdbms_job.yaml
- demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_spanner_job.yaml
- docs/admin/planning/benchmarking.md
- docs/admin/recipes/benchmark.md
> fix(docker-jans-loadtesting-jmeter): errors running flow executor

- docs/admin/recipes/stepped-up-authn.md
> fix(docs): #4881 improvised

- mkdocs.yml
Included Stepped-up Authentication in navigation
#4881
> fix(docs): Included Stepped-up Authentication in navigation

- jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java
> feat: store AttestationType

- docs/admin/auth-server/client-management/software-statements.md
> docs: software statement DCR usecase

- docs/admin/reference/openapi.md
> docs: update API reference page for javadocs links
