.github/workflows/central_code_quality_check.yml, .github/workflows/central_sync_workflows.yml, .github/workflows/code_quality_check.yml
This pull request has Github action workflow that is generic and can be applied all current Jans repos. 
It enables static code analysis and code coverage on each repository.
It should start showing static code analysis data on SonarCloud once this workflow is deployed in respective repos.
Code coverage would be shown less than actual for some of the repositories due to exclusion of those tests that depend on Jans server being up and running. As we figure out how to either make Jans server run within a Github action (probably via Github Service containers) or make tests run against an externally hosted Jans server. Once this is in place we can enable all the tests and modules. SonarCloud will then start reporting complete code coverage percentage. This will also allow us to remove switch …
=> Sonar integration

.github/workflows/central_code_quality_check.yml
- code will now skip tests for those repos where tests are not standalone and hence failing during github build.
- removed additional build for repositories
=> ci: skip test case execution during analysis

.github/workflows/central_code_quality_check.yml
This will enable clean build every time this action is executed.
Fixes JanssenProject/jans-auth-server#196
=> fix: remove m2 caching during sonar analysis

docker-jans-persistence-loader/scripts/couchbase_setup.py, docker-jans-persistence-loader/scripts/ldap_setup.py
When parsing LDIF files, scripts will ensure file descriptors are closed using `with` context. Related issue: https://github.com/JanssenProject/jans-cloud-native/issues/153
=> fix: always close file descriptors after parsing LDIF files

.github/CODEOWNERS
Adding @duttarnab as a code owner to /jans-ce-setup/static/scripts/admin_ui_plugin.py
=> ci: add codeowner

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/conf/jans-sql.properties.tmpl, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-certmanager/Dockerfile, docker-jans-client-api/Dockerfile, docker-jans-client-api/scripts/bootstrap.py, docker-jans-client-api/templates/jans-sql.properties.tmpl, docker-jans-config-api/Dockerfile, docker-jans-config-api/conf/jans-sql.properties.tmpl, docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/plugins.py, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-fido2/conf/jans-sql.properties.tmpl, docker-jans-fido2/scripts/bootstrap.py, docker-jans-persistence-loader/Dockerfile, docker-jans-scim/Dockerfile, docker-jans-scim/conf/jans-sql.properties.tmpl, docker-jans-scim/scripts/bootstrap.py
Overview:
- all Java-centric images are based on `bellsoft/liberica-openjre-alpine:11` image (for Java gRPC compatibility)
- add `enabledTLSProtocols=TLSv1.2` option to SQL connection URI
- install `py3-grpcio 1.41` from Alpine v3.15 repo
=> feat: update base images #672

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/jarm/AuthorizationResponseModeJwtResponseTypeCodeSignedEncryptedHttpTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java
formatted code and corrections for Brazil OB JARM fapi1-advanced-final issue (new numbers on monorepo)# 310 to 315
=> fix: brazilob jarm fapi conformance test last7 issues

README.md
As suggested by Mike, we are moving content of `Quick start` section to Jans [Wiki](https://github.com/JanssenProject/jans/wiki)
=> docs: move quick start content to wiki

jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalDynamicClientRegistrationService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/external/ExternalDynamicClientRegistrationServiceTest.java
If there no any custom script for dynamic registration we should not fail entire call (avoid npe).
https://github.com/JanssenProject/jans/issues/710
=> fix(jans-auth-server): don't fail registration without custom script (#710)

.github/ISSUE_TEMPLATE/development-item.md, .github/ISSUE_TEMPLATE/failing-tests.md, .github/SECURITY.md, docs/community/CONTRIBUTING.md, docs/community/testing.md, docs/community/triage.md
Consolidate `docs`, `home` and `.github` repo into `jans` monorepo
- `docs` repo: 
Not moving content from this repo into `jans`. This repo has lot of `work-in-progress` or placeholder content. Not suitable for moving into `jans` at this point in one go. Right approach would be to take work from this repo, finish it and then incrementally add it to `jans/docs`.
- `home` repo:
Can be archived as most of the content from this repo is now moved to appropriate places in `jans`. 
- `.github`
Can be archived. Moved all content to `jans`.
=> ci: consolidate home and .gitHub repo

jans-cli/cli/config_cli.py
Add logout option as explained in https://github.com/JanssenProject/jans/issues/706
=> feat: jans-cli logout

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
fix(jans-auth-server): if consent is off then check whether response already have code
https://github.com/JanssenProject/jans/issues/736
=> fix(jans-auth-server): if consent is off then check whether response already have code

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
fix(jans-auth-server): if consent is off then check whether response already have access_token
https://github.com/JanssenProject/jans/issues/736
=> fix(jans-auth-server): if consent is off then check whether response already have access_token

jans-config-api/server/src/test/resources/feature/config/properties/properties.feature
@yuriyz, request you to please review and approve.
Jenkins build was failing due to failed test case for patch of `statWebServiceIntervalLimitInSeconds` which was removed.
Commented the individual property patch test case and kept only one to test the endpoint.
=> test: excluded test from execution

.github/workflows/release.yaml, docker-jans-auth-server/libs/casa-external_fido2.py, docker-jans-auth-server/libs/casa-external_super_gluu.py, docker-jans-auth-server/libs/casa-external_twilio_sms.py, docker-jans-auth-server/libs/casa-external_u2f.py
Updates some  external scripts
=> fix: update scripts

docker-jans-fido2/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/templates/jans-auth/dynamic-conf.json, docker-jans-persistence-loader/templates/jans-auth/dynamic-conf.ob.json
Overview:
- update `jans-fido2-server` to address bad archive issue
- auto-update of `jansConfDyn` attribute in persistence
=> fix(image): update images

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/auth_conf.py, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-auth-server/scripts/entrypoint.sh
The changeset enable pushing `otp_configuration.json` and `super_gluu_creds.json` to secrets layer.
=> feat(image): push otp and super_gluu configuration to secrets

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectUriResponse.java, jans-auth-server/server/src/main/java/io/jans/as/server/util/RedirectUtil.java
fix(jans-auth-server): corrected 500 error if absent redirect_uri in object for fapi
(caught by fapi1-advanced-final-ensure-request-object-without-redirect-uri-fails, fapi1-advanced-final-ensure-redirect-uri-in-authorization-request)
https://github.com/JanssenProject/jans/issues/801
=> fix(jans-auth-server): corrected 500 error if absent redirect_uri in object for fapi

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java
fix(jans-auth-server): corrected error code for absent redirect_uri in object (fapi)
(caught by fapi1-advanced-final-ensure-request-object-without-redirect-uri-fails, fapi1-advanced-final-ensure-redirect-uri-in-authorization-request)
https://github.com/JanssenProject/jans/issues/801
=> fix(jans-auth-server): corrected error code for absent redirect_uri in object (fapi)

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SetPublicSubjectIdentifierPerClient.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SetPublicSubjectIdentifierPerClientTest.java, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterErrorResponseType.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SectorIdentifierService.java, jans-linux-setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/issues/368
=> feat(jans-auth-server): set public subject identifier per client

jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ParAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/authorize/JwtAuthorizationRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParService.java, jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParValidator.java
feat(jans-auth-server): added to par extra nbf and exp (for 60min) validation
https://github.com/JanssenProject/jans/issues/824
=> feat(jans-auth-server): added to par extra nbf and exp (for 60min) validation

jans-scim/service/src/main/java/io/jans/scim/auth/ScimService.java, jans-scim/service/src/main/java/io/jans/scim/auth/oauth/BaseOAuthProtectionService.java, jans-scim/service/src/main/java/io/jans/scim/auth/oauth/DefaultOAuthProtectionService.java
=> Jans SCIM issue 834

jans-config-api/docs/jans-config-api-swagger.yaml
@yuriyz, request you to please review and approve swagger spec changes for default values for openid client endpoint.
Due to incorrect default value jans-cli was failing.
=> feat(jans-config-api): swagger update for default value

docker-jans-auth-server/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-client-api/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-scim/requirements.txt, jans-pycloudlib/jans/pycloudlib/persistence/spanner.py, jans-pycloudlib/jans/pycloudlib/persistence/sql.py
Overview:
- table mapping for SQL persistence now omitting extra info like COLLATION in column type
- table mapping for Spanner persistence loads the column info using queries
The changes are mainly used for comparing data type from static file against column types in persistence.
=> refactor: table mapping for SQL and Spanner persistence

docker-jans-config-api/Dockerfile, docker-jans-config-api/README.md, docker-jans-config-api/jetty/log4j2.xml, docker-jans-config-api/plugins/admin-ui/log4j2-adminui.xml.tmpl, docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/entrypoint.sh
Overview:
- update jans-config-api-server
- update URLs of downloadable plugins
- add facter script
- update `log4j2.xml` customization
- add `log4j2-adminui.xml` (generated if admin-ui plugin is enabled); see modified `README.md` for its configuration
=> feat: update config-api image

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/AdminRole.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/user/UserManagementService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java
https://github.com/JanssenProject/jans/issues/888
=> feat: add deletable flag to admin-ui role object #888

jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json
Added a few missing e.g. `jwt` `responseType` and `private_key_jwt` token auth method and `scopes_supported`
=> fix: added missing values for openbanking

jans-cli/cli/jca.yaml, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/JwksResource.java
[Issue 958](https://github.com/JanssenProject/jans/issues/958):  Jwks endpoint not returning all attributes.
Analysis: issue due to missing attributes in swagger spec
Impacted components:
1. `jans-config-api`
2. `jans-cli`
Swagger spec and jans-cli spec has been updated
=> fix: change in swagger spec for jwks to return missing attributes

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/utils.py
- Added support for role-based clients (i.e. `jans-cli`)
- the new `/app/templates/jans-cli` directory under `janssenproject/persistence-loader` image is synchronized from `jans-linux-setup`
- added new key `role_based_client_id` into config layer (will be pre-populated into template)
- added new key `role_based_client_pw` and `role_based_client_encoded_pw` (will be pre-populated into template)
=> feat: add support for role-based client (i.e. jans-cli)

.github/workflows/central_code_quality_check.yml
Currently sonar workflow is not correctly identifying directories that has undergone changes in a particular PR. And hence Sonar analysis is not getting triggered. 
=> fix(ci): fix change identification logic

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/DefaultPromptLoginTest.java, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java
=> feat(jans-auth-server): new client config option defaultpromptlogin

docker-jans-auth-server/requirements.txt, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/README.md, docker-jans-certmanager/requirements.txt, docker-jans-certmanager/scripts/base_handler.py, docker-jans-certmanager/scripts/client_api_handler.py, docker-jans-certmanager/scripts/ldap_handler.py, docker-jans-certmanager/scripts/web_handler.py, docker-jans-client-api/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-scim/requirements.txt, jans-pycloudlib/jans/pycloudlib/pki.py, jans-pycloudlib/jans/pycloudlib/utils.py
- Target issue #684
- Added new option named `valid-to` (example: `certmanager patch web --opts valid-to:397`) where value is an integer greater than equal 1 (if value is below 1 or non-integer, fallback to default value `365`); the value represents number of days.
- Affected services: `web`, `ldap`, `client-api`
- Refer to `README.md` for new option
=> feat: add validity length (in days) for certs

jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
fix(jans-auth-server): reduce noise in logs when session can't be found
https://github.com/GluuFederation/oxAuth/issues/1646
=> fix(jans-auth-server): reduce noise in logs when session can't be found

jans-linux-setup/jans_setup/templates/scripts.ldif
As part of issue https://github.com/JanssenProject/jans/issues/978
=> fix: jans-linux-setup remove fido authentication scripts from template

docker-jans-auth-server/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-scim/Dockerfile
- base image pinned to `liberica-openjre-alpine:11.0.13-8`
- updated upstream source (`.war`/`.jar`)
- sync upstream source (removed Fido u2f) for persistence-loader and auth-server
=> chore: update image dependencies

jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java
fix(jans-auth-server): validate pkce after extraction data from request object (#999)
https://github.com/JanssenProject/jans/issues/999
=> fix(jans-auth-server): validate pkce after extraction data from request object (#999)

docker-jans-client-api/Dockerfile, docker-jans-client-api/templates/jans.properties.tmpl
The changeset introduces the following changes
- base image pinned to `bellsoft/liberica-openjre-alpine:11.0.13-8`
- updated `jans-client-api-server` source (contains fix for #1006)
- added missing `configApi_ConfigurationEntryDN` config in `jans.properties`
=> chore: update client-api image

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/jetty/jans-auth.xml, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-auth-server/scripts/entrypoint.sh, docker-jans-config-api/Dockerfile, docker-jans-config-api/jetty/jans-config-api.xml, docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/entrypoint.sh, docker-jans-fido2/Dockerfile, docker-jans-fido2/jetty/jans-fido2.xml, docker-jans-fido2/scripts/bootstrap.py, docker-jans-fido2/scripts/entrypoint.sh, docker-jans-scim/Dockerfile, docker-jans-scim/jetty/jans-scim.xml, docker-jans-scim/jetty/log4j2.xml, docker-jans-scim/scripts/bootstrap.py, docker-jans-scim/scripts/entrypoint.sh
- Target issue #1010 
1. switch to archived `.war` instead of exploded directory under `/opt/jans/jetty/$app/webapps`
1. set `jetty.deploy.scanInterval=0` via command-line to disable hot-deployment
- Misc.
- customization on `/opt/jans/jetty/$app/start.d/server.ini` file is removed in favor of passing arguments when running Jetty
- added missing `additivity` attribute for SCIM `log4j2.xml` file
=> feat: avoid jetty hot-deployment issue

docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json, jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizationRedirectUrisRegexTest.java, jans-auth-server/client/src/test/resources/testng.properties, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterErrorResponseType.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/RedirectionUriServiceTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-cli/cli/jca.yaml, jans-cli/docs/cli/cli-jans-authorization-server.md, jans-cli/docs/im/im-jans-authorization-server.md, jans-config-api/docs/jans-config-api-swagger.yaml, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/issues/348
1. Added client attribute to validate redirect uris using a regex.
2. Added feature flag `redirectUrisRegexEnabled`.
=> feat: support regex client attribute to validate redirect uris

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/couchbase_setup.py, docker-jans-persistence-loader/scripts/ldap_setup.py, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docs/user/how-to/add-custom-ldifs.md
- Target issue: #891
1. the entrypoint will scan for all `.ldif` files under predefined directory `/app/custom_ldif` (where users can mount files into this directory)
1. for every `.ldif` file found, entrypoint will try to generate rendered template (if file contains template context) under `/app/tmp/`
1. entrypoint will import data parsed from the generated template into user-selected persistence (`ldap`/`sql`/`spanner`/`couchbase`)
=> feat: add support to import custom ldif

jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/RedirectionUriServiceTest.java, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
1. Fixing redirect_uri validator issue when single item is in client redirect uris and param received is blank.
2. Enabling `redirectUrisRegexEnabled` to run test in Jenkins.
=> Fix: Validate redirect_uri blank and client redirect uris single item

jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/AuthorizationResponseAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ForceSignedRequestObjectTest.java, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
- Target issue #378
- new configuration entry:
``` 
{
...
"forceSignedRequestObject": true,
...
}
```
=> feat(jans-auth-server): force signed request object

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizedAcrValuesTest.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterRestWebServiceImpl.java
- Target issue #333
Now you can configure the authorized acr values for a client with Dynamic Client Registration endpoint to restrict requests to use only acr in the list.
=> feat(jans-auth-server): authorized acr values

jans-linux-setup/jans_setup/schema/jans_schema.json, jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
As explained in https://github.com/JanssenProject/jans/issues/1088
=> fix: jans-linux-setup multivalued json mapping (ref: #1088)

README.md
Link to Wiki on README was broken.
=> docs: fix link to Janssen Wiki

docker-jans-auth-server/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-client-api/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-persistence-loader/templates/configuration.ldif, docker-jans-scim/Dockerfile
- updated `BUILD_DATE`
- synchronized upstream templates and schema in `persistence-loader` image
- upgraded `libcrypto` and `libssl` to address CVE-2022-0778
=> chore: images update

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
Since default string size is 64, we don't need explicitly specify attributes of size 64 in sql_data_type.json
=> fix: jans-linux-setup remove attributes of size 64 from sql_data_type.json

docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/audit/debug/ServletLoggingFilter.java, jans-cli/cli/jca.yaml, jans-cli/docs/cli/cli-jans-authorization-server.md, jans-cli/docs/cli/cli-logging-configuration.md, jans-cli/docs/im/im-jans-authorization-server.md, jans-cli/docs/im/im-janssen-logging-configuration.md, jans-config-api/common/src/main/java/io/jans/configapi/rest/model/Logging.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/LoggingResource.java, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/issues/1085
-----------------------------
Fix typo "httpLoggingExludePaths" in different places:
jans-auth-server 
jans-cli 
jans-config-api 
jans-linux-setup 
docker-jans-persistence-loader
-----------------------------
"httpLoggingExludePaths" was changed to "httpLoggingExcludePaths" in next documents and config files:
https://github.com/JanssenProject/jans/blob/main/docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
https://github.com/JanssenProject/jans/blob/main/docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
https://github.com/JanssenProject/jans/blob/main/jans-cli/cli/jca.yaml
https://github.com/JanssenProject/jans/blob/main/jans-cli/docs/cli/cli-jans-au …
=> fix: Typo httpLoggingExludePaths to httpLoggingExcludePaths

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-persistence-loader/scripts/upgrade.py
The changeset introduced to address several issues:
- typo on `httpLoggingExludePaths` (renamed to `httpLoggingExcludePaths`) config
- MySQL indexes for `jansClntAuthz.jansClntId` column are skipped due to unsupported feature of the server
- Spanner indexes for `ARRAY` are skipped
=> fix: typo and indexing error

docs/assets/README.md, docs/technical/README.md, docs/technical/technical-overview-template.md
- Target issue
Currently technical documentation for Janssen modules doesn't exist. Earlier(before monorepo) documentation existed under docs repo [here](https://github.com/JanssenProject/docs/tree/main/source/janssen-modules). This documentation is scant and not available in all modules.
Under `jans` monorepo, we have to start an effort to put together detailed technical design documentation for all modules.  Under `jans` monorepo, technical design documentation should go under `docs/technical`.
This PR attempts to provide basic structure and template that all code owners can follow while writing technical design documents for respective modules:
- README for main `/technical` directory: This is supposed to capture overall Janssen design …
=> docs: add README for technical docs

jans-auth-server/common/src/main/java/io/jans/as/common/service/common/InumService.java, jans-auth-server/common/src/test/java/io/jans/as/common/service/common/InumServiceTest.java, jans-auth-server/common/src/test/resources/testng.xml
Part of the work to be done for issue: https://github.com/JanssenProject/jans/issues/331
https://github.com/JanssenProject/jans/issues/331
Restored call to the external id generator for people and client types.
=> Fix: Restored IdGenerator call to external custom script

docker-jans-configurator/scripts/bootstrap.py, docker-jans-persistence-loader/scripts/utils.py
Overview:
- added missing config and secrets of clients in `configurator` (previously they are created in `persistence-loader` instead)
- added notes about deprecated clients config and secrets
#1133 
The changeset guarantees client ID and secrets are created upfront in `configurator` so they can be exported into `config.json` and `secret.json`. Note this only work in fresh installation.
For installation upgrade, make sure to run `janssenproject/configurator dump` to pull latest config and secrets into `config.json` and `secret.json`. Afterwards, proceed to upgrading images
=> fix: avoid duplicated client when re-running persistence-loader and configurator

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java, jans-auth-server/server/src/main/webapp/login.xhtml
fix(jans-auth-server): escape login_hint before rendering
https://github.com/GluuFederation/oxAuth/issues/1657
=> fix(jans-auth-server): escape login_hint before rendering

docs/CONTRIBUTING.md
Closes #1156 
- Added GPG signing requirements to the contribution guide
- Rearrange content in commit conventions
=> docs: add commit signing and rearrange

docs/user/using-jans-cli/cli-ldap-configuration.md, docs/user/using-jans-cli/im/im-openid-connect-clients.md, docs/user/using-jans-cli/im/im-user.md
This PR should fix some grammar and typos in [jans cli doc](https://github.com/JanssenProject/jans/blob/main/docs/user/using-jans-cli/im/im-openid-connect-clients.md#create-a-new-openid-client).
=> fix: typos in jans cli doc

jans-auth-server/model/src/main/java/io/jans/as/model/jwk/JSONWebKey.java
fix(jans-auth-server): do not serialize jwkThumbprint
We need it to resolve config-api build failure.
See https://github.com/JanssenProject/jans/pull/1150
=> fix(jans-auth-server): do not serialize jwkThumbprint

jans-linux-setup/jans_setup/static/auth/fido2/server_metadata/.dontdelete, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
#1107 
1. jansAuthData in jansFido2AuthnEntry table changed to TEXT type because it was too short 
2. added jansCodeChallengeHash column in jansFIDO2AuthnEntry
=> Issue 1107

jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java, jans-auth-server/model/src/main/java/io/jans/as/model/util/CertUtils.java
fix(jans-auth-server): corrected signature algorithm identification with java 11 and later
https://github.com/GluuFederation/oxAuth/issues/1661
=> fix(jans-auth-server): corrected signature algorithm identification with java 11 and later

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/scripts/utils.py, docker-jans-persistence-loader/templates/jans-config-api/dynamic-conf.json
The changeset synchronize templates + static from upstream while preserving functionality as seen in https://github.com/JanssenProject/jans/pull/1183
Role scope mapping (i.e. `api-admin`) is now pre-populated from `jans-config-api-swagger.yaml` and `role-scope-mappings.json`.
On upgrading, the mapping will be compared between current and pre-populated mapping.
=> feat: pre-populate role scope mapping dynamically

jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java, jans-orm/core/src/main/java/io/jans/orm/reflect/property/BasicPropertyAccessor.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlConnectionProvider.java
=> feat: merge ORM from Gluu

docker-jans-persistence-loader/scripts/sql_setup.py
The changeset fixes error on index creation (MySQL 5.7).
Ref: #1204 
When using MySQL 5.7, instead of creating index with `CAST` query on it, create virtual column + index specified for JSON columns.
=> fix: handle index error for JSON columns

docs/interception-scripts/GoogleSignIn.md.txt, jans-auth-server/server/src/main/webapp/auth/google/login.xhtml, jans-linux-setup/jans_setup/static/extension/person_authentication/GoogleExternalAuthenticator.py
=> feat: add script for Google login

jans-cli/cli/config_cli.py
CLI was sending only modified key when using **Puts/replaces JSON Web Keys**
=> fix: jans-cl update WebKeysConfiguration

docker-jans-persistence-loader/scripts/couchbase_setup.py, docker-jans-persistence-loader/scripts/upgrade.py
The changeset fixes 2 errors found while using Couchbase persistence:
1. Some entries are placed into incorrect bucket
2. Loading role mapping from persistence throws `TypeError`
1. Trailing comma must be added into the tuple (i.e. `("tokens_",)` instead of `("tokens_")`) to ensure key prefix is checked against a tuple (not a list of characters)
2. Load role mapping from persistence using `json.loads` if it's a JSON string, otherwise use the role mapping directly
=> fix: errors adding/upgrading data into couchbase persistence

docs/user/how-to/authn-with-apache-reverse-proxy.md, docs/user/using-jans-cli/cli-tips.md
Documentation did not cover CLI device authentication step. Adding this details to CLI documentation and other related docs.
=> docs: update docs for CLI device authn

jans-linux-setup/tools/key_regeneration.py
=> fix: jans-linux-setup-key key-regeneration fix spanner host

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/scripts/utils.py, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
The changeset updates `jans-auth` dynamic config in persistence
1. Templates/static/schemas are re-synchronized from `jans-linux-setup`
2. Upgrade script handles the automatic updates for existing entry
=> chore: sync jans-auth dynamic config

jans-client-api/debian/client-api
`netstat` is not default in recent distros instead `ss` comes.
I also replaced tabs with spaces
=> fix: jans-client-api replace netstat with ss in startup script

jans-fido2/model/src/main/java/io/jans/fido2/model/entry/Fido2Entry.java, jans-fido2/model/src/main/java/io/jans/fido2/model/entry/Fido2RegistrationEntry.java, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> fix: adjust beans and schema #1107

jans-auth-server/model/src/main/java/io/jans/as/model/uma/persistence/UmaPermission.java, jans-auth-server/model/src/main/java/io/jans/as/model/uma/persistence/UmaResource.java, jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java, jans-auth-server/model/src/test/java/io/jans/as/model/util/UtilTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AbstractToken.java
Ticket: https://github.com/JanssenProject/jans/issues/1236
=> Fix: Use Duration class instead of custom util to calculate seconds from date to now

docs/CONTRIBUTING.md
Updated table of content to add issue guidelines
=> fix: add issue guidelines to TOC

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
refactor(jans-auth-server): added authz request service
=> refactor(jans-auth-server): added authz request service

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/AdminPermission.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/LicenseSpringCredentials.java, jans-config-api/plugins/admin-ui-plugin/pom.xml, jans-config-api/plugins/admin-ui-plugin/src/main/assembly/assembly.xml, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/LicenseConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/AppConstants.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ClientFactory.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/CommonUtils.java
https://github.com/JanssenProject/jans/issues/1258
=> fix: the admin-ui backend issues related to jetty 11 migration #1258

docker-jans-auth-server/requirements.txt, docker-jans-auth-server/scripts/keystore_mod.py, docker-jans-certmanager/requirements.txt, docker-jans-certmanager/scripts/auth_handler.py, docker-jans-client-api/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-config-api/scripts/utils.py, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-persistence-loader/scripts/couchbase_setup.py, docker-jans-persistence-loader/scripts/ldap_setup.py, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-scim/requirements.txt, jans-pycloudlib/.coveragerc, jans-pycloudlib/jans/pycloudlib/persistence/__init__.py, jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py, jans-pycloudlib/jans/pycloudlib/persistence/ldap.py, jans-pycloudlib/jans/pycloudlib/persistence/spanner.py, jans-pycloudlib/jans/pycloudlib/persistence/sql.py, jans-pycloudlib/jans/pycloudlib/version.py, jans-pycloudlib/jans/pycloudlib/wait.py, jans-pycloudlib/setup.py, jans-pycloudlib/tests/conftest.py, jans-pycloudlib/tests/test_manager.py, jans-pycloudlib/tests/test_persistence.py, jans-pycloudlib/tests/test_wait.py
Helper methods are added into jans-pycloudlib directly to promote code reuse for internal/external images (i.e. `gluufederation/casa`) that need to create entry from LDIF file.
Each persistence client classes has `create_from_ldif` method that allows importing data from LDIF file into respected persistence (`ldap/couchbase/sql/spanner`). By providing this method, any additional LDIF files (i.e. for Casa) can be moved from `janssenproject/persistence-loader` into 3rd-party images.
=> feat: add helper to create persistence entry from LDIF file

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py
Overview:
1. Added missing permission and `defaultPermissionInToken` attribute in role-scope mapping
2. Changed `jansCodeChallengeHash` column type (from `TEXT` to `INT`)
1. Entrypoint loads `role-scope-mappings.json` to compare to role-scope permissions in persistence. Any missing permission will be added into persistence. The same rule applied to missing `defaultPermissionToken` attribute. 
Ref: d61be0bf633020c6bd989e603bb983dc7a45b78b
1. The `jansCodeChallengeHash` column type is changed to `INT` (previously a `TEXT` type). 
Ref: 369129d0c2614afb536d0e1329ac106fd7da187d
=> fix: update persistence schema and entry

jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java
fix(jans-auth-server): removed CONFIG_API from AS supported script types #1286
=> fix(jans-auth-server): removed CONFIG_API from AS supported script types #1286

jans-cli/cli/config_cli.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
Releated issue https://github.com/JanssenProject/jans/issues/1283
=> feat: jans-cli use test client (ref: #1283)

docs/user/how-to/authn-with-apache-reverse-proxy.md
Link to section for Jans CLI authorization via device flow wasn't correct
=> docs: fix CLI device flow link

jans-config-api/server/src/main/java/io/jans/configapi/filters/AuthorizationFilter.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ScopeService.java, jans-config-api/server/src/main/java/io/jans/configapi/util/AuthUtil.java
@yuriyz request your review and approval.
Added check to validate scope while client creation
Related issue [1282](https://github.com/JanssenProject/jans/issues/1282)
=> feat(jans-config-api): added scope DN validation while client creation

jans-cli/cli/config_cli.py, jans-cli/cli/enums.json
When creating user we add each attrbiute as **customAttributes** schema  in the following format:
```
{
"name": "attribName",
"multiValued": false,
"values": [
"attribValue"
]
}
```
Admin should type **attribName* but he does not know which attributes are allowed. In this PR, CLI obtains list of attribute names from endpoint `/jans-config-api/api/v1/attributes` of jans-config-api, and provides as suggestion:
=> feat: jans-cli obtain list of attrbiutes from server when creating user

jans-cli/cli/config_cli.py
As discussed in https://github.com/JanssenProject/jans/issues/892, common items are grouped and placed in submenu:
=> feat: jans-cli group common items in menu (ref: #892)

jans-linux-setup/jans_setup/setup_app/installers/config_api.py
1) Jans Scim Server should be installed to be able to use scim-plugin 
2) Jans Fido2 Server should be installed to be able to use fido2-plugin
=> fix: jans-linux-setup config-api plugin dependencies

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/entrypoint.sh, docker-jans-certmanager/Dockerfile, docker-jans-client-api/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/entrypoint.sh, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/entrypoint.sh, docker-jans-persistence-loader/Dockerfile, docker-jans-scim/Dockerfile, docker-jans-scim/scripts/entrypoint.sh
The changeset fixes incorrect usage of ownership/permission (in docker context) as reported in #1307 
- remove `chown` command as it increases the size of the image
- replace `chgroup -R` command with `chmod -R g=u` to set directory ownership/permission
- use `chmod 664` command to set file permission
=> feat: adjust ownership and permission to avoid bloated images

jans-cli/cli/config_cli.py, jans-config-api/docs/jans-config-api-swagger.yaml
When querying list of scopes, we can enumerate scope type as follows:
=> feat: config-cli enumerate scope type

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile
Running `janssenproject/auth-server` on KNative is failed due to permission on `jans-auth.xml`. This changeset set the ownership/permission to running user (1000) explicitly.
=> fix: set permission for jans-auth.xml explicitly

docker-jans-persistence-loader/scripts/upgrade.py
While trying to upgrade data using `ldap` persistence, a LDAP schema error is thrown.
Here's the problematic line:
```
inum={token_server_admin_ui_client_id},ou=clients,o=jans
```
As `token_server_admin_ui_client_id` fetched from config layer may returns empty string (possibly `admin-ui` is not deployed), the empty `inum` value produces invalid DN.
This changeset checks whether the config is available before running data upgrade.
=> fix: invalid LDAP schema reading token_server client ID

jans-cli/cli/pylib/tabulate/tabulate.py, jans-linux-setup/jans_setup/setup_app/data/package_list.json, jans-linux-setup/jans_setup/setup_app/downloads.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/pylib/jproperties.py, jans-linux-setup/jans_setup/setup_app/utils/base.py, jans-linux-setup/jans_setup/setup_app/utils/crypto64.py
=> feat: Jans linux setup ubuntu22 Installation

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py, jans-linux-setup/jans_setup/setup_app/utils/crypto64.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py
Use python libs instead of external commands for getting and decoding ssl cert
=> feat: Jans linux setup refactor

jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java
@yuriyz request you to please review and approve changes to fix build issue due to LocalizedString change
=> feat(jans-config-api): fixed build issue due to LocalizedString change

jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
In this PR logging level of jans-auth is set to TRACE when test data is loaded, that is with `-t` option.
=> fix: jans-linux-setup set log level to TRACE for test data

jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
fix(jans-linux-setup): defaults loggingLevel to INFO
=> fix(jans-linux-setup): defaults loggingLevel to INFO

jans-eleven/pom.xml, jans-notify/pom.xml
Some of the maven repository URLs in POM files are not using secure HTTP (https). 
also, jans-notify was pointing to `repo2` in the maven repo. This URL was not accessible. It should be using `repo1`.
Manually varify if the new https URLs are accessible.
=> fix: use secure http urls for maven repositories

jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java
feat(jans-core): added more error logs if script is not loaded
=> feat(jans-core): added more error logs if script is not loaded

jans-cli/cli/config_cli.py
In automated testing WordCompleter is not needed, since expect causes issue. Option ` --no-suggestion` is added so that it does not suggest possible values.
=> feat: jans-cli --no-suggestion for automated testing

jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/admin-ui-plugin/pom.xml, jans-config-api/plugins/fido2-plugin/pom.xml, jans-config-api/plugins/fido2-plugin/src/main/assembly/assembly.xml, jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/rest/ApiApplication.java, jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/rest/Fido2RegistrationResource.java, jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/service/Fido2RegistrationService.java, jans-config-api/plugins/fido2-plugin/src/main/java/io/jans/configapi/plugin/fido2/util/Constants.java
https://github.com/JanssenProject/jans/issues/1465
=> feat: need endpoint to get details of connected FIDO devices registered to users #1465

jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java
SqlEntryManager: method to get LocalizedString values was modified similar to SqlLdapEntryManager
detected trying to persist sites with mysql DB.
https://github.com/JanssenProject/jans/issues/260
=> fix(jans-orm):sql localizedstring persistence SqlEntryManager

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/model/user/CustomUser.java, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java
@yuriyz request you to please review and approve swagger spec change to expose inum in root level of response
Related issue https://github.com/JanssenProject/jans/issues/1348
=> feat(jans-config-api): swagger spec change to expose user inum at root level of response

jans-linux-setup/jans_setup/templates/jans-cli/.#client.ldif
Remove unnecessary temporary link file
=> fix: jans-linux-setup remove temporary link file

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/profiles/local/test.properties, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ConfigResource.java
@yuriyz, request you to please review and approve the changes for agama configuration.
Related issue#[1493](https://github.com/JanssenProject/jans/issues/1493)
=> feat(jans-config-api): agama configuration integration

jans-cli/cli/config_cli.py
Fix logic of hidin menu in case plugin is not available.
=> fix: jans-cli hide menu item

jans-linux-setup/jans_setup/jans_setup.py
gcs path should be added after package check so that missing python libraries installed.
This PR solves issue https://github.com/JanssenProject/jans/issues/1514
=> fix: jans-linux-setup add gcs path after packages check (ref: #1514)

jans-cli/cli/config_cli.py
Users obtained via scim is tabluated as follows:
```
+----+--------------------------------------+------------+--------------------+----------+
|    | id                                   | userName   | displayName        | active   |
+====+======================================+============+====================+==========+
|  1 | 8d50a04b-08f8-4bd6-b779-ceb441a4c360 | admin      | Default Admin User | True     |
+----+--------------------------------------+------------+--------------------+----------+
|  2 | 2e8d340e-4289-4e6a-9c71-798b0239635a | devrim     | Devrim Yatar            | False    |
+----+--------------------------------------+------------+--------------------+----------+
```
=> feat: jans-cli tabulate scim user list

jans-cli/cli/config_cli.py
If **customAttributes** of a user is `None`, for iteration was failing.
=> fix: jans-cli user list failing for empty customAttributes

jans-linux-setup/jans_setup/setup_app/downloads.py
Since gcs path was missing in `download_all()`, download was failed
=> fix: jans-linux-setup add gcs module path for downloading apps

docs/user/how-to/authn-with-apache-reverse-proxy.md
`mod_auth_openidc` guide did not mention the attribute(claim) release. So adding that.
=> docs: add claims release to mod_auth_openidc

docs/README.md
fix links to contributing guide and CoC
=> docs: fix links to contributing guide and CoC

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/authorize/JwtAuthorizationRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectUriResponse.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/RedirectionUriService.java, jans-auth-server/server/src/test/java/io/jans/as/server/model/authorize/JwtAuthorizationRequestTest.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
feat(jans-auth-server): added restriction for request_uri parameter (blocklist and allowed client.request_uri) #1503
https://github.com/JanssenProject/jans/issues/1503
=> feat(jans-auth-server): added restriction for request_uri parameter (blocklist and allowed client.request_uri) #1503

docker-jans-auth-server/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
The changeset adds support for `requestUriBlockList` config.
Misc:
* rename `CASA_EXTRAS_VERSION` to `FLEX_SOURCE_VERSION`
* rename `JANS_AGAMA_VERSION` to `JANS_SOURCE_VERSION`
* rename `JANS_LINUX_SETUP_VERSION` to `JANS_SOURCE_VERSION`
* update `jans-auth-server` WAR file
No docs need to be updated.
=> feat: add support for requestUriBlockList config

jans-pycloudlib/README.md, jans-pycloudlib/docs/conf.py, jans-pycloudlib/docs/config.rst, jans-pycloudlib/docs/manager.rst, jans-pycloudlib/docs/secret.rst, jans-pycloudlib/jans/pycloudlib/config/base_config.py, jans-pycloudlib/jans/pycloudlib/config/consul_config.py, jans-pycloudlib/jans/pycloudlib/config/google_config.py, jans-pycloudlib/jans/pycloudlib/config/kubernetes_config.py, jans-pycloudlib/jans/pycloudlib/manager.py, jans-pycloudlib/jans/pycloudlib/secret/base_secret.py, jans-pycloudlib/jans/pycloudlib/secret/google_secret.py, jans-pycloudlib/jans/pycloudlib/secret/kubernetes_secret.py, jans-pycloudlib/jans/pycloudlib/secret/vault_secret.py, jans-pycloudlib/pyproject.toml, jans-pycloudlib/tests/conftest.py, jans-pycloudlib/tests/test_config.py, jans-pycloudlib/tests/test_manager.py, jans-pycloudlib/tests/test_secret.py
The changeset adds and/or updates typehint in the following sourcecode:
- `jans.pycloudlib.manager` module
- `jans.pycloudlib.config` sub-package
- `jans.pycloudlib.secret` sub-package
This PR is a part of tasks listed in #1565 
Typehint are added/updated based on reports from `mypy`.
=> refactor(pycloudlib): add more typehint on manager, secret, and config modules

docker-jans-auth-server/Dockerfile, docker-jans-fido2/Dockerfile
Ref: #1588 
The changeset updates WAR files and casa-external modules.
=> fix: update external modules for otp/fido2

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/entrypoint.sh
Ref: #1588 
Added Fido2 client as a workaround (as mentioned [here](https://github.com/JanssenProject/jans/issues/1499#issuecomment-1163429001))
=> fix: a workaround for fido2 dependency

jans-linux-setup/jans_setup/setup.properties.sample, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
1) setup should choose opendj if not set in setup.properties file as described in https://github.com/JanssenProject/jans/issues/1612
2) Add sample mysql backend usage in `setup.properties.sample`
=> Jans linux setup setup properties opendj

jans-pycloudlib/docs/README.md, jans-pycloudlib/docs/cli.rst, jans-pycloudlib/docs/conf.py, jans-pycloudlib/docs/index.rst, jans-pycloudlib/jans/pycloudlib/cli/__init__.py, jans-pycloudlib/jans/pycloudlib/cli/encoding.py
The changeset adds and/or updates typehint in `jans.pycloudlib.cli` modules.
This PR is a part of tasks listed in https://github.com/JanssenProject/jans/issues/1565
Typehint are added/updated based on reports from `mypy`.
=> refactor(pycloudlib): add more typehint on cli modules

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
As described in https://github.com/JanssenProject/jans/issues/1596
=> feat: jans linux setup enable/disable script via arg

jans-cli/setup.py
In commit https://github.com/JanssenProject/jans/commit/ea929c0637c40ee75f3adbd5377c5e08aebbe087 , jans-setup copies yaml files from server directories (feat: jans-cli no local yaml files). For that reason, pyz file is missing yaml files and fails. In this PR, setup.py modified so that it downloads yaml files when building.
=> fix: jans-cli download yaml files for build

jans-auth-server/static/pom.xml
fix(jans-auth-server): disable surefire for jans-auth-static
https://github.com/JanssenProject/jans/issues/1644
=> fix(jans-auth-server): disable surefire for jans-auth-static

jans-auth-server/client/src/main/java/io/jans/as/client/service/StatService.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/StatWSTest.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/StatResource.java, jans-config-api/server/src/main/java/io/jans/configapi/security/client/AuthClientFactory.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AuthService.java
https://github.com/JanssenProject/jans/issues/1575
=> feat: add support for date ranges in statistic endpoint #1575

docs/admin/integration/custom-web-development/authn-with-apache-reverse-proxy.md
The link to CLI main menu was broken after the restructuring of docs.
=> fix: correct the link to image

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py
`source_files` should be class attirbute for `JansAuthInstaller` so that they are downloaded for packaging.
=> fix: jans-linux-setup download jans-auth and jans-auth-client fro --download-exit

jans-linux-setup/jans_setup/templates/scripts.ldif
Script **Forgot_Password_2FA_Token** is not working properly. Disabled until it is fixed.
It can be enabled after installation by `python3 /opt/jans/jans-setup/setup.py -enable-script=B270-381E` for testing.
=> fix: jans-linux-setup disable script Forgot_Password_2FA_Token

jans-config-api/docs/jans-config-api-swagger.yaml
As JAVA programs can be used for custom scripts, we need add it to **programmingLanguage**
=> fix: jans-config-api add JAVA to programmingLanguage (ref: #1656)

jans-config-api/common/src/main/java/io/jans/configapi/util/AttributeNames.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/StatResource.java, jans-config-api/shared/src/main/java/io/jans/configapi/core/rest/BaseResource.java
https://github.com/JanssenProject/jans/issues/1665
=> fix: fix typos and other issues in jans-config-api swagger specs #1665

jans-linux-setup/jans_setup/setup_app/installers/scim.py
As described in https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest
a dummy **jansRedirectURI** is added to scime client.
=> fix: jans-linux-setup add dummy jansRedirectURI to scim client

jans-linux-setup/jans_setup/scan/static/extension/update_token/UpdateToken.py, jans-linux-setup/jans_setup/scan/static/extension/update_token/updatetoken.json
=> feat(jans-auth-server): #1731

jans-client-api/README.md, jans-client-api/gen-client/pom.xml, jans-client-api/pom.xml, jans-client-api/server/pom.xml, jans-client-api/server/src/main/java/io/jans/ca/server/persistence/service/MainPersistenceService.java
- jans-config-api dependency removed
- Additionally I have solved a problem to find test dependency (jans-client-api-common) when it is built with maven.test.skip = true    (https://jenkins.jans.io/jenkins/job/jans-client-api/86/)
https://github.com/JanssenProject/jans/issues/1723
Dependency removed, and test dependencies problems fixed.
- [ X] Static code analysis has been run locally and issues have been fixed
README was updated (command to run test with url).
=> fix(jans-client-api): jans-config-api dependency removed and wrong test dependencies solved

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
jans-eleven is not working properly, thus propmting to install jans-eleven is hided. Developers can still install jans-eleven with argument `--install-eleven`, for example:
`python3 install.py --args="--install-eleven"`
or installer
`python3 /opt/jans/jans-setup/setup.py --install-eleven`
=> fix: jans-linux-setup no prompt for eleven installation

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/KeyGeneratorTimer.java
feat(jans-auth-server): jwt "exp" must consider "keyRegenerationInterval" #1233
#1233
jwt "exp" must consider "keyRegenerationInterval"
=> feat(jans-auth-server): jwt "exp" must consider "keyRegenerationInterval" #1233

jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/data/package_list.json, jans-linux-setup/jans_setup/setup_app/installers/base.py, jans-linux-setup/jans_setup/setup_app/installers/jetty.py, jans-linux-setup/jans_setup/setup_app/installers/opendj.py, jans-linux-setup/jans_setup/setup_app/utils/base.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py
* debian 11 package dependecies
* remove `fix_init_scripts()` - we have no init.rc system anymore
=> feat: jans-linux-setup debian 11 packages

jans-core/cache/src/main/java/io/jans/service/cache/NativePersistenceCacheProvider.java, jans-core/cache/src/main/java/io/jans/service/cache/NativePersistenceConfiguration.java
Added config to disable attempt to update before insert in cache.
https://github.com/JanssenProject/jans/issues/207
=> FEAT / Added config to disable attempt to update before insert in cache

agama/pom.xml
As per the description in the target issue, it seems from the error log that PR check for Sonar doesn't know where the Sonar server is as it is trying to look for server on localhost.
Closes #1810 
- pom file in Agama is missing Sonar properties. So added appropriate properties.
- At the same time, Jans project on Sonar didn't have Agama module onboarded. So I have configured that as well.
=> ci: fix failing Sonar check for Agama

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/util/ServerUtil.java, jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidatorTest.java
Split grant validation logic into TokenRestWebServiceValidator.
#1591
- [-] Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)
=> feat(jans-auth-server): split grant validation logic into TokenRestWebServiceValidator  #1591

jans-linux-setup/jans_setup/install.py
Remove apache configuration when uninstall as described in https://github.com/JanssenProject/jans/issues/1809
Closes #1845,
=> fix: jans-linux-setup remove apache config when uninstall

jans-config-api/docs/jans-config-api-swagger.yaml
Attribute indentation issue causing the parser to fail
[1848](https://github.com/JanssenProject/jans/issues/1848)
Fixed indentation of the element.
NA
Closes: #1850,
=> docs(jans-config-api): fixed swagger format issue

docs/admin/scim.md, jans-linux-setup/jans_setup/templates/jans-scim/dynamic-conf.json, jans-scim/model/src/main/java/io/jans/scim/model/scim2/provider/config/BulkConfig.java, jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/BulkWebService.java, jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/ServiceProviderConfigWS.java, jans-scim/service/src/main/java/io/jans/scim/model/conf/AppConfiguration.java
=> feat(jans-scim): make max no. of operations and payload size of bulks operations parameterizable

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java
client tests expects "scope to claim" mapping which are disabled by default
Closes #1873
=> fix(jans-auth-server): client tests expects "scope to claim" mapping which are disabled by default #1873

.github/pull_request_template.md
As per chat messages [here](https://chat.gluu.org/group/project_jans?msg=syHzy3SXJWdiRnZ6T), We have updated the PR template so that issue gets properly attached to PR.
closes #1877 
- added `closes` keyword under `Target issue` section
- added comments in `Target issue` section as a guideline around using GH task lists to create target issue
=> ci: add closes keyword to PR template

docker-jans-auth-server/.hadolint.yaml, docker-jans-auth-server/Dockerfile, docker-jans-auth-server/Makefile, docker-jans-certmanager/.hadolint.yaml, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/Makefile, docker-jans-client-api/.hadolint.yaml, docker-jans-client-api/Dockerfile, docker-jans-client-api/Makefile, docker-jans-config-api/.hadolint.yaml, docker-jans-config-api/Dockerfile, docker-jans-config-api/Makefile, docker-jans-configurator/.hadolint.yaml, docker-jans-configurator/Dockerfile, docker-jans-configurator/Makefile, docker-jans-fido2/.hadolint.yaml, docker-jans-fido2/Dockerfile, docker-jans-fido2/Makefile, docker-jans-persistence-loader/.hadolint.yaml, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/Makefile, docker-jans-scim/.hadolint.yaml, docker-jans-scim/Dockerfile, docker-jans-scim/Makefile
Overview:
- upgrade to Alpine 3.16.1 via alpine:3.16 and bellsoft/liberica-openjre-alpine:11.0.16 base images
- upgrade to Jetty 11.0.11
- add `hadolint` linter configuration file
- add local `grype` scanner task in `Makefile`
closes #1892 
=> chore: apply security updates

docs/CONTRIBUTING.md
Documentation style guide is required to bring consistency to the documentation
closes #1905 
Initial version of style guide has been added and is follows [Gluu style guide](https://github.com/GluuFederation/docs-management-prod#style-guide). This will continue to evolve and be customized for Janssen documentation.
=> docs: add documentation style guide

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ConfigurationRestWebServiceHttpTest.java
…m" mapping which is disabled by default #1873
docs: no docs required
Fixed client tests effected by "scope to claim" mapping which is disabled by default.
closes #1873
=> fix(jans-auth-server): fixing client tests effected by "scope to claim" mapping which is disabled by default #1873

.github/workflows/pr-ref-issue.yml
The problem is as described in the target issue.
Root cause is that on click of `Create PR` button, the workflow ran before GH APIs could process the PR description and identify and attach an issue if mentioned in the description by the author.
closes #1908 
Added a new step that makes the workflow wait for 5 seconds. 
=> ci: add sleep to the workflow

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidator.java
Removed builder variable - we should strive to more isolated/decoupled code.
Closes #1591
=> refactor(jans-auth-server): removed builder variable from Token Endpoint #1591

jans-config-api/common/src/main/java/io/jans/configapi/rest/model/CustomScope.java, jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ScopesResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ScopeService.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/UmaResourceService.java
https://github.com/JanssenProject/jans/issues/1923
Closes #1947,
=> Jans config api issue 1923

jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ScopeService.java
docs: no docs
closes #2030
- [  Relevant documentation has been updated if any (i.e. user guides, installation and configuration guides, technical design docs etc)
=> fix(jans-config-api): config-api compilation failed in main #2030

docker-jans-configurator/scripts/bootstrap.py, docker-jans-configurator/scripts/parameter.py, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/bootstrap.py, docker-jans-persistence-loader/scripts/utils.py
The changeset add feature to allow creating entry directly from docker-jans-fido2.
This means redundant code in docker-jans-persistence-loader and docker-jans-configurator are removed.
closes #2026
=> feat(docker-jans-fido2): allow creating initial persistence entry

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaFlowService.java
=> fix(jans-config-api): avoid loss of attributes in agama endpoints

jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwk/Algorithm.java, jans-auth-server/model/src/test/java/io/jans/as/model/jwk/AlgorithmTest.java, jans-auth-server/model/src/test/resources/testng.xml
fix(jans-auth-server): generate description during built-in key rotation #1790
closes #1790
=> fix(jans-auth-server): generate description during built-in key rotation #1790

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
From a support ticket, we found that we need to include dynamic scopes as part of idToken generation for CIBA grant type.
Closes #2109,
=> Fix / Include idtoken with dynamic scopes for ciba

jans-auth-server/server/conf/jans-couchbase.properties, jans-linux-setup/jans_setup/templates/jans-couchbase.properties
Remove/update CB default configuration
Closes #2119,
=> feat: update Coucbase ORM to conform SDK 3.x (config updates) #1851

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SpontaneousScopeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaScopeService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/SpontaneousScopeServiceTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-config-api/docs/jans-config-api-swagger.yaml, jans-linux-setup/jans_setup/setup_app/test_data_loader.py
Added allowSpontaneousScopes AS JSON config
closes #2074 
=> feat(jans-auth-server): added allowSpontaneousScopes AS JSON config #2074

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/conf/jans-couchbase.properties.tmpl, docker-jans-client-api/Dockerfile, docker-jans-client-api/conf/jans-couchbase.properties.tmpl, docker-jans-config-api/Dockerfile, docker-jans-config-api/conf/jans-couchbase.properties.tmpl, docker-jans-fido2/Dockerfile, docker-jans-fido2/conf/jans-couchbase.properties.tmpl, docker-jans-scim/Dockerfile, docker-jans-scim/conf/jans-couchbase.properties.tmpl, jans-pycloudlib/Makefile, jans-pycloudlib/README.md, jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py, jans-pycloudlib/mkdocs.yml, jans-pycloudlib/tests/test_persistence.py
=> fix(images): conform to new couchbase persistence configuration

docs/admin/recipes/passwordless.md
Since HTML tags used for center alignment are not supported in MKDocs, the integration component diagram was not showing up in the document. 
So, removed the alignment for now so that image is visible in the doc
closes #2229
=> docs: remove non-fuctional middle alignment

agama/inboundID/CustomMappings.java.txt, agama/inboundID/pom.xml, agama/inboundID/src/main/java/io/jans/inbound/IdentityProcessor.java, agama/inboundID/src/main/java/io/jans/inbound/Mappings.java, agama/inboundID/src/main/java/io/jans/inbound/Provider.java, agama/inboundID/src/main/java/io/jans/util/NetworkUtils.java, docs/admin/developer/agama/java-classpath.md, docs/script-catalog/agama/inboundID/README.md, docs/script-catalog/agama/inboundID/io.jans.inbound.ExternalSiteLogin
=> feat(agama): add utility classes for inbound identity

jans-linux-setup/jans_setup/templates/jans-auth/people.ldif
closes https://github.com/JanssenProject/jans/issues/1830
=> fix: jans-linux-setup lowercase admin user status

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
closes https://github.com/JanssenProject/jans/issues/2275
=> fix: jans-linux-setup config api prompt

jans-cli/cli/config_cli.py
=> fix: jans-cli displayName for OpenID Clients with MySQL backend

jans-linux-setup/jans_setup/setup_app/installers/config_api.py
=> fix: jans-linux-setup config-api scope type oauth

jans-cli/cli/config_cli.py
closes https://github.com/JanssenProject/jans/issues/2303
=> fix: jans-cli user patch

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidatorTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/docs/jans-config-api-swagger.yaml
Setting max_age parameter with 0 value in a authorization request doesn't allow user to log in at all. After postlogin call user is redirected back to login page.
In addition we can introduce `disableAuthnForMaxAgeZero` with default value `false`. If `true` - authn will be disabled.
```
max_age
OPTIONAL. Maximum Authentication Age. Specifies the allowable elapsed time in seconds since the last time the End-User was actively authenticated by the OP. If the elapsed time is greater than this value, the OP MUST attempt to actively re-authenticate the End-User. (The max_age request parameter corresponds to the OpenID 2.0 PAPE [OpenID.PAPE] max_auth_age request parameter.) When max_age is used, the ID Token returned MUST include an auth_time Claim Value.
```
closes #2361 …
=> feat(jans-auth-server): allow authentication for max_age=0 #2361

jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/logging/AuditLoggerResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/user/UserManagementResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/user/UserManagementService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml
=> feat: admin-ui apis refactoring #2388

jans-cli/cli/config_cli.py
closes #2381
closes #2374
closes #2302
=> fix: Jans cli SCIM fixes

docs/admin/config-guide/scim-cli.md, jans-scim/server/src/main/java/io/jans/scim/service/scim2/Scim2UserService.java
=> fix(jans-scim): X509 cert not set after successful POST request

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/static.py, jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py, jans-linux-setup/jans_setup/static/rdbm/ldap_sql_data_type_mapping.json, jans-linux-setup/jans_setup/static/rdbm/pgsql_index.json, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json, jans-linux-setup/jans_setup/templates/jans-mysql.properties, jans-linux-setup/jans_setup/templates/jans-pgsql.properties, jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java, jans-orm/couchbase/src/main/java/io/jans/orm/couchbase/operation/impl/CouchbaseOperationServiceImpl.java, jans-orm/spanner/src/main/java/io/jans/orm/cloud/spanner/impl/SpannerFilterConverter.java, jans-orm/sql/src/main/java/io/jans/orm/sql/dsl/template/MySQLJsonTemplates.java, jans-orm/sql/src/main/java/io/jans/orm/sql/dsl/template/PostgreSQLJsonTemplates.java, jans-orm/sql/src/main/java/io/jans/orm/sql/dsl/types/PostgreSQLJsonType.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlOps.java, jans-orm/sql/src/main/java/io/jans/orm/sql/model/JsonString.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/SqlOperationService.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/SupportedDbType.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlConnectionProvider.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java, jans-orm/sql/src/test/java/io/jans/orm/sql/impl/test/SqlFilterConverterCheckExcludeFilterTest.java, jans-orm/sql/src/test/java/io/jans/orm/sql/impl/test/SqlFilterConverterTest.java
=> feat: jans-linux-setup postgresql support

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> feat: jans-linux-setup option reset-rdbm-db

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImplTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/test/resources/feature/config/properties/openid/config/config.json
Allow end session with expired id_token_hint(by checking signature and sid) #2430
closes #2430
=> feat(jans-auth-server): allow end session with expired id_token_hint(by checking signature and sid) #2430

jans-linux-setup/jans_setup/setup_app/installers/jetty.py
=> feat: jans-linux-setup set_class_path()

jans-cli/cli/config_cli.py
closes #1350
closes #1773
closes #1349
closes #1655
closes #1657
closes #1753
closes #1878
closes #1911
=> fix: jans-cli fixes

jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/crypto64.py, jans-linux-setup/jans_setup/templates/scripts.ldif
Reflection of https://github.com/JanssenProject/jans/issues/2487
=> fix: jans-linux-setup scan docs/script-catalog for custom scripts

jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
fix(jans-auth-server): npe in discovery if SSA endpoint is absent #2497
closes #2497
=> fix(jans-auth-server): npe in discovery if SSA endpoint is absent #2497

jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/ClientService.java
chore(jans): client should use CustomObjectAttribute instead of CustomAttribute #2483
closes #2483
=> chore(jans): client should use CustomObjectAttribute instead of CustomAttribute #2483

jans-linux-setup/docs/README.md, jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/data/package_list.json, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jetty.py, jans-linux-setup/jans_setup/setup_app/installers/jre.py, jans-linux-setup/jans_setup/setup_app/installers/jython.py, jans-linux-setup/jans_setup/setup_app/static.py, jans-linux-setup/jans_setup/setup_app/utils/package_utils.py
=> fix: jans-linux-setup typo

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/utils.py
=> fix: scan docs/script-catalog for custom scripts

jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java
"login:prompt" property passed in request object JWT breaks authentication #2493
closes #2493
=> fix(jans-auth-server): "login:prompt" property passed in request object JWT breaks authentication #2493

jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ScopesResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ScopeService.java
closes #2517 
fixed code to fetch associated clients for scope
=> fix(config-api): fix for associated client not fetched for scope

jans-linux-setup/jans_setup/install.py, jans-linux-setup/jans_setup/jans_setup.py
=> fix: jans-linux-setup install dependencies without interaction if --download-exit

jans-config-api/common/src/main/java/io/jans/configapi/rest/model/CustomScope.java, jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ScopeService.java
=> fix(config-api): fix for returning associated-clients for scope

jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/SsaAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-linux-setup/jans_setup/schema/jans_schema_mappings.json, jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/base.ldif, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-errors.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-static-conf.json, jans-linux-setup/jans_setup/templates/test/jans-auth/data/oxauth-test-data.ldif
Was able to get SSA tests working doing manual execution of "DeployServer" job first and then build using LDAP.
- https://jenkins.jans.io/jenkins/job/jans-auth-server/7648/
- https://jenkins.jans.io/jenkins/job/DeployServer/5059/
**I'm reviewing embedded tests failures**
https://github.com/JanssenProject/jans/issues/2576
Added required config to get SSA structure working in new deployments.
=> Initial SSA structure for new deployments

jans-core/document-store/pom.xml, jans-core/document-store/src/main/java/io/jans/service/document/store/conf/DBDocumentStoreConfiguration.java, jans-core/document-store/src/main/java/io/jans/service/document/store/conf/DocumentStoreConfiguration.java, jans-core/document-store/src/main/java/io/jans/service/document/store/conf/DocumentStoreType.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DBDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DocumentStore.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/JcaDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/LocalDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/WebDavDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/BaseDocumentStoreService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/DBDocumentService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/Document.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/OxDocument.java, jans-core/document-store/src/test/java/io/jans/service/document/store/manual/JcaDocumentStoreManualTest.java, jans-linux-setup/jans_setup/schema/jans_schema.json
feat(jans-core): port Gluu ORM-based document store
=> feat(jans-core): port Gluu ORM-based document store

jans-linux-setup/jans_setup/templates/jans-mysql.properties
=> fix: jans-linux-setup MySQL schema name is db name

docker-jans-fido2/Dockerfile
closes #2602 
The static file `metadata-root-ca.cer` which is synchronized from jans-linux-setup directory is no longer copied into the image.
=> fix(image): remove metadata-root-ca.cer inside fido2 image

docker-jans-persistence-loader/Dockerfile
closes #2617 
Copy the corresponding extension script from upstream jans-linux-setup template.
=> fix(image): add missing script for openbanking installation

jans-linux-setup/jans_setup/install.py
=> fix: jans-linux-setup don't call package installation unless missing packages

docs/admin/planning/vm-cluster.md, docs/admin/planning/vm-single-instance.md
Added initial docs for single and clusted VM deployment.
[docs: Update Architecture Guide](https://github.com/JanssenProject/jans/issues/2628)
Wrote initial docs.
=> VM Architecture Docs

docker-jans-auth-server/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-scim/requirements.txt, jans-pycloudlib/jans/pycloudlib/persistence/sql.py
=> fix(pycloudlib): set default values for JSONB column

docs/admin/scim/README.md
Co-authored-by: jgomer2001 <bonustrack310@gmail.com>
Co-authored-by: shmorri <sam@gluu.org>
Co-authored-by: moabu <47318409+moabu@users.noreply.github.com>
Co-authored-by: imshakil <mh.ice.iu@gmail.com>
add SCIM overview to README
closes #2692 
Some of the content of this document is migrated from Gluu docs.
=> docs: add SCIM overview to README

jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java
Requesting `/.well-known/openid-configuration` for the first time returns unexpected output for `grant_types_supported` and `response_mode_supported`, it returns uppercase values.
https://github.com/JanssenProject/jans/issues/2183
closes #2183
Loading of `grant_types_supported` and `response_mode_supported`
was modified to `List<String>` in endpoint `/.well-known/openid-configuration`
because `JSONArray` loading was causing the issue.
=> fix(jans auth server): well known uppercase grant_types response_mode

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenExchangeService.java, jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenExchangeServiceTest.java
fix(jans-auth-server): npe - regression in token endpoint
Native SSO
https://github.com/JanssenProject/jans/issues/2518
https://github.com/JanssenProject/jans/issues/2762
closes #2762
=> fix(jans-auth-server): npe - regression in token endpoint

jans-scim/server/pom.xml
=> chore(jans-scim): log4j-plugin-fluency reports vulnerability

jans-auth-server/client/src/main/java/io/jans/as/client/TokenResponse.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/Asserter.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/JwtAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/TokenResponseAssertBuilder.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenExchangeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenExchangeServiceTest.java
Native sso - return device secret if device_sso scope is present #2790
closes #2790
Parent ticket
https://github.com/JanssenProject/jans/issues/2518
=> fix(jans-auth-server): native sso - return device secret if device_sso scope is present #2790

docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
=> fix(image): missing configuration for openbanking discovery

docs/admin/fido/config.md
=> docs: #2840

agama/engine/src/main/java/io/jans/agama/engine/service/AppInitializer.java, agama/engine/src/main/java/io/jans/agama/engine/service/ServicesFactory.java
=> fix(agama): avoid NPE when configuration is missing 

jans-auth-server/client/src/main/java/io/jans/as/client/ssa/revoke/SsaRevokeClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/revoke/SsaRevokeRequest.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/revoke/SsaRevokeResponse.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/validate/SsaValidateClient.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaCreateTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaGetTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaRevokeTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaValidateTest.java, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ModifySsaResponseService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaRevokeAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImplTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaRevokeActionTest.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/ssa/DummyModifySsaResponseType.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/ssa/ModifySsaResponseType.java, jans-linux-setup/jans_setup/static/extension/ssa_modify_response/ssa_modify_response.py
Implemented API method to revoke an existing SSA
https://github.com/JanssenProject/jans/issues/2240
closes #2240
https://gluu-arpine.stoplight.io/docs/ssa-1/5d9cdfc605988-revoke-ssa
=> feat: add SSA Revoke Endpoint

docs/admin/install/helm-install/amazon-eks.md, docs/admin/install/helm-install/google-gke.md, docs/admin/install/helm-install/microsoft-azure.md
=> docs: Helm install on GKE, AKS, and EKS

jans-auth-server/client/src/main/java/io/jans/as/client/ClientAuthnEnabler.java, jans-auth-server/client/src/main/java/io/jans/as/client/TokenRequest.java
Fixes test failures on jenkins
fix(jans-auth-server): corrected regression made in token request #2921
closes #2921
=> fix(jans-auth-server): corrected regression made in token request #2921

jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java, jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/security/api/ApiProtectionService.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/SessionService.java
…endpoint filter
closes #2937 #2946 
=> fix(config-api):  added check for scope creation and swagger spec for client

jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java, jans-auth-server/model/src/test/java/io/jans/as/model/util/UtilTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java
fix(jans-auth-server): wrong userinfo_encryption_enc_values_supported in OpenID Configuration #2725
closes #2725
=> fix(jans-auth-server): wrong userinfo_encryption_enc_values_supported in OpenID Configuration #2725

jans-auth-server/docs/swagger.yaml
Swagger doc for SSA API methods
https://github.com/JanssenProject/jans/issues/2952
closes #2952
Add required changes to YAML file about Swagger new endpoints.
**I had to add the schema to handle authorization properly.**
=> feat(jans-auth-server): swagger docs for ssa

jans-core/service/src/main/java/io/jans/service/logger/LoggerService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/mds/AttestationCertificateService.java, jans-fido2/server/src/main/resources/log4j2.xml
=> fix(jans-fido2): #2971

jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix: jans-linux-setup fido2 script placeholder in scripts template

jans-linux-setup/jans_setup/static/system/systemd/jans-auth.service
=> fix: jans-linux-setup service description for jans-auth

jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaContextBuilder.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaRevokeAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaValidateAction.java
Java docs for all new methods and classes implemented.
https://github.com/JanssenProject/jans/issues/2954
closes #2954
Just added comments over existing methods.
=> feat(jans-auth-server): java docs for ssa

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/user/UserManagementResource.java
=> fix: the admin-ui role/permission/mapping delete apis are not protected by appropriate permissions #2991

docs/admin/reference/database/mysql-schema-ERdiagram.md, docs/admin/reference/database/mysql-schema-indexes.md, docs/admin/reference/database/mysql-schema.md
=> fix: #2666

docs/admin/planning/delegated-user-admin.md, docs/admin/planning/machine-to-machine.md, docs/admin/planning/passwordless-auth.md, docs/admin/planning/stepped-up-auth.md
Initial content
Initial checkin
=> Initial check for delegated admin, m2m, passwordless and stepped-up

docker-jans-persistence-loader/README.md, docker-jans-persistence-loader/scripts/upgrade.py
closes #2990 
The changeset added `CN_PERSISTENCE_UPDATE_AUTH_DYNAMIC_CONFIG` env var (default to `true`) as feature flag to enable/disable automatic updates on jans-auth configuration.
=> feat(image): preserve attribute's values in jans-auth config

agama/engine/profiles/default/config-agama-test.properties, docs/admin/developer/agama/quick-start.md, jans-auth-server/server/conf/jans-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/scripts.ldif
=> chore(agama): create custom parameter for agama flows

jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix: disable github authentication and interception scripts by default and other changes. #3022

jans-config-api/common/pom.xml, jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml, jans-config-api/plugins/sample/helloworld/pom.xml, jans-config-api/pom.xml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaResource.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/OrganizationResource.java
=> fix(config-api): error handling for agama get and org patch

docs/admin/auth-server/endpoints/ssa.md, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/get/SsaGetClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/get/SsaGetRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaGetTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaRevokeTest.java, jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaScopeType.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImplTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaGetActionTest.java
Documentation for the public site and remove software roles because it was not included as part of this scope for SSA.
https://github.com/JanssenProject/jans/issues/2996
closes #2996 
Documentation for the public site and remove software roles because it was not included as part of this scope for SSA.
=> Documentation for SSA

docs/script-catalog/person_authentication/github-external-authenticator/GithubExternalAuthenticator.py
In init() method there was duplicate print function like `print "GitHub: Initialized successfully"`. Which should be before return statement.
=> Duplicate print function remove from init() method

jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java, jans-auth-server/common/src/test/java/io/jans/as/common/model/registration/ClientSerializationTest.java, jans-orm/model/src/main/java/io/jans/orm/model/base/LocalizedString.java
fix:(jans-auth-server): fixed Client serialization/deserialization issue #2946
```
Error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`) at [Source: (org.eclipse.jetty.server.HttpInput); line: 25, column: 23] (through reference chain: io.jans.as.common.model.registration.Client[&quot;logoUriLocalized&quot;])
```
More details in this comment https://github.com/JanssenProject/jans/issues/2946#issuecomment-1320073974
closes #2946
=> fix:(jans-auth-server): fixed Client serialization/deserialization issue #2946

jans-config-api/docs/jans-config-api-swagger-auto.yaml, jans-orm/model/src/main/java/io/jans/orm/model/base/CustomObjectAttribute.java, jans-orm/model/src/main/java/io/jans/orm/model/base/LocalizedString.java
Added null check to resolve two NullPointerException
1. CustomObjectAttribute NPE while executing User management endpoint -  jenkins build
Error: `Caused by: java.lang.NullPointerException
at io.jans.orm.model.base.CustomObjectAttribute.getDisplayValue(CustomObjectAttribute.java:92)`
2. LocalizedString while testing OpenID Client functionality
Error: `Caused by: 
java.lang.NullPointerException
at io.jans.orm.model.base.LocalizedString.getLanguageTags(LocalizedString.java:77)`
closes #3074 
=> fix(jans): added null check to avoid NullPointerException

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/RegistrationRestWebServiceHttpTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/registration/RegisterParamsValidator.java
Relax requirement for redirect_uri for back-channel OAuth flows
https://github.com/JanssenProject/jans/issues/3017
closes #3017
Updated conditions to process client registration.
=> Relax requirement for redirect_uri for back-channel OAuth flows

jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java
=> fix:(jans-auth-server): fixed client's sortby #3075

docs/admin/install/vm-install/rhel.md, docs/admin/install/vm-install/suse.md, docs/admin/install/vm-install/ubuntu.md
Enhance VM install docs by adding details below:
=> docs: improve vm install instructions

docs/admin/install/vm-install/rhel.md, docs/admin/install/vm-install/suse.md, docs/admin/install/vm-install/ubuntu.md
Fix formatting issues in install docs.
=> docs: formatting and proofreading of install docs

docs/developer/implementation-design/README.md
remove redundant API details sections from dev documentation
=> doc: remove redundant API details sections

docs/admin/auth-server/client-management/configuration/client-config.md, jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/common/src/test/resources/testng.xml, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterCreateAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthzRequestServiceTest.java
feat(jans-auth-server): specify minimum acr for clients #343
closes #343
=> feat(jans-auth-server): specify minimum acr for clients #343

jans-cli-tui/docs/build.md, jans-cli-tui/docs/remote_install.md
Update links in docs. Closes #3117
=> fix: jans-cli-docs update links

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/plugins/010_oxauth/edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py
This PR fixes the following issues:
1. Issue when user logout and exits
2. closes #3119
3. saving user
=> fix: client-name, logout, user

docs/admin/auth-server/endpoints/client-registration.md, jans-auth-server/model/src/main/java/io/jans/as/model/common/SoftwareStatementValidationType.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaValidationConfig.java, jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaValidationType.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/SsaValidationConfigContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/SsaValidationConfigService.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/SsaValidationConfigServiceTest.java, jans-auth-server/server/src/test/resources/testng.xml
…dynamic  registration #2980
feat(jans-auth-server): draft for - improve dcr / ssa validation for dynamic  registration
closes #2980
=> feat(jans-auth-server): draft for - improve dcr / ssa validation for dynamic  registration #2980

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidatorTest.java, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
feat: block authentication flow originating from a web view (mobile app).
closes #3016
Added a new `validateNotWeview` method and also a new configuration parameter `blockWebviewAuthorizationEnabled` (default is false).
The method validation is based on request header, if there is `X-Requested-With` header then it is a request originated from a web view.
Closes #3205,
=> Feature: Block authentication flow originating from a web view (mobile app)

docs/admin/auth-server/README.md, docs/admin/auth-server/crypto/supported-algorithms.md, docs/admin/vm-ops/README.md
Initial checkin, plus some format fixes for other READMEs.
Checkin of README Overview page that lists the specs the server implements
=> First draft README for Auth Sever

jans-core/util/pom.xml, jans-core/util/src/main/java/io/jans/util/security/AESUtil.java, jans-core/util/src/test/java/io/jans/util/security/AESUtilTest.java
feat(jans-core): added AES utility class #3215
closes #3215
=> feat(jans-core): added AES utility class #3215

docs/admin/config-guide/tui.md
=> fix(docs): jans TUI configuration -- Fido Administration - TUI

jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/ApiApplication.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ADSDeploymentsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ADSDeploymentsService.java
=> feat: add endpoints for MVP ADS projects management 

jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> fix: jans-linux-setup longtext for pgsql

jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java
feat(jans-auth-server): end session - if id_token is expired but signature is correct, we should make attempt to look up session by "sid" claim 
closes #3231
=> feat(jans-auth-server): end session - if id_token is expired but signature is correct, we should make attempt to look up session by "sid" claim #3231

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/AdminConf.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/MainSettings.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/OIDCClientSettings.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/OIDCSettings.java, jans-config-api/plugins/admin-ui-plugin/pom.xml, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/AUIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/user/UserManagementService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/AppConstants.java
ToDos:
- **appType**: `admin-ui`, `agama-developer-studio`.
1. `API`: `/app/{appType}/oauth2/config` -- To get ADS client configuration.
2. `API`: `/app/{appType}/oauth2/access-token` -- To generate access_token to get user-info
3. `API`: `/app/{appType}/oauth2/user-info` -- To get user-info
4. `API`: `/app/{appType}/oauth2/api-protection-token` -- To generate api-protection-token containing required scopes to access confg-api endpoints.
closes #3085
=> feat: changes in admin-ui plugin to allow agama-developer-studio to use its OAuth2 apis #3085

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
closes #2733
In regard to comment https://github.com/JanssenProject/jans/issues/2733#issuecomment-1346779637
=> fix: jans-linux-setup agama test data file locations

docs/script-catalog/person_authentication/fido2-external-authenticator/README.md
=> docs: testing note added

docs/admin/developer/customization/customize-web-pages.md
=> fix: minor

.github/workflows/build-docs.yml, docs/CONTRIBUTING.md
closes #3327 
Added a release marker as documented in CONTRIBUTION.md
CI flow will replace the marker with the appropriate release number.
=> ci: introduce release number marker for documentation

docs/admin/install/vm-install/ubuntu.md
When we install deb package from home, we got warning
```
Download is performed unsandboxed as root as file '/root/jans_1.0.5.ubuntu20.04_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```
So it is better to download debian package to `/tmp`
=> Download ubuntu package to /tmp not home directory

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
For agama test data loading
Copy contents of https://github.com/JanssenProject/jans/tree/main/jans-auth-server/agama/engine/src/test/resources/libs to `/opt/jans/jetty/jans-auth/agama/scripts`
as  described at https://github.com/JanssenProject/jans/issues/2733#issuecomment-1361232095
=> fix: jans-linux-setup copy libs directory of agama test data

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenExchangeService.java
when obtain new token using refresh token, check whether scope is null
closes #3381
=> Fix: when obtain new token using refresh token

jans-auth-server/model/src/main/java/io/jans/as/model/jwt/JwtClaimSet.java, jans-auth-server/model/src/test/java/io/jans/as/model/jwt/JwtClaimsTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
fix(jans-auth-server): Duplicate iss and aud on introspection as jwt
closes #3366
=> fix(jans-auth-server): Duplicate iss and aud on introspection as jwt #3366

docs/admin/config-guide/tui.md
Updated TUI page of configuration guide to add more details about how to run, how user is authenticated, and where 
the configuration is stored. 
Wrote docs! 
=> TUI Docs update

docs/admin/config-api/README.md
Janssen config API README on documentation site was pointing to swagger documentation of `head`. 
Changed this link to point to API reference section of the documentation. 
API reference section will have dynamic links which will be updated as new versions of Janssen Project is released.
=> fix: add link to api reference

README.md
Janssen Project README had the wrong version of Ubuntu mentioned. Correcting the same 22.04 -> 20.04
=> fix: use correct Ubuntu version in README

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/utils/package_utils.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py
=> fix: jans-linux-setup centos/rhel pgsql installation

jans-auth-server/agama/engine/pom.xml, jans-auth-server/agama/model/pom.xml, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/SsaValidationConfigService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/net/UriService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/net/UriServiceTest.java, jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): added externalUriWhiteList configuration property before call external uri from AS #3130
closes #3130
=> feat(jans-auth-server): added externalUriWhiteList configuration property before call external uri from AS #3130

jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/test/jans-auth/server/config-oxauth-test-data.properties
=> fix: jans-linux-setup load test data with jans-auth only

docs/admin/config-guide/curl.md
- added instructions to create minimal client using CURL
- replaced sections on getting scopes and grant types with more inclusive section of getting client information
- fixed typo in command for getting access token
- added expected responses
=> docs: add details to curl command guide

docs/admin/developer/interception-scripts.md, docs/admin/developer/managed-beans.md, docs/admin/developer/scripts/person-authentication-faq.md, docs/admin/developer/scripts/person-authentication-interface.md, docs/admin/developer/scripts/person-authentication.md, docs/admin/recipes/social-login.md
=> fix: #2201

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
=> fix: jans-linux-setup enable mysqld on boot for el8

jans-auth-server/server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java
feat(jans-auth-server): renamed "code"->"random" uniqueness claims of id_token to avoid confusion with Authorization Code Flow 
closes #3466
=> feat(jans-auth-server): renamed "code"->"random" uniqueness claims of id_token to avoid confusion with Authorization Code Flow #3466

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-scim/Dockerfile, jans-pycloudlib/jans/pycloudlib/persistence/sql.py
=> fix: modify clnId column type

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
=> fix: jans-cli-tui refactor mouse operations

mkdocs.yml
Corrected mismatched nav address for config-api docs.
#3486 
closes #3486 
=> docs: fixed navigation to config API docs

.github/workflows/build-docs.yml, automation/docs/generate-javadocs.sh
In order to version javadocs generated by each module, it was decided to host them in GH repo. This PR will generate javadocs for all the modules and move them to respective locations under `jans/docs/admin/reference/javadoc/<module>`.
A subsequent CR will process them further and publish them on MKDocs site as discussed with Mo.
=> docs: host javadocs on GH

docs/admin/auth-server/endpoints/clientinfo.md
Add documentation for clientinfo endpoint
closes #3518
=> docs: add documentation for clientinfo endpoint

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImplTest.java
feat(jans-auth-server): implemented auth server config property to disable prompt=login #3006
closes #3006
=> feat(jans-auth-server): implemented auth server config property to disable prompt=login #3006

docker-jans-config-api/Dockerfile, docker-jans-persistence-loader/Dockerfile
=> feat(docker-jans): add admin-ui scopes

jans-auth-server/model/src/main/java/io/jans/as/model/jwk/Algorithm.java
fix(jans-auth-server): corrected keys description "id_token <purpose>" -> "Connect <purpose>" #3415
closes #3415
=> fix(jans-auth-server): corrected keys description "id_token <purpose>" -> "Connect <purpose>" #3415

jans-auth-server/model/src/main/java/io/jans/as/model/common/FeatureFlagType.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/error/ErrorResponseFactory.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatService.java
chore(jans-auth-server): move enabledFeatureFlags out of AppConfiguration to avoid patch issues on jans-config-api side 
closes #3577
=> chore(jans-auth-server): move enabledFeatureFlags out of AppConfiguration to avoid patch issues on jans-config-api side #3577

mkdocs.yml
#3572
page admin/auth-server/oauth-features/auth-code-grant.md has been added.
=> docs: fix missing link to auth code flow grant

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/RegisterServiceTest.java
feat(jans-auth-server): added dynamicRegistrationDefaultCustomAttributes to provide default custom attributes during dcr #3595
closes #3595
=> feat(jans-auth-server): added dynamicRegistrationDefaultCustomAttributes to provide default custom attributes during dcr #3595

jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java
fix(jans-auth-server): wrong Client Authn Method at token endpoint throws npe 
closes #3503
=> fix(jans-auth-server): wrong Client Authn Method at token endpoint throws npe #3503

docs/script-catalog/person_authentication/github-external-authenticator/GithubAuthenticatorForADS.py, jans-auth-server/server/src/main/webapp/auth/github/detailsForm.xhtml, jans-auth-server/server/src/main/webapp/auth/github/login.xhtml, jans-linux-setup/jans_setup/templates/scripts.ldif
=> feat: add custom Github External Authenticator script for ADS #3625

jans-linux-setup/jans_setup/setup_app/installers/fido.py
=> fix: jans-linux-setup external libs in jans-fido2.xml

jans-cli-tui/docs/remote_install.md, jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py, jans-linux-setup/jans_setup/templates/jans-cli/client.ldif
=> fix: jans-linux-setup rename role_based_client as tui_client

jans-linux-setup/jans_setup/app_info.json
=> fix: jans-linux-setup downgrade cryptography

docker-jans-configurator/README.md, docker-jans-configurator/scripts/bootstrap.py, docker-jans-configurator/scripts/parameter.py
=> feat(docker-jans-configurator): allow user-defined salt

docs/admin/auth-server/tokens/oauth-access-tokens.md, docs/admin/auth-server/tokens/openid-id-token.md
Initial checkin
Initial checkin of the access token page. 
=> docs: Admin Guide / Tokens / Access Token Page

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java
feat(jans-auth-server): provided ability to set scriptDns related attributes of client (e.g. introspectionScripts) 
closes #3645
=> feat(jans-auth-server): provided ability to set scriptDns related attributes of client (e.g. introspectionScripts) #3645

docs/admin/developer/scripts/introspection.md, docs/script-catalog/introspection/README.md, jans-auth-server/docs/swagger.yaml
doc(jans-auth-server): docs has outdated run_introspection_script_before_access_token_as_jwt_creation_and_include_claims
instead of run_introspection_script_before_jwt_creation 
closes #3673
=> doc(jans-auth-server): docs has outdated run_introspection_script_before_access_token_as_jwt_creation_and_include_claims

docs/admin/auth-server/client-management/README.md
small fixes for readability
Docs update to fix typos in README
=> docs: Auth Server Guide Client Management README typo fixes

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/ldif_utils.py
closes #3695
To create test-client, the following arguments can be provided to `setup.py`
* __-test-client-id__ ID of test client which has all available scopes (this argument triggers test client creation, other arguments are optional)
* __-test-client-secret__  Secret for test client (if not provided secret will be random characters)
* __-test-client-redirect-uri__  Redirect URI for test client (you can provide multiple uri's with comma, if not provided redirect uris will be same as config-api-client)
* __--test-client-trusted__ Make test client trusted (default is **false**)
=> feat: jans-linux-setup create test client with all available scopes

jans-linux-setup/jans_setup/setup_app/installers/scim.py, jans-linux-setup/jans_setup/setup_app/utils/ldif_utils.py
closes #3701
In this PR, setup always uses case sensitive `objectClass`. It is important when ldif is imported to non-ldap db.
=> fix: jans-linux-setup ldif property objectClass should be case sensitive

jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/ldif_utils.py
closes #3705
In this PR
* installation without test client id is fixed
* client display name is changed for TUI and test client
=> fix: jans-linux-setup installation without test client

jans-auth-server/client/src/main/java/io/jans/as/client/ssa/jwtssa/SsaGetJwtClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/jwtssa/SsaGetJwtRequest.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/jwtssa/SsaGetJwtResponse.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/AssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/SsaGetJwtAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaGetJwtTest.java, jans-auth-server/client/src/test/resources/testng.xml, jans-auth-server/docs/swagger.yaml, jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaContextBuilder.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaGetJwtAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaRevokeAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidatorTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateActionTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaGetActionTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaGetJwtActionTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaRevokeActionTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaValidateActionTest.java
- This new endpoint allows to obtain the `JWT` of an `SSA` based on the `JTI`.
- Only the `ssa.admin` scope can consume this service.
closes #3723
=> Feature: New endpoint for get JWT of SSA based on JTI

jans-linux-setup/jans_setup/static/rdbm/pgsql_index.json
=> fix: missing comma delimiter for Postgres index fields

jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py, jans-linux-setup/jans_setup/templates/jans-cli/client.ldif, jans-linux-setup/jans_setup/templates/scopes.ldif
=> feat: jans-linux-setup ssa admin scope

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/cli_style.py, jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/.#edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py, jans-cli-tui/cli_tui/plugins/030_scim/main.py, jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py, jans-cli-tui/cli_tui/utils/static.py, jans-cli-tui/cli_tui/utils/utils.py, jans-cli-tui/cli_tui/wui_components/jans_cli_dialog.py, jans-cli-tui/cli_tui/wui_components/jans_drop_down.py, jans-cli-tui/cli_tui/wui_components/jans_label_container.py, jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py, jans-cli-tui/setup.py
In this PR the following fixes/enhancements are implemented
- Re-post  those properties not modified by TUI for oauth clients (closes #3650)
- Check if valid json for json claims in edit user (closes #3652)
- SSA Management (closes #3686)
=> fix: jans-cli-tui working branch 5

docker-jans-auth-server/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/scripts/auth_handler.py, docker-jans-certmanager/scripts/utils.py, docker-jans-configurator/Dockerfile, docker-jans-configurator/scripts/bootstrap.py
=> feat(docker-jans): introduce key_ops when generating keys

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
chore(jans-auth-server): clean up 
closes #3779
=> chore(jans-auth-server): clean up #3779

jans-auth-server/client/src/main/java/io/jans/as/client/util/KeyGenerator.java, jans-auth-server/client/src/main/java/io/jans/as/client/util/KeyGeneratorContext.java, jans-auth-server/client/src/test/java/io/jans/as/client/util/KeyGeneratorContextTest.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AbstractCryptoProvider.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/ElevenCryptoProvider.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwk/JSONWebKey.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwk/JWKParameter.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwk/KeyOpsType.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/token/JwrService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/token/JwtSigner.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/ServerCryptoProvider.java, jans-auth-server/server/src/main/java/io/jans/as/server/userinfo/ws/rs/UserInfoRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/comp/CrossEncryptionTest.java
feat(jans-auth-server): renamed "key_ops" -> "key_ops_type"
Some frameworks does not allow custom key_ops like "ssa" (e.g. nimbus)
closes #3790
=> feat(jans-auth-server): renamed "key_ops" -> "key_ops_type" #3790

demos/jans-tent/clientapp/__init__.py
use general Exception instead
Signed-off-by: christian 
There was unused (deleted) modules references in error handling, which caused #3785 
closes #3785 
=> fix(tent): remove unknown module refference

jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaErrorResponseType.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateActionTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaGetJwtActionTest.java, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-errors.json
- The `generateJwt` method has been modified to filter by `key_ops=ssa` to obtain the `keyId`.
- A new `invalid_signature` exception has been added to check that the algorithm configured in `ssaSigningAlg` exists in the `webKeysConfiguration` list.
closes #3746
=> Feature: use key_ops=ssa to generate JWT from SSA

jans-cli-tui/Makefile, jans-cli-tui/README.md, jans-cli-tui/docs/build.md, jans-cli-tui/setup.py
=> fix: jans-cli-tui documentation and setup

jans-pycloudlib/jans/pycloudlib/config/aws_config.py, jans-pycloudlib/jans/pycloudlib/secret/aws_secret.py
=> fix(jans-pycloudlib): avoid overwritten data by using merge strategy for AWS wrappers

jans-cli-tui/pyproject.toml
=> fix: jans-cli-tui include pyproject.toml

jans-auth-server/model/src/main/java/io/jans/as/model/crypto/AuthCryptoProvider.java
fix(jans-auth-server): provided corrected public key for outdated key stores during id_token creation if key_ops_type is absent #3840
closes #3840
=> fix(jans-auth-server): provided corrected public key for outdated key stores during id_token creation if key_ops_type is absent #3840

jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> fix: jans-linux-setup save test_client_id to setup.properties

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalPostAuthnContext.java
feat(jans-auth-server): provide ability to ignore/bypass prompt=consent 
closes #3721
=> feat(jans-auth-server): provide ability to ignore/bypass prompt=consent #3721

docker-jans-persistence-loader/scripts/upgrade.py
closes #3848 
To validate the config addition, run the following command (example in mysql):
```
mysql \
-u $DB_USER \
--password=$DB_PASSWORD \
$DB_NAME \
-e "SELECT jansConfDyn FROM jansAppConf where doc_id = 'jans-auth'" | grep persistIdToken
```
=> fix(docker-jans-persistence-loader): add missing persist tokens config when upgrading from previous version

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
closes #3861
Test Client variable names changed:
- **Arguments:** `-test-client-id`, `-test-client-pw`, `--test-client-trusted`
- **setup.properties** and **setup.properties.last**:  `test_client_id`, `test_client_pw`, `test_client_trusted`
=> fix: jans-linux-setup sync test client variable names

jans-auth-server/model/src/main/java/io/jans/as/model/common/IntrospectionResponse.java, jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
feat(jans-auth-server): OAuth 2.0 Step-up - added acr and auth_time to introspection response 
closes #2589
=> feat(jans-auth-server): OAuth 2.0 Step-up - added acr and auth_time to introspection response #2589

jans-pycloudlib/jans/pycloudlib/secret/google_secret.py
=> fix(jans-pycloudlib): split google secrets when payload is larger than 65536 bytes

jans-cli-tui/cli_tui/cli_style.py, jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py, jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-cli-tui/cli_tui/plugins/999_jans/main.py, jans-cli-tui/cli_tui/utils/static.py, jans-cli-tui/cli_tui/wui_components/jans_path_browser.py, jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
In this PR:
- fix: new scope missing from client configuration menu (closes #3860)
- ask project name if not exist in `project.json` for agama deployment
- fix: unable to start if jans-cli.ini is not exist (closes #3873)
- fix: unable to use SSA endpint in first start (closes #3874)
- feat: import script from file (closes #3884)
=> fix(jans-cli-tui):  working branch 9

docker-jans-certmanager/scripts/auth_handler.py, jans-pycloudlib/jans/pycloudlib/meta/kubernetes_meta.py
=> fix(docker-jans): handle failure on running API requests to Kubernetes API server in Google Cloud Run

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalScriptContext.java
fix(jans-auth-server): error from introspection interception script is not propagated during AT as JWT creation 
closes #3904
=> fix(jans-auth-server): error from introspection interception script is not propagated during AT as JWT creation #3904

docker-jans-persistence-loader/Dockerfile
=> chore(docker-jans-persistence-loader): remove github_ads script from default installation

jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
=> fix(jans-linux-setup): install ncurses-compat-libs cb backend for el8

docs/admin/developer/agama/dsl-full.md, docs/admin/developer/agama/faq.md, docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
=> feat: add to AS session the data passed in `Finish`

jans-pycloudlib/jans/pycloudlib/secret/aws_secret.py
=> fix(jans-pycloudlib): split aws secrets when payload is larger than 65536 bytes

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/couchbase.py
closes  #3268
In thi PR, instead of re-writing progress bar, installing couchbase-server before jans deployment was implemented.
=> fix(jans-linux-setup): install cb before jans installation

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
fix(jans-auth-server): WebApplicationException is not propagated out of "Update Token" script 
closes #3996
=> fix(jans-auth-server): WebApplicationException is not propagated out of "Update Token" script #3996

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/main/java/io/jans/as/client/builder/RegistrationBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/RegisterRequestTest.java, jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java, jans-auth-server/common/src/test/java/io/jans/as/common/model/registration/ClientTest.java, jans-auth-server/common/src/test/resources/testng.xml, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/common/AuthenticationMethod.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/MTLSService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/registration/RegisterParamsValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/token/ClientAssertion.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/ClientService.java
feat(jans-auth-server): introduced additional_token_endpoint_auth_method client's property 
closes #3473
=> feat(jans-auth-server): introduced additional_token_endpoint_auth_method client's property #3473

jans-auth-server/docs/swagger.yaml
fix(jans-auth-server): bad indentation in AS swagger.yaml 
closes #4108
=> fix(jans-auth-server): bad indentation in AS swagger.yaml #4108

jans-scim/model/src/main/java/io/jans/scim/model/scim2/fido/DeviceData.java, jans-scim/model/src/main/java/io/jans/scim/model/scim2/fido/Fido2DeviceResource.java, jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/Fido2DeviceWebService.java, jans-scim/service/src/main/java/io/jans/scim/model/GluuFido2Device.java, jans-scim/service/src/main/java/io/jans/scim/model/fido2/Fido2DeviceData.java
=> feat: include jansDeviceData in SCIM Fido2Resource schema

docs/admin/auth-server/endpoints/client-registration.md, docs/governance/triage.md
=> fix: formatting issues in dcr document

docs/admin/auth-server/tokens/oauth-refresh-tokens.md, jans-auth-server/model/src/main/java/io/jans/as/model/common/ScopeConstants.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/ldap/TokenAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/GrantService.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/GrantServiceTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-linux-setup/jans_setup/openbanking/templates/scopes.ldif, jans-linux-setup/jans_setup/templates/scopes.ldif
feat(jans-auth-server): added online_access scope to issue session bound refresh token 
closes #3012
=> feat(jans-auth-server): added online_access scope to issue session bound refresh token #3012

docker-jans-persistence-loader/scripts/upgrade.py
=> fix(docker-jans-config-api): remove licenseSpringCredentials from admin-ui jansConfDyn

docs/admin/developer/agama/engine-config.md, docs/admin/developer/agama/faq.md, docs/admin/developer/agama/quick-start.md, jans-auth-server/server/conf/jans-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/scripts.ldif
=> feat(jans-linux-setup): enable agama engine by default 

jans-cli-tui/cli_tui/wui_components/jans_drop_down.py
=> fix(jans-cli-tui): dropdown raises error if not initial values provided

jans-fido2/model/src/main/java/io/jans/fido2/model/u2f/error/Fido2ErrorResponseFactory.java, jans-fido2/model/src/main/java/io/jans/fido2/model/u2f/error/Fido2ErrorResponseType.java, jans-fido2/server/src/main/java/io/jans/fido2/service/sg/converter/AssertionSuperGluuController.java, jans-fido2/server/src/main/java/io/jans/fido2/service/sg/converter/AttestationSuperGluuController.java
Issue was caused due to direct exception throwing
https://github.com/JanssenProject/jans/issues/3902 
closes #3902
ErrorResponse was implemented similar to jans-auth-server using a WebApplicationException.
The error is showed in a detailed json.
=> fix(jans-fido2):handling exception fido2 get endpoints by invalid params

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
=> feat(docker-jans-persistence-loader): add online_access scope and enable agama engine by default

jans-linux-setup/jans_setup/templates/configuration.ldif
In this PR **jansAuthMode** was set to default value as mentioned in issue #4159
=> fix(jans-linux-setup): set jansAuthMode - default acr mode

jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-auth-server/server/src/test/java/io/jans/as/server/servlet/OpenIdConfigurationTest.java
fix(jans-auth-server): simple_password_auth is missed in acr_values_supported #4258
closes #4258
=> fix(jans-auth-server): simple_password_auth is missed in acr_values_supported #4258

docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json
=> fix(docker-jans-persistence-loader): set highest level script to false by default

jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java
According to test suite:
"...MUST contain "status" field, and it MUST be of type DOMString and set to "ok" (b) response MUST contain "errorMessage" field, and it MUST be of type DOMString ...."
Closes #4241,
=> feat: restore status/errorMessage and timeout attributes

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeActionTest.java, jans-auth-server/server/src/test/resources/testng.xml
fix(jans-auth-server) : Authorization with acr_values=simple_password_auth failing 
closes #4278
=> fix(jans-auth-server) : Authorization with acr_values=simple_password_auth failing #4278

demos/jans-tent/clientapp/__init__.py, demos/jans-tent/clientapp/client_handler.py, demos/jans-tent/clientapp/config.py, demos/jans-tent/main.py
As not requested by Apache 2.
Closes #4304,
=> chore(tent): remove source licensing copyright notice

docs/script-catalog/person_authentication/super-gluu-external-authenticator/README.md
=> fix(docs): temporary record incase of one_step #3340

docs/script-catalog/person_authentication/super-gluu-external-authenticator/README.md
=> fix(docs): post-install setup #3340

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/jans_cli_tui.py
closes #4316
In this PR, TUI displays complete verification url as follows
=> feat(jans-cli-tui): device verification url with code

docker-jans-persistence-loader/Dockerfile
=> chore(docker-jans-persistence-loader): add default_flow_name property to agama script

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(jans-auth-server): avoid redirect 302 exception every time an authentication request is issued 
closes #2287
=> fix(jans-auth-server): avoid redirect 302 exception every time an authentication request is issued #2287

jans-cli-tui/setup.py
=> fix(jans-cli-tui): use -dev isntead of -SNAPSHOT in build version

jans-linux-setup/jans_setup/templates/scripts.ldif
fix(jans-linux-setup): disable agama script by default (avoid blank page) 
closes #4374
=> fix(jans-linux-setup): disable agama script by default (avoid blank page) #4374

docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json
=> fix(docker-jans-persistence-loader): disable agama engine by default

jans-auth-server/common/src/main/java/io/jans/as/common/service/common/ConfigurationService.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ConfigSmtpResource.java, jans-core/service/src/main/java/io/jans/service/MailService.java, jans-core/util/src/main/java/io/jans/model/SmtpConfiguration.java, jans-scim/service/src/main/java/io/jans/scim/service/ConfigurationService.java
Renamed:
userName -> smtpAuthenticationAccountUsername (json prop '**smtp_authentication_account_username**');
password -> smtpAuthenticationAccountPassword (json prop '**smtp_authentication_account_password**');
passwordDecrypted -> smtpAuthenticationAccountPasswordDecrypted;
i.e. now:
```
/opt/jans/jans-cli/cli/config_cli.py --operation-id put-config-smtp --data ./smtp.json
```
, where **smtp.json** contains:
```
{
"connectProtectionList":
[
"NONE",
"START_TLS",
"SSL_TLS"
],
"trust_host": true,
"connect-protection": "SslTls",
"host": "smtp.gmail.com",
"port": 465,
"smtp_authentication_account_username": "sman2dev@gmail.com",
"from_name": "Sergey Man",
"from_email_address": "sman2dev@gmail.com",
"requires_authentication": true,
"smtp_authentication_account_password":"********************* …
```
=> feat: userName -> smtpAuthenticationAccountUsername;

jans-auth-server/common/src/test/java/io/jans/as/common/service/common/UserServiceTest.java
test(jans-auth-server): UserServiceTest.addUser_noEmptyPersonCustomObject_user is failing after changes in UserService 
closes #4408
=> test(jans-auth-server): UserServiceTest.addUser_noEmptyPersonCustomObject_user is failing after changes in UserService #4408

README.md
Added the following to Janssen Project README
- Link to Twitter
- Badges for digital public good and Linux Foundation membership
Chages highlighted in red box :point_down: 
closes #4406
=> docs: update README to add social and DPGA info

docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.json, docker-jans-persistence-loader/templates/jans-auth/jans-auth-config.ob.json, docs/admin/config-guide/jans-cli/cli-jans-authorization-server.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/conf/jans-config.json, jans-linux-setup/jans_setup/openbanking/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
feat(jans-auth-server): increase sessionIdUnauthenticatedUnusedLifetime value in setup
closes #4445
=> feat(jans-auth-server): increase sessionIdUnauthenticatedUnusedLifetime value in setup #4445

jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/ExternalScriptContext.java
feat(jans-auth-server): use "nologs" version of WebApplicationException in custom script context to avoid stacktrace during redirects 
closes #4447
=> feat(jans-auth-server): use "nologs" version of WebApplicationException in custom script context to avoid stacktrace during redirects #4447

jans-auth-server/server/src/main/java/io/jans/as/server/model/registration/RegisterParamsValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/RegisterServiceTest.java
fix(jans-auth-server) - client registration request defaults to code flow 
>> response_types
OPTIONAL. JSON array containing a list of the OAuth 2.0 response_type values that the Client is declaring that it will restrict itself to using. **If omitted, the default is that the Client will use only the code Response Type.**
>> grant_types
OPTIONAL. JSON array containing a list of the OAuth 2.0 Grant Types that the Client is declaring that it will restrict itself to using.  **If omitted, the default is that the Client will use only the authorization_code Grant Type.**
https://openid.net/specs/openid-connect-registration-1_0.html
closes #4296
=> fix(jans-auth-server) - client registration request defaults to code flow #4296

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): display jansId when editing client's scope

docs/admin/developer/agama/gama-deployment.md, jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaDeploymentsService.java
=> fix(jans-config-api): agama deployment detail endpoint not including all flows IDs

demos/jans-tent/README.md
Tent requires `python >= 3.11`
Also rewrite information regarding pyenv for Mac users
=> docs(tent): add required python version

demos/jans-tent/clientapp/__init__.py
Debug information was being printed to console calling `print` function.
Closes #4588,
=> fix(tent): remove print calls

docker-jans-config-api/scripts/bootstrap.py
=> fix(docker-jans-config-api): add missing smtp keystore

jans-auth-server/pom.xml
fix(jans-auth-server): upgraded jettison, 1.5.2 -> 1.5.4 
closes #4591
=> fix(jans-auth-server): upgraded jettison, 1.5.2 -> 1.5.4 #4591

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-scim/Dockerfile
=> chore(docker-jans): sync jans-auth-config template

jans-config-api/docs/jans-config-api-swagger.yaml, jans-core/util/src/main/java/io/jans/model/SmtpConnectProtectionType.java
```
/opt/jans/jans-cli/cli/config_cli.py --operation-id get-config-smtp
```
doesn't return "connect_protection" property.
Response should contain property:
"connect_protection": "xxxxxxxx".
Ldap Db contains in **jansSmtpConf**:
...
"connectProtectionList":["NONE","START_TLS","SSL_TLS"],
"connect_protection":"SSL_TLS"
...
After fix:
Ldap Db contains in **jansSmtpConf**:
```
"connectProtectionList":["None","StartTls","SslTls"],
"connect_protection":"SslTls"
```
.
Issue: #4602
=> fix: jsonvalue has been added;

jans-linux-setup/jans_setup/jans_setup.py
closes #4666
(Related to #4627)
=> feat(jans-linux-setup): detect arch before starting setup

demos/jans-tent/.gitignore, demos/jans-tent/README.md, demos/jans-tent/clientapp/__init__.py, demos/jans-tent/clientapp/config.py, demos/jans-tent/clientapp/helpers/client_handler.py, demos/jans-tent/clientapp/helpers/custom_msg_factory.py, demos/jans-tent/clientapp/utils/dcr_from_config.py, demos/jans-tent/tests/unit_integration/test_client_register_endpoint.py, demos/jans-tent/tests/unit_integration/test_dcr_from_config.py, demos/jans-tent/tests/unit_integration/test_dynamic_client_registration.py
As discussed in the related issue, sending `scope` in DCR request  is unusual but is allowed by specs. This PR address this issue.
Scopes added in `config.py` are now included in DCR request.
closes #4615
=> feat(tent): add `scope` in DCR request

jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/utils/crypto64.py
=> fix(jans-linux-setup): default keystore type pkcs12

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py, jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py, jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py, jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
- closes #4793: set selection to zero in JansVerticalNav when cleared
- closes #4795: update claims list on edit user page if attribute is saved/deleted
- closes #4796: checked state of user custom attribute
- closes #4800: When hit return to select < back > ...  cannot use the tab anymore to navigate and had to ctrl-c
=> fix(jans-cli-tui): set seleted to zero in JansVerticalNav when cleared

automation/startjanssenmonolithdemo.sh, docker-jans-monolith/Dockerfile, docker-jans-monolith/scripts/entrypoint.sh
1. Add support for running processes using scripts under `/opt/dist/scripts` directory (for example: `/opt/dist/scripts/opendj start`)
2. allow build mode (instead of pulling image) only if `JANS_BUILD_COMMIT` passed to `automation/startjanssenmonolithdemo.sh`
closes #4809 
=> fix(docker-jans-monolith): add support for using /opt/dist/scripts

jans-auth-server/server/src/main/java/io/jans/as/server/service/LocalResponseCache.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalAuthenticationService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/LocalResponseCacheTest.java, jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): invalidate discovery cache if some scripts are (re)loaded 
closes #4500
=> feat(jans-auth-server): invalidate discovery cache if some scripts are (re)loaded #4500

jans-config-api/pom.xml
Security vulnerability reported in `jans-config-api` due to json-smart.
json-smart is shaded dependency on in `nimbus-jose-jwt`
Bump nimbus-jose-jwt version to resolve vulnerability
closes #4842
=> chore(deps): bump nimbus-jose-jwt from 9.11.1 to 9.28

jans-pycloudlib/jans/pycloudlib/wait.py, jans-pycloudlib/tests/test_wait.py
=> fix(jans-pycloudlib): service label is missing on subsequent wait function calls

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/jans_cli_tui.py
- closes #4880: process auth only  endpoint has security constraint
- closes #4874: check health of config-api before start
=> fix(jans-cli-tui): process auth  endpoint has security constraint

demos/benchmarking/docker-jans-loadtesting-jmeter/Dockerfile, demos/benchmarking/docker-jans-loadtesting-jmeter/Makefile, demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-test/load_test_auth_code.yaml, demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_couchbase_job.yaml, demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_ldap_job.yaml, demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_rdbms_job.yaml, demos/benchmarking/docker-jans-loadtesting-jmeter/yaml/load-users/load_users_spanner_job.yaml, docs/admin/planning/benchmarking.md, docs/admin/recipes/benchmark.md
=> fix(docker-jans-loadtesting-jmeter): rename incorrect reference to OCI image

docs/admin/reference/json/properties/janssenauthserver-properties.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-auth-server/server/src/test/java/io/jans/as/server/servlet/OpenIdConfigurationTest.java, jans-config-api/docs/jans-config-api-swagger.yaml
fix(jans-auth-server): Illegal op_policy_uri parameter: - exclude entries with blank values from discovery response (oxauth counterpart) 
closes #4888
=> fix(jans-auth-server): Illegal op_policy_uri parameter: - exclude entries with blank values from discovery response (oxauth counterpart) #4888

jans-fido2/notify-client/pom.xml
fix(jans-fido2): compilation is failing due to missed jans-doc dependency 
closes #5051
=> fix(jans-fido2): compilation is failing due to missed jans-doc dependency #5051

demos/jans-tent/clientapp/__init__.py, demos/jans-tent/clientapp/helpers/client_handler.py, demos/jans-tent/clientapp/utils/dcr_from_config.py, demos/jans-tent/tests/unit_integration/helper.py, demos/jans-tent/tests/unit_integration/test_dcr_from_config.py, demos/jans-tent/tests/unit_integration/test_logout_endpoint.py
Logout using Session Management. Kill session and redirects to `end_session_endpoint`
Details:
1. `post_logout_redirect_uris` is now sent in `DCR`, parsed from `redirect_uris` (localhost:9090).
2. `end_session_endpoint` is persisted to `client-info.json` for now.
3. `logout` endpoint requires authentication to be accessed, clear session and redirect to `end_session_endpoint` with the following query string params: `token_hint` , `post_logout_redirect_uri`
Tests:
https://github.com/JanssenProject/jans/commit/4addca2526bd5559520574bbb00c27fe48601009 provides integration tests that ensures item 3 mentioned above.
Closes #4727 ,
=> feat(tent): support RP initiated logout

docker-jans-auth-server/scripts/auth_conf.py
=> fix(docker-jans-auth-server): compare contents before pushing otp_configuration and super_gluu_creds to secrets

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/DeviceAuthorizationAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/DeviceAuthorizationRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/DeviceAuthorizationRestWebServiceImpl.java
fix(jans-auth-server): Device Flow fails if web session already exists 
closes #3388
=> fix(jans-auth-server): Device Flow fails if web session already exists #3388

jans-fido2/server/src/main/java/io/jans/fido2/service/mds/AttestationCertificateService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/AppleAttestationProcessor.java, jans-linux-setup/jans_setup/setup_app/installers/fido.py
Moving the harcoded value, to Fido2 configurations
https://github.com/JanssenProject/jans/issues/4744
closes #4744
Property was implemented
docs were updated
installer was updated including default value
=> fix(jans-fido2):move appleWebauthnRootCa to Fido2 configurations issue#4744

docs/admin/auth-server/endpoints/client-registration.md, jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterCreateAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/action/RegisterCreateActionTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-config-api/docs/jans-config-api-swagger.yaml, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
feat(jans-auth-server): add ability to set client expiration via DCR 
closes #5057
=> feat(jans-auth-server): add ability to set client expiration via DCR #5057

jans-fido2/server/src/main/java/io/jans/fido2/service/mds/TocService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/CertificateVerifier.java, jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/CertificateVerifierTest.java
- Added method for validating acceptable status
- Validation of acceptable status during MDS load process
closes #5191
=> feat(fido2): validate acceptable status when loading MDS

docker-jans-fido2/Dockerfile
=> chore(docker-jans-fido2): move location of downloaded Apple WebAuthn Root CA file

demos/jans-tarp/src/options/oidcClientDetails.tsx, demos/jans-tarp/src/options/registerForm.tsx
=> feat(jans-tarp): on registering client the scope parameter should be space separated string #5259

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ciba/BackchannelAuthenticationPollMode.java, jans-auth-server/client/src/test/java/io/jans/as/client/ciba/BackchannelAuthenticationPushMode.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/MultivaluedClaims.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/OpenIDRequestObjectHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SectorIdentifierUrlVerificationHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/Tester.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/TokenSignaturesHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/UserInfoRestWebServiceHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/uma/ClientAuthenticationByAccessTokenHttpTest.java
test(jans-auth-server): some tests fail after removing automatic client scopes granting 
closes #5262
Closes #5272,
=> test(jans-auth-server): some tests fail after removing automatic client scopes granting #5262

jans-linux-setup/jans_setup/setup_app/installers/cache_refresh.py, jans-linux-setup/jans_setup/templates/jans-cache-refresh/configuration.ldif, jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json
=> fix(jans-linux-setup): CR variable names and snapshot dir

jans-linux-setup/jans_setup/install.py
=> fix(jans-linux-setup): opendj stop for nonldap backends

jans-pycloudlib/jans/pycloudlib/persistence/sql.py, jans-pycloudlib/tests/test_persistence.py
=> fix(jans-pycloudlib): unable to parse mysql server version

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SelectAccountHttpTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/CookieService.java
fix(jans-auth-server): corrected current_sessions cookie value encoding 
closes #5262
=> fix(jans-auth-server): corrected current_sessions cookie value encoding #5262

jans-linux-setup/jans_setup/templates/scopes.ldif
feat(jans-linux-setup): make jans_stat a default oauth scope
closes  #5393
=> feat(jans-linux-setup): make jans_stat a default oauth scope #5393

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(jans-auth-server): check client has access before granting
closes #5247
=> fix(jans-auth-server): check client has access before granting

jans-config-api/plugins/jans-link-plugin/src/test/resources/feature/link/dynamiconf.json, jans-link/src/main/java/io/jans/link/constants/JansConstants.java, jans-linux-setup/jans_setup/static/cache-refresh/o_site.ldif, jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json
=> feat(jans-link): change schema name cache refresh to link

jans-core/pom.xml
chore(jans-core): notify-client is not included in parent pom.xml 
closes #5511
=> chore(jans-core): notify-client is not included in parent pom.xml #5511

docs/script-catalog/application_session/jans-session-audit/README.md, docs/script-catalog/application_session/jans-session-audit/jans-session-audit.py, jans-orm/model/src/main/java/io/jans/orm/model/base/CustomObjectEntry.java
Demo script **jans-session-audit**/**application_session** (**session audit**) has been added;
closes #5557
- The script **jans-session-audit.py** (**jans-session-audit**) creates DB record and writes field **creationDate**;
- Usage of **io.jans.orm.model.base.CustomEntry** works ok on LDAP Db, but doesn't work on SQL Db, so class
**io.jans.orm.model.base.CustomObjectEntry** has been added;
- The script **jans-session-audit.py** (**jans-session-audit**) works ok on LDAP and SQL DBs;
- Generated audit json report, saved in the field **jansData** is valid (accordintg to json format requirements).
=> docs: demo script application_session (session audit) has been added;

docs/contribute/development.md
Update documentation to document steps for running integration tests from developer workspace
closes #5572 
With this PR, the steps to run integration tests for `jans-auth-server` and `agama` are documented. Subsequent PRs will add
steps for other modules like Fido etc.
=> docs(integ-tests): document steps for running integration tests from developer workspace

docs/admin/install/setup.md, jans-linux-setup/jans_setup/setup_app/setup_options.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
=> fix(jans-linux-setup): casa install option --with-casa

docs/admin/vm-ops/backup.md
In this PR you will able to know 
=> docs(vm-ops): update Jans Server backup

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
fix(jans-auth-server): if scopes are missed in grant_type=refresh_token AS must take scopes from previous grant 
closes #5462
=> fix(jans-auth-server): if scopes are missed in grant_type=refresh_token AS must take scopes from previous grant #5462

docker-jans-auth-server/jetty/log4j2.xml, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-config-api/jetty/log4j2.xml, docker-jans-config-api/plugins/admin-ui/log4j2-adminui.xml, docker-jans-config-api/scripts/bootstrap.py, docker-jans-fido2/jetty/log4j2.xml, docker-jans-fido2/scripts/bootstrap.py, docker-jans-link/jetty/log4j2.xml, docker-jans-link/scripts/bootstrap.py, docker-jans-scim/jetty/log4j2.xml, docker-jans-scim/scripts/bootstrap.py
The changeset sets namespaced context for `log.console.*` in `log4j2.xml`.
closes #5616 
=> refactor(docker): avoid context collision on custom log4j2.xml

jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DBDocumentStoreProvider.java
chore(jans-core): document-store does not compile which prevents FullRebuild from run 
closes #5631
=> chore(jans-core): document-store does not compile which prevents FullRebuild from run #5631

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
=> fix(jans-linux-setup): new location of jans_test_client_keys.zip

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py, jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-fido2/server/src/main/java/io/jans/fido2/service/app/AppInitializer.java
=> feat: add new methnod to fido2 extension to allow modify json

docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/upgrade.py, docker-jans-config-api/templates/jans-config-api/testing-clients.ldif, docs/admin/reference/kubernetes/config-secret-keys.md, docs/admin/terraform/README.md
The changeset modifies `docker-jans-config-api` entrypoint to create/update test client (with all scopes).
closes #5663 
1. To create new test client: run `docker-jans-config-api`
2. To manually update test client: run `kubectl -n $NAMESPACE exec $CONFIG_API_POD -- python3 /app/scripts/upgrade.py`
=> fix(docker-jans): add test client with all scopes to CN-based setup

jans-link/model/src/main/java/io/jans/link/model/JansInumMap.java
https://github.com/JanssenProject/jans/issues/5695
corrected jansTertiaryKeyValue attribute in jansInumMap.
=> fix(jans-link): corrected jansTertiaryKeyValue attribute #5695

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
=> fix(jans-linux-setup): OS dependent location of jwks.json

jans-link/server/src/main/java/io/jans/link/service/SystemResteasyInitializer.java, jans-link/server/src/main/java/io/jans/link/ws/rs/HealthCheckController.java, jans-link/server/src/main/webapp/index.jsp
=> feat(jans-link): add health check service in jans link #5608

jans-linux-setup/tools/gamarchive.py
=> feat(jans-cli-tui): agama-cli

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): load test data with setup.properties

docs/admin/developer/agama/projects-deployment.md, jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java
=> fix: remove pending deployments when exceeding 5 minutes

charts/janssen/charts/link/README.md, charts/janssen/charts/link/values.yaml, docker-jans-link/Dockerfile, docker-jans-link/scripts/healthcheck.py
=> feat(docker-jans-link): add healthcheck support

docs/admin/config-guide/config-tools/jans-tui/.#README.md, jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
=> feat(jans-linux-setup): salt with argument

docker-jans-persistence-loader/scripts/couchbase_setup.py, docker-jans-persistence-loader/scripts/entrypoint.sh, docker-jans-persistence-loader/scripts/ldap_setup.py, docker-jans-persistence-loader/scripts/settings.py, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-persistence-loader/scripts/upgrade.py
closes #5791 
Point 1: change logger prefix to persistence-loader
The prefix of entrypoint has been changed from:
```
INFO - entrypoint - 2023-08-04 18:02:33,256 - Creating tables (if not exist)
INFO - entrypoint - 2023-08-04 18:02:33,327 - Updating schema (if required)
INFO - entrypoint - 2023-08-04 18:02:33,461 - Creating indexes (if not exist)
INFO - entrypoint - 2023-08-04 18:02:33,676 - Importing builtin LDIF files
```
to
```
INFO - persistence-loader - 2023-08-04 18:02:33,256 - Creating tables (if not exist)
INFO - persistence-loader - 2023-08-04 18:02:33,327 - Updating schema (if required)
INFO - persistence-loader - 2023-08-04 18:02:33,461 - Creating indexes (if not exist)
INFO - persistence-loader - 2023-08-04 18:02:33,676 - Importing builtin LDIF files
``` …
=> refactor(docker-jans-persistence-loader): reusable assets for custom image

jans-linux-setup/jans_setup/setup_app/installers/casa.py
=> feat(jans-linux-setup): make Casa .administrable by default

jans-linux-setup/jans_setup/app_info.json, jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jre.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
closes #5828
You can specify java version with option `-java-version`, it can be either 11 or 17. Default is 11
=> feat(jans-linux-setup): option for java version

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): check if host in config

jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java
=> Fix load on script npe

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/util/ConnectionStatus.java
Currently the source LDAP test is failing on jans-auth server that has non LDAP persistence DB.
closes #5818 
=> fix(config-api): source LDAP server test

docs/admin/config-guide/agama-configuration.md
=> fix(docs): removed Agama Developer Studio reference

docs/admin/developer/scripts/application-session.md
- Added docs for application session script
closes #4704
=> Docs(script): Application session script

docs/admin/developer/scripts/README.md
=> fix(docs): add missing interception scripts to the listing

docs/admin/recipes/benchmark.md
closes #4792 
Corrected the benchmarking document by changing 'CPU' to 'vCPU' at all places.
=> docs: changed CPU to vCPU

docs/admin/fido/config.md, docs/admin/fido/vendor-metadata.md, jans-fido2/model/src/main/java/io/jans/fido2/model/conf/Fido2Configuration.java, jans-fido2/server/src/main/java/io/jans/fido2/service/app/MDS3UpdateTimer.java, jans-fido2/server/src/main/java/io/jans/fido2/service/mds/AttestationCertificateService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/mds/TocService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/AndroidKeyAttestationProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/AndroidSafetyNetAttestationProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/AppleAttestationProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/PackedAttestationProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/TPMProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/processor/attestation/U2FAttestationProcessor.java, jans-fido2/server/src/main/java/io/jans/fido2/service/util/AppleUtilService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/util/CommonUtilService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/CommonVerifiers.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/AndroidKeyAttestationProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/AndroidSafetyNetAttestationProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/AppleAttestationProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/PackedAttestationProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/TPMProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/processor/attestation/U2FAttestationProcessorTest.java, jans-fido2/server/src/test/java/io/jans/fido2/service/util/CommonUtilServiceTest.java, jans-fido2/server/src/test/java/io/jans/util/TestUtil.java, jans-linux-setup/jans_setup/templates/jans-fido2/dynamic-conf.json
- Added 2 new configuration parameters: 
* `skipDownloadMdsEnabled`: Boolean value indicating whether the MDS download should be omitted
* `skipValidateMdsInAttestationEnabled`: Boolean value indicating whether MDS validation should be omitted during attestation
- Skip MDS validation in attestation for `packet`, `fido-u2f`, `tpm`, `android-key`, `android-safetynet` and `apple`
closes #5171
=> feat(fido2): make mds and attestation optional

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/plugins.py, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/bootstrap.py, docker-jans-link/Dockerfile, docker-jans-link/scripts/bootstrap.py, docker-jans-scim/Dockerfile, docker-jans-scim/scripts/bootstrap.py
=> refactor(docker-jans): unify path to JVM cacert file

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py
=> fix(docker-jans-persistence-loader): data type too small for jansDevice data

jans-core/script/pom.xml, jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java, jans-core/script/src/main/java/io/jans/service/custom/script/jit/DiscardableClassLoader.java, jans-core/script/src/main/java/io/jans/service/custom/script/jit/IndentedPrintWriter.java, jans-core/script/src/main/java/io/jans/service/custom/script/jit/JavaCodeGenerator.java, jans-core/script/src/main/java/io/jans/service/custom/script/jit/SimpleJavaCompiler.java, jans-core/script/src/test/java/io/jans/service/custom/script/test/java/SimpleJavaCompileTest.java, jans-core/script/src/test/java/io/jans/service/custom/script/test/java/Testable.java
feat(jans-auth-server): added JIT compiler support under jvm 17
closes #5837
=> fix(jans-auth-server): added JIT compiler support under jvm 17

jans-auth-server/server/src/main/java/io/jans/as/server/service/ClientService.java
fix(jans-auth-server): ignore custom OC for non-LDAP during client merge
closes #5977
=> fix(jans-auth-server): ignore custom OC for non-LDAP during client merge

docker-jans-configurator/scripts/bootstrap.py
=> fix(docker-jans-configurator): use longer expiration time for initial jwks

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
fix(jans-auth-server): server can handle prompts incorrectly when acr is changed 
closes #5930
=> fix(jans-auth-server): server can handle prompts incorrectly when acr is changed #5930

jans-bom/pom.xml
=> chore: use bc-fips <= 1.0.2.4

docs/admin/auth-server/endpoints/end-session.md, jans-auth-server/docs/swagger.yaml, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImplTest.java
feat(jans-auth-server): add client_id parameter support to /end_session 
closes #5942
=> feat(jans-auth-server): add client_id parameter support to /end_session #5942

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py
=> fix(docker-jans-persistence-loader): search session by deviceSecret

docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/upgrade.py
=> fix(docker-jans-fido2): search cache for session instead of persistence

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
=> fix: remove content-type in header from /retrieve GET request #6096

jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImplTest.java
fix(jans-auth-server): redirect when session does not exist but client_id parameter is present
closes #5942
=> fix(jans-auth-server): redirect when session does not exist but client_id parameter is present

jans-linux-setup/jans_setup/app_info.json, jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/couchbase.py, jans-linux-setup/jans_setup/setup_app/installers/eleven.py, jans-linux-setup/jans_setup/setup_app/installers/fido.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/installers/jans_casa.py, jans-linux-setup/jans_setup/setup_app/installers/jans_link.py, jans-linux-setup/jans_setup/setup_app/installers/oxd.py, jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/installers/scim.py
=> fix(jans-linux-setup): casa url

docs/admin/developer/agama/projects-deployment.md, jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java, jans-auth-server/agama/model/src/main/java/io/jans/ads/model/DeploymentDetails.java, jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaDeploymentsService.java
=> feat(agama): add support for autoconfiguration 

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/requirements.txt, docker-jans-casa/Dockerfile, docker-jans-casa/requirements.txt, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/requirements.txt, docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-configurator/Dockerfile, docker-jans-configurator/requirements.txt, docker-jans-fido2/Dockerfile, docker-jans-fido2/requirements.txt, docker-jans-link/Dockerfile, docker-jans-link/requirements.txt, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-scim/Dockerfile, docker-jans-scim/requirements.txt
=> feat(docker-jans): upgrade base image to Java 17

mkdocs.yml
=> fix(docs): scripts should be shown alphabetically

docs/admin/planning/load-balancers.md, docs/admin/planning/platform-goal.md, docs/admin/planning/use-cases.md, docs/admin/terraform/README.md, docs/script-catalog/person_authentication/fido2-external-authenticator/README.md, jans-config-api/README.md
=> docs: fixes

jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrantList.java
fix(jans-auth-server): cnf introspection response is null even when valid cert is send during MTLS #6343
closes #6343
=> fix(jans-auth-server): cnf introspection response is null even when valid cert is send during MTLS #6343

jans-linux-setup/jans_setup/templates/base.ldif
=> fix(jans-linux-setup): change oxtrust to Janssen

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py, jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix: registration_uri for super gluu script defaults to an /identity

jans-cli-tui/setup.py
=> fix(jans-cli-tui): ruamel.yaml<0.18.0

docs/admin/auth-server/endpoints/token-revocation.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/config/Constants.java, jans-auth-server/server/src/main/java/io/jans/as/server/revoke/RevokeRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/revoke/RevokeRestWebServiceImplTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-linux-setup/jans_setup/templates/scopes.ldif
feat(jans-auth-server): allow revoke any token - explicitly allow by config and scope #6381
closes #6381
=> feat(jans-auth-server): allow revoke any token - explicitly allow by config and scope #6381

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
=> fix(jans-cli-tui): save logging response is app properties not schema

terraform-provider-jans/CHANGELOG.md, terraform-provider-jans/docs/resources/oidc_client.md, terraform-provider-jans/docs/resources/scope.md, terraform-provider-jans/jans/oidc_client.go, terraform-provider-jans/provider/resource_oidc_client.go
Bug Fixes
* oidc backchannel_user_code_parameter schema type 
Closes #6525, #6523
=> fix(terraform-provider-jans): update terraform module

docs/admin/auth-server/crypto/keys.md, docs/admin/auth-server/endpoints/archived-jwks-uri.md, jans-auth-server/client/src/main/java/io/jans/as/client/OpenIdConfigurationClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/OpenIdConfigurationResponse.java, jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/common/src/main/java/io/jans/as/common/model/common/ArchivedJwk.java, jans-auth-server/common/src/main/java/io/jans/as/common/model/common/ArchivedKeyAttributes.java, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/config/BaseDnConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/ConfigurationResponseClaim.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwk/JSONWebKeySet.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/conf/jans-static-conf.json, jans-auth-server/server/src/main/java/io/jans/as/server/jwk/ws/rs/ArchivedJwksService.java, jans-auth-server/server/src/main/java/io/jans/as/server/jwk/ws/rs/ArchivedJwksWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/CleanerTimer.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/KeyGeneratorTimer.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/ResteasyInitializer.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/FapiOpenIdConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-auth-server/server/src/test/java/io/jans/as/server/jwk/ws/rs/ArchivedJwksServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/TestResteasyInitializer.java, jans-linux-setup/jans_setup/schema/jans_schema.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-static-conf.json, mkdocs.yml
Archived jwks:
1. When key is rotated, public part must be archived
2. It is possible to fetch it `https://as.com/jwks/archived/{kid}`
3. Added configuration property for `exp` of archived keys. Default value 1 year. After it's passed archived key is removed from DB.
closes #6437
=> feat(jans-auth-server): archived jwks

jans-auth-server/server/src/main/java/io/jans/as/server/service/ClientService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SpontaneousScopeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/uma/service/UmaValidationService.java
Use guava instead of internal jython classes.
Closes #6570,
=> chore: fix dependecies to guava lib

automation/startjanssendemo.sh, charts/janssen/values.schema.json
=> feat: add postgres option

docs/admin/developer/scripts/update-token.md, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java
fix(jans-auth-server): UpdateToken script is not invoked during Implicit Flow #6561
closes #6561
=> fix(jans-auth-server): UpdateToken script is not invoked during Implicit Flow #6561

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/OIDCClientSettings.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java
=> feat: replace jwt token with reference token to access config-api (admin ui plugin) #6562

jans-linux-setup/jans_setup/templates/jetty/jans-auth
=> fix: avoid crash when variables at the top of util.js are serialized

docs/admin/auth-server/oauth-features/pkce.md
=> docs: pkce formats !!! note

jans-core/util/pom.xml
fix(jans-core): jans-core starts to fail after dependencies upgrade 
closes #6783
=> fix(jans-core): jans-core starts to fail after dependencies upgrade #6783

jans-bom/pom.xml
fix(jans-bom): resteasy 6.2.x required weld upgrade thus reverting resteasy back to 6.0.3.Final 
closes #6787
=> fix(jans-bom): resteasy 6.2.x required weld upgrade thus reverting resteasy back to 6.0.3.Final #6787

jans-auth-server/client/pom.xml
fix(jans-auth-server): ClassNotFoundException: javax.xml.bind.annotation.XmlElement 
closes #6798
=> fix(jans-auth-server): ClassNotFoundException: javax.xml.bind.annotation.XmlElement #6798

jans-auth-server/docs/swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/ApiApplication.java, jans-fido2/docs/jansFido2Swagger.yaml, jans-scim/server/src/main/resources/jans-scim-openapi.yaml
Since we do not want to use the `info`->`version` element but we have to because the `editor.swagger.io` shows warning otherwise.
Ideal solution is to put `vreplace-janssen-version` in there and let the release process fill in the right version number. But at the moment yaml files are not covered in this replacement process. So as a stop-gap, I have added version with static value of `OAS Version` as it looks logical on screen :point_down: and doesn't have to be replaced.
closes #6622 
=> fix: openapi spec version element

jans-bom/pom.xml
fix(jans-auth-server): common-text upgrade 1.11.0 leads to class initialization problems 
closes #6826
=> fix(jans-auth-server): common-text upgrade 1.11.0 leads to class initialization problems #6826

jans-auth-server/server/pom.xml, jans-auth-server/server/src/test/java/io/jans/as/server/ConfigurableTest.java
test(jans-auth-server): embedded tests are failing after testng upgrade to 7.8.0 
closes #6837
=> test(jans-auth-server): embedded tests are failing after testng upgrade to 7.8.0 #6837

jans-fido2/server/pom.xml
fix(fido2): tests are failing due to NoClassDefFoundError: javax/xml/bind/annotation/XmlElement 
https://jenkins.jans.io/jenkins/job/jans-fido2/3555/testReport/junit/io.jans.fido2.service.sg/FullFlowAndroidTest/testFinishAttestationTwoStepAndroid_String__String__String_/
closes #6865
=> fix(fido2): tests are failing due to NoClassDefFoundError: javax/xml/bind/annotation/XmlElement #6865

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py
=> feat(docker-jans-persistence-loader): set feature flags state

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py
=> feat(docker-jans): use mixed strategy for Agama serialization

jans-core/message/pom.xml, jans-core/message/src/main/java/io/jans/service/BaseMessageService.java, jans-core/message/src/main/java/io/jans/service/MessageService.java, jans-core/message/src/main/java/io/jans/service/message/AbstractMessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/MessageInterface.java, jans-core/message/src/main/java/io/jans/service/message/MessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/MessageProviderFactory.java, jans-core/message/src/main/java/io/jans/service/message/NullMessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/PostgresMessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/RedisMessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/StandaloneMessageProviderFactory.java, jans-core/message/src/main/java/io/jans/service/message/model/config/MessageConfiguration.java, jans-core/message/src/main/java/io/jans/service/message/model/config/MessageProviderType.java, jans-core/message/src/main/java/io/jans/service/message/model/config/NullMessageConfiguration.java, jans-core/message/src/main/java/io/jans/service/message/model/config/PostgresMessageConfiguration.java, jans-core/message/src/main/java/io/jans/service/message/pubsub/PubSubInterface.java, jans-core/message/src/main/java/io/jans/service/message/pubsub/PubSubRedisAdapter.java, jans-core/message/src/main/resources/META-INF/beans.xml, jans-core/message/src/test/java/io/jans/service/message/test/dev/StandalonePostresMessageTest.java, jans-core/message/src/test/java/io/jans/service/message/test/dev/StandaloneRedisMessageTest.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqConnectionProviderPool.java
https://github.com/JanssenProject/jans/issues/6538
Closes #6894,
=> feat: add jans-lock-event library to publish messages to event server from jans-auth

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java
fix(jans-auth-server): authz challenge session attributes are overwritten after external script run 
closes #6933
=> fix(jans-auth-server): authz challenge session attributes are overwritten after external script run #6933

docker-jans-persistence-loader/scripts/upgrade.py
=> fix(docker-jans-persistence-loader): passing CN_SCIM_ENABLED doesn't toggle jansScimEnabled config

docker-jans-all-in-one/app/requirements.txt
Remove `jwcrypto` library from requirements as the dependant `flex-all-in-one` image has been adding the library directly.
closes #6835 
=> chore(deps): remove jwcrypto dependency from jans-all-in-one image

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): save client

jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java, jans-config-api/docs/jans-config-api-swagger.yaml
=> fix(config-api): hide authenticationMethod client model utility method

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py, jans-linux-setup/jans_setup/static/system/systemd/kc.service, jans-linux-setup/jans_setup/templates/apache/https_jans.conf, jans-linux-setup/jans_setup/templates/jans-saml/jans-saml-config.json
=> feat(jans-linux-setup): put KC behind apache

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/static/system/systemd/jans-casa.service
=> fix(jans-linux-setup): systemctl fido2 start order

jans-keycloak-integration/pom.xml
Excluded libraries causing `kc-storage-plugin` to prevent Keycloak from starting.
=> fix(keycloak-integration): Keycloak startup issue #7123

jans-auth-server/common/src/main/java/io/jans/as/common/model/registration/Client.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-orm/model/src/main/java/io/jans/orm/model/base/CustomObjectAttribute.java
- 7082: Json processing handling for request with `displayName`  value as null for custom attribute.
- 7134: tokenEndpointAuthMethod to be defined as enum in sepc
closes #7082 , #7134
=> fix(config-api): changes for json processing of customattribute & tokenEndpointAuthMethod  definition in spec

jans-fido2/server/profiles/default/config-build.properties, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
- jansPublicKeyId field size update to 256 characters
- Updating the fido config-build.properties file
closes #7114
=> fix(jans-fido2): jansPublicKeyId updated to 256 characters

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
=> fix(jans-cli-tui): don't include client secret in summary

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/010_auth_server/message.py, jans-cli-tui/cli_tui/utils/utils.py
=> feat(jans-cli-tui): message configuration

jans-auth-server/docs/swagger.yaml
- Format in array swagger yaml
closes #7188
=> fix(jans-auth-server): fix swagger.yaml

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
=> fix(jans-cli-tui): rename Message to Lock

jans-linux-setup/jans_setup/app_info.json, jans-linux-setup/jans_setup/setup_app/data/package_list.json, jans-linux-setup/jans_setup/setup_app/downloads.py, jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/utils/base.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/setup_app/utils/package_utils.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
closes #7214
- Removes MariaDB Support due to JSON indexing
- Install MySQL-8 Community Edition on SuSE
=> feat(jans-linux-setup): remove MariaDB support

jans-pycloudlib/jans/pycloudlib/lock/__init__.py, jans-pycloudlib/jans/pycloudlib/lock/couchbase_lock.py, jans-pycloudlib/jans/pycloudlib/lock/ldap_lock.py, jans-pycloudlib/jans/pycloudlib/lock/sql_lock.py, jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py, jans-pycloudlib/jans/pycloudlib/persistence/sql.py, jans-pycloudlib/jans/pycloudlib/utils.py, jans-pycloudlib/setup.py, jans-pycloudlib/tests/test_utils.py
=> refactor(jans-pycloudlib): rename CN_LOCK env vars to avoid conflict with jans-lock

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/par/ws/rs/ParRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/action/RegisterCreateAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/stat/StatWS.java
chore(jans-auth-server): do not log WebApplicationException as error
closes #7285
=> chore(jans-auth-server): do not log WebApplicationException as error #7285

jans-lock/server/src/main/resources/log4j2.xml, jans-lock/service/src/main/resources/log4j2-lock.xml
=> chore: avoid duplicy in logging when jans-lock is part of jans-auth-server

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py
=> fix(jans-cli-tui): save auth server logging config

jans-linux-setup/jans_setup/setup_app/utils/printVersion.py
closes #7451
With this fix:
```
Title: Jans authentication server
Version: 1.0.22-SNAPSHOT
Builddate: 2024-01-18 18:59:18
Build: 39b609640aa290f7607089950ac3525ab09e6d1f
Title: SCIM API Server
Version: 1.0.22-SNAPSHOT
Builddate: 2023-12-18 12:08:48
Build: 07e078bb4457800296ba74f3cadf70a639f39c79
Title: jans-config-api-server
Version: 1.0.22-SNAPSHOT
Builddate: 2024-01-18 20:31:16
Build: 39b609640aa290f7607089950ac3525ab09e6d1f
root@myjans:/opt/jans# /opt/jans/printVersion.py
Title: Jans authentication server
Version: 1.0.22-SNAPSHOT
Builddate: 2024-01-18 18:59:18
Build: 39b609640aa290f7607089950ac3525ab09e6d1f
Title: SCIM API Server
Version: 1.0.22-SNAPSHOT
Builddate: 2023-12-18 12:08:48
Build: 07e078bb4457800296ba74f3cadf70a639f39c79
Title: jans-config-api-server
Version: 1.0.22-SNAPSHOT …
```
=> fix(jans-linux-setup): modification date of MANIFEST.MF in war file is build date

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): Jans KC install option

jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py, jans-cli-tui/cli_tui/plugins/100_saml/main.py
closes #7590
Also **idpMetadataFilePattern** is removed form SAML configuration (ref: https://github.com/JanssenProject/jans/pull/7569/files )
=> feat(jans-cli-tui): custom validation for attrbiutes

demos/jans-tarp/src/options/oidcClientDetails.tsx
=> fix: for authorization with multiple redirects the one with redirect_url should be considered #7646

docker-jans-auth-server/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/upgrade.py, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py
=> fix(docker-jans): add missing dynamic config

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
=> fix(jans-linux-setup): remove server word from casa in installer prompt

docs/admin/auth-server/endpoints/authorization-challenge.md, docs/admin/developer/scripts/authorization-challenge.md, docs/script-catalog/authorization_challenge/AuthorizationChallenge.java, docs/script-catalog/authorization_challenge/multi_step/AuthorizationChallenge.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/EndSessionBackchannelRestServerTest.java, jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): authz challenge should not require client_id and acr_values if valid device_session is provided 
closes #6867
=> feat(jans-auth-server): authz challenge should not require client_id and acr_values if valid device_session is provided #6867

.github/workflows/docker_build_image.yml
Enhances docker build speed
closes #7739
=> ci(dockerbuild): enhance speed of workflow

jans-cli-tui/cli_tui/cli/config_cli.py
closes #7716
Write operations **post**, **put**, **patch** were written to file `cli_cmd.log` in logging directory. Only **delete** operation was added in this PR.
=> feat(jans-cli-tui): log command for delete operation

jans-orm/ldap/src/main/java/io/jans/orm/ldap/impl/LdapFilterConverter.java
=> feat: ldap ORM shoould ignore lower case statement in filters #7749

jans-fido2/server/src/main/java/io/jans/fido2/service/persist/AuthenticationPersistenceService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/persist/RegistrationPersistenceService.java, jans-link/model/src/main/java/io/jans/link/model/Fido2Entry.java, jans-orm/model/src/main/java/io/jans/orm/model/fido2/Fido2Entry.java, jans-scim/service/src/main/java/io/jans/scim/model/fido2/Fido2Entry.java
=> fix: jansCodeChallengeHash should be defiend as Integer

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AttributesResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AttributeService.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ConfigurationService.java
=> feat(config-api): user management search enhancement

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/RegistrationRestWebServiceHttpTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/DiscoveryService.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/DiscoveryServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/servlet/OpenIdConfigurationTest.java, jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): rely on end_session feature flag value when return discovery response 
closes #5255
=> feat(jans-auth-server): rely on end_session feature flag value when return discovery response #5255

.github/workflows/docker_build_image.yml
=> ci(dockerbuild): docker build speed

jans-pycloudlib/jans/pycloudlib/secret/vault_secret.py, jans-pycloudlib/tests/conftest.py, jans-pycloudlib/tests/test_secret.py
=> feat(jans-pycloudlib): allow configurable Vault KV and AppRole paths

jans-cli-tui/cli_tui/utils/static.py
=> fix(jans-cli-tui): documentation link

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/MainSettings.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/UIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/OAuth2ConfigResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/AUIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java
=> feat: add SESSION_TIMEOUT_IN_MINUTES to admin-ui configuration in persistence #7792

jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
fix(jans-auth-server): introspection endpoint must return 401 when ORM throws "Failed to find entry" exception 
closes #7772
=> fix(jans-auth-server): introspection endpoint must return 401 when ORM throws "Failed to find entry" exception #7772

docs/admin/planning/persistence.md
=> docs(deployment): note default DB for PROD and VM

jans-bom/pom.xml
upgrade org.postgresql:postgresql from 42.6.0 to 42.6.1 
closes #7924
=> chore(jans-bom): upgrade org.postgresql:postgresql from 42.6.0 to 42.6.1 #7924

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/rest/TrustRelationshipResource.java, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/util/Constants.java, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java
1. Issue#7976: SAML TR update file name fix
2. Issue#7913: user mgmt validation for custom attributes
3. Issue#7803: user mgmt added search filter for givenName, middleName, nickName and sn
closes #7976 7913 7803
=> fix(config-api): SAML TR fix for filename and  user mgmt enhancement for search and custom attribute validation 

jans-config-api/plugins/docs/kc-saml-plugin-swagger.yaml, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/rest/TrustRelationshipResource.java, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/service/SamlIdpService.java, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/service/SamlService.java
Minor enhancements to the saml api to fetch the file metadata
=> feat(jans-config-api): enhancements to saml api #7362

jans-auth-server/server-fips/pom.xml, jans-config-api/server-fips/pom.xml
chore(jans-auth-server): fix typo build-oxauth-fips-war 
closes #8036
=> chore(jans-auth-server): fix typo build-oxauth-fips-war #8036

jans-keycloak-link/pom.xml, jans-link/pom.xml, jans-lock/pom.xml
closes #8053 
- [] Static code analysis has been run locally and issues have been fixed
=> fix(javadoc): fix javadoc generation due to `doclint` warnings

jans-cli-tui/cli_tui/plugins/040_config_api/main.py
=> fix(jans-cli-tui): if adminui permissons added do not display error

docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/requirements.txt, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-auth-server/scripts/entrypoint.sh, docker-jans-casa/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-config-api/scripts/upgrade.py, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/requirements.txt, docker-jans-link/requirements.txt, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/requirements.txt, docker-jans-scim/requirements.txt
=> chore(deps): sync image assets and dependencies

jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py
closes #8040
closes #8095
closes #8094
=> fix(jans-cli-tui): user management fixes

docs/admin/developer/interception-scripts.md, docs/admin/developer/scripts/create-user.md, docs/admin/developer/scripts/health-check.md, docs/script-catalog/health_check/HealthCheck.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalCreateUserService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalHealthCheckService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/controller/HealthCheckController.java, jans-core/script/src/main/java/io/jans/model/custom/script/CustomScriptType.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/health/DummyHealthCheck.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/health/HealthCheckType.java
feat(jans-auth-server): new HealthCheck custom sсript
closes #7991
=> feat(jans-auth-server): new HealthCheck custom sсript

jans-auth-server/common/src/main/java/io/jans/as/common/service/common/fido2/RegistrationPersistenceService.java
-  The `attachDeviceRegistrationToUser` method has been extended to support a new `deviceName` field.
closes #8172
=> fix(jans-auth-server): extend attachDeviceRegistrationToUser method

docs/casa/plugins/accts-linking/account-linking-index.md, jans-auth-server/agama/inboundID/pom.xml, jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/ConfigProcessor.java, jans-casa/plugins/acct-linking/extras/agama/lib/io/jans/casa/acctlinking/UidUtils.java
=> fix(jans-casa): wrong endpoint to retrieve userinfo in accts linking plugin

jans-config-api/common/src/main/java/io/jans/configapi/util/ApiAccessConstants.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/fido2-plugin-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AssetService.java, jans-config-api/server/src/main/resources/config-api-rs-protect.json
Fixed scope name and jansAlias fetch issue on PGSQL
closes #8198
=> fix(config-api): asset management fetch issue

docs/admin/auth-server/oauth-features/README.md, docs/admin/auth-server/openid-features/acrs.md, jans-auth-server/model/src/main/java/io/jans/as/model/authorize/AuthorizeErrorResponseType.java, jans-auth-server/server/conf/jans-errors.json, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidatorTest.java, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-errors.json
feat(jans-auth-server): support unmet_authentication_requirements error code 
closes #7900
=> feat(jans-auth-server): support unmet_authentication_requirements error code #7900

docs/script-catalog/person_authentication/otp-external-authenticator/OtpExternalAuthenticator.py, jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/controller/HealthCheckController.java, jans-core/script/src/main/java/io/jans/service/custom/script/CustomScriptManager.java
=> feat: healt-check should check script manager initialization status

.gitignore, jans-casa/plugins/bioid/README.md, jans-casa/pom.xml, mkdocs.yml
closes #8230 
Adds bioid to the casa maven builds. Also adds the BioID Readme to the navigation menu, and adds `.factorypath` to gitignore for Eclipse JDTLS and its extended LSPs. These language servers create `.factorypath` files during directory traversal.
N/A
=> chore(jans-casa): bioid tasks

jans-cli-tui/cli_tui/plugins/120_lock/main.py
=> feat(jans-cli-tui): missing Lock Configuration parameters

docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-saml/scripts/bootstrap.py, docker-jans-saml/scripts/configure_kc.py, docker-jans-saml/templates/jans-saml/clients.ldif, docker-jans-scim/Dockerfile
=> chore(docker): sync assets and kc setup

docs/admin/config-guide/jans-authorization-server-config.md, docs/admin/reference/json/properties/janssenauthserver-properties.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/RegisterServiceTest.java, jans-cli-tui/cli_tui/plugins/120_lock/main.py, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/ClientService.java, jans-config-api/server/src/test/resources/feature/config/properties/dynamic/registration/registration.feature, jans-config-api/server/src/test/resources/feature/config/properties/dynamic/registration/registration.json, jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json, jans-linux-setup/jans_setup/templates/test/docs/oxauth-config-update.md
Reviewed and renamed dynamicGrantTypeDefault->grantTypesSupportedByDynamicRegistration with tests 
closes #8089
=> feat(jans-auth-server): reviewed and renamed dynamicGrantTypeDefault->grantTypesSupportedByDynamicRegistration with tests #8089

jans-auth-server/server/pom.xml, jans-bom/pom.xml, jans-config-api/pom.xml, jans-config-api/server/pom.xml, jans-fido2/server/pom.xml
=> feat: disable jdk15on dependecies

jans-cli-tui/cli_tui/plugins/120_lock/main.py
=> fix(jans-cli-tui): LOCK OPA Configuration

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/model/user/CustomUser.java, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/rest/UserResource.java, jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java, jans-config-api/pom.xml, jans-config-api/server/pom.xml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AssetResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AssetService.java, jans-config-api/shared/src/main/java/io/jans/configapi/core/rest/BaseResource.java
User creation was failing with error as duplicate `jansStatus` column.  It seems that a `status` attribute was added at base level which was earlier at customAttribute level causing the error. 
closes #8258
=> fix(config-api): user mgt error for duplicate jansStatus issue

docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/upgrade.py, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile
=> chore(docker): sync assets and config

docker-jans-config-api/scripts/upgrade.py
=> fix(docker-jans-config-api): handle NULL jansScope.creatorAttrs during upgrade

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
As explained in #7782 , if agama project has configuration, there will be **View Configuration** button in Details popup.
Closes #8352,
=> feat(jans-cli-tui): display agama project configuration

jans-pycloudlib/jans/pycloudlib/persistence/spanner.py, jans-pycloudlib/jans/pycloudlib/persistence/sql.py
=> feat(jans-pycloudlib): handle rdbm_json_column in schema definitions

jans-auth-server/agama/engine/profiles/default/config-agama-test.properties, jans-auth-server/agama/engine/src/test/java/io/jans/agama/test/BaseTest.java, jans-auth-server/agama/engine/src/test/resources/testng.properties, jans-linux-setup/jans_setup/templates/test/agama/config-agama-test.properties
=> fix: update test cases

jans-auth-server/server/src/main/java/io/jans/as/server/service/AcrService.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/AcrServiceTest.java
feat(jans-auth): removed extra info from `acr` claim in `id_token` when it's an agama flow
closes #8348
=> feat(jans-auth): removed extra info from `acr` claim in `id_token` when it's an agama flow

jans-auth-server/client/pom.xml, jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/page/AbstractPage.java, jans-auth-server/client/src/test/java/io/jans/as/client/page/SelectPage.java, jans-bom/pom.xml
=> feat(jans-auth): update htmlunit driver to htmlunit3

jans-casa/app/pom.xml
=> fix: remove bouncy castle exclusion

docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, docker-jans-persistence-loader/scripts/upgrade.py
=> fix(docker-jans-persistence-loader): handle missing data type for overriden column

jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthenticationService.java
=> feat(jans-auth): add utility methods for external authenticators

jans-auth-server/model/src/main/java/io/jans/as/model/jwt/JwtType.java, jans-auth-server/model/src/test/java/io/jans/as/model/jwt/JwtTypeTest.java
feat(jans-auth-server): uppercased typ=JWT
closes #8419
=> feat(jans-auth-server): uppercased typ=JWT

jans-linux-setup/jans_setup/install.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/base.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py, jans-linux-setup/jans_setup/static/system/systemd/kc-scheduler.service, jans-linux-setup/jans_setup/static/system/systemd/kc-scheduler.sh, jans-linux-setup/jans_setup/templates/jans-saml/kc-scheduler/kc-scheduler-cron, jans-linux-setup/jans_setup/templates/jans-saml/kc-scheduler/kc-scheduler.sh, jans-linux-setup/jans_setup/templates/jans-saml/kc_jans_api/jans.api-user.json
=> feat(jans-linux-setup): keycloak scheduler service

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py
=> chore(docker-jans-persistence-loader): added password grantType to grantTypesSupportedByDynamicRegistration

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): Transaction Token properties to TUI client panel

jans-casa/extras/casa-external_otp.py
=> fix: update how external uids are retrieved

jans-casa/extras/casa-external_fido2.py, jans-casa/extras/casa-external_super_gluu.py
=> fix: update authenticate method for step 1

docker-jans-all-in-one/.hadolint.yaml, docker-jans-all-in-one/Dockerfile
=> fix(cloud-native): resolve missing pkg_resources module

docs/requirements.txt, mkdocs.yml
closes #8543 
Since the transitive dependencies were having trouble with hash verification, I have added them separately with a corresponding hash that can be verified.
=> fix(docs): install `mkdocs-include-markdown-plugin` along with dependencies

jans-cli-tui/cli_tui/plugins/100_saml/edit_identity_provider_dialog.py
=> fix(jans-cli-tui): replace checkbox with drowdown for saml-idp metadata type

jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
https://github.com/JanssenProject/jans/issues/8600
Closes #8610,
=> feat(orm): store json values without escaping them

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TxTokenService.java
fix(jans-auth-server): tx token replace failing with 500 
```
POST /jans-auth/restv1/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&audience=http%3A%2F%2Ftrusted2.com&subject_token=eyJraWQiOiJjb25uZWN0XzViODA2OWM3LWM5MDQtNDM4Mi1iNDNkLWVlNWJmMzBhNjQwYV9zaWdfcnMyNTYiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJyY3R4Ijp7InJlcV9pcCI6IjY5LjE1MS43Mi4xMjMifSwiYXVkIjpbIjgzYmM2NWYyLWIxNTUtNGQxNS1iODBkLWFiMWY0ZDlhMjQwZCIsImh0dHA6Ly90cnVzdGVkLmNvbSJdLCJzdWIiOiIiLCJwdXJwIjoidHhuX3Rva2VuIiwiaXNzIjoiaHR0cHM6Ly9qZW5raW5zLWJ1aWxkLmphbnMuaW8iLCJhemQiOnsiY2xpZW50X2lkIjoiODNiYzY1ZjItYjE1NS00ZDE1LWI4MGQtYWIxZjRkOWEyNDBkIn0sInR4biI6ImZiNzg2OWY5LTE1ZjgtNDhjNS05OWE0LWI3ZjQzOGUxYjJjNCIsImV4cCI6MTcxNzE0NjE0NiwiaWF0IjoxNzE3MTQ1OTY2fQ.he …
```
=> fix(jans-auth-server): tx token replace failing with 500 #8623

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): file browser not re-open in asset mgt

jans-auth-server/server/src/test/java/io/jans/as/server/service/external/ExternalAuthenticationServiceTest.java
test(jans-auth-server): ExternalAuthenticationServiceTest test failure 
closes #8655
=> test(jans-auth-server): ExternalAuthenticationServiceTest test failure #8655

docs/agama/language-reference.md, jans-casa/extras/casa-external_super_gluu.py
=> docs: update looping section of lang reference

jans-linux-setup/jans_setup/templates/jans-lock/dynamic-conf.json, jans-lock/lock-master/model/src/main/java/io/jans/lock/model/config/AppConfiguration.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/util/ResteasyInitializer.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/util/ServerUtil.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/ConfigurationRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/audit/AuditRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/audit/AuditRestWebServiceImpl.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/config/ConfigRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/config/ConfigRestWebServiceImpl.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/sse/SseRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/sse/SseRestWebServiceImpl.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/sse/TokenListRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/sse/TokenSseBroadcater.java
=> Lock Endpoint Scaffolding

jans-casa/app/src/main/resources/labels/user.properties
https://github.com/JanssenProject/jans/pull/8676
=> feat(jans-casa): replace Touch Id with PassKey

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/templates/apache/https_jans.conf, jans-linux-setup/jans_setup/templates/jans-lock/dynamic-conf.json, jans-linux-setup/jans_setup/templates/jetty/jans-auth
=> feat(jans-linux-setup): lock metadata well-known endpoint

jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/config/ConfigRestWebService.java, jans-lock/lock-master/service/src/main/java/io/jans/lock/service/ws/rs/config/ConfigRestWebServiceImpl.java
=> feat(jans-auth): fix schema endpoint

jans-auth-server/server/src/main/java/io/jans/as/server/auth/Authenticator.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AcrService.java
fix(jans-auth-server): agama_flow acr in id_token does not correspond to acr in request #8692
closes #8692
=> fix(jans-auth-server): agama_flow acr in id_token does not correspond to acr in request #8692

agama/transpiler/src/main/java/io/jans/agama/dsl/Transpiler.java
=> fix: reduce Freemarker's "incompatible improvements version"

docs/admin/config-guide/cache-configuration.md
=> fix(docs): update content of cache configuration documentation

docs/admin/scim/config.md, docs/admin/usermgmt/usermgmt-scim.md, jans-linux-setup/jans_setup/templates/jans-scim/dynamic-conf.json, jans-scim/model/src/main/java/io/jans/scim/model/conf/AppConfiguration.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/Scim2UserService.java, jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/UserWebService.java
=> feat: apply password validation

jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/static/scripts/jans, jans-linux-setup/jans_setup/templates/system_profile_systemd
closes #8697
In this PR a command `jans` is located under directory `/opt/jans/bin` and this directory is added to `$PATH` so that command is available without full path. To see help,
```
usage: jans [-h] {version,cli,tui,logs,status,start,stop,restart,health,info} ...
A top-level wrapper script for Janssen
positional arguments:
{version,cli,tui,logs,status,start,stop,restart,health,info}
version             shows version of currently installed Janssen Server
cli                 invokes jans-cli
tui                 invokes jans text based user interface
logs                Shows the log file paths for various Janssen Server modules
status              Show status of Janssen Server module services
start               Starts services for Janssen Server ( -service=<service-name> if you want …
```
=> feat(jans-linux-setup): top level wrapper command jans

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli): --schema option renamed to --schema-sample

docs/casa/index.md, jans-casa/plugins/acct-linking/extras/agama/lib/io/jans/casa/acctlinking/UidUtils.java
=> fix: avoid user provisioning when user already exists

jans-casa/plugins/acct-linking/extras/Casa.py, jans-casa/plugins/acct-linking/pom.xml, jans-casa/plugins/acct-linking/src/main/java/io/jans/casa/plugins/acctlinking/vm/SiteRedirectVM.java
=> chore: remove usage of agama_flow param in plugin

docs/admin/config-guide/jans-authorization-server-config.md, docs/admin/developer/agama/quick-start-using-agama-lab.md
=> docs: remove remaining mentions of agama_flow param

jans-lock/lock-master.yaml
=> docs(jans-lock): add swagger

jans-linux-setup/jans_setup/templates/jans-pgsql.properties
=> feat(jans-linux-setup): disable time zone for pgsql

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/templates/jans-pgsql.properties, docker-jans-casa/Dockerfile, docker-jans-casa/templates/jans-pgsql.properties, docker-jans-config-api/Dockerfile, docker-jans-config-api/templates/jans-pgsql.properties, docker-jans-fido2/Dockerfile, docker-jans-fido2/templates/jans-pgsql.properties, docker-jans-keycloak-link/Dockerfile, docker-jans-keycloak-link/templates/jans-pgsql.properties, docker-jans-link/Dockerfile, docker-jans-link/templates/jans-pgsql.properties, docker-jans-scim/Dockerfile, docker-jans-scim/templates/jans-pgsql.properties
=> feat(cloud-native): disable timezone for pgsql

jans-scim/model/src/main/java/io/jans/scim/model/conf/AppConfiguration.java, jans-scim/server/src/main/java/io/jans/scim/service/init/AppInitializer.java
=> feat: add flag to disable logger timer

jans-cli-tui/cli_tui/cli_style.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py, jans-cli-tui/cli_tui/utils/static.py, jans-cli-tui/cli_tui/utils/utils.py, jans-cli-tui/cli_tui/wui_components/jans_date_picker.py
closes #8779
@ossdhaval Please update Date Time picker navigation
To go into edit mode, press **Enter** on date-time widget
**key:tab** navigates among date-time widgets
Navigation on days:
**key: left-arrow** prvious day
**key: right-arrow** next day
**key: up-arrow** goes a week back
**key: down-arrow** goes a week forward
Navigation in month/year/time area:
**key: up-arrow** increases value by one
**key: down-arrow** decreases value by one
After you adjust date-time, press **Enter** button again to set date-time
To unset date/time, press **Delete** button when it is not in edit mode:
After pressing **Delete** button:
=> fix(jans-cli-tui): re-write date-time picker

docs/admin/reference/openapi.md
=> docs(jans-lock): add swagger reference

docs/admin/config-guide/default-authentication-method-config.md
=> docs(default-auth): add schema format and example

docs/admin/config-guide/ldap-configuration.md
=> docs(ldap-conf): LDAP config doc updates

docs/admin/config-guide/logging-configuration.md
=> docs(logging): add schema format and example

jans-cli-tui/cli_tui/plugins/030_scim/main.py
=> fix(jans-cli-tui): scim configuration skipDefinedPasswordValidation

jans-core/service/src/main/java/io/jans/service/logger/LoggerService.java
https://github.com/JanssenProject/jans/issues/8799
Closes #8803,
=> feat(jans-core): do log4j reconfigure only on log level change

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/templates/jans-saml/keycloak.conf
=> fix(jans-linux-setup): dummy values for KC db options

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/token/StatusListHttpTest.java
test(jans-auth-server): fixed StatusListHttpTest failure 
closes #8823
=> test(jans-auth-server): fixed StatusListHttpTest failure #8823

jans-auth-server/server/src/main/java/io/jans/as/server/service/stat/StatService.java
feat(jans-auth-server): stat RDN must have date to be unique under RDBMS 
closes #8825
=> feat(jans-auth-server): stat RDN must have date to be unique under RDBMS #8825

jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/token/StatusListHttpTest.java, jans-linux-setup/jans_setup/setup_app/test_data_loader.py
feat(jans-linux-setup): status list must be enabled during tests #8838
closes #8838
=> feat(jans-linux-setup): status list must be enabled during tests #8838

.github/pull_request_template.md, .github/workflows/documenation_check.yml
=> ci: add docs check to make sure every PR is doc checked

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/templates/jans-saml/jans-saml-config.json, jans-linux-setup/jans_setup/templates/jans-saml/keycloak.conf
closes #8840\nPlease check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the below checklist is not selected.\n- [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**
=> fix(jans-linux-setup): typo

.github/workflows/docs.yml, .github/workflows/documenation_check.yml
=> ci: fix catching the docs commit

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> feat(jans-linux-setup): KC disable verify_profile required action

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/templates/jans-saml/kc_jans_api/jans.userstorage-provider-component.json
=> fix(jans-linux-setup):  KC setup - providerId UserStorageProvider

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> fix(jans-linux-setup): disable kc verify_profile

.github/workflows/test_docker_linux_installer.yml, automation/startjanssenmonolithdemo.sh
=> ci: fix override on running tests and registered FQDN

docker-jans-monolith/jans-ldap-compose.yml, docker-jans-monolith/jans-mysql-compose.yml, docker-jans-monolith/jans-postgres-compose.yml, docker-jans-monolith/scripts/entrypoint.sh
=> ci(docker-jans-monolith): allow fqdn override

jans-auth-server/server/src/main/java/io/jans/as/server/service/CleanerTimer.java
fix(jans-auth-server): clean up jansDeviceSess entries after expiration 
closes #8704
=> fix(jans-auth-server): clean up jansDeviceSess entries after expiration #8704

jans-linux-setup/jans_setup/install.py
closes #8905
We don't have kc-scheduler.service, instead we moved to crontab
=> fix(jans-linux-setup): kc-scheduler.service upon uninstall

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
closes #8985
@moabu setup can't install spanner emulator. It is not possible to automate spanner emulator installetion. So you should install spanner emulator manually and add these to your `setup.properties` file:
```
rdbm_type=spanner
rdbm_install_type=2
spanner_emulator_host=myhost
spanner_project=jans-project
spanner_instance=jans-instance
spanner_database=jansdb
```
If you use defaults for the last three items, you don't need to add them.
=> fix(jans-linux-setup): install with setup.properties

docs/admin/lock/lock-auth-server-config.md, docs/admin/lock/lock-client-config.md, docs/admin/lock/lock-installation.md, docs/admin/lock/lock-opa.md, docs/admin/lock/lock-pdp-plugin.md, mkdocs.yml
Add new lock documentation files with placeholder content.
Closes #9018,
=> docs(lock): add missing files with placeholder content

docs/admin/lock/cedarling.md
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Michael Schwartz
https://github.com/JanssenProject/jans/issues/8831
Just edits for readability
=> docs: Cedarling Overview edits for readability.

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/templates/jans-saml/clients.json
=> fix(jans-linux-setup): client kc_saml_openid is trusted

jans-linux-setup/jans_setup/templates/jans-saml/clients.json
=> fix(jans-linux-setup): remove saml_scim_client

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): asset upload

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> fix(jans-linux-setup): set size of acr in jansToken is 1024

jans-linux-setup/jans_setup/schema/jans_schema.json
The changeset removes trailing whitespace from `eventType ` column name.
closes #9065 
=> fix(jans-linux-setup): remove trailing whitespace on eventType column

jans-linux-setup/jans_setup/templates/apache/https_jans.conf
=> fix(jans-linux-setup): apache config for jans-lock wellknown endpoint

jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java
fix(jans-auth-server): introspection endpoint returns error for valid basic client authentication and invalid token 
closes #9093
=> fix(jans-auth-server): introspection endpoint returns error for valid basic client authentication and invalid token #9093

mkdocs.yml
doc(jans-auth-server): client authn script is missed in navigation 
closes #9140
=> doc(jans-auth-server): client authn script is missed in navigation #9140

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): focus to container after deleting asset

charts/janssen-all-in-one/README.md, charts/janssen-all-in-one/templates/nginx-ingress.yaml, charts/janssen-all-in-one/values.yaml, charts/janssen/README.md, charts/janssen/charts/auth-server/templates/auth-server-virtual-services.yaml, charts/janssen/charts/nginx-ingress/templates/ingress.yaml, charts/janssen/values.yaml, docker-jans-all-in-one/Dockerfile, docker-jans-all-in-one/app/templates/nginx/jans-auth-location.conf, docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/upgrade.py, docker-jans-persistence-loader/Dockerfile, docs/admin/lock/cedarling.md, docs/admin/reference/kubernetes/helm-chart.md, jans-lock/lock-server.yaml
=> feat(cloud-native): change lock-master-configuration to lock-server-configuration

demos/benchmarking/docker-jans-loadtesting-jmeter/Dockerfile, docs/admin/developer/agama/flows-navigation-ui.md, jans-auth-server/agama/engine/pom.xml, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/page/Page.java, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/service/MethodInvoker.java
=> feat: allow access to values stored in cache from templates

jans-auth-server/server/src/main/java/io/jans/as/server/filter/HeadersFilter.java
fix(jans-auth-server): missed chain call in header filter
closes #9204
=> fix(jans-auth-server): missed chain call in header filter

jans-core/document-store/src/main/java/io/jans/service/document/store/service/DBDocumentService.java
=> feat(jans-config-api): update swagger api

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): change according to new asset Document schema

demos/jans-tarp/src/options/registerClient.tsx, demos/jans-tarp/src/options/userDetails.tsx
=> feat: changing format of access token and user-info to JWT

demos/jans-tarp/src/static/chrome/manifest.json
=> fix: remove unrecognized manifest key #9301

docs/admin/config-guide/fido2-config/janssen-fido2-configuration.md, docs/admin/fido/config.md, docs/admin/fido/logs.md, docs/admin/reference/json/properties/fido2-properties.md, jans-config-api/plugins/docs/fido2-plugin-swagger.yaml, jans-config-api/plugins/fido2-plugin/src/test/resources/feature/fido2/dynamiconf.json, jans-config-api/plugins/fido2-plugin/src/test/resources/feature/fido2/fido2.json, jans-config-api/plugins/fido2-plugin/src/test/resources/feature/fido2/ref_dynami_conf.json, jans-fido2/model/src/main/java/io/jans/fido2/model/conf/Fido2Configuration.java, jans-fido2/model/src/main/java/io/jans/fido2/model/conf/RequestedParty.java, jans-fido2/server/src/main/java/io/jans/fido2/service/mds/FetchMdsProviderService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java, jans-linux-setup/jans_setup/templates/jans-fido2/dynamic-conf.json
https://github.com/JanssenProject/jans/issues/9111
Changes to refactor requestedParties
=> feat(jans-fido): changes to refactor requestedParties #9111

jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py
=> fix(jans-cli-tui): authn page for non-ldap backend

jans-core/pom.xml
=> feat(jans-core): fix javadocs generation

jans-scim/pom.xml
=> feat(jans-scim): fix javadocs generation

jans-config-api/common/src/main/java/io/jans/configapi/util/ApiConstants.java, jans-config-api/pom.xml
=> feat(jans-config-api): fix javadocs generation

.github/workflows/build-packages.yml
=> ci: forces download each time on packaging

jans-config-api/plugins/docs/lock-plugin-swagger.yaml, jans-linux-setup/jans_setup/app_info.json
=> feat(jans-core): update OpeDJ version

docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
=> chore: use pythonic style in Agama bridge

jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthenticationService.java
=> feat(jans-auth): add warn to check if server can't set authenticated

jans-linux-setup/jans_setup/setup_app/messages.py
=> chore(jans-linux-setup): restart jans services in post-setup

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AssetResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AssetService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/manager/DocumentStoreManager.java, jans-core/document-store/src/main/java/io/jans/service/document/store/model/Document.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DBDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DocumentStore.java, jans-linux-setup/jans_setup/schema/jans_schema.json
=> feat(jans-core): store file_name and file_path in separate columns 

jans-cli-tui/cli_tui/plugins/140_config_api/main.py, jans-cli-tui/cli_tui/utils/background_tasks.py
=> fix(jans-cli-tui): re-order feed and background task messages

docs/admin/reference/database/mysql-ops.md
=> docs: fix mysql-ops command order

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, mkdocs.yml
=> fix(jans-cli-tui): hide Messages configuration page

docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
=> fix: update wrong clause

demos/jans-tarp/src/options/authFlowInputs.tsx, demos/jans-tarp/src/options/registerClient.tsx
=> feat: allow specifying scopes during execution of authz url

demos/jans-tarp/src/options/options.css
=> fix(jans-trap): Next Month Arrow is Hidden in calender of client expiry date input while register new OIDC client

docs/admin/install/setup.md, jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_link.py, jans-linux-setup/jans_setup/setup_app/setup_options.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): jans ldap link server

docs/admin/config-guide/scim-config/user-config.md, jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): scim patch operation

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): duplicate schema names in info

jans-config-api/plugins/lock-plugin/src/main/java/io/jans/configapi/plugin/lock/model/stat/TelemetryEntry.java
Signed-off-by: Yuriy Movchan <Yuriy.Movchan@gmail.com>
closes #9487
=> feat(jans-conf-api): evaluationTimeNs should be integer

jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix(jans-fido): correct display name for fido interception script #9485

docs/admin/auth-server/endpoints/end-session.md, docs/admin/config-guide/auth-server-config/jans-authorization-server-config.md, docs/admin/reference/json/properties/janssenauthserver-properties.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImplTest.java, jans-linux-setup/jans_setup/setup_app/test_data_loader.py
fix(jans-auth-server): typo in forceIdTokenHintPrecense, precense -> presence 
closes #9559
=> fix(jans-auth-server): typo in forceIdTokenHintPrecense, precense -> presence #9559

jans-casa/app/src/main/resources/labels/user.properties, jans-casa/app/src/main/webapp/user/fido2-detail.zul
=> chore: update labels in fido2 page

jans-orm/sql/pom.xml
=> feat(jans-orm): use protobuf-java defined in upstream dependecies

jans-linux-setup/jans_setup/setup_app/utils/base.py
=> fix(jans-linux-setup): import ruamel in fucntion read_yaml_file()

docs/janssen-server/developer/agama/engine-bridge-config.md
=> docs: fix wrong Agama engine paths

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): mysql backend with setup.properties

jans-linux-setup/jans_setup/setup_app/utils/package_utils.py
closes #9743
There is a recent MySQL built with `libc.so.6(GLIBC_2.38)(64bit)` and SUSE repositories does not provide GLIBC_2.38:
```
Problem: 1: nothing provides 'libc.so.6(GLIBC_2.38)(64bit)' needed by the to be installed mysql-community-server-8.0.40-1.sl15.x86_64
Solution 1: do not install mysql-community-server-8.0.40-1.sl15.x86_64
Solution 2: break mysql-community-server-8.0.40-1.sl15.x86_64 by ignoring some of its dependencies
```
To fix this issue, mysql version is restricted to `mysql-community-server-8.0.39`
=> fix(jans-linux-setup): suse mysql version 8.0.39

docs/cedarling/cedarling-policy-store.md
=> docs: adding Trusted Issuer Schema format in docs #9784

docs/janssen-server/config-guide/auth-server-config/authentication-method-config.md, jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py
=> fix(jans-cli-tui): do not hide ldap servers in authn when database is not ldap

jans-core/document-store/src/main/java/io/jans/service/document/store/manager/DocumentStoreManager.java
=> fix(jans-core): document store manager should use filePath

docs/script-catalog/person_authentication/fido2-external-authenticator/Fido2ExternalAuthenticator.py, jans-fido2/model/src/main/java/io/jans/fido2/model/attestation/AttestationErrorResponseType.java, jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AssertionService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AttestationService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/verifier/CommonVerifiers.java
=> Add origin parameter in Fido2ExternalAuthenticator script for attestation and assertion API calls #9248

jans-core/document-store/src/main/java/io/jans/service/document/store/manager/DocumentStoreManager.java
=> fix(jans-core): document store manager load filePath attribute

jans-cedarling/cedarling/Cargo.toml, jans-cedarling/cedarling/src/common/cedar_schema.rs, jans-cedarling/cedarling/src/common/mod.rs, jans-cedarling/cedarling/src/common/policy_store.rs, jans-cedarling/test_files/policy-store_blobby.json, jans-cedarling/test_files/policy-store_readable.json, jans-cedarling/test_files/policy-store_readable.yaml
There are two main goals this PR aims to achieve:
1) Extend the `policy-store_xxx.json` to allow for metadata for `cedar_schema` and `policy_content` fields.
2) Provide a proof of concept for a 100% human-readable test fixture, in yaml.
https://github.com/JanssenProject/jans/issues/9961
1) In `policy-store_xxx.json` files, allow for `cedar_schema` and `policy_content` fields to store human-readable values, rather than only the base64-encoded values that agama lab produces. To achieve this, the `policy-store_xxx.json` json for `cedar_schema` and `policy_content` is extended slightly with the following:
```
"policy_content": {
"encoding": "none",
"content_type": "cedar",
"body": "permit(...) when { ... };"
}
```
- `encoding` can be one of `none` or `base64`
- …
=> human-readable test fixtures

jans-pycloudlib/jans/pycloudlib/persistence/sql.py
=> feat(jans-pycloudlib): detect JSON data format

jans-linux-setup/jans_setup/setup_app/utils/progress.py
=> fix(jans-linux-setup): increase setup time-out

jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAuthorization.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/PairwiseIdentifier.java, jans-casa/plugins/client-authorizations/src/main/java/io/jans/casa/plugins/consent/model/ClientAuthorization.java, jans-linux-setup/jans_setup/schema/jans_schema.json
feat(jans-auth-server): used single-valued attribute for client id instead of multi-valued where it is needed (e.g. jansClntAuthz ) 
closes #10033
=> feat(jans-auth-server): used single-valued attribute for client id instead of multi-valued where it is needed (e.g. jansClntAuthz ) #10033

jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> fix(jans-orm): throw exception if table in DB is not exists

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): remove filePath when putting asset

docs/janssen-server/lock/lock-server.md
=> fix(jans-lock): fix broken link in lock docs

jans-cedarling/bindings/cedarling_python/README.md, jans-cedarling/bindings/cedarling_python/example.py
closes #10114 
Adds environment variable `CEDARLING_LOCAL_POLICY_STORE` for the python example. Not providing this variable will cause the script to print an error and exit.
N/A
=> feat(jans-cedarling): add env variable for python

jans-cedarling/bindings/cedarling_python/cedarling_python.pyi, jans-cedarling/bindings/cedarling_python/example.py, jans-cedarling/bindings/cedarling_python/print_documentation.py, jans-cedarling/bindings/cedarling_python/tests/test_authorize.py, jans-cedarling/bindings/cedarling_python/tests/test_logger.py, jans-cedarling/bindings/cedarling_python/tests/test_policy_store.py, jans-cedarling/cedarling/src/common/cedar_schema/mod.rs, jans-cedarling/cedarling/src/common/policy_store/test.rs, jans-cedarling/test_files/agama-store.yaml, jans-cedarling/test_files/agama-store_2.yaml, jans-cedarling/test_files/bootstrap_props.yaml, jans-cedarling/test_files/policy-store_ok.yaml, jans-cedarling/test_files/policy-store_ok_2.yaml, jans-cedarling/test_files/policy-store_ok_namespace_Jans2.yaml, jans-cedarling/test_files/policy-store_policy_err_broken_policy.yaml, jans-cedarling/test_files/policy-store_readable.yaml, jans-cedarling/test_files/policy-store_schema_err.yaml, jans-cedarling/test_files/policy-store_schema_err_cedar_mistake.yaml, jans-cedarling/test_files/policy-store_with_multiple_role_mappings_err.yaml, jans-cedarling/test_files/policy-store_with_trusted_issuers_ok.yaml, jans-cedarling/test_utils/src/lib.rs, jans-cedarling/test_utils/src/sort_json.rs
This PR adds the missing license headers in the Cedarling files.
target issue: #10323
closes: #10323
License headers were just added to the files. Most of the files are python files.
```py
#
```
=> chore(jans-cedarling): add missing license headers

jans-linux-setup/jans_setup/install.py
=> fix(jans-linux-setup): download from tags

docker-jans-all-in-one/app/bin/entrypoint.sh, docker-jans-auth-server/scripts/entrypoint.sh, docker-jans-casa/Dockerfile, docker-jans-casa/scripts/entrypoint.sh, docker-jans-config-api/scripts/entrypoint.sh, docker-jans-fido2/scripts/entrypoint.sh, docker-jans-keycloak-link/scripts/entrypoint.sh, docker-jans-link/scripts/entrypoint.sh, docker-jans-scim/scripts/entrypoint.sh
closes #10224
- use `curl` command to download `prometheus` java agent; this replaces `wget` command that may not work when running behind a proxy
- upgrade prometheus agent to v1.0.1 (the older version is vulnerable)
=> fix(cloud-native): applications are failing to start when prometheus metrics are enabled

jans-auth-server/agama/engine/pom.xml
=> feat(jans-agama): update htmlunit

docs/janssen-server/auth-server/endpoints/authorization-challenge.md, docs/janssen-server/auth-server/oauth-features/README.md, docs/script-catalog/authorization_challenge/AuthorizationChallenge.java, docs/script-catalog/authorization_challenge/authorization-challenge.md, jans-auth-server/common/src/main/java/io/jans/as/common/model/session/AuthorizationChallengeSessionAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/DpopService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeEndpoint.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeSessionService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AbstractAuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrantList.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidator.java, jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidatorTest.java, jans-core/service/src/main/java/io/jans/model/token/TokenAttributes.java
Update first party native authn implementation.
It must be updated in backwards compatibilty way because it is already in use.
https://datatracker.ietf.org/doc/draft-parecki-oauth-first-party-apps/02/
closes #10380
=> feat(jans-auth-server): updated first party native authn implementation ( in backwards compatibility way) #10380

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/sql_setup.py
=> fix(docker-jans-persistence-loader): exclude external tables when creating indexes

automation/startjanssendemo.sh, docs/includes/cn-system-requirements.md
=> fix(startjanssendemo): remove unneeded code and packages installation

docs/cedarling/cedarling-authz.md, jans-cedarling/bindings/cedarling_python/PYTHON_TYPES.md, jans-cedarling/bindings/cedarling_python/cedarling_python.pyi, jans-cedarling/bindings/cedarling_python/example.py, jans-cedarling/bindings/cedarling_python/pyproject.toml, jans-cedarling/bindings/cedarling_python/src/authorize/mod.rs, jans-cedarling/bindings/cedarling_python/src/authorize/request.rs, jans-cedarling/bindings/cedarling_python/tests/test_authorize.py, jans-cedarling/cedarling/examples/authorize_with_jwt_validation.rs, jans-cedarling/cedarling/examples/authorize_without_jwt_validation.rs, jans-cedarling/cedarling/src/authz/entities/create.rs, jans-cedarling/cedarling/src/authz/entities/workload.rs, jans-cedarling/cedarling/src/authz/mod.rs, jans-cedarling/cedarling/src/authz/request.rs, jans-cedarling/cedarling/src/lib.rs, jans-cedarling/cedarling/src/tests/cases_authorize_different_principals.rs, jans-cedarling/cedarling/src/tests/cases_authorize_namespace_jans2.rs, jans-cedarling/cedarling/src/tests/cases_authorize_without_check_jwt.rs, jans-cedarling/cedarling/src/tests/mapping_entities.rs, jans-cedarling/cedarling/src/tests/schema_type_mapping.rs, jans-cedarling/cedarling/src/tests/success_test_json.rs
target issue: #10437
closes #10437
moves the tokens in the AuthZ interface into a `tokens` field:
```js
input = { 
"tokens": {
"access_token": "encoded_token_str", 
"id_token": "encoded_token_str", 
"userinfo_token": "encoded_token_str", 
"tx_token": "encoded_token_str" 
},
"resource": {"id": "12345", "type": "Ticket", "creator": "mike@gluu.org", "organization": "gluu"},
"action": "View",
"context": {
"ip_address": "54.9.21.201",
"network_type": "VPN",
"user_agent": "Chrome 125.0.6422.77 (Official Build) (arm64)",
"time": "1719266610.98636",
}
}
decision_result = authz(input)
```
Please check the below before submitting your PR. The PR will not be merged if there are no commits that start with `docs:` to indicate documentation changes or if the …
=> refactor(jans-cedarling): update AuthZ interface to use `tokens` for all JWTs sent as input

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java
chore(jans-auth-server): log webapplicationexceptions for /authorize-challenge in TRACE logging level 
closes #10540
=> chore(jans-auth-server): log webapplicationexceptions for /authorize-challenge in TRACE logging level #10540

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/CacheGrant.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalAuthorizationChallengeService.java, jans-linux-setup/jans_setup/templates/scripts.ldif
fix(jans-auth-server): challenge endpoint returns 400 if authorize throws an unexpected exception
closes #10553
=> fix(jans-auth-server): challenge endpoint returns 400 if authorize throws an unexpected exception

docs/janssen-server/developer/agama/native-applications.md, jans-auth-server/agama/engine/src/test/java/io/jans/agama/test/CustomConfigsFlowTest.java
=> fix: update expected status code

jans-keycloak-link/server/pom.xml, jans-keycloak-link/server/src/main/java/io/jans/keycloak/link/server/service/ConfigurationService.java, jans-keycloak-link/server/src/main/java/io/jans/keycloak/link/service/config/ApplicationFactory.java
https://github.com/GluuFederation/flex/issues/1957
Closes #10628,
=> fix(jans-keycloak-link): unstatisfied dependencies

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
fix(jans-auth-server): access evaluation tests are failing on jenkins
closes #10629
=> test(jans-auth-server): access evaluation tests are failing on jenkins

docker-jans-auth-server/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-kc-scheduler/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile
Fixes missing permissions for /app/template
closes #10640
-  [x] **I confirm that there is no impact on the docs due to the code changes in this PR.**
=> fix(docker-jans-auth): missing permissions on /app/templates

docs/script-catalog/consent_gathering/sample-script/ConsentGatheringSample.py, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java, jans-auth-server/server/src/main/webapp/WEB-INF/incl/layout/authorize-extended-template.xhtml, jans-linux-setup/jans_setup/static/extension/consent_gathering/ConsentGatheringSample.py
=> feat(jans-auth): Show valid client name or id in consent form

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java
fix(jans-auth-server): NPE during client name rendering 
closes #10663
=> fix(jans-auth-server): NPE during client name rendering #10663

jans-auth-server/server/src/main/webapp/WEB-INF/incl/layout/authorize-extended-template.xhtml, jans-auth-server/server/src/main/webapp/authz/authorize.xhtml, jans-auth-server/server/src/main/webapp/authz/transaction.xhtml
=> feat(jans-auth): Remove copyright footer

.github/workflows/build-packages.yml, demos/jans-tarp/src/options/homePage.tsx
=> feat: cedarling integration with tarp

jans-auth-server/server/src/test/java/io/jans/as/server/comp/db/UserServiceTest.java, jans-orm/model/src/main/java/io/jans/orm/model/base/CustomObjectAttribute.java
=> Path to salt

jans-cli-tui/cli_tui/plugins/140_config_api/main.py
=> fix(jans-cli-tui): ScrollablePane for config-api main screen

docs/script-catalog/consent_gathering/AgamaConsentGathering.py, docs/script-catalog/consent_gathering/consent-gathering.md, jans-auth-server/server/src/main/java/io/jans/as/server/util/AgamaConsentUtil.java, jans-linux-setup/jans_setup/templates/scripts.ldif
=> feat(agama): allow integration of Agama flows in AS consent

agama/misc/json_finished.ftlh, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/servlet/ExecutionServlet.java
=> fix: account absent start url in native flows

jans-linux-setup/jans_setup/static/scripts/jans
=> chore(jans-linux-setup): revert admin-ui restart

docs/script-catalog/authorization_challenge/AgamaChallenge.java, docs/script-catalog/authorization_challenge/AuthorizationChallenge.java, docs/script-catalog/authorization_challenge/multi_step/AuthorizationChallenge.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalAuthorizationChallengeService.java
fix(jans-auth-server): second authorization challenge call does not invoke the right script 
closes #10745
=> fix(jans-auth-server): second authorization challenge call does not invoke the right script #10745

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/ConsentGatheringSessionService.java
fix(jans-auth-server): typo in determineConsentFlow method 
closes #10758
=> fix(jans-auth-server): typo in determineConsentFlow method #10758

jans-cedarling/flask-sidecar/Dockerfile, jans-cedarling/flask-sidecar/main/base/cedarling/cedarling.py
=> fix(jans-cedarling): fix token handling

docs/janssen-server/developer/agama/native-applications.md, docs/script-catalog/consent_gathering/consent-gathering.md
=> docs: add Agama section for consent flows

jans-scim/service/src/main/java/io/jans/scim/service/ConfigurationService.java
=> chore: replace deprecated LDAP enum by DB

jans-linux-setup/jans_setup/setup_app/installers/fido.py, jans-linux-setup/jans_setup/templates/jans-fido2/docuemts.ldif
=> fix(jans-linux-setup): fido document store paths

jans-auth-server/client/src/main/java/io/jans/as/client/uma/UmaPermissionService.java, jans-auth-server/client/src/main/java/io/jans/as/client/util/KeyExporter.java, jans-auth-server/client/src/main/java/io/jans/as/client/util/KeyGenerator.java, jans-auth-server/common/src/main/java/io/jans/as/common/service/common/ConfigurationService.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/binding/TokenBinding.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/binding/TokenBindingExtension.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/binding/TokenBindingMessage.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/signature/EDDSAKeyFactory.java, jans-auth-server/model/src/main/java/io/jans/as/model/crypto/signature/EDDSAPublicKey.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SectorIdentifierService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/uma/ws/rs/UmaResourceRegistrationWS.java
- [ x] Read [PR guidelines](https://github.com/JanssenProject/jans/blob/main/docs/CONTRIBUTING.md#prs)
- [ x] Read [license information](https://github.com/JanssenProject/jans/blob/main/LICENSE)
Javadoc was inconsistent with the code, and did not properly follow javadoc syntax, causing the "mvn javadoc:javadoc" command to fail build.
#4120 
closes #4120 
- [x ] **I confirm that there is no impact on the docs due to the code changes in this PR.**
=> docs: javadocs are now consistent with code, issue#4120

jans-auth-server/docs/swagger.yaml
doc(jans-auth-server): added /internal/stat to swagger 
closes #10839
=> doc(jans-auth-server): added /internal/stat to swagger #10839

jans-linux-setup/jans_setup/templates/attributes.ldif
=> fix(jans-linux-setup): rename permission to role in attribute inum=6049

jans-linux-setup/jans_setup/setup_app/installers/base.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py
=> fix(jans-linux-setup): lock client creation with setup.properties

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
Closes #10963
With this PR, installation of Jans LDAP Link Server is not prompted. But you can still install by passing argument `--install-jans-ldap-link` to `setup.py`
=> feat(jans-linux-setup): LDAP Link installation is optional

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/test/java/io/jans/ca/plugin/adminui/test/services/LicenseServiceTest.java
=> fix(jans-config-api): admin UI unable to fetch MAU _threshold on restart of config-api

jans-cedarling/bindings/cedarling_wasm/example_data.js
Fix bootstrap property for wasm app
[link](https://github.com/JanssenProject/jans/issues/10981)
closes #10981
Added namespace to `cedar-policy` type
=> bug(jans-cedarling): cedarling wasm app has wrong default bootstrap properties

jans-auth-server/server/src/main/java/io/jans/as/server/rate/RateLimitFilter.java, jans-auth-server/server/src/main/java/io/jans/as/server/rate/RateLimitService.java, jans-linux-setup/jans_setup/setup_app/test_data_loader.py
feat(jans-auth-server): rate limit - use guava cache to auto-expire buckets during high load 
closes #11054
=> feat(jans-auth-server): rate limit - use guava cache to auto-expire buckets during high load #11054

jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/SsaCreateAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaCreateTest.java
test(jans-auth-server): SsaCreateTest is failing on jenkins 
closes #11078
=> test(jans-auth-server): SsaCreateTest is failing on jenkins #11078

docs/cedarling/cedarling-policy-store.md
- remove principal_identifier
- add more information for the Token Metadata fields
This updates a section in the docs missed in #10888 
closes #11086
- Added additional info in the Token Metadata Section
- Removed `principal_identifier`
=> docs(jans-cedarling): update token metadata section

jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-auth-server/server/src/test/java/io/jans/as/server/BaseComponentTest.java, jans-auth-server/server/src/test/resources/testng.xml
fix(jans-auth-server): correction after removing CleanerTimer from AS (replaced by independent clean service) 
closes #10935
Closes #11109,
=> fix(jans-auth-server): correction after removing CleanerTimer from AS (replaced by independent clean service) #10935

jans-cli-tui/cli_tui/plugins/070_users/main.py
=> fix(jans-cli-tui): Catch errors when changing user password

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
=> fix: validate license configuration in the database when fetching license details from Agama Lab server upon expiry (Admin UI)

jans-cli-tui/cli_tui/jans_cli_tui.py
=> fix(jans-cli-tui): add pylib to path before importing promptoolkit

jans-linux-setup/jans_setup/static/system/initd/jetty.sh
=> fix(jans-linux-setup): jetty.sh script waits service started

jans-linux-setup/jans_setup/setup_app/data/jetty_app_configuration.json
#11276
closes #11276
Closes #11325,
=> feat(jans-config-api): disable jetty ee9-jsp module in jans-config-api

jans-auth-server/server/src/main/java/io/jans/as/server/auth/Authenticator.java
fix(jans-auth-server): improve logging - do not print that user is logged in in logs if it failed to login 
closes #11475
=> fix(jans-auth-server): improve logging - do not print that user is logged in in logs if it failed to login #11475

docs/cedarling/cedarling-properties.md
Moved required properties to the top.
https://github.com/JanssenProject/jans/issues/8831
Moved the required bootstrap properties to the top, removed some duplication, and made the boolean property more clear. 
=> docs(jans-cedarling): Updated Cedarling bootstrap properties docs

jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py
=> fix(jans-cli-tui): user jansStatus is in body not custom attrbiute

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
fix(jans-auth-server): set sub claim to client identifier for "client credentials grant" for AT as JWT 
closes #11413
=> fix(jans-auth-server): set sub claim to client identifier for "client credentials grant" for AT as JWT #11413

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py
Closes #11790
In this PR, **jansStatus** is removed from available claims for users as mentioned in #8258
=> fix(jans-cli-tui): adjust entries per page dynamiccally

jans-config-api/plugins/pom.xml
=> feat(jans-config-api): restore jans-config-api plugins jans-link-plugin

jans-cli-tui/cli_tui/cli/config_cli.py
Closes #11899
User and Client passwords are logged as follows
=> fix(jans-cli-tui): avoid logging plain texts

jans-keycloak-integration/pom.xml
added exclusions for dependencies already provided by quarkus which created a conflict
=> fix(jans-keycloak-integration): kc health and metrics endpoint throw error #12001

jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java
fix(jans-auth-server): client registration script jwks is not used during validation
closes #12036
=> fix(jans-auth-server): client registration script jwks is not used during validation #12036

jans-linux-setup/jans_setup/setup_app/data/package_list.json
=> fix(jans-linux-setup): missing python libs for rhel-8

jans-linux-setup/jans_setup/setup_app/data/package_list.json
=> fix(jans-linux-setup): missing py libs for suse

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): hide logging plain text password when changing user password

jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> fix(jans-linux-setup): jans command linked to /usr/sbin
