docs/admin/developer/managed-beans.md
notes on CustomObjectAttribute;
=> docs(fix): #1217

demos/jans-tarp/public/options.html, demos/jans-tarp/src/popup.css, demos/jans-tarp/src/popup.js
=> feat (jans-tarp) : shift additional param field to Auth request form #5054

jans-linux-setup/jans_setup/templates/scopes.ldif
=> fix(jans-linux-setup): type of jans_stat is oauth

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py, jans-auth-server/model/src/main/java/io/jans/as/model/util/Util.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-auth-server/server/src/main/java/io/jans/as/server/util/ServerUtil.java, jans-fido2/notify-client/src/main/java/io/jans/notify/client/NotifyClientFactory.java, jans-fido2/notify-client/src/main/java/io/jans/notify/client/NotifyClientService.java, jans-fido2/notify-client/src/main/java/io/jans/notify/client/NotifyMetadataClientService.java
=> feat: update SG script and notify client to conform scan API #5061

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> chore: increase application column size to 96 #5063

docs/admin/auth-server/client-management/README.md
=> fix(docs): #3675

docs/admin/auth-server/tokens/openid-id-token.md
=> fix(docs): Mention of Update Token script #3465

docs/admin/reference/README.md
=> docs(reference guide): update README.md

jans-auth-server/common/pom.xml, jans-auth-server/model/pom.xml, jans-auth-server/pom.xml
chore(jans-auth-server): upgraded snakeyaml cross-dependency to 2.0 
closes #5071
=> chore(jans-auth-server): upgraded snakeyaml cross-dependency to 2.0 #5071

terraform-provider-jans/CHANGELOG.md, terraform-provider-jans/docs/resources/organization.md, terraform-provider-jans/jans/client.go, terraform-provider-jans/jans/fido2_config.go, terraform-provider-jans/jans/fido2_config_test.go, terraform-provider-jans/provider/resource_fido2_configuration.go, terraform-provider-jans/provider/resource_organization.go, terraform-provider-jans/provider/resource_organization_test.go
Features
* add missing attributes for fido2 app configuration updates 
* fido2 config error and put operation 
* fixed request for sending binary data 
* update method name to match naming scheme 
* updated organisation mappings 
Closes #5075,
=> fix(terraform-provider-jans): update terraform module

docs/admin/reference/json/README.md
=> docs(reference): update README.md

docs/admin/auth-server/client-management/software-statements.md
=> docs(client mgmt): remove mention of stmt as id

demos/jans-tarp/public/manifest.json
=> feat: enable working of tarp in incognito mode #5080

docs/admin/recipes/stepped-up-authn.md
=> fix(docs): minor addition #4881

docs/script-catalog/persistence_extension/SampleScript.py
removing unnecessary folder #4707
=> docs(fix) : removing unnecessary folder #4707

docs/admin/developer/scripts/persistence.md
#4707
Explaining Persistence Extension script
=> fix(docs): #4707

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py, jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/net/HttpService2.java
=> feat: add authorization headers needed to access scan API from SG

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py
=> chore(docker-jans-persistence-loader): increase jansApp column size

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
=> fix(jans-linux-setup): maridb json columns

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/templates/configuration.ldif, docker-jans-scim/Dockerfile
closes #5098
- updated `configuration.ldif` template
- sync schema and templates for persistence
=> chore(docker): sync assets from upstream

docs/admin/scim/logs.md
=> docs: add instructions to set SCIM log level

docs/admin/scim/oauth-protection.md
=> docs: add details of how oauth protection mode works

docs/admin/auth-server/crypto/key-generation.md, docs/admin/vm-ops/managing-key-rotation.md
docs(vm-ops): create Managing Key Rotation documentation
closes #4692
=> docs(vm-ops): create Managing Key Rotation documentation

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/jans_cli_tui.py
=> feat(jans-cli-tui): log command line for write operations

jans-core/script/src/main/java/io/jans/service/PythonService.java, jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java
fix: failed to initialize resteasy proxy from script at server startup #5116
=> fix: failed to initialize resteasy proxy from script at server

docs/admin/recipes/ACRouter.md
=> docs(jans-auth): Create ACRouter.md #5120

docs/admin/auth-server/logging/README.md, docs/admin/auth-server/logging/audit-logs.md, docs/admin/auth-server/logging/custom-logs.md, docs/admin/auth-server/logging/log-levels.md, docs/admin/auth-server/logging/log4j2.md, docs/admin/auth-server/logging/standard-logs.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java
docs(jans-auth-server): create documentation for logging 
closes #4879
=> docs(jans-auth-server): create documentation for logging #4879

mkdocs.yml
=> docs(jans-auth) : #3494 adding User Journeys

jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py
=> fix(jans-cli-tui): userPassword should not be sent in customAttributes

docs/admin/developer/external-libraries.md
=> docs: write external scripts document

docs/admin/developer/interception-scripts.md, docs/admin/developer/scripts/select-account.md, docs/script-catalog/select_account/select-account/select_account.py, jans-auth-server/server/src/main/java/io/jans/as/server/auth/SelectAccountAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalSelectAccountService.java, jans-auth-server/server/src/main/resources/jans-auth.properties, jans-auth-server/server/src/main/resources/jans-auth_en.properties, jans-auth-server/server/src/test/java/io/jans/as/server/model/common/ExecutionContextTest.java, jans-auth-server/server/src/test/resources/testng.xml, jans-core/script/src/main/java/io/jans/model/custom/script/CustomScriptType.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/selectaccount/DummySelectAccountType.java, jans-core/script/src/main/java/io/jans/model/custom/script/type/selectaccount/SelectAccountType.java, mkdocs.yml
feat(jans-auth-server):  Support of Select Account interception script 
closes #3452
=> feat(jans-auth-server):  Support of Select Account interception script #3452

docs/admin/auth-server/endpoints/README.md, docs/admin/reference/json/feature-flags/README.md, docs/admin/reference/json/properties/README.md
closes #4886, closes #4887, closes #4896
=> docs: write topic overview pages for properties, feature flags and endpoint sections

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): agama project upload

demos/jans-tarp/src/options/ILooseObject.ts, demos/jans-tarp/src/options/IOption.ts, demos/jans-tarp/src/options/oidcClientDetails.tsx, demos/jans-tarp/src/options/registerForm.tsx
=> feat: override acr when triggering auth-flow #5168

docs/admin/vm-ops/managing-key-rotation.md
=> docs(jans-auth-server): Update managing-key-rotation.md

docs/admin/vm-ops/managing-key-rotation.md
=> (docs jans-auth-server): Update managing-key-rotation.md

docs/agama/gama-format.md, docs/agama/introduction.md, jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java, jans-auth-server/agama/model/src/main/java/io/jans/ads/model/ProjectMetadata.java
=> feat(agama): update deployer to account project's metadata `noDirectLaunch`

jans-config-api/docs/jans-config-api-swagger.yaml, jans-core/service/src/main/java/io/jans/service/custom/CustomScriptService.java
=> Jans config api fixes

docs/admin/scim/bulk-users.md
=> docs: create documentation for SCIM adding bulk users

docs/admin/auth-server/oauth-features/password-grant.md
=> docs(oauth): add content about password grant

docs/admin/reference/database/README.md
=> docs(persistence): create documentation for the overview section of the database guide

docs/admin/auth-server/openid-features/id-token.md, docs/admin/auth-server/tokens/openid-id-token.md
=> docs(OpenID): add content about id token

docs/admin/auth-server/endpoints/par.md, docs/admin/auth-server/oauth-features/par.md
docs(OAuth feature): create documentation for PAR 
closes #4859
=> docs(OAuth feature): create documentation for PAR #4859

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli): remove local jwt token when session is revoked

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/LicenseApiResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> feat (jans-config-api): add feature in admin-ui to request trial license#5109

charts/janssen/charts/opendj/templates/statefulset.yaml
https://github.com/JanssenProject/jans/issues/5042
Closes #5101,
=> fix: adjust opendj permissions and remove unneeded initContainer

docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/upgrade.py
=> feat(docker-jans-fido2): loading mds using external urls

jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/AuthorizationResponseAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizationCodeFlowHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizeRestWebServiceHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ClientInfoRestWebServiceHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/EncodeClaimsInStateParameter.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/EndSessionRestWebServiceHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SSOWithMultipleBackendServicesHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SetPublicSubjectIdentifierPerClientTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/Tester.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/TokenEndpointAuthMethodRestrictionHttpTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/TokenSignaturesHttpTest.java
test(jans-auth-server): some tests fail after removing automatic client scopes granting 
closes #5262
=> test(jans-auth-server): some tests fail after removing automatic client scopes granting #5262

docs/admin/auth-server/endpoints/end-session.md, docs/admin/auth-server/openid-features/logout/README.md
=> docs(openid): write documentation for logout methods

jans-cache-refresh/pom.xml
=> chore: fix CR version

jans-cache-refresh/pom.xml, jans-cache-refresh/src/main/java/io/jans/cacherefresh/service/AttributeService.java, jans-cache-refresh/src/main/java/io/jans/cacherefresh/service/OrganizationService.java
=> fix(jans-cache-refresh): cache refresh fixes

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/cache-refresh-plugin/src/main/java/io/jans/configapi/plugin/cacherefresh/model/config/CacheRefreshConfiguration.java, jans-config-api/plugins/docs/cache-refresh-plugin-swagger.yaml, jans-config-api/plugins/docs/fido2-plugin-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml
=> feat(config-api): cache config plugin refresh attributes

jans-linux-setup/jans_setup/templates/jetty/jans-cache-refresh
closes #5277
Also closes https://github.com/GluuFederation/flex/issues/1107
=> fix(jans-linux-setup): cache refresh port

docs/admin/developer/agama/flows-navigation-ui.md, docs/admin/scim/config.md
=> docs(scim): add more details to documentation for SCIM configuration

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
=> fix: admin-ui should redirect to login page if license has been already activated #5282

jans-scim/model/src/main/java/io/jans/scim/model/scim2/extensions/ExtensionField.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/ExtensionService.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/Scim2UserService.java
=> fix(jans-scim): date custom attribute not returned on user creation when set via custom script

jans-auth-server/client/src/test/java/io/jans/as/client/ciba/CibaPingModeJwtAuthRequestTests.java, jans-auth-server/client/src/test/java/io/jans/as/client/ciba/CibaPollModeJwtAuthRequestTests.java, jans-auth-server/client/src/test/java/io/jans/as/client/interop/CanProvideEncryptedUserInfoResponse.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/ResponseTypesRestrictionHttpTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-linux-setup/jans_setup/templates/test/jans-auth/data/oxauth-test-data.ldif
fix(jans-auth-server): ClassCastException during select account 
closes #5285
=> fix(jans-auth-server): ClassCastException during select account #5285

jans-auth-server/server/src/main/java/io/jans/as/server/auth/SelectAccountAction.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/CookieService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
chore(jans-auth-server): added more trace logs 
closes #5262
=> chore(jans-auth-server): added more trace logs #5262

docs/admin/auth-server/oauth-features/dpop.md
=> Docs oauth dpop

docs/script-catalog/person_authentication/twilio-2fa/README.md
=> docs: #819 Twilio interception script

docs/admin/install/vm-install/suse.md
=> document updated for gpg key import

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py
=> Jans cli tui combobox spacing

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): set checkbox selected index to 0 upon filtering

charts/janssen/charts/nginx-ingress/templates/ingress.yaml
=> fix: remove unneeded configuration snippet

docs/admin/install/vm-install/suse.md
[docs(suse VM install): Fix some formatting errors in SUSE VM install docs](https://github.com/JanssenProject/jans/issues/5331)
closes #5331
minor edits
=> Some minor fixes to Jans SUSE install

jans-linux-setup/jans_setup/install.py
=> feat(jans-linux-setup): add option --keep-setup

jans-scim/client/src/main/java/io/jans/scim2/client/AbstractScimClient.java
=> Restore usage of PoolingHttpClientConnectionManager in scim client

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java
chore(jans-auth-server): added more logs during select account #5262
closes #5262
=> chore(jans-auth-server): added more logs during select account #5262

docs/admin/kubernetes-ops/README.md, docs/admin/kubernetes-ops/upgrade.md, mkdocs.yml
https://github.com/JanssenProject/jans/issues/5345 
Closes #5350,
=> docs: helm upgrade

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/OAuth2ConfigResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java
=> feat (config-api): add opHost url in /config response in admin-ui plugin #5353

jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/scopes.ldif
=> fix(jans-linux-setup): scope offline_access is non-default

jans-linux-setup/jans_setup/templates/jans-auth/role-scope-mappings.json
=> fix(jans-linux-setup): mapping changes for admin-ui

docs/admin/usermgmt/usermgmt-scim.md
On this docs we will familiar with 
This docs motivated from [here](https://gluu.org/docs/gluu-server/4.5/user-management/scim2/)
=> docs(usermgmt): Update scim user management

docs/admin/reference/database/mysql-schema-indexes.md, docs/admin/reference/database/mysql-schema.md
=> fix(docs): autogenerate MYSQL RDBMS docs

docs/admin/reference/database/pgsql-schema-indexes.md, docs/admin/reference/database/pgsql-schema.md
=> fix(docs): autogenerate PGSQL RDBMS docs

jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> feat(jans-linux-setup): disable selinux

docs/admin/install/vm-install/rhel.md
Update rhel.md for gpg key changes
https://github.com/JanssenProject/jans/issues/5392
closes #5396
=> Update rhel.md for gpg key changes

docs/admin/install/vm-install/ubuntu.md
Update ubuntu.md for gpgkey
closes #5392 
=> Update ubuntu.md for gpgkey

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> feat(jans-linux-setup): argument -disable-selinux

README.md
[5371 - docs: Refresh content on main Janssen Readme](https://github.com/JanssenProject/jans/issues/5371)
closes #5371
Content from @nynymike 
=> docs: much needed content refresh of main Janssen Project README home page.

automation/docs/generate-rdbms-docs.py
=> fix(docs): markdown structure of RDBM schema creation

jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapUserFieldRemove.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/model/SimpleUser.java
fix(jans-orm): orm compilation failure 
closes #5412
=> fix(jans-orm): orm compilation failure #5412

jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
=> fix(jans-linux-setup): spanner import ldif with modify add

jans-linux-setup/jans_setup/static/extension/cache_refresh/SampleScript.py
corrected the import class in py script
Closes #5441,
=> fix(jans-link): corrected import class in py script

mkdocs.yml
=> docs(cli): add agama CLI to nav

jans-auth-server/common/src/main/java/io/jans/as/common/model/session/SessionId.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthorizeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
fix(jans-auth-server): maintain client scopes during authorization 
closes #5247
=> fix(jans-auth-server): maintain client scopes during authorization #5247

jans-cli-tui/docs/build.md
find tui client id
Closes #5451,
=> doc(jans-cli-tui): find tui client id

docs/admin/developer/scripts/update-token.md
=> docs: #605 - mention setting integer value claim

jans-linux-setup/jans_setup/templates/jans-cache-refresh/jans-cache-refresh-config.json
https://github.com/JanssenProject/jans/issues/5471
Closes #5473,
=> feat(jans-link): set jans-link by default disabled

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
closes https://github.com/JanssenProject/jans/issues/5458
closes https://github.com/JanssenProject/jans/issues/5458
Closes #5467,
=> fix(jans-cli-tui): remove agama developer studio

agama/transpiler/src/main/java/io/jans/agama/dsl/Transpiler.java, agama/transpiler/src/main/java/io/jans/agama/dsl/Visitor.java, agama/transpiler/src/main/resources/JSGenerator.ftl, agama/transpiler/src/main/resources/util.js, docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/script/LogUtils.java
=> feat(agama): prefix log statements generated by Agama flows with the qualified name

jans-auth-server/server/src/test/java/io/jans/as/server/service/SessionIdServiceTest.java
test(jans-auth-server): adapted test after new methods added into SessionIdService 
closes #5476
=> test(jans-auth-server): adapted test after new methods added into SessionIdService #5476

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/couchbase.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/opendj.py, jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/static/system/systemd/jans-auth.service, jans-linux-setup/jans_setup/static/system/systemd/jans-cache-refresh.service, jans-linux-setup/jans_setup/static/system/systemd/jans-config-api.service, jans-linux-setup/jans_setup/static/system/systemd/jans-eleven.service, jans-linux-setup/jans_setup/static/system/systemd/jans-fido2.service, jans-linux-setup/jans_setup/static/system/systemd/jans-scim.service
=> refactor(jans-linux-setup): order start level of jans services

docs/admin/developer/agama/jans-agama-engine.md
=> docs(agama): describe what (and where) is logged in Agama

docs/admin/install/vm-install/suse.md
=> Update jans suse.md doc for enable package

docs/admin/auth-server/oauth-features/README.md
docs(auth-server): created documentation for OAuth features overview README #4899
closes #4899
=> docs(auth-server): created documentation for OAuth features overview README #4899

docs/admin/install/docker-install/compose.md, docs/admin/reference/kubernetes/docker-jans-auth-server.md, docs/admin/reference/kubernetes/docker-jans-certmanager.md, docs/admin/reference/kubernetes/docker-jans-config-api.md, docs/admin/reference/kubernetes/docker-jans-configurator.md, docs/admin/reference/kubernetes/docker-jans-fido2.md, docs/admin/reference/kubernetes/docker-jans-monolith.md, docs/admin/reference/kubernetes/docker-jans-persistence-loader.md, docs/admin/reference/kubernetes/docker-jans-scim.md, docs/admin/reference/kubernetes/helm-chart.md
=> fix(docs): autogenerate docs

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, jans-core/server/src/main/java/io/jans/server/filters/AbstractCorsFilter.java
=> fix: authentication Filter should not process OPTIONS request method 

jans-cli-tui/cli_tui/cli/config_cli.py
Closes https://github.com/JanssenProject/jans/issues/5509
Closes #5531,
=> fix(jans-cli-tui): get information for Agama and AgamaConfiguration

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
closes https://github.com/JanssenProject/jans/issues/5452
Closes #5454,
=> fix(jans-linux-setup): remove disabling selinux and apply policies

jans-linux-setup/jans_setup/templates/jans.properties
=> fix(jans-linux-setup): link configuration DN

docs/admin/config-guide/jans-cli/cli-attribute.md
=> docs: updated cli-attribute.md

docs/admin/auth-server/endpoints/client-registration.md, docs/admin/reference/json/properties/janssenauthserver-properties.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/TrustedIssuerConfig.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/context/DynamicClientRegistrationContext.java, jans-auth-server/server/src/test/java/io/jans/as/server/register/ws/rs/RegisterValidatorTest.java, jans-auth-server/server/src/test/resources/testng.xml
feat(jans-auth-server): automatically provision scopes if they are present in the SSA for trusted issuer #5164
closes #5164
=> feat(jans-auth-server): automatically provision scopes if they are present in the SSA for trusted issuer #5164

jans-linux-setup/jans_setup/setup_app/data/package_list.json, jans-linux-setup/jans_setup/setup_app/utils/base.py
closes #5540 , closes #5542 , closes #5541
=> fix(jans-linux-setup):  cryptography, opensuse tumbleweed support, openssl requirement

jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterValidator.java
fix(jans-auth-server): npe during client registration 
closes #5559
=> fix(jans-auth-server): npe during client registration #5559

demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/register_client.jmx
feat(jans-auth-server): added dcr load test 
closes #5438
=> feat(jans-auth-server): added dcr load test #5438

demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/register_client.jmx
fix(jans-auth-server): clean up register_client.jmx 
closes #5438
=> fix(jans-auth-server): clean up register_client.jmx #5438

jans-fido2/server/src/main/java/io/jans/fido2/service/operation/AssertionService.java
=> fix: use filter by RP if it's SG request

docs/admin/developer/agama/jans-agama-engine.md
=> docs: highlight key differences between Java and Groovy code in agama docs

jans-cli-tui/cli_tui/plugins/090_jans_link/main.py
=> fix(jans-cli-tui): inumdb server in jans link

jans-auth-server/server/src/main/java/io/jans/as/server/service/net/HttpService2.java
https://github.com/JanssenProject/jans/issues/5585
=> feat: add proxy support to HttpService2

docker-jans-configurator/Dockerfile, docker-jans-configurator/scripts/bootstrap.py, docker-jans-configurator/scripts/entrypoint.sh
=> refactor(docker-jans-configurator): allow custom location for db and certs directories

README.md
=> docs: fixes in Jans README

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/UserInfoRequest.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java
=> feat: adding PKCE in admin-ui authentication (Admin UI plugin) #5595

charts/janssen/charts/nginx-ingress/templates/ingress.yaml, charts/janssen/charts/nginx-ingress/values.yaml, charts/janssen/values.yaml
https://github.com/JanssenProject/jans/issues/5570#event-9859609766
closes #5570 
=> fix: remove ingress.class annotation and add spec.ingressClassName

docs/admin/terraform/README.md, docs/admin/vm-ops/upgrade.md, mkdocs.yml
=> docs: vm upgrade using terraform

jans-linux-setup/jans_setup/install.py
=> fix(jans-linux-setup): remove service files after stop in uninstall

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/dpop/DpopTokenRequestHttpTest.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/jwt/DPoPJwtPayloadParam.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/model/src/main/java/io/jans/as/model/token/TokenErrorResponseType.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/AuthenticationFilter.java, jans-auth-server/server/src/main/java/io/jans/as/server/auth/DPoPService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-errors.json
feat(jans-auth-server): added DPoP-Nonce and client level dpop control "dpop_bound_access_tokens"
closes #5288
=> feat(jans-auth-server): added DPoP-Nonce and client level dpop control "dpop_bound_access_tokens"

jans-scim/server/src/main/java/io/jans/scim/service/scim2/UserPersistenceHelper.java
=> chore: ensure primary e-mail (if any) is sent 1st to persistence

jans-cli-tui/cli_tui/cli_style.py, jans-cli-tui/cli_tui/plugins/090_jans_link/main.py, jans-cli-tui/cli_tui/utils/static.py
=> fix(jans-cli-tui): source ldap server dialog

jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DBDocumentStoreProvider.java
#5619 
moved fixes from Gluu repo.
=> fix(jans-core): db document Store fixes #5619

docs/admin/install/helm-install/amazon-eks.md, docs/admin/install/helm-install/google-gke.md, docs/admin/install/helm-install/microsoft-azure.md
https://github.com/JanssenProject/jans/issues/5603
closes #5603 
=> docs: add couchbase helm instructions

jans-linux-setup/jans_setup/templates/apache/https_jans.conf
=> fix(jans-linux-setup): remove fido-u2f-configuration proxypass from apache

jans-linux-setup/jans_setup/templates/apache/https_jans.conf
=> fix(jans-linux-setup): remove proxypass fido-configuration

docker-jans-auth-server/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py
=> feat(docker-jans): add dpop nonce

demos/benchmarking/docker-jans-loadtesting-jmeter/Makefile, docker-jans-auth-server/Makefile, docker-jans-certmanager/Makefile, docker-jans-config-api/Makefile, docker-jans-configurator/Makefile, docker-jans-fido2/Makefile, docker-jans-link/Makefile, docker-jans-monolith/Makefile, docker-jans-persistence-loader/Makefile, docker-jans-scim/Makefile
The changeset modify `Makefile`s to extract required values from `Dockerfile`.
closes #5637 
=> ci(docker-jans): extract info from Dockerfile to build local image

jans-bom/pom.xml, jans-config-api/pom.xml, jans-config-api/server/pom.xml
=> chore: update libs

jans-auth-server/common/src/main/java/io/jans/as/common/service/AttributeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/clientinfo/ws/rs/ClientInfoRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/idgen/ws/rs/InumGenerator.java, jans-auth-server/server/src/main/java/io/jans/as/server/jans/ws/rs/JansConfigurationWS.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/token/IdTokenFactory.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/ScopeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/FapiOpenIdConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/userinfo/ws/rs/UserInfoRestWebServiceImpl.java, jans-auth-server/server/src/test/java/io/jans/as/server/service/ScopeServiceTest.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/interceptor/RequestReaderInterceptor.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AttributesResource.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/ClientsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AttributeService.java, jans-core/jsf-util/src/main/java/io/jans/jsf2/converter/AttributeNameConverter.java, jans-core/jsf-util/src/main/java/io/jans/jsf2/validator/AttributeValidator.java, jans-core/service/src/main/java/io/jans/model/JansAttribute.java, jans-core/service/src/main/java/io/jans/model/JansCustomAttribute.java, jans-core/service/src/main/java/io/jans/service/AttributeService.java, jans-link/service/src/main/java/io/jans/link/service/AttributeService.java, jans-link/service/src/main/java/io/jans/link/service/InumService.java, jans-scim/server/src/main/java/io/jans/scim/service/antlr/scimFilter/FilterListener.java, jans-scim/server/src/main/java/io/jans/scim/service/antlr/scimFilter/ScimFilterParserService.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/ExtensionService.java, jans-scim/service/src/main/java/io/jans/scim/model/GluuCustomAttribute.java, jans-scim/service/src/main/java/io/jans/scim/service/AttributeService.java, jans-scim/service/src/main/java/io/jans/scim/service/PersonService.java
`GluuAttribute` name for Jans class renamed to `JansAttribute`
- `jans-auth-server`
- `jans-core`
- `jans-config-api`
- `jans-link`
- `jans-scim`
closes #5622 
=> refactor(jans): rename `GluuAttribute` to `JansAttribute` in all project

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py
=> fix(docker-jans-persistence-loader): enlarge column adsPrjDeplDetails

terraform-provider-jans/CHANGELOG.md, terraform-provider-jans/provider/resource_app_configuration.go
Bug Fixes
* fixed dpop_use_nonce attribute type 
* fixed dpop_use_nonce attribute type 
* fixed dpop_use_nonce attribute type 
Closes #5666,
=> fix(terraform-provider-jans):  dpop_use_nonce attribute type

docs/contribute/development.md
=> docs: steps for running integration tests for jans modules

docs/admin/developer/agama/jans-agama-engine.md, docs/agama/language-reference.md
=> docs: clarify syntax of Finish directive

docs/admin/README.md, docs/admin/usermgmt/usermgmt-jans-link.md, mkdocs.yml
=> docs(navigation): add jans-link to nav

jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
=> fix(jans-linux-setup): non-document entry

docs/admin/developer/agama/projects-deployment.md
=> docs: remove occurrences of ADS in agama docs

jans-link/server/src/main/java/io/jans/link/timer/CacheRefreshTimer.java
=> fix(jans-link): polling interval and time difference calculation #5667

jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py
=> feat: add new methnod to fido2 extension to allow modify json

jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
=> fix(jans-linux-setup): typed value when setting value

jans-linux-setup/jans_setup/setup_app/installers/jetty.py
=> fix(jans-linux-setup): remove modification of dirAllowed

jans-linux-setup/jans_setup/setup_app/installers/jans_link.py
=> fix(jans-linux-setup): jans-link download url

jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/session/ws/rs/EndSessionUtils.java
fix(jans-auth-server): state is not always returned on redirect from /end_session endpoint 
closes #5704
=> fix(jans-auth-server): state is not always returned on redirect from /end_session endpoint #5704

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/bootstrap.py, docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/bootstrap.py, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/bootstrap.py, docker-jans-link/Dockerfile, docker-jans-link/scripts/bootstrap.py, docker-jans-scim/Dockerfile, docker-jans-scim/scripts/bootstrap.py
=> refactor(docker-jans): handle custom jetty.xml and webdefault.xml

jans-cli-tui/cli_tui/plugins/090_jans_link/main.py
=> fix(jans-cli-tui): remove serverIpAddress from link configuration

jans-link/server/src/main/java/io/jans/link/timer/CacheRefreshTimer.java
https://github.com/JanssenProject/jans/issues/5709
=> fix(jans-link): fix null pointer exception for sourceConfig #5709

docs/contribute/development.md
=> docs: improve instructions for integration test execution

demos/jans-tarp/README.md, demos/jans-tarp/pack.js, demos/jans-tarp/src/static/chrome/manifest.json, demos/jans-tarp/src/static/firefox/manifest.json, demos/jans-tarp/webpack.common.js, demos/jans-tarp/webpack.dev.js, demos/jans-tarp/webpack.prod.js
=> feat(jans-tarp): creating build compatible to firefox browser #5568

jans-auth-server/server/src/test/java/io/jans/as/server/session/ws/rs/EndSessionRestWebServiceImplTest.java
test(jans-auth-server): fix EndSessionRestWebServiceImplTest 
closes #5781
=> test(jans-auth-server): fix EndSessionRestWebServiceImplTest #5781

docs/admin/config-guide/config-tools/jans-tui/.#README.md
=> fix(docs): remove tmp file

docs/admin/install/README.md, docs/admin/install/vm-install/rhel.md
=> enhancement(docs): SELinux note

docs/admin/install/README.md
=> docs(installation): proofread the note on SELinux policy

jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> feat(jans-linux-setup): add selinux policies to post setup messages

docs/admin/recipes/casa.md
=> fix(docs): Corrected path #5810

docs/admin/reference/database/converting-data.md, docs/admin/reference/database/mysql-ops.md
=> docs(database): move content for data conversion

docs/agama-catalog/jans/inboundID/README.md, docs/agama-catalog/jans/inboundID/project/project.json
=> chore: add missing descriptor 

docs/admin/developer/scripts/persistence.md
=> docs: minor fix #4707

jans-core/script/src/main/java/io/jans/service/custom/script/ExternalTypeCreator.java
Issue: https://github.com/JanssenProject/jans/issues/5838
=> chore: update script load logging on error

docs/admin/reference/database/mysql-ops.md
=> fix(docs): mysql-operation-1

docs/admin/reference/database/mysql-ops.md
=> fix(docs): Adding custom attribute - mysql-ops.md

docs/admin/reference/database/pgsql-ops.md
=> fix(docs): initial commit - Update pgsql-ops.md

demos/jans-tarp/src/options/alerts.css, demos/jans-tarp/src/options/oidcClientDetails.tsx, demos/jans-tarp/src/options/options.css, demos/jans-tarp/src/options/userDetails.tsx
=> feat: display access_token and id_token generated during authentication flow #5804

docs/admin/auth-server/config.md, docs/admin/install/helm-install/amazon-eks.md, docs/admin/install/helm-install/google-gke.md
=> docs:  fixes and additions

docs/admin/reference/database/pgsql-ops.md
=> fix(docs): Update pgsql-ops.md

mkdocs.yml
=> Docs fix navigation

docs/admin/auth-server/endpoints/client-registration.md, docs/admin/auth-server/oauth-features/README.md
doc(jans-auth-server): changed "spec" to "draft spec" for attestationpages 
closes #5871
=> doc(jans-auth-server): changed "spec" to "draft spec" for attestationpages #5871

docs/admin/reference/database/ldap-ops.md
On this documentation I've done 
[4952](https://github.com/JanssenProject/jans/issues/4952)
=> docs(persistence): Update ldap-operation docs

docs/admin/auth-server/crypto/key-storage.md
Java KeyStores, used by Janssen.
closes #4898
=> docs: key-storage.md has been updated;

docs/admin/auth-server/openid-features/user-claims/built-in-claims.md, docs/admin/auth-server/openid-features/user-claims/custom-claims.md
=> docs: correct formatting and sentences in user claims docs #5893

docs/admin/vm-ops/certificates.md
=> docs(vm-ops): update certificates instruction

docs/admin/link/README.md
I'v added on this docs.
[5896](https://github.com/JanssenProject/jans/issues/5896)
=> docs(jans-link): create initial docs for jans-link

docker-jans-configurator/scripts/bootstrap.py
=> feat(docker-jans-configurator): custom location for generate.json via ENV

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): prompt for Gluu Casa

docker-jans-auth-server/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-fido2/scripts/bootstrap.py, docker-jans-fido2/scripts/upgrade.py, docker-jans-link/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-persistence-loader/scripts/upgrade.py, docker-jans-scim/Dockerfile
=> feat(docker-jans): sync assets of images

docs/admin/reference/database/pgsql-ops.md
Here I've done
[4964](https://github.com/JanssenProject/jans/issues/4964)
=> docs(persistence): Update postgres operation docs.

jans-auth-server/model/src/test/java/io/jans/as/model/jwk/JSONWebKeyTest.java, jans-auth-server/model/src/test/java/io/jans/as/model/util/HashUtilTest.java, jans-auth-server/server/src/main/java/io/jans/as/server/crypto/cert/CertificateParser.java, jans-auth-server/server/src/main/java/io/jans/as/server/crypto/signature/SHA256withECDSASignatureVerification.java, jans-auth-server/server/src/test/java/io/jans/as/server/comp/CrossEncryptionTest.java, jans-config-api/pom.xml, jans-eleven/server/pom.xml, jans-eleven/server/src/main/java/io/jans/eleven/service/AppInitializer.java, jans-eleven/server/src/main/java/io/jans/eleven/service/PKCS11Service.java
- BCFIPS support has been added (sub-part 04).
closes #5853
The part (sub-part 04) of this PR (some functionality):
https://github.com/JanssenProject/jans/tree/fips-support-issue-2278
https://github.com/JanssenProject/jans/issues/2278
https://github.com/JanssenProject/jans/pull/3751
=> feat: BCFIPS support (sub-part 04)

jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> feat: commit the admin-ui openapi specs changes #5913

docs/admin/developer/agama/projects-deployment.md, jans-auth-server/agama/inboundID/pom.xml, jans-bom/pom.xml
=> chore(agama): update nimbus oauth2-oidc-sdk version in agama-inbound

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py
=> fix(jans-linux-setup): Gluu/Flex Casa

jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequest.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImplTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthzRequestTest.java, jans-auth-server/server/src/test/resources/testng.xml
fix(jans-auth-server): fixed prompts handling when acr is changed 
closes #5930
=> fix(jans-auth-server): fixed prompts handling when acr is changed #5930

jans-linux-setup/jans_setup/setup_app/installers/node.py
=> fix(jans-linux-setup): node installer

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py
=> fix: fix typo in SG script

jans-linux-setup/jans_setup/setup_app/utils/base.py
=> fix(jans-linux-setup): suse apache version

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
Issue: https://github.com/JanssenProject/jans/issues/5940
=> fix: data type too small for jansDeviceData #5940

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> fix: data type too small for jansDeviceNotificationConf #5940

jans-bom/pom.xml
chore(jans-auth-server): upgraded quartz 2.3.2 -> 2.4.0-rc2
closes #5955
=> chore(jans-auth-server): upgraded quartz 2.3.2 -> 2.4.0-rc2

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/RegistrationWithSoftwareStatementTest.java
test(jans-auth-server): fix test failures - added issuers to test ssa 
closes #5959
=> test(jans-auth-server): fix test failures - added issuers to test ssa 

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/DCRResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java
=> fix: update org_id in persistence when ssa is uploaded from UI #5966

docker-jans-fido2/jetty/log4j2.xml
=> fix(docker-jans-fido2): duplicate logs for fido2 prefix

docs/admin/install/setup.md
services updated in setup instruction
Install Jans Config API? [Yes] :
Install Scim Server? [Yes] :
Install Fido2 Server? [Yes] :
Install Jans Link Server? [Yes] :
Install Gluu Casa? [No] : yes
closes #5998
=> services installation instruction updated in setup.md

docs/admin/kubernetes-ops/README.md, docs/admin/kubernetes-ops/tui-k8s.md, mkdocs.yml
https://github.com/JanssenProject/jans/issues/5995
Closes #5997, #5995
=> docs: TUI install and connect to k8s installation

docs/admin/fido/config.md, docs/admin/reference/json/properties/fido2-properties.md, jans-core/cache/src/main/java/io/jans/service/BaseCacheService.java, jans-fido2/model/src/main/java/io/jans/fido2/model/conf/AppConfiguration.java, jans-fido2/server/src/main/java/io/jans/fido2/service/persist/UserSessionIdService.java, jans-linux-setup/jans_setup/templates/jans-fido2/dynamic-conf.json
storage when its caching is enabled #5975
=> feat: fido2 needs to search cache for session instead of persistent

jans-linux-setup/jans_setup/schema/jans_schema.json
=> fix: failed to search session by deviceSecret if DB is PostgreSQL #6012

docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py
=> feat: add encrypted inum to session params 

jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImplTest.java
test(jans-auth-server): fixed prompt test 
closes #5977
=> test(jans-auth-server): fixed prompt test #5977

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
=> fix(jans-cli-tui): table widget size for agama details dialog

jans-linux-setup/jans_setup/schema/jans_schema.json, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapBatchJobSample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapDeleteSample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapSample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapSimpleSessionSample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapUpateMissingEntrySample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/LdapUserFieldRemove.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/MailUniquenessConfigurationSample.java, jans-orm/ldap-sample/src/main/java/io/jans/orm/ldap/persistence/LdapEntryManagerSample.java
=> fix: fix schema and update ldap samples

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py, jans-cli-tui/cli_tui/wui_components/jans_table.py
=> fix(jans-cli-tui): table rows fith dialog

jans-scim/client/src/test/java/io/jans/scim2/client/singleresource/Fido2DeviceTest.java
=> fix: add exception handling in Fido2DeviceTest test case

jans-auth-server/docs/swagger.yaml
fix(jans-auth-server): swagger is malformed due to typo 
closes #6085
=> fix(jans-auth-server): swagger is malformed due to typo #6085

docs/admin/install/helm-install/rancher.md
=> docs: janssen install using rancher

docs/admin/install/helm-install/rancher.md
=> docs: add note for single node deployment and update links to latest

jans-cli-tui/cli_tui/plugins/070_users/main.py, jans-cli-tui/cli_tui/plugins/090_jans_link/main.py, jans-cli-tui/cli_tui/utils/utils.py
=> fix(jans-cli-tui): mail validation and link log level

docs/admin/auth-server/openid-features/native-sso.md
=> docs(native-sso): create documentation for native SSO support

docs/admin/developer/scripts/ropc.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizeRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthzRequestService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/RequestParameterService.java
feat(jans-auth-server): passing custom parameters in the body of POST authorization request and ROPC 
closes #6141
=> feat(jans-auth-server): passing custom parameters in the body of POST authorization request and ROPC #6141

docs/admin/install/helm-install/amazon-eks.md, docs/admin/install/helm-install/google-gke.md, docs/admin/install/helm-install/microsoft-azure.md, docs/admin/kubernetes-ops/tui-k8s.md
=> docs: add postgres and tui instructions

jans-scim/client/src/test/java/io/jans/scim2/client/singleresource/FullUserTest.java
=> test(jans-scim): add test case to confirm custom attributes of type date are returned on retrieval

jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix(jans-linux-setup): script hide attribute

docs/admin/recipes/casa.md, docs/admin/reference/kubernetes/docker-jans-casa.md, mkdocs.yml
=> docs: migrate casa from flex to jans

jans-auth-server/server/src/main/webapp/casa/login.xhtml, jans-casa/app/src/main/resources/labels/admin.properties, jans-casa/app/src/main/resources/labels/general.properties, jans-casa/app/src/main/resources/labels/user.properties, jans-casa/app/src/main/webapp/WEB-INF/zk.xml, jans-casa/plugins/custom-branding/pom.xml, jans-casa/plugins/custom-branding/src/main/resources/labels/zk-label.properties
=> chore(jans-casa): remove Gluu references in UI and logs

jans-config-api/docs/jans-config-api-swagger.yaml
=> docs: update swagger descriptor wrt issue #6192

docs/admin/auth-server/endpoints/ssa.md, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/create/SsaCreateClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/ssa/create/SsaCreateRequest.java, jans-auth-server/client/src/main/java/io/jans/as/client/util/ClientUtil.java, jans-auth-server/client/src/test/java/io/jans/as/client/BaseTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/SsaCreateAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/SsaGetAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/client/assertbuilders/SsaGetJwtAssertBuilder.java, jans-auth-server/client/src/test/java/io/jans/as/client/ssa/SsaCreateTest.java, jans-auth-server/client/src/test/java/io/jans/as/client/util/ClientUtilTest.java, jans-auth-server/common/src/main/java/io/jans/as/common/model/ssa/SsaAttributes.java, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaErrorResponseType.java, jans-auth-server/model/src/main/java/io/jans/as/model/ssa/SsaRequestParam.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/SsaService.java, jans-auth-server/server/src/main/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateAction.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaJsonServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaRestWebServiceValidatorTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/SsaServiceTest.java, jans-auth-server/server/src/test/java/io/jans/as/server/ssa/ws/rs/action/SsaCreateActionTest.java, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-errors.json
- Added new error type `invalid_ssa_metadata`.
- A new one was made to validate ssa metadata, as first validation, this `lifetime`.
- Documentation updated
- Swagger updated
closes #6171
=> feat(jans-auth): new lifetime attribute in ssa

keycloak-integration/pom.xml
=> fix(kc): add configuration for sonarcloud

docs/admin/auth-server/endpoints/authorization-challenge.md, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeService.java, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/config/Constants.java, jans-auth-server/server/src/test/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeValidatorTest.java, jans-linux-setup/jans_setup/templates/scopes.ldif, jans-linux-setup/jans_setup/templates/test/jans-auth/data/oxauth-test-data.ldif
feat(jans-auth-server): added "authorization_challenge" scope enforcement #5856
closes #5856
=> feat(jans-auth-server): added "authorization_challenge" scope enforcement #5856

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py, jans-linux-setup/jans_setup/setup_app/messages.py, jans-linux-setup/jans_setup/setup_app/utils/package_utils.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): post-setup install issues

jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> fix(jans-linux-setup): post setup fix for config-api

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> feat(jans-linux-setup): hide saml setup for developers

jans-linux-setup/jans_setup/app_info.json
=> chore(jans-linux-setup): Java 17

charts/janssen/charts/auth-server-key-rotation/templates/cronjobs.yaml
=> fix(charts): use interval-based cronjob schedule syntax

docs/admin/auth-server/endpoints/authorization-challenge.md, docs/admin/developer/scripts/authorization-challenge.md, docs/script-catalog/authorization_challenge/multi_step/AuthorizationChallenge.java
feat(jans-auth-server): multi-step authn challenge flow custom script
closes  #6188
=> feat(jans-auth-server): multi-step authn challenge flow custom script

jans-linux-setup/jans_setup/templates/scopes.ldif
feat(jans-auth-server): enabled authorization_challenge scope for dynamic registration 
closes #6277
=> feat(jans-auth-server): enabled authorization_challenge scope for dynamic registration #6277

docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-scim/Dockerfile, jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py, jans-pycloudlib/jans/pycloudlib/persistence/utils.py, jans-pycloudlib/jans/pycloudlib/wait.py, jans-pycloudlib/tests/test_persistence.py
=> fix(jans-pycloudlib): incorrect persistence entry check for ldap and couchbase

jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-cli-tui/cli_tui/plugins/060_scripts/main.py
=> feat(jans-cli-tui): obtain script types from config-api

jans-linux-setup/jans_setup/jans_setup.py
=> feat(jans-linux-setup): display casa brwose url after setup

jans-linux-setup/jans_setup/install.py, jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/base.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py, jans-linux-setup/jans_setup/static/system/systemd/kc.service, jans-linux-setup/jans_setup/templates/jans-saml/jans-saml-config.json
Fixes for KC installation
Closes #6312, 
Closes #6294
=> fix(jans-linux-setup): KC install fixes

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/AuthorizationChallengeHttpTest.java
test(jans-auth-server): fixed test client for AuthorizationChallengeHttpTest 
closes #6318
=> test(jans-auth-server): fixed test client for AuthorizationChallengeHttpTest #6318

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/OIDCSettings.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/AUIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java
=> feat: changing names of clients used in admin-ui

jans-linux-setup/jans_setup/static/auth/conf/super_gluu_creds.json
=> fix(jans-linux-setup): super gluu credentials url

jans-linux-setup/jans_setup/setup_app/test_data_loader.py
=> fix(jans-linux-setup): super gluu credentials url for test data

docs/contribute/developer-faq.md
=> Update developer-faq.md for letsencrypte

docs/admin/auth-server/endpoints/authorization-challenge.md, jans-auth-server/server/src/main/java/io/jans/as/server/authorize/ws/rs/AuthorizationChallengeEndpoint.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/token/TokenService.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java, jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidator.java, jans-auth-server/server/src/test/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceValidatorTest.java
feat(jans-auth-server): added PKCE support to authz challenge endpoint 
closes #6180
=> feat(jans-auth-server): added PKCE support to authz challenge endpoint #6180

jans-casa/app/src/main/java/io/jans/casa/core/ConfigurationHandler.java, jans-casa/app/src/main/java/io/jans/casa/core/PasswordStatusService.java, jans-casa/app/src/main/java/io/jans/casa/core/PersistenceService.java, jans-casa/app/src/main/java/io/jans/casa/rest/config/PasswordResetAvailWS.java, jans-casa/app/src/main/java/io/jans/casa/ui/vm/admin/PassResetViewModel.java, jans-casa/app/src/main/webapp/admin-api.yaml, jans-casa/app/src/main/webapp/admin/pass-reset.zul, jans-casa/app/src/main/webapp/menubuttons.zul, jans-casa/app/src/main/webapp/user.zul
=> chore: refactor 2FA requirements related to password

docs/admin/install/vm-install/rhel.md, docs/admin/install/vm-install/suse.md, docs/admin/install/vm-install/ubuntu.md
=> certbot_instruction updates

docs/admin/install/docker-install/compose.md, docs/admin/install/docker-install/quick-start.md, docs/admin/install/helm-install/local.md
=> docs: add clear cli instructions

jans-pycloudlib/jans/pycloudlib/lock/sql_lock.py
=> fix(jans-pycloudlib): handle operational error when creating table for lock

README.md, docs/admin/planning/platform-goal.md
The messaging on the main project Janssen README.md was in bad need of updation. 
https://github.com/JanssenProject/jans/issues/6358
closes #6358
Mike agonizingly wordsmithed it as best he could.
=> Sharpen messaging on README and platform goals doc.

docs/governance/charter.md
=> fix(docs): remove additional Agama title

docker-jans-casa/scripts/bootstrap.py
=> fix(docker-jans-casa): add missing smtp-keys.pkcs12 file

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): hide client scret

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/080_smtp/main.py, jans-cli-tui/cli_tui/utils/utils.py
=> fix(jans-cli-tui): save changes before testing STMP config

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): jans-saml dependencies

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> fix(jans-linux-setup): kc maven urls

docker-jans-auth-server/Dockerfile
=> fix(docker-jans-auth-server): add agama inbound jar 

docs/admin/auth-server/endpoints/introspection.md
=> docs: fix formatting issues in introspection endpoint doc

docs/admin/developer/scripts/persistence.md
=> docs: fix formatting issues in persistence doc

docker-jans-all-in-one/Dockerfile
=> fix(docker-jans-all-in-one): adjust permissions for jans-link component

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> fix(jans-linux-setup): saml install issues

jans-linux-setup/jans_setup/templates/jans-saml/jans-saml-config.json
=> fix(jans-linux-setup): selected idp

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/AdminPermission.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/ApiTokenRequest.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/auth/OAuth2Resource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java
=> feat: adding scopes in config-api endpoint access token based on tags (admin-ui) #6413

docs/script-catalog/introspection/introspection-role-based-scope/introspection_role_based_scope.py, jans-cli-tui/setup.py, jans-linux-setup/jans_setup/templates/jans-auth/role-scope-mappings.json
=> fix(jans-linux-setup) role based script

.github/workflows/build-wars.yml, .github/workflows/central_code_quality_check.yml
=> ci: update java versions

jans-auth-server/agama/engine/pom.xml, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/service/TemplatingService.java
=> chore(agama): update dependencies used by the engine

docs/admin/install/helm-install/local.md
=> docs(jans-helm): memory allocation

jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> fix:generate latest openApi spec from code #6444

docs/admin/auth-server/logging/README.md, docs/admin/auth-server/logging/standard-logs.md, docs/admin/keycloak/README.md, docs/admin/keycloak/keycloak-saml-inbound.md, docs/admin/keycloak/keycloak-saml-sso.md, docs/admin/kubernetes-ops/tui-k8s.md, docs/admin/link/README.md, docs/admin/link/jans-link.md, docs/admin/link/keycloak-synch.md
=> docs: fixes

jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
=> fix(jans-linux-setup): enable agama by default

jans-auth-server/client/src/main/java/io/jans/as/client/RegisterRequest.java, jans-auth-server/docs/swagger.yaml, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/ConfigurationResponseClaim.java, jans-auth-server/model/src/main/java/io/jans/as/model/register/RegisterRequestParam.java, jans-auth-server/persistence-model/src/main/java/io/jans/as/persistence/model/ClientAttributes.java, jans-auth-server/server/src/main/java/io/jans/as/server/introspection/ws/rs/IntrospectionWebService.java, jans-auth-server/server/src/main/java/io/jans/as/server/model/registration/RegisterParamsValidator.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterJsonService.java, jans-auth-server/server/src/main/java/io/jans/as/server/register/ws/rs/RegisterService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/IntrospectionService.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/FapiOpenIdConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/OpenIdConfiguration.java
feat(jans-auth-server): enabled JWT response at introspection endpoint configured by AS and client config
closes #3658
=> feat(jans-auth-server): enabled JWT response at introspection endpoint configured by AS and client config

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py
=> fix(jans-cli-tui): add client properties client uri, policy uri, logo uri

docs/admin/kubernetes-ops/cert-management.md
Updated instruction on rotating LDAP certificate and key.
closes #6466
=> docs(kubernetes): update instruction to rotate LDAP cert and key

docs/admin/lock/README.md
=> docs(lock): markdown fixes

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/installers/jans_casa.py
=> fix(jans-linux-setup): typo in filename of casa plugin twilio

demos/jans-tarp/package.json, demos/jans-tarp/src/options/StyledDropzone.tsx, demos/jans-tarp/src/options/options.css, demos/jans-tarp/src/options/registerForm.tsx
=> feat(jans-tarp): user should be allowed to paste an SSA (or specify a file from disk) in DCR form #6161

docs/admin/developer/agama/faq.md, docs/agama/gama-format.md
=> docs: mention custom jars can be included in the project archive

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/AdminPermission.java
=> fix: permission not getting added successfully #6519

docs/script-catalog/scim/sample-script/SampleScript.py
=> fix(jans-auth): SCIM sample script doesnt have all methods

jans-casa/app/src/main/java/io/jans/casa/plugins/authnmethod/service/otp/HOTPAlgorithmService.java, jans-casa/app/src/main/java/io/jans/casa/plugins/authnmethod/service/otp/TOTPAlgorithmService.java
=> fix(jans-casa): error while enrolling OTP

docker-jans-monolith/jans-ldap-compose.yml, docker-jans-monolith/jans-mysql-compose.yml, docker-jans-monolith/jans-postgres-compose.yml
Updated jans version from 19_dev to latest 20-1
=> Updated jans version from 19_dev to latest 20-1

jans-auth-server/docs/swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/ApiApplication.java, jans-fido2/docs/jansFido2Swagger.yaml, jans-scim/server/src/main/resources/jans-scim-openapi.yaml
=> fix: API spec metadata

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_scope_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py, jans-cli-tui/cli_tui/utils/background_tasks.py
=> feat(jans-cli-tui): replace list by label container for scope claims

jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> feat: if DB column is boolean convert string "true" and '1' to true

jans-cli-tui/cli_tui/cli/config_cli.py
=> feat(jans-linux-tui): tag field for endpoint adminUIPermissions

docker-jans-configurator/scripts/parameter.py
=> fix(docker-jans-configurator): add missing salt field

jans-auth-server/server/pom.xml, jans-bom/pom.xml
chore(jans-auth-server): added oauth2-oidc-sdk dependency 
closes #6545
=> chore(jans-auth-server): added oauth2-oidc-sdk dependency #6545

docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-link/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-persistence-loader/scripts/upgrade.py
=> feat(docker-jans): add archived jwks

automation/startjanssendemo.sh
=> feat: add casa, and enable public endpoints

jans-keycloak-link/server/src/main/java/io/jans/keycloak/link/server/service/KeycloakService.java, jans-keycloak-link/server/src/main/java/io/jans/keycloak/link/timer/JansKeycloakLinkTimer.java, jans-link/service/src/main/java/io/jans/link/util/PropertyUtil.java
#6334 added code to handle encrypted and non encrypted password and client secret key.
=> feat(jans-keycloak-link): implement password decryption

docs/admin/developer/agama/engine-bridge-config.md, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/exception/FlowCrashException.java, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/script/ScriptUtils.java, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/servlet/ExecutionServlet.java, jans-auth-server/agama/inboundID/pom.xml
=> chore(agama): rephrase misleading message in log

jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py
=> fix(jans-cli-tui): fix saving acr script

docs/admin/install/helm-install/amazon-eks.md, docs/admin/install/helm-install/google-gke.md, docs/admin/install/helm-install/microsoft-azure.md
=> docs: fix postgres host

docker-jans-config-api/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py
=> feat(docker-jans): use reference token for TUI client

docker-jans-config-api/Dockerfile
Ref: https://github.com/GluuFederation/flex/issues/1325
closes #6577 
=> feat(docker-jans-config-api): change the location of admin-ui log files

docs/admin/config-guide/config-tools/jans-cli/README.md
=> docs: added details for `.config` directory

docs/admin/install/docker-install/compose.md, docs/admin/kubernetes-ops/README.md, docs/admin/reference/database/README.md, docs/admin/usermgmt/usermgmt-cli-tui.md, mkdocs.yml
=> docs: some fixes

jans-linux-setup/jans_setup/setup_app/installers/config_api.py
=> feat(jans-linux-setup): config-api idp-plugin

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/060_scripts/main.py, jans-cli-tui/cli_tui/utils/background_tasks.py, jans-cli-tui/cli_tui/wui_components/jans_label_container.py, jans-cli-tui/cli_tui/wui_components/jans_label_widget.py
=> feat(jans-cli-tui): provide list of enabled scripts for client scripts

jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py
=> fix(jans-cli-tui): search attribute

jans-linux-setup/jans_setup/templates/test/agama/agama-test-data.ldif
=> fix: add missing attribute name

docker-jans-persistence-loader/scripts/spanner_setup.py, docker-jans-persistence-loader/scripts/sql_setup.py, jans-pycloudlib/jans/pycloudlib/persistence/spanner.py
=> feat(docker-jans): automatically update schema of sql/spanner tables

jans-casa/extras/casa-external_super_gluu.py
=> chore(jans-casa): update custom script to support scan api

docs/admin/kubernetes-ops/cert-management.md
=> docs: add a note in certificate and key generation in jans

jans-auth-server/model/src/main/java/io/jans/as/model/common/FeatureFlagType.java, jans-core/doc/src/main/java/io/jans/doc/annotation/DocFeatureFlag.java
=> fix: fix feature flag default values

docs/admin/kubernetes-ops/customization.md
=> docs: add custom jar in customization doc

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
=> fix(jans-linux-setup): postgresql permission

docs/admin/kubernetes-ops/custom-attributes.md, mkdocs.yml
=> docs: custom attributes in k8s setup

automation/startjanssendemo.sh, automation/startjanssenmonolithdemo.sh
=> fix: command to External/LB IP

.github/workflows/backport.yml, .github/workflows/docker_build_image.yml
=> ci: fix packages permissions

.github/workflows/build-docs.yml, .github/workflows/commit-check.yml, .github/workflows/docker_build_image.yml
=> ci: replace set-out per workflow

jans-auth-server/server/src/test/java/io/jans/as/server/dev/TokenTest.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
fix(jans-config-api): getting pgsql exception after device auth verfication #6870
=> fix: support boolean jdbc data type #6953

jans-keycloak-integration/authenticator/src/main/java/io/jans/kc/spi/auth/JansAuthenticator.java, jans-keycloak-integration/authenticator/src/main/java/io/jans/kc/spi/rest/JansAuthResponseResourceProvider.java, jans-keycloak-integration/pom.xml
Keycloak version bump caused the build to fail. This fixes the issue
Closes #6972,
=> chore(keycloak-integration): fix broken build due to version bump

jans-core/pom.xml
=> chore: add message artifcat

jans-auth-server/common/src/main/java/io/jans/as/common/service/common/ApplicationFactory.java, jans-core/message/src/main/java/io/jans/service/message/NullMessageProvider.java, jans-core/message/src/main/java/io/jans/service/message/NullPool.java, jans-linux-setup/jans_setup/schema/jans_schema.json
=> chore: fix schema

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/templates/jans-saml/jans-saml-config.json
=> fix(jans-linux-setup): jans saml installation

jans-linux-setup/tools/key_regeneration.py
=> fix(jans-linux-setup): sql key regeneration fails

jans-cli-tui/cli_tui/plugins/100_saml/edit_tr_dialog.py, jans-cli-tui/cli_tui/plugins/100_saml/main.py
=> fix(jans-cli-tui): saml tr issues

jans-lock/client/pom.xml, jans-lock/model/pom.xml, jans-lock/pom.xml, jans-lock/server-fips/pom.xml, jans-lock/server/pom.xml, jans-lock/service/pom.xml
=> chore: update version

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/build-wars.yml, .github/workflows/central_code_quality_check.yml, .github/workflows/release.yaml
=> ci: add jans-lock to workflows

docker-jans-auth-server/Dockerfile
=> fix: remove agama inbound jar dependency

docker-jans-config-api/Dockerfile
=> fix: location for saml plugin

jans-linux-setup/jans_setup/app_info.json
=> fix(jans-linux-setup): KC version 23.0.3

docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/requirements.txt, docker-jans-casa/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/requirements.txt, docker-jans-link/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/requirements.txt, docker-jans-scim/requirements.txt
=> chore(deps): remove optional libcst dependency

docker-jans-certmanager/requirements.txt, docker-jans-configurator/requirements.txt
=> chore(deps): upgrade click version

jans-config-api/docs/jans-config-api-swagger.yaml, jans-core/message/pom.xml, jans-core/message/src/main/java/io/jans/service/message/model/config/MessageConfiguration.java
=> chore: exclude null message conf

jans-linux-setup/jans_setup/templates/jans-saml/kc_jans_api/jans.api-openid-client.json
=> fix(jans-linux-setup): KC client

jans-linux-setup/jans_setup/app_info.json, jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/setup_app/utils/arg_parser.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py, jans-linux-setup/jans_setup/static/system/systemd/opa.service
=> feat(jans-linux-setup): install OPA

jans-config-api/server/src/test/resources/feature/config/message/message.feature
https://github.com/JanssenProject/jans/issues/6982
=> chore: fix message patch tests

jans-linux-setup/jans_setup/install.py
=> fix(jans-linux-setup): uninstall opa

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): CLI asks creds for unauthorized request

docs/contribute/development.md
=> fix(docs): add section for schema setup

jans-linux-setup/jans_setup/templates/base.ldif
=> chore(jan-linux-setup): create ou=archived_jwks,o=jans

docs/casa/administration/credentials-stored.md, docs/casa/administration/faq.md, docs/casa/index.md
=> docs: add links to OpenAPI descriptors

docker-jans-all-in-one/Dockerfile, docker-jans-config-api/Dockerfile
=> chore(docker-jans): add parent directory for admin-ui plugin logs

jans-pycloudlib/jans/pycloudlib/utils.py, jans-pycloudlib/tests/test_utils.py
=> fix(jans-pycloudlib): specify decoder to load password from file

docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/requirements.txt, docker-jans-casa/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/requirements.txt, docker-jans-link/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/requirements.txt, docker-jans-scim/requirements.txt
=> chore(docker-jans): update jans-pycloudlib version in images

jans-linux-setup/jans_setup/setup_app/installers/base.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py
=> fix(jans-linux-setup): opa and jans-lock unit files

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/utils/printVersion.py
=> fix(jans-linux-setup): print version

jans-lock/service/src/main/java/io/jans/lock/model/config/AppConfiguration.java, jans-lock/service/src/main/java/io/jans/lock/service/policy/PolicyDownloadService.java
=>  feat: lock should periodically check policies updates in git and update them in OPA

docs/script-catalog/person_authentication/agama-bridge/AgamaBridge.py, docs/script-catalog/person_authentication/forgot_password/forgot_password.py, docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py, docs/script-catalog/person_authentication/user-cert-external-authenticator/UserCertExternalAuthenticator.py, jans-casa/extras/Casa.py, jans-casa/extras/casa-external_super_gluu.py, jans-casa/plugins/email_2fa_core/extras/email_2fa_core.py
=> chore: fix typo in import

docs/README.md
This PR replaces #7335 
closes #7334 
=> fix(docs): minor updates to the Docs README

jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py
=> fix(jans-linux-setup): write default lock config even not installed

jans-linux-setup/jans_setup/schema/jans_schema.json
=> feat(jans-linux-setup): schema for admin-ui webhook

docs/requirements.txt, mkdocs.yml
=> ci(docs): exclude unreferenced docs from search results

docs/admin/developer/agama/faq.md, docs/admin/developer/agama/jans-agama-engine.md, docs/agama/language-reference.md
=> docs: add details on CDI usage and logging in agama flows

jans-orm/core/src/main/java/io/jans/orm/model/AttributeType.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/SqlOperationService.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlConnectionProvider.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
fix(jans-config-api): getting 500 Server Error while creating IDP using endpoint #7396
=> chore: use column names from DB definition in filters

jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> chore: don't call operationService from tests

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/AuthorizationGrant.java
Avoided NPE if UpdateToken script returned False 
closes #7342
=> fix(jans-auth-server): avoid NPE if UpdateToken script returned False #7342

jans-auth-server/server/src/main/java/io/jans/as/server/model/common/ExecutionContext.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/external/ExternalUpdateTokenService.java, jans-auth-server/server/src/main/java/io/jans/as/server/util/TokenServiceUtil.java
feat(jans-auth-server): provide internal way to obtain client_credential access_token 
closes #7412
=> feat(jans-auth-server): provide internal way to obtain client_credential access_token #7412

jans-linux-setup/jans_setup/templates/jans-lock/dynamic-conf.json, jans-lock/service/src/main/java/io/jans/lock/service/policy/PolicyDownloadService.java
https://github.com/JanssenProject/jans/issues/6541
Closes #7417,
=> feat: use access token to download policies

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> postLogoutRedirectUris should be multi valued

jans-cli-tui/cli_tui/plugins/100_saml/edit_identity_provider_dialog.py, jans-cli-tui/cli_tui/plugins/100_saml/main.py
=> fix(jans-cli-tui): display provider list and edit provider

jans-casa/app/src/main/java/io/jans/casa/core/PersistenceService.java, jans-casa/app/src/main/java/io/jans/casa/core/model/Person.java, jans-linux-setup/jans_setup/templates/jans-auth/people.ldif
=> feat(jans-casa): use an attribute to designate administrative role

docs/casa/administration/quick-start.md, docs/casa/index.md
=> docs: describe how to make a user and administrator in Casa

agama/README.md, docker-jans-auth-server/README.md, docker-jans-casa/README.md, docker-jans-certmanager/README.md, docker-jans-config-api/README.md, docker-jans-configurator/README.md, docker-jans-fido2/README.md, docker-jans-link/README.md, docker-jans-monolith/README.md, docker-jans-persistence-loader/README.md, docker-jans-scim/README.md, docs/README.md, jans-auth-server/README.md, jans-bom/README.md, jans-casa/README.md, jans-cli-tui/README.md, jans-config-api/README.md, jans-core/README.md, jans-eleven/README.md, jans-fido2/README.md, jans-linux-setup/README.md, jans-orm/README.md, jans-pycloudlib/README.md, jans-scim/README.md
=> fix: prepare for 1.0.22 release

.github/CODEOWNERS, .github/workflows/build-packages.yml, automation/packaging/deb/focal/debian/control, automation/packaging/deb/focal/debian/copyright, automation/packaging/deb/jammy/debian/control, automation/packaging/deb/jammy/debian/copyright, demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/authorization_code_flow.jmx, demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/implicit_flow.jmx, demos/benchmarking/docker-jans-loadtesting-jmeter/scripts/tests/resource_owner_password_credentials.jmx
=> ci: fix packages

jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
=> feat: allow to persist Map as JSON in MySQL DB

docs/script-catalog/person_authentication/super-gluu-external-authenticator/SuperGluuExternalAuthenticator.py
=> fix: fix typos in SG script

jans-cli-tui/cli_tui/plugins/100_saml/edit_tr_dialog.py, jans-cli-tui/cli_tui/plugins/100_saml/main.py
=> fix(jans-cli-tui): Saml KC names

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
https://github.com/JanssenProject/jans/pull/7564
Closes #7567,
=> feat: override JSON types for sql tables

jans-pycloudlib/jans/pycloudlib/persistence/couchbase.py
=> fix(jans-pycloudlib): resolve transform value for json type in couchbase persistence

jans-linux-setup/jans_setup/setup_app/data/jetty_app_configuration.json, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> Jans linux setup 7592

docs/admin/install/install-faq.md, docs/admin/install/vm-install/dynamic-download.md, docs/admin/install/vm-install/rhel.md, docs/admin/install/vm-install/suse.md, docs/admin/install/vm-install/ubuntu.md
=> docs(install): add notes for uninstallation of persistence

jans-config-api/docs/jans-config-api-swagger.yaml
=> docs(config-api): removed duplicate property

jans-cli-tui/cli_tui/plugins/999_jans/main.py
=> feat(jans-cli-tui): application versions

demos/jans-tarp/src/options/oidcClientDetails.tsx
=> fix: agama Lab's tab closing automatically if same window has tarp opened #7621

jans-cli-tui/cli_tui/jans_cli_tui.py, jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py, jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py, jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py, jans-cli-tui/cli_tui/plugins/010_auth_server/edit_client_dialog.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/010_auth_server/message.py, jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py, jans-cli-tui/cli_tui/plugins/060_scripts/main.py, jans-cli-tui/cli_tui/plugins/070_users/edit_user_dialog.py, jans-cli-tui/cli_tui/plugins/070_users/main.py, jans-cli-tui/cli_tui/plugins/080_smtp/main.py, jans-cli-tui/cli_tui/plugins/100_saml/edit_identity_provider_dialog.py, jans-cli-tui/cli_tui/plugins/100_saml/edit_tr_dialog.py, jans-cli-tui/cli_tui/utils/background_tasks.py, jans-cli-tui/setup.py, jans-linux-setup/jans_setup/app_info.json, jans-linux-setup/setup.py
=> fix: revert prompt-toolkit upgrade

jans-auth-server/server/src/main/java/io/jans/as/server/service/AppInitializer.java, jans-lock/service/src/main/java/io/jans/lock/service/config/ConfigurationFactory.java
=> fix(jans-auth): configuration changes not taking effect #7631

jans-cli-tui/cli_tui/cli/config_cli.py, jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
closes #7638
closes #7639
- When suffix is missing, CLI gives example:
- Hint **Press F1 for Help** is displayed for all list containers:
- Hint **Press F1 for Help** is displayed for all list containers:
=> feat(jans-cli-tui): enhance help

charts/janssen/Chart.yaml
=> fix(charts): add featureflag for cn-istio-ingress subchart

docs/admin/auth-server/session-management/README.md, docs/admin/config-guide/jans-authorization-server-config.md, docs/admin/planning/timeout-management.md, jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/conf/jans-config.json, jans-auth-server/server/src/main/java/io/jans/as/server/service/CookieService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java, jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/server/src/test/resources/feature/config/properties/server/session/sessionId.feature, jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json, terraform-provider-jans/jans/app_configuration.go
feat(jans-auth-server): improved session lifetime properties 
closes #5275
=> feat(jans-auth-server): improved session lifetime properties #5275

jans-lock/pom.xml
=> chore: remove unused plugin

jans-config-api/plugins/user-mgt-plugin/src/main/java/io/jans/configapi/plugin/mgt/service/UserMgmtService.java
Parent issue# https://github.com/GluuFederation/flex/issues/1566
closes #7446
=> fix: fix array java.lang.IndexOutOfBoundsException

jans-lock/server/pom.xml
https://github.com/JanssenProject/jans/issues/7666
=> chore: move jans-auth base configuration to jans-core-service #7673

docs/script-catalog/person_authentication/apple-external-authenticator/AppleExternalAuthenticator.py, docs/script-catalog/person_authentication/github-external-authenticator/GithubAuthenticatorForADS.py, docs/script-catalog/person_authentication/github-external-authenticator/GithubExternalAuthenticator.py, docs/script-catalog/person_authentication/google-external-authenticator/GoogleExternalAuthenticator.py, docs/script-catalog/person_authentication/oidc/oidc-jans-script.py, docs/script-catalog/person_authentication/other/bioid/BioIDExternalAuthenticator.py, jans-casa/extras/Casa.py
=> chore: change package name in custom scripts

jans-linux-setup/jans_setup/setup_app/utils/package_utils.py
=> fix(jans-linux-setup): disable gpg checks for installing suse packages

docker-jans-certmanager/scripts/auth_handler.py
=> fix(docker-jans-certmanager): resolve key_ops_type created on key rotation

.github/CODEOWNERS
Update codeowners
Closes #7757,
=> ci(codeowners): update CODEOWNERS

.github/workflows/docker_build_image.yml
=> ci(build-docker-builds): fix dockerbuild

.github/workflows/build-docs.yml, docs/overrides/main.html
=> docs(scarf): integration with Scarf Pixel

jans-keycloak-link/server/pom.xml, jans-link/server/pom.xml
https://github.com/JanssenProject/jans/issues/7779
Closes https://github.com/JanssenProject/jans/issues/7781
Closes #7789,
=> fix: fix link deps

jans-cli-tui/cli_tui/utils/utils.py
=> fix(jans-cli-tui): List types

jans-linux-setup/jans_setup/setup_app/installers/jans_keycloak_link.py
=> feat(jans-linux-setup): config-api kc-link-plugin

jans-orm/cdi/src/main/java/io/jans/orm/service/PersistanceFactoryService.java
=> feat: allow to override ORM connection properties #7816

jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/static/system/systemd/opa.service
=> feat(jans-linux-setup): opa logs to file

docs/agama-catalog/jans/inboundID/README.md, docs/agama-catalog/jans/inboundID/project/code/io.jans.inbound.ExternalSiteLogin.flow, docs/agama-catalog/jans/inboundID/project/code/provider/io.jans.inbound.Apple.flow, docs/agama-catalog/jans/inboundID/project/code/provider/io.jans.inbound.GenericProvider.flow, jans-auth-server/agama/engine/src/main/java/io/jans/agama/Utils.java, jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/ConfigProcessor.java, jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/OpenIdParams.java, jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/Provider.java
=> feat(agama): add openId support to agama inbound identity project

jans-config-api/server/src/main/resources/config-api-rs-protect.json
=> feat(jans-cli-tui): Jans Lock Configuration #7855

jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans_cli.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py
=> feat(jans-linux-setup): lock-plugin

jans-linux-setup/jans_setup/setup_app/utils/properties_utils.py
=> fix(jans-linux-setup): prompt for http cert info

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/KeyValuePair.java, jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/OIDCClientSettings.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/AppConfigResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/AUIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/webhook/WebhookEntry.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/adminui/AdminUIService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> feat: add configurable additional parameters in admin-ui configuration #7880

docker-jans-auth-server/Dockerfile, docker-jans-auth-server/scripts/mod_context.py, docker-jans-auth-server/scripts/upgrade.py, docker-jans-casa/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-config-api/README.md, docker-jans-config-api/scripts/plugins.py, docker-jans-config-api/scripts/upgrade.py, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile, jans-pycloudlib/jans/pycloudlib/utils.py
=> chore(docker-jans): sync assets to OCI images

jans-cli-tui/cli_tui/plugins/010_auth_server/attributes.py, jans-cli-tui/cli_tui/plugins/090_jans_link/main.py
=> fix(jans-cli-tui): backend ldap server for jans-link

jans-cli-tui/cli_tui/plugins/100_saml/edit_identity_provider_dialog.py, jans-cli-tui/cli_tui/utils/utils.py
=> fix(jans-cli-tui): check required fields for IDP

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/BaseService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/auth/OAuth2Service.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/webhook/WebhookService.java
=> fix: remove javadocs error logged during jenkins build #7969

docs/admin/config-guide/config-tools/jans-tui/README.md
=> docs(jans-cli-tui): executi tui with sudo

.github/CODEOWNERS
=> ci(CODEOWNERS): add codeowner

jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
feat(jans-orm): print root cause when invalid json object is present in db
closes #7998
=> feat(jans-orm): print root cause when invalid json object is present in db

jans-config-api/plugins/docs/kc-saml-plugin-swagger.yaml, jans-config-api/plugins/kc-saml-plugin/src/main/java/io/jans/configapi/plugin/saml/service/SamlIdpService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DBDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DocumentStore.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/JcaDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/LocalDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/provider/WebDavDocumentStoreProvider.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/BaseDocumentStoreService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/DBDocumentService.java, jans-core/document-store/src/main/java/io/jans/service/document/store/service/DocumentStoreService.java, jans-core/document-store/src/test/java/io/jans/service/document/store/manual/JcaDocumentStoreManualTest.java
#7981
#7920
#7917
#7980
Closes #8010,
=> feat: doc store update

demos/jans-tarp/package.json, demos/jans-tarp/src/options/authFlowInputs.tsx, demos/jans-tarp/src/static/chrome/manifest.json, demos/jans-tarp/src/static/firefox/manifest.json
=> fix: issues found in tarp #8007

charts/janssen-all-in-one/README.md, charts/janssen-all-in-one/templates/cronjobs.yaml, charts/janssen-all-in-one/templates/deployment.yml, charts/janssen-all-in-one/values.yaml, docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/requirements.txt, docker-jans-casa/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/requirements.txt, docker-jans-link/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/requirements.txt, docker-jans-scim/requirements.txt
=> chore: update pycloudlib and fix aio cronjob

docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile
=> chore(docker): sync assets

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/webhook/ShortCodeRequest.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/webhook/WebhookResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/resources/example/webhook/get-all-webhooks.json, jans-config-api/plugins/admin-ui-plugin/src/main/resources/example/webhook/get-webhook-by-feature-id.json, jans-config-api/plugins/admin-ui-plugin/src/main/resources/example/webhook/post-webhook-response.json, jans-config-api/plugins/admin-ui-plugin/src/main/resources/example/webhook/put-webhook.json, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> fix: : bugs in admin-ui webhook #8018

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
=> fix(jans-cli-tui): re-enable agama project config management

jans-pycloudlib/jans/pycloudlib/persistence/sql.py
=> feat(docker): allow custom sql_data_types

docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-config-api/scripts/upgrade.py, docker-jans-persistence-loader/requirements.txt
=> chore(deps): update pycloudlib and jans-config-api-server

docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/requirements.txt, docker-jans-casa/requirements.txt, docker-jans-certmanager/requirements.txt, docker-jans-config-api/requirements.txt, docker-jans-configurator/requirements.txt, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/requirements.txt, docker-jans-link/requirements.txt, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/requirements.txt, docker-jans-scim/requirements.txt
=> chore(deps): update pycloudlib requirement

docs/requirements.txt
fixes python req file
closes #8124
=> docs: fix versions

jans-linux-setup/jans_setup/static/extension/scim/SampleScript.py
=> fix: update deprecated scim sample script

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py
=> fix(jans-cli-tui): typo in agama help popup

docs/admin/auth-server/README.md
=> fix(docs): add new OIDC SPEC to supported list

jans-casa/extras/casa-external_super_gluu.py
=> chore: sync SG script wrt latest updates

docs/casa/plugins/accts-linking/account-linking-index.md
=> docs(jans-casa): fix typo in accounts linking plugin

jans-cli-tui/setup.py
=> fix(jans-cli-tui): update plugin docs list

jans-casa/plugins/acct-linking/extras/agama/lib/io/jans/casa/acctlinking/Mappings.java
=> chore(jans-casa): use friendlier ID attribute for sample mappings of accts linking plugin

docker-jans-monolith/jans-ldap-compose.yml, docker-jans-monolith/jans-mysql-compose.yml, docker-jans-monolith/jans-postgres-compose.yml
=> fix(monolith): update monolith version in compose files

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py
=> fix(docker): resolve jansMessageConf value upon upgrade

charts/janssen-all-in-one/templates/nginx-ingress.yaml
=> fix(jans-aio): adjust config-api port

docs/admin/install/vm-install/vm-requirements.md
=> docs(VM install): update the system h/w requirements for VM installations

docs/casa/plugins/accts-linking/account-linking-index.md, docs/casa/plugins/accts-linking/accts-linking-agama.md, mkdocs.yml
=> docs(casa): add account linking to navigation

docs/script-catalog/person_authentication/otp-external-authenticator/OtpExternalAuthenticator.py, jans-core/model/src/main/java/io/jans/model/user/authenticator/UserAuthenticatorList.java, jans-core/service/src/main/java/io/jans/service/UserAuthenticatorService.java
=> feat(jans-core): add new Person claim jansAuthenticator #8158

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> feat: increase document attribute size

jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
https://github.com/JanssenProject/jans/issues/8208
=> feat: increase document attribute size #8209

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/templates/jans-saml/clients.json
=> fix(jans-linux-setup): saml clients

jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py, jans-linux-setup/jans_setup/setup_app/installers/scim.py, jans-linux-setup/jans_setup/templates/jans-saml/kc_jans_api/jans.userstorage-provider-component.json, jans-linux-setup/jans_setup/templates/jans-saml/keycloak.conf
=> fix(jans-linuux-setup): KC setup issues

docs/admin/developer/scripts/person-authentication.md
=> feat: add documentation to explain details about new jansAuthenticator

docs/admin/developer/scripts/person-authentication.md, mkdocs.yml
=> docs: refactor and proofread the person authn script doc

jans-auth-server/common/pom.xml
=> feat: disable jdk15on dependecies

jans-linux-setup/jans_setup/schema/jans_schema.json, jans-linux-setup/jans_setup/static/rdbm/sql_data_types.json
=> feat(jans-core): define sql type for jansAuthenticator

docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/Dockerfile, docker-jans-auth-server/requirements.txt, docker-jans-casa/Dockerfile, docker-jans-casa/requirements.txt, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/requirements.txt, docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-configurator/Dockerfile, docker-jans-configurator/requirements.txt, docker-jans-fido2/Dockerfile, docker-jans-fido2/requirements.txt, docker-jans-keycloak-link/Dockerfile, docker-jans-keycloak-link/requirements.txt, docker-jans-link/Dockerfile, docker-jans-link/requirements.txt, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/Dockerfile, docker-jans-saml/requirements.txt, docker-jans-scim/Dockerfile, docker-jans-scim/requirements.txt
=> chore: update docker image build date

jans-auth-server/agama/inboundID/src/main/java/io/jans/util/NetworkUtils.java
=> fix(agama-inbound): make method urlBeforeContextPath public

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py, jans-linux-setup/jans_setup/setup_app/installers/jans_casa.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/setup_app/installers/jetty.py
=> chore(jans-linux-setup): use wildcard for auth-server custom libs

docs/casa/plugins/custom-branding.md
=> docs: fix incorrect plugin download link

jans-casa/plugins/email_2fa_core/pom.xml, jans-casa/pom.xml
=> fix: update bouncy castle lib

jans-auth-server/client/pom.xml
=> feat(jans-auth): allocate more memory for client

jans-bom/pom.xml
=> feat(core): update aws-sns

.github/workflows/docker_build_image.yml
This PR adds signatures to our GH registry and signs all images
=> ci: sign all jans containers using cosign

jans-linux-setup/jans_setup/templates/jans-auth/jans-auth-config.json
chore(jans-linux-setup): added password grantType to grantTypesSupportedByDynamicRegistration
closes #8437
=> chore(jans-linux-setup): added password grantType to grantTypesSupportedByDynamicRegistration

docs/admin/developer/agama/faq.md, docs/casa/administration/faq.md, docs/casa/plugins/2fa-settings.md, docs/casa/plugins/bioid.md, docs/casa/plugins/consent-management.md, docs/casa/plugins/custom-branding.md
=> docs: fix broken links and add missing tags

jans-core/document-store/src/main/java/io/jans/service/document/store/service/Document.java
=> feat(jans-document-store): remove transient select field

docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/upgrade.py, docker-jans-saml/Dockerfile, docker-jans-saml/scripts/upgrade.py
=> feat(cloud-native): save asset on server based on the service list provided

jans-core/document-store/src/main/java/io/jans/service/document/store/service/Document.java
=> fix(document-store): jansLevel datatype mismatch

jans-cli-tui/cli_tui/plugins/100_saml/edit_identity_provider_dialog.py
=> fix(jans-cli-tui): principalAttribute and principalType for SAML TR

docker-jans-all-in-one/Dockerfile, docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/Dockerfile, docker-jans-auth-server/requirements.txt, docker-jans-casa/Dockerfile, docker-jans-casa/requirements.txt, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/requirements.txt, docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-configurator/Dockerfile, docker-jans-configurator/requirements.txt, docker-jans-fido2/Dockerfile, docker-jans-fido2/requirements.txt, docker-jans-kc-scheduler/Dockerfile, docker-jans-kc-scheduler/requirements.txt, docker-jans-keycloak-link/Dockerfile, docker-jans-keycloak-link/requirements.txt, docker-jans-link/Dockerfile, docker-jans-link/requirements.txt, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/Dockerfile, docker-jans-saml/requirements.txt, docker-jans-scim/Dockerfile, docker-jans-scim/requirements.txt
=> fix(cloud-native): resolve failure on sync assets using git

.gitignore, jans-core/service/src/main/java/io/jans/service/UserAuthenticatorService.java, jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java, jans-orm/core/src/main/java/io/jans/orm/model/AttributeData.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlEntryManager.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
=> feat(orm): store json values without escaping them

charts/janssen-all-in-one/templates/cronjobs.yaml
=> fix(charts): resolve overlapping cronjobs in all-in-one setup

demos/jans-tarp/src/static/chrome/manifest.json
=> feat: adding version comments and version_name field

docs/admin/kubernetes-ops/memory-dump.md, mkdocs.yml
=> docs: jans memory dump

docs/admin/scim/custom-attributes.md
Adding custom attribute In SCIM Extensions.
=> docs(scim): Adding custom attribute In SCIM Extensions

docker-jans-all-in-one/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-saml/scripts/configure_kc.py
=> feat(cloud-native): disable keycloak verify_profile action

docker-jans-all-in-one/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-saml/scripts/configure_kc.py
=> fix(cloud-native): pre-populate parentId in userstorage config

mkdocs.yml
added global token revocation page to mkdocs
closes #9001
=> doc(jans-auth-server): added global token revocation page to mkdocs

docker-jans-all-in-one/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-persistence-loader/scripts/utils.py
=> fix(cloud-native): remove oxauth variable naming inside templates

charts/janssen/charts/auth-server/templates/deployment.yml, charts/janssen/charts/fido2/templates/deployment.yml, charts/janssen/charts/scim/templates/deployment.yml
=> fix(charts): pass correct indentation

docker-jans-config-api/Dockerfile, docker-jans-config-api/README.md, docker-jans-config-api/scripts/bootstrap.py, docker-jans-config-api/scripts/plugins.py, docs/admin/reference/kubernetes/docker-jans-config-api.md
=> feat(cloud-native): import SSL cert of internal proxy service

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): asset creation date

jans-linux-setup/jans_setup/setup_app/installers/rdbm.py
=> fix(jans-linux-setup): auto convert varchar to string for spanner

docs/admin/config-guide/custom-assets-configuration.md
=> docs(config): updates to custom assets config page

jans-linux-setup/jans_setup/static/extension/fido2/Fido2ExtensionSample.py, jans-linux-setup/jans_setup/templates/scripts.ldif
#8995 
Add interception script for registration
=> feat(jans-fido): add interception script for registration

jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> feat(jans-linux-setup): update jansServiceModule for config-api in post-setup

jans-core/document-store/src/main/java/io/jans/service/document/store/provider/DocumentStoreProviderFactory.java
=> fix(jans-core): register DB document store in Store factory

jans-cli-tui/cli_tui/plugins/010_auth_server/edit_scope_dialog.py, jans-linux-setup/jans_setup/templates/scopes.ldif
=> fix(jans-linux-setup): scope id permission to role for inum: C4F5

docs/admin/developer/customization/customize-web-pages.md
=> docs(customization): update the customization instructions to aling with custom assets

jans-orm/core/src/main/java/io/jans/orm/impl/BaseEntryManager.java
closes #9102
- [x ] **I confirm that there is no impact on the docs due to the code changes in this PR.**
=> feat(jans-orm): mask password attribute values

jans-linux-setup/jans_setup/templates/scripts.ldif
https://github.com/JanssenProject/jans/issues/9087
Corrected JansScr as per @devrimyatar  suggestion.
Closes #9101,
=> fix(jans-setup): corrected jansscr

docs/script-catalog/person_authentication/other/basic.multi_auth_conf/BasicMultiAuthConfExternalAuthenticator.py
=> feat(jans-auth): fix ldap multi ad script to conform Jans

jans-auth-server/server/src/main/java/io/jans/as/server/service/AuthenticationService.java
=> fix(jans-auth): fix AD user authentication

docker-jans-all-in-one/Dockerfile, docker-jans-all-in-one/app/requirements.txt, docker-jans-auth-server/Dockerfile, docker-jans-auth-server/requirements.txt, docker-jans-casa/Dockerfile, docker-jans-casa/requirements.txt, docker-jans-certmanager/Dockerfile, docker-jans-certmanager/requirements.txt, docker-jans-config-api/Dockerfile, docker-jans-config-api/requirements.txt, docker-jans-configurator/Dockerfile, docker-jans-configurator/requirements.txt, docker-jans-fido2/Dockerfile, docker-jans-fido2/requirements.txt, docker-jans-kc-scheduler/Dockerfile, docker-jans-kc-scheduler/requirements.txt, docker-jans-keycloak-link/Dockerfile, docker-jans-keycloak-link/requirements.txt, docker-jans-link/Dockerfile, docker-jans-link/requirements.txt, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/requirements.txt, docker-jans-saml/Dockerfile, docker-jans-saml/requirements.txt, docker-jans-scim/Dockerfile, docker-jans-scim/requirements.txt
Upgrade Alpine OS to v3.20.
closes #9151 
=> feat(cloud-native): upgrade Alpine OS to v3.20

jans-cli-tui/cli_tui/plugins/130_assets/main.py
=> fix(jans-cli-tui): save asset

jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix(jans-setup): #9174 corrected fido extension description

jans-auth-server/agama/engine/src/main/java/io/jans/ads/Deployer.java, jans-auth-server/agama/engine/src/main/java/io/jans/agama/engine/servlet/ExecutionServlet.java
=> fix: do not remove shared source files

jans-auth-server/client/pom.xml, jans-auth-server/server/pom.xml
=> fix(jans-auth): sync test file profile with setup

jans-config-api/plugins/docs/lock-plugin-swagger.yaml, jans-config-api/plugins/lock-plugin/src/main/java/io/jans/configapi/plugin/lock/model/stat/HealthEntry.java, jans-config-api/plugins/lock-plugin/src/main/java/io/jans/configapi/plugin/lock/model/stat/LogEntry.java, jans-config-api/plugins/lock-plugin/src/main/java/io/jans/configapi/plugin/lock/model/stat/TelemetryEntry.java, jans-linux-setup/jans_setup/schema/jans_schema.json
=> feat(jans-config-api): add missing properties to log/audit/telemetry records

.github/workflows/build-packages.yml
=> ci: fix packaging

docs/admin/auth-server/openid-features/acrs.md
doc(jans-auth-server): improved doc for acr aliasing 
closes #9438
=> doc(jans-auth-server): improved doc for acr aliasing #9438

jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/IdentityProcessor.java
=> fix: update jansExtUid regardless of skipProfileUpdate value

jans-casa/app/src/main/java/io/jans/casa/core/OIDCFlowService.java, jans-casa/app/src/main/java/io/jans/casa/ui/vm/HeaderViewModel.java
=> chore: remove id_token_hint from logout url

docs/admin/lock/cedarling.md, docs/admin/reference/openapi.md, jans-linux-setup/jans_setup/templates/jans-couchbase.properties, jans-lock/lock-server.yaml, jans-lock/lock-server/pom.xml, mkdocs.yml
=> feat(jans-lock): rename Lock Master to Lock Server

demos/jans-chip/android/docs/authChallengeScript.java
=> fix: changes in passkey script

jans-auth-server/docs/swagger.yaml
fix(jans-auth-server): added operationId to /ssa/validate swagger
closes #9597
=> fix(jans-auth-server): added operationId to /ssa/validate swagger

demos/jans-tarp/src/options/authFlowInputs.tsx, demos/jans-tarp/src/options/options.css, demos/jans-tarp/src/options/registerClient.tsx
closes [9498](https://github.com/JanssenProject/jans/issues/9498)
=> feat(jans-tarp): Show loader in jans tarp on Submit/Add form until response comes from API.

jans-core/document-store/src/main/java/io/jans/service/document/store/service/DBDocumentService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/CertificateService.java, jans-fido2/server/src/main/java/io/jans/fido2/service/mds/TocService.java
=> feat(jans-fido): move fidoconfig folder properties to db #9369

jans-bom/pom.xml, jans-orm/sql/pom.xml
=> feat(orm): update ORM drivers #9618

jans-auth-server/common/src/main/java/io/jans/as/common/util/RedirectUri.java, jans-auth-server/common/src/test/java/io/jans/as/common/util/RedirectUriTest.java
fix(jans-auth-server): prevent rxss
closes #9613
=> fix(jans-auth-server): prevent rxss #9613

.github/workflows/scorecard.yml
=> chore: update scorecard workflow

jans-bom/pom.xml
=> feat(jans-bom): update spanner libs

jans-bom/pom.xml, jans-orm/sql/pom.xml
=> feat(jans-orm): redefine protobuf-java version

docs/janssen-server/config-guide/auth-server-config/agama-project-configuration.md, docs/janssen-server/config-guide/auth-server-config/authentication-method-config.md, docs/janssen-server/config-guide/auth-server-config/json-web-key-config.md, docs/janssen-server/config-guide/auth-server-config/logging-configuration.md, docs/janssen-server/config-guide/auth-server-config/oauth-scopes-config.md, docs/janssen-server/config-guide/auth-server-config/openid-connect-client-configuration.md, docs/janssen-server/config-guide/config-tools/config-api/config.md, docs/janssen-server/config-guide/custom-assets-configuration.md, docs/janssen-server/config-guide/fido2-config/janssen-fido2-configuration.md, docs/janssen-server/config-guide/scim-config/user-config.md, docs/janssen-server/config-guide/smtp-configuration.md, docs/janssen-server/developer/cors.md, docs/janssen-server/install/vm-install/rhel.md, docs/janssen-server/install/vm-install/suse.md, docs/janssen-server/install/vm-install/ubuntu.md, docs/janssen-server/scim/config.md, docs/janssen-server/scim/custom-attributes.md, docs/janssen-server/scim/logs.md
=> fix(docs): update old tui command with new `jans` wrapper version

jans-pycloudlib/docs/api/wait.md, jans-pycloudlib/docs/guides/container_app.md, jans-pycloudlib/jans/pycloudlib/lock/__init__.py, jans-pycloudlib/jans/pycloudlib/persistence/__init__.py, jans-pycloudlib/jans/pycloudlib/persistence/sql.py, jans-pycloudlib/jans/pycloudlib/persistence/utils.py, jans-pycloudlib/jans/pycloudlib/schema/__init__.py, jans-pycloudlib/jans/pycloudlib/utils.py, jans-pycloudlib/jans/pycloudlib/validators.py, jans-pycloudlib/jans/pycloudlib/wait.py, jans-pycloudlib/mkdocs.yml, jans-pycloudlib/setup.py, jans-pycloudlib/tests/conftest.py, jans-pycloudlib/tests/test_manager.py, jans-pycloudlib/tests/test_persistence.py, jans-pycloudlib/tests/test_schema.py, jans-pycloudlib/tests/test_validators.py, jans-pycloudlib/tests/test_wait.py
=> feat(jans-pycloudlib): remove support for ldap persistence

jans-linux-setup/jans_setup/static/scripts/logmanager.sh
Refactoring log manager script for Janssen setup
Closes #9736,
=> fix(jans-linux-setup): fix logmanager.sh

jans-cli-tui/cli_tui/plugins/140_config_api/main.py, jans-cli-tui/cli_tui/wui_components/jans_label_widget.py
=> fix(jans-cli-tui): config-api configuration

jans-orm/sql-sample/src/main/java/io/jans/orm/sql/SqlSample.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> feat(jans-orm): fix like_regex in json array

docs/casa/plugins/bioid.md, jans-casa/plugins/bioid/src/main/java/io/jans/casa/plugins/bioid/vm/RedirectViewModel.java
closes #9771 
This fixes the launching agama flow step of the BioID enrollment
=> feat(jans-casa): update bioid plugin

jans-orm/sql-sample/src/main/java/io/jans/orm/sql/SqlSample.java, jans-orm/sql-sample/src/main/java/io/jans/orm/sql/SqlSessionSample.java, jans-orm/sql/src/main/java/io/jans/orm/sql/dsl/template/MySQLJsonTemplates.java, jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> feat(jans-orm): add search support in json path

docs/cedarling/python/usage.md
=> docs(jans-cedarling): update python example

jans-casa/app/src/main/java/io/jans/casa/plugins/authnmethod/service/Fido2Service.java
=> fix(jans-casa): fix issue caused by refactoring

jans-orm/sql/src/main/java/io/jans/orm/sql/impl/SqlFilterConverter.java
=> feat(jans-orm): use right booelan type in JSON and plan SQL queries

jans-cli-tui/cli_tui/plugins/010_auth_server/main.py, jans-cli-tui/cli_tui/plugins/020_fido/main.py, jans-cli-tui/cli_tui/plugins/030_scim/main.py, jans-cli-tui/cli_tui/plugins/080_smtp/main.py, jans-cli-tui/cli_tui/plugins/090_jans_link/main.py, jans-cli-tui/cli_tui/plugins/100_saml/main.py, jans-cli-tui/cli_tui/plugins/110_kc_link/main.py
=> refactor(jans-cli-tui): display popup for save action

jans-linux-setup/jans_setup/templates/scripts.ldif
=> fix(jans-linux-setup): script location

docs/janssen-server/config-guide/auth-server-config/authentication-method-config.md, jans-casa/pom.xml, jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py, jans-linux-setup/jans_setup/templates/scripts.ldif, jans-scim/pom.xml
=> merge from main

jans-linux-setup/jans_setup/schema/jans_schema.json, jans-linux-setup/jans_setup/setup_app/installers/rdbm.py, jans-linux-setup/jans_setup/setup_app/utils/attributes.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py
=> fix(jans-linux-setup): json values in arrays

jans-cedarling/schema/cedarling_core.cedarschema, jans-cedarling/schema/cedarling_core.json
=> docs(jans-cedarling): add Application Entity back and Update Action Principal and Resources

jans-auth-server/server/src/main/java/io/jans/as/server/ws/rs/controller/HealthCheckController.java, jans-core/service/src/main/java/io/jans/service/HealthCheckPluginService.java, jans-lock/lock-server/server/src/main/java/io/jans/lock/ws/rs/HealthCheckController.java, jans-lock/lock-server/service/src/main/java/io/jans/lock/service/HealthCheckLockPluginService.java, jans-lock/lock-server/service/src/main/java/io/jans/lock/service/TokenStsatusListService.java, jans-lock/lock-server/service/src/main/java/io/jans/lock/service/config/ConfigurationFactory.java
=> Lock health check plugin

jans-linux-setup/jans_setup/templates/jetty/jans-auth_web_resources.xml
=> fix: add slash

charts/janssen/charts/saml/templates/deployment.yaml
=> fix(charts): resolve error parsing jans helm chart

jans-fido2/server/src/main/java/io/jans/fido2/service/mds/TocService.java
=> fix(jans-fido2): fix document refactoring issue

jans-linux-setup/jans_setup/setup_app/installers/jans.py
=> fix(jans-linux-setup): permission of jans_services_status.py

jans-casa/app-fips/pom.xml
=> chore: misc descriptor updates

jans-linux-setup/jans_setup/static/scripts/jans_services_status.py
=> feat(jans-linux-setup): status script optionally accepts service

demos/jans-tarp/README.md
=> feat: update Readme

jans-fido2/server/src/main/java/io/jans/fido2/service/app/ConfigurationFactory.java
=> fix(jans-fido2): fix issues due unused injects

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/shared/src/main/java/io/jans/configapi/core/util/DataUtil.java
=> fix(config-api): date filter fix

jans-cedarling/schema/cedarling_core.cedarschema, jans-cedarling/schema/cedarling_core.json
=> chore(jans-cedarling): remove ipaddr

jans-orm/sql/src/test/java/io/jans/orm/sql/impl/test/SqlFilterConverterCheckExcludeFilterTest.java, jans-orm/sql/src/test/java/io/jans/orm/sql/impl/test/SqlFilterConverterTest.java
=> fix(jans-orm): update SQL ORM tests to conform latest JSON Filter API

jans-bom/pom.xml
=> fix(jans-bom): update libs

docs/agama-catalog/jans/inboundID/project/web/samples/basic/login.ftlh, jans-auth-server/agama/engine/src/test/resources/templates/login.ftlh, jans-casa/agama/project/web/authn/code.ftlh, jans-casa/agama/project/web/authn/fido-authn.ftlh, jans-casa/agama/project/web/authn/sms.ftlh, jans-casa/agama/project/web/authn/sms_prompt.ftlh, jans-casa/agama/project/web/main.ftlh, jans-casa/agama/project/web/selector.ftlh, jans-casa/app-fips/pom.xml, jans-casa/app/pom.xml, jans-casa/plugins/acct-linking/agama/project/web/acctlinking.ftlh, jans-casa/plugins/samples/sample-cred/agama/web/color-prompt.ftlh
=> chore: adjust projects that use localization labels

jans-cli-tui/cli_tui/plugins/010_auth_server/sessions.py, jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-cli-tui/cli_tui/plugins/060_scripts/main.py
=> fix(jans-cli-tui): file type scripts

jans-fido2/server/src/test/java/io/jans/fido2/service/verifier/CommonVerifiersTest.java
=> Make CommonVerifiersTest class test cases functational

.github/workflows/build-docker-image.yml, demos/benchmarking/docker-jans-loadtesting-jmeter/Makefile, docker-jans-all-in-one/Makefile, docker-jans-auth-server/Makefile, docker-jans-casa/Makefile, docker-jans-certmanager/Makefile, docker-jans-config-api/Makefile, docker-jans-configurator/Makefile, docker-jans-fido2/Makefile, docker-jans-kc-scheduler/Makefile, docker-jans-keycloak-link/Makefile, docker-jans-link/Makefile, docker-jans-monolith/Makefile, docker-jans-persistence-loader/Makefile, docker-jans-saml/Makefile, docker-jans-scim/Makefile
=> ci: fix docker build

.github/workflows/build-docs.yml, .github/workflows/build-packages.yml, .github/workflows/ops-docs.yml, .github/workflows/ops-label-pr-issues.yml
=> ci: fix workflows with nightly bulid

.github/workflows/build-docs.yml, .github/workflows/build-packages.yml
=> ci: fix packages and docs build

.github/workflows/build-packages.yml
=> ci: fix el8 and suse15 nightly package 

.github/workflows/build-packages.yml
=> ci: fix package paths

jans-cli-tui/cli_tui/plugins/010_auth_server/sessions.py
=> fix(jans-cli-tui): display error for session search

.github/workflows/build-packages.yml, .github/workflows/build-test.yml, automation/packaging/rpm/el8/checksum.sh, automation/packaging/rpm/el8/jans.spec, automation/packaging/rpm/suse15/checksum.sh, automation/packaging/rpm/suse15/jans.spec
=> ci: fix building jassen assets on GH

jans-linux-setup/jans_setup/static/scripts/jans
=> fix(jans-linux-setup): display CLI logs in jans script

jans-cli-tui/cli_tui/version.py, jans-linux-setup/jans_setup/setup_app/version.py, jans-pycloudlib/jans/pycloudlib/version.py
=> chore(jans-pycloudlib): conform to PEP 440 versioning

jans-linux-setup/jans_setup/install.py, jans-linux-setup/jans_setup/setup_app/downloads.py
=> fix(jans-linux-setup): bug if version passed is a tag

jans-auth-server/server/src/main/java/io/jans/as/server/service/cluster/StatusIndexPoolService.java, jans-auth-server/server/src/main/java/io/jans/as/server/service/token/StatusListIndexService.java
lower possibility to get data loss during status index pool update 
closes #10284
=> fix(jans-auth-server): lower possibility to get data loss during status index pool update #10284

docs/cedarling/cedarling-logs.md, jans-cedarling/cedarling/Cargo.toml, jans-cedarling/cedarling/src/authz/mod.rs, jans-cedarling/cedarling/src/log/log_entry.rs
Added logging cedar language version and cedar SDK version
[link](https://github.com/JanssenProject/jans/issues/10286)
closes #10286
Updated version of `cedar-policy` lib.
Used methods in `cedar-policy` lib
=> feat(jans-cedarling): add logging `cedarling` version on start application

jans-orm/filter/src/main/java/io/jans/orm/search/filter/Filter.java, jans-orm/filter/src/main/java/io/jans/orm/search/filter/FilterProcessor.java, jans-orm/ldap/src/main/java/io/jans/orm/ldap/impl/LdapEntryManager.java
=> fix(orm): merge ORM changes from Gluu

jans-casa/plugins/email_2fa/agama/project/project.json
=> fix(jans-casa): assign nightly version for email 2fa plugin

jans-linux-setup/jans_setup/setup_app/config.py, jans-linux-setup/jans_setup/setup_app/installers/jans.py, jans-linux-setup/jans_setup/static/scripts/get_agama_lab_projects.py
=> feat(jans-linux-setup): Retreive Agama Lab project scripts

jans-linux-setup/jans_setup/setup_app/test_data_loader.py, jans-linux-setup/jans_setup/templates/test/jans-auth/server/config-jans-auth-test-sql.properties.nrnd
=> fix(jans-linux-setup): auth server test configuration

jans-linux-setup/jans_setup/setup_app/installers/jans_keycloak_link.py, jans-linux-setup/jans_setup/setup_app/installers/jans_lock.py, jans-linux-setup/jans_setup/setup_app/installers/jans_saml.py
=> fix(jans-linux-setup): config-api plugin installation

jans-cedarling/flask-sidecar/main/base/cedarling/cedarling.py
=> fix(jans-cedarling): add handling nonexistent authorization decisions

docker-jans-config-api/Dockerfile, docker-jans-config-api/scripts/external_healthcheck.py
=> chore(docker-jans-config-api): add external script to poll components healthcheck

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): update user password

docker-jans-all-in-one/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/upgrade.py
=> refactor(docker-jans-persistence-loader): remove unnecessary smtp config upgrade

jans-linux-setup/jans_setup/setup_app/installers/jans_auth.py
=> feat(jans-linux-setup): jans-fido2-model auth lib

jans-cedarling/schema/cedarling_core.cedarschema, jans-cedarling/schema/cedarling_core.json
=> docs(jans-cedarling): update schema

docs/janssen-server/install/vm-install/ubuntu.md
=> Update ubuntu.md for stable release

docs/janssen-server/install/vm-install/rhel.md, docs/janssen-server/install/vm-install/suse.md
=> Update rhel.md for stable release

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/user-mgt-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AcrsResource.java
1. Issue#10511: resolved error while setting agama flow as ACR
closes #10511
=> fix(config-api): setting agama flow as auth method

.github/SECURITY.md
=> docs: update security policy

.github/workflows/build-nightly-build.yml, .github/workflows/build-packages.yml, jans-cedarling/flask-sidecar/Dockerfile, jans-cedarling/flask-sidecar/pyproject.toml
=> ci: fix sidecar versioning and signing whls

jans-auth-server/server/src/main/java/io/jans/as/server/token/ws/rs/TokenRestWebServiceImpl.java
Test is failing - TokenRestWebServiceHttpTest requestAccessTokenFail 
closes #10637
=> fix(jans-auth-server): test is failing - TokenRestWebServiceHttpTest requestAccessTokenFail #10637

docs/script-catalog/authorization_challenge/AgamaChallenge.java
=> fix: implement missing method from interface

jans-auth-server/client/src/test/java/io/jans/as/client/ws/rs/SelectAccountHttpTest.java
fix(jans-auth-server): failing test - SelectAccountHttpTest selectAccountTest 
closes #10647
=> fix(jans-auth-server): failing test - SelectAccountHttpTest selectAccountTest #10647

jans-auth-server/server/src/test/java/io/jans/as/server/comp/db/UserJansExtUidAttributeTest.java
=> feat(jans-auth): log current folder in UserJansExtUidAttributeTest test

jans-cedarling/flask-sidecar/Dockerfile
=> ci: change commit sha

jans-auth-server/server/src/test/java/io/jans/as/server/comp/db/UserServiceTest.java
=> feat(jans-auth): log current folder in UserServiceTest test

jans-linux-setup/jans_setup/templates/jans-keycloak-link/jans-keycloak-link-config.json
=> fix(jans-kc-link): remove default keycloak configs

.github/workflows/build-packages.yml, demos/jans-tarp/package.json, demos/jans-tarp/src/options/userDetails.tsx, demos/jans-tarp/src/static/chrome/manifest.json, demos/jans-tarp/src/static/firefox/manifest.json
=> feat: extract wasm tar in /jans-tarp folder

jans-cli-tui/cli_tui/plugins/140_config_api/main.py
=> fix(jans-cli-tui): save config-api configuration

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/scim-plugin/src/test/java/io/jans/configapi/plugin/scim/ScimBaseTest.java, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaDeploymentsResource.java, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AgamaDeploymentsService.java
- 1. Issue#10749: Fixed issue with scim test case
-2 . Issue#10747: Added logs for agama deployment issue
closes  #10749 #10747
=> test(config-api) scim test failure

docs/janssen-server/developer/customization/customize-web-pages.md
=> docs(config-api): customization doc

docs/cedarling/cedarling-krakend.md, jans-cedarling/cedarling-krakend/README.md
=> docs(jans-cedarling): update readme for scope based access

docs/janssen-server/config-guide/config-tools/config-api/config.md, docs/janssen-server/install/helm-install/amazon-eks.md, docs/janssen-server/install/helm-install/google-gke.md, docs/janssen-server/install/helm-install/microsoft-azure.md, docs/janssen-server/planning/multi-tenancy.md, terraform-provider-jans/README.md, terraform-provider-jans/docs/index.md, terraform-provider-jans/examples/resources/jans_script/resource.tf
=> docs(terraform-provider-jans): fix docs example

terraform-provider-jans/jans/api_app_configuration.go, terraform-provider-jans/jans/app_configuration.go, terraform-provider-jans/provider/resource_api_app_configuration.go, terraform-provider-jans/provider/resource_app_configuration.go
syncs tf provider with the API spec
closes #10835
=> fix: update resource endpoints for terraform

jans-config-api/server/src/main/java/io/jans/configapi/security/service/OpenIdAuthorizationService.java
=> fix: getting 401 Unauthorized for /jans-config-api/api/v1/stat

docs/cedarling/uniffi/cedarling-ios.md, docs/cedarling/uniffi/cedarling-uniffi.md
=> docs(jans-cedarling): fix formatting of uniffi binding of cedarling #10897

demos/jans-chip/README.md
=> docs: add README for jans-chip

jans-link/server/src/main/java/io/jans/link/timer/JansLinkTimer.java
[Issue #8965](https://github.com/JanssenProject/jans/issues/8965)
closes #8965 
fix(logging): replace string concatenation with parameterized placeholders
=> fix(logging): improve detail formatting

docs/cedarling/cedarling-quick-start.md
=> docs(jans-cedarling): update namespace for quick start

nhi-meeting-notes.txt
=> chore: remove external file

docs/cedarling/cedarling-properties.md, jans-cedarling/bindings/cedarling_python/README.md
fix documentation
[link](https://github.com/JanssenProject/jans/issues/10854)
closes #10854
updated documentation
=> fix(jans-cedarling): fix documentation CEDARLING_POLICY_STORE_LOCAL can hold only string

jans-cli-tui/cli_tui/plugins/010_auth_server/view_property.py
=> fix(jans-cli-tui): properties acrMappings

jans-cedarling/bindings/cedarling_python/example.py, jans-cedarling/flask-sidecar/main/base/cedarling/cedarling.py
=> chore(jans-cedarling): update python components

jans-auth-server/server/src/test/java/io/jans/as/server/ws/rs/AuthorizationCodeFlowEmbeddedTest.java
test(jans-auth-server): fix AuthorizationCodeFlowEmbeddedTest 
closes #11116
=> test(jans-auth-server): fix AuthorizationCodeFlowEmbeddedTest #11116

demos/jans-tarp/package.json
=> chore: upgrade cedarling_wasm dependency version in tarp

demos/jans-tarp/package.json, demos/jans-tarp/src/options/cedarling.tsx
=> feat: code refactoring for UI improvement in tarp

agama/transpiler/pom.xml, docs/script-catalog/authorization_challenge/AgamaChallenge.java, jans-auth-server/agama/engine/pom.xml, jans-scim/server/src/main/java/io/jans/scim/service/scim2/Scim2GroupService.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/Scim2UserService.java, jans-scim/server/src/main/java/io/jans/scim/service/scim2/UserPersistenceHelper.java, jans-scim/server/src/main/java/io/jans/scim/ws/rs/scim2/BaseScimWebService.java, jans-scim/service/src/main/java/io/jans/scim/service/Fido2DeviceService.java, jans-scim/service/src/main/java/io/jans/scim/service/GroupService.java
=> fix: return 500 instead of 404 on lookup error

.github/workflows/build-packages.yml, demos/jans-tarp/src/options/cedarling.tsx, demos/jans-tarp/src/options/options.tsx
=> fix(jans-tarp): unsigned authorization form not working

.github/workflows/build-packages.yml, jans-config-api/plugins/fido2-plugin/pom.xml, jans-config-api/plugins/jans-link-plugin/pom.xml, jans-config-api/plugins/kc-link-plugin/pom.xml, jans-config-api/plugins/kc-saml-plugin/pom.xml, jans-config-api/plugins/lock-plugin/pom.xml, jans-config-api/plugins/user-mgt-plugin/pom.xml
=> fix: modified plugins

.github/workflows/build-packages.yml, docker-jans-all-in-one/Dockerfile, docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-certmanager/Dockerfile, docker-jans-cloudtools/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-kc-scheduler/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile, jans-cedarling/flask-sidecar/Dockerfile
=> ci: skip publish to firefox

docs/janssen-server/vm-ops/data-cleaning.md, jans-linux-setup/jans_setup/static/auth/data_clean/clean-data.py, mkdocs.yml
=> feat(jans-linux-setup): support for cleanUpInactiveClientAfterHoursOfInactivity for clients

jans-pycloudlib/jans/pycloudlib/schema/__init__.py, jans-pycloudlib/tests/test_schema.py
=> fix(jans-pycloudlib): resolve schema error caused by marshmallow upgrades

docker-jans-all-in-one/Dockerfile, docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-cloudtools/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile
=> chore(cloud-native): sync jans-pycloudlib to handle marshmallow library API changes

jans-casa/app/pom.xml
=> chore: updgrade nimbus so json-smart is bumped to 2.5.2

jans-config-api/plugins/sample/demo/pom.xml, jans-config-api/plugins/sample/helloworld/pom.xml, jans-config-api/pom.xml, jans-config-api/server/pom.xml
=> build(config-api): lib version to resolve vulnerabilities 

jans-cedarling/bindings/cedarling_python/PYTHON_TYPES.md, jans-cedarling/bindings/cedarling_python/example.py, jans-cedarling/bindings/cedarling_python/src/authorize/entity_data.rs, jans-cedarling/bindings/cedarling_uniffi/androidApp/app/src/main/assets/resource.json, jans-cedarling/bindings/cedarling_uniffi/androidApp/app/src/main/java/com/example/androidapp/MainActivity.kt, jans-cedarling/bindings/cedarling_uniffi/iOSApp/iOSApp/data/resource.json, jans-cedarling/bindings/cedarling_uniffi/iOSApp/iOSApp/views/ContentView.swift, jans-cedarling/bindings/cedarling_uniffi/src/lib.rs
Updated examples and documentation
[link](https://github.com/JanssenProject/jans/issues/11265)
closes #11265
Updated:
- python example and documentation file (regenerated)
- uniffi ios and android examples
=> fix(jans-cedarling): fix usage outdated field resource_type

jans-bom/pom.xml
=> fix(bom): use right jakarta.ws.rs-api version

jans-cedarling/Cargo.toml
Updated build profile for release version to optimaze size
[link](https://github.com/JanssenProject/jans/issues/11280)
closes #11280
Updated Cargo.toml
```
[profile.release]
strip = "symbols"
debug-assertions = false
lto = true
opt-level = "z"
codegen-units = 1
overflow-checks = false
```
=> feat(jans-cedarling): Optimize Cedar libraries size

jans-core/util/pom.xml, jans-core/util/src/main/java/io/jans/util/Util.java
=> fix(bom): deprecate jackson-module-jaxb-annotations

jans-casa/plugins/acct-linking/src/main/java/io/jans/casa/plugins/acctlinking/AccountsLinkingPlugin.java, jans-casa/plugins/acct-linking/src/main/java/io/jans/casa/plugins/acctlinking/AccountsLinkingService.java, jans-casa/plugins/acct-linking/src/main/java/io/jans/casa/plugins/acctlinking/conf/Config.java, jans-casa/plugins/acct-linking/src/main/java/io/jans/casa/plugins/acctlinking/vm/AccountsLinkingVM.java, jans-casa/plugins/acct-linking/src/main/resources/assets/user/index.zul
=> feat: allow linking to occur in a popup

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/fido2-plugin-swagger.yaml, jans-config-api/plugins/docs/jans-link-plugin-swagger.yaml, jans-config-api/plugins/docs/kc-link-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/CustomScriptResource.java
11307: Fixed NPE while creating script. Support issue#73
closes #11307
=> fix(config-api): custom script creation failing #11307

docs/janssen-server/fido/passwordlessLoginExperience.md
minor edits
#11331
closes #11331
=> fix(jans-fido2): #11331 minor edits

jans-cli-tui/setup.py
=> fix(jans-cli-tui): include jans-logo.txt in package

jans-auth-server/model/pom.xml
=> feat(jans-auth): restore Nashorn engine

demos/janssen-tarp/src/static/chrome/manifest.json
=> fix: remove version_name attribute from manifest.json

.github/workflows/build-packages.yml
=> ci(jans-cedarling): remove conflicting asset

docs/casa/plugins/email-otp.md
=> docs: fix broken link

docs/agama-catalog/jans/inboundID/README.md, jans-auth-server/agama/inboundID/src/main/java/io/jans/inbound/IdentityProcessor.java
=> chore(agama): refactor handling of jansExtUid in inbound identity

jans-auth-server/server/pom.xml, jans-bom/pom.xml, jans-config-api/server/pom.xml, jans-core/service/pom.xml
=> fix: mail dependencies

jans-bom/pom.xml, jans-config-api/pom.xml, jans-config-api/server/pom.xml, jans-core/service/pom.xml
#1425
closes #1425
Closes #11429,
=> feat(jans-core): add jakarta.mail for TLS support

.github/workflows/ops-sbom.yml
=> ci: fix sbom

jans-cli-tui/cli_tui/plugins/060_scripts/edit_script_dialog.py, jans-cli-tui/cli_tui/plugins/080_smtp/main.py, jans-cli-tui/cli_tui/wui_components/jans_vetrical_nav.py
=> fix(jans-cli-tui): edit script config proprty

jans-linux-setup/jans_setup/install.py, jans-linux-setup/jans_setup/lock_setup.py, jans-linux-setup/jans_setup/setup_app/installers/jetty.py, jans-linux-setup/jans_setup/setup_app/installers/jython.py, jans-linux-setup/jans_setup/setup_app/utils/base.py, jans-linux-setup/jans_setup/setup_app/utils/collect_properties.py, jans-linux-setup/jans_setup/setup_app/utils/db_utils.py, jans-linux-setup/jans_setup/setup_app/utils/setup_utils.py
=> fix(jans-linux-setup): re compatibility

jans-orm/core/src/main/java/io/jans/orm/model/PersistenceMetadata.java, jans-orm/sql/src/main/java/io/jans/orm/sql/operation/impl/SqlOperationServiceImpl.java
=> feat(orm): fetch databaseName for PersistenceMetadata

mkdocs.yml
#11494
closes #11494
Closes #11498,
=> feat(orm): fix doc file

jans-cli-tui/cli_tui/plugins/010_auth_server/authn.py, jans-cli-tui/cli_tui/utils/background_tasks.py
=> fix(jans-cli-tui): persistence type

docker-jans-all-in-one/Dockerfile, docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-cloudtools/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile, jans-cedarling/flask-sidecar/Dockerfile
=> chore: update jans source commit

jans-cli-tui/cli_tui/plugins/999_jans/main.py
=> feat(jans-cli-tui): display build date and build versions

docs/cedarling/cedarling-quick-start-tbac.md, docs/cedarling/cedarling-quick-start-unsigned.md
=> docs(jans-cedarling): add JanssenProject link

jans-cli-tui/cli_tui/cli/config_cli.py
=> feat: add Jans-Client header

jans-cli-tui/cli_tui/plugins/010_auth_server/ssa.py
=> fix(jans-cli-tui): enforce setting SSA life time at least 5 minutes

docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py
=> feat(cloud-native): introduce Logout Status JWT

docs/javascripts/full-screen-sections.js, docs/javascripts/skeleton-loader.js, docs/overrides/main.html, docs/stylesheets/home.css, mkdocs.yml
closes #11640 , #11641 
Also fixes the copy code blocks and LF block size and hyperlink
=> ci: fixes copy code and aligns titles

jans-linux-setup/jans_setup/templates/jans-auth/role-scope-mappings.json
=> feat: add the mandatory permissions for default roles in Admin UI

docs/script-catalog/introspection/role-based-scopes-update-token/role_based_scopes_update_token.py
=> feat: add check to prevent unsigned user-info jwt in the role_based_scopes_update_token script (Admin UI)

jans-linux-setup/jans_setup/jans_setup.py
=> fix(jans-linux-setup): re-order app installations

jans-auth-server/model/src/main/java/io/jans/as/model/config/adminui/UIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/adminui/CedarlingLogType.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/auth/AppConfigResponse.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/model/config/AUIConfiguration.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/adminui/AdminUIService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/config/AUIConfigurationService.java, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> feat(jans-config-api): add cedarlingLogType attribute in Admin UI configuration

jans-cedarling/bindings/cedarling-java/pom.xml
=> feat(jans-cedarling): add maven javadocs plugin in java binding

jans-auth-server/server/src/main/java/io/jans/as/server/service/SessionIdService.java
feat(jans-auth-server): improved SessionIdService - added option to load session without local copy 
closes #11366
=> feat(jans-auth-server): improved SessionIdService - added option to load session without local copy #11366

jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/rest/license/LicenseResource.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/service/license/LicenseDetailsService.java, jans-config-api/plugins/admin-ui-plugin/src/main/java/io/jans/ca/plugin/adminui/utils/ErrorResponse.java, jans-config-api/plugins/docs/jans-admin-ui-plugin-swagger.yaml
=> fix(jans-config-api): changing the /admin-ui/license/resetConfig to DELETE Http method

jans-casa/shared/pom.xml
=> chore: misc libs updates

jans-keycloak-integration/job-scheduler/src/main/java/io/jans/kc/scheduler/config/AppConfiguration.java
…n scopes for jans-config-api client
=> fix(jans-kc-scheduler): typo prevented proper loading of authz scopes #11802

jans-keycloak-link/server/pom.xml, jans-keycloak-link/service/pom.xml
=> test(kc-link): use junit version from jans bom for kc-link

.github/CODEOWNERS
=> ci: update codeowner for Cedarling module

jans-cli-tui/cli_tui/plugins/010_auth_server/agama.py, jans-cli-tui/cli_tui/plugins/140_config_api/audit_logs.py
=> fix(jans-cli-tui): pagination AIP change for repositories endpoints

jans-linux-setup/jans_setup/static/scripts/get_agama_lab_projects.py
=> fix(jans-linux-setup): github API endpoint changes for agama projects

jans-cedarling/cedarling-krakend/go.mod, jans-cedarling/cedarling-krakend/go.sum, jans-cedarling/cedarling-krakend/main.go
=> fix(jans-cedarling): fix krakend plugin to reflect resource changes

demos/janssen-tarp/src/options/registerClient.tsx
=> feat: increase the validity period of tokens in tarp to one day

jans-config-api/plugins/pom.xml
#1837
closes #1837
Closes #11913,
=> feat(jans-config-api): restore jans-config-api plugins jans-link-plugin

jans-linux-setup/jans_setup/jans_setup.py, jans-linux-setup/jans_setup/setup_app/installers/config_api.py, jans-linux-setup/jans_setup/setup_app/installers/fido.py, jans-linux-setup/jans_setup/templates/test/jans-fido2/client/config-jans-fido2-test-data.properties, jans-linux-setup/jans_setup/templates/test/jans-fido2/data/fido2-device-registration-test-data.ldif, jans-linux-setup/jans_setup/templates/test/jans-fido2/server/fido2-device-registration-test-config.properties
=> fix(jans-linux-setup): fido2 test setup fixes

.github/workflows/build-packages.yml, .github/workflows/scan-codeql.yml
=> ci: fix krakend build

jans-cli-tui/cli_tui/defeat_gorn.py, jans-cli-tui/cli_tui/jans_cli_tui.py
=> fix: add no gorn mode

jans-linux-setup/jans_setup/templates/jans-saml/kc-scheduler/kc-scheduler-cron
=> feat(jans-linux-setup): redirecting errors on stderr for the scheduler

jans-auth-server/model/src/main/java/io/jans/as/model/configuration/AppConfiguration.java, jans-auth-server/server/src/main/java/io/jans/as/server/servlet/AccountAccessConsentServlet.java
feat(jans-auth-server): provided configuration for changing case-sensitivity of FAPI response 
closes #11394
=> feat(jans-auth-server): provided configuration for changing case-sensitivity of FAPI response #11394

jans-config-api/docs/jans-config-api-swagger.yaml, jans-config-api/plugins/docs/lock-plugin-swagger.yaml, jans-config-api/server/src/main/java/io/jans/configapi/service/auth/AssetService.java
=> fix(config-api): asset endpoint fix for upload and fetch

jans-keycloak-integration/pom.xml
Dependency version upgrades across the spi and the scheduler.
=> chore(jans-keycloak-integration): upgrade dependency versions #12049

jans-auth-server/client/src/main/java/io/jans/as/client/BaseClient.java, jans-auth-server/client/src/main/java/io/jans/as/client/UserInfoClient.java
=> feat(jans-auth): handle gzip compressed token responses 

jans-bom/pom.xml, jans-config-api/docs/jans-config-api-swagger.yaml
Bumps org.bouncycastle:bcpkix-jdk18on fom 1.78 to 1.79 
closes #12046
=> chore(deps): bump org.bouncycastle:bcpkix-jdk18on fom 1.78 to 1.79 in /jans-bom

jans-keycloak-integration/pom.xml, jans-linux-setup/jans_setup/app_info.json
=> chore(jans-keycloak-integration): bump keycloak version to 26.3.3 #12057

jans-linux-setup/jans_setup/static/system/systemd/kc.service
=> fix(jans-linux-setup): remove redirecting of SE to file for KC

.github/workflows/scan-sonar.yml
=> ci: update sonarcloud github action

docs/cedarling/cedarling-jwt-validation.md, docs/cedarling/cedarling-policy-store.md, docs/cedarling/cedarling-properties.md, jans-cedarling/cedarling/src/authz/trust_mode.rs
This PR updates the docs related to JWT validation in Cedarling.
closes #11198
This PR updates files in the `jans/docs/cedarling` and doesn't change any functionality.
=> docs(cedarling): update JWT validation section

jans-cli-tui/cli_tui/cli/config_cli.py
=> fix(jans-cli-tui): error saving auth logging

docker-jans-all-in-one/Dockerfile, docker-jans-auth-server/Dockerfile, docker-jans-casa/Dockerfile, docker-jans-cloudtools/Dockerfile, docker-jans-config-api/Dockerfile, docker-jans-configurator/Dockerfile, docker-jans-fido2/Dockerfile, docker-jans-keycloak-link/Dockerfile, docker-jans-link/Dockerfile, docker-jans-monolith/Dockerfile, docker-jans-persistence-loader/Dockerfile, docker-jans-persistence-loader/scripts/hooks.py, docker-jans-saml/Dockerfile, docker-jans-scim/Dockerfile, jans-cedarling/flask-sidecar/Dockerfile
Updates source commits in Dockerfiles
closes #12322
=> chore: update jans source version

.github/workflows/test-cedarling.yml, jans-cedarling/.cargo/config.toml, jans-cedarling/bindings/cedarling_wasm/Cargo.toml, jans-cedarling/cedarling/Cargo.toml
[link](https://github.com/JanssenProject/jans/issues/12327)
closes #12327
added missing dependencies to `Cargo.toml`
=> fix(jans-cedarling): Fix broken Cedarling build
